// AUTO-GENERATED by scripts/generate-guide-locations.mjs - do not edit by hand.
// Re-run that script after adding, moving or removing a study guide outside
// src/app/revision/texts. It runs in `npm run prebuild`.

/** One guide, and the specification it was written against. */
export interface GuideLocation {
  href: string
  /** The board this guide targets, or null when it is board-neutral. */
  board: string | null
}

/**
 * Set-text guides that live somewhere other than /revision/texts/<slug>.
 *
 * Consulted only when a text has no real page of its own, so a text with a
 * guide in both places keeps its canonical URL. A slug can have more than one -
 * War Photographer has an Edexcel IGCSE guide and an AQA Power and Conflict
 * guide - so the caller matches on board. See the generator's docblock for why
 * twenty-eight guides were unreachable before this existed.
 */
export const GUIDE_LOCATIONS: ReadonlyMap<string, readonly GuideLocation[]> = new Map([
  ['127-hours', [{ href: '/igcse/edexcel-lang/anthology/127-hours', board: 'edexcel-igcse-lang' }]],
  ['a-dolls-house', [{ href: '/resources/revision-notes/a-dolls-house', board: null }]],
  [
    'a-game-of-polo-with-a-headless-goat',
    [
      {
        href: '/igcse/edexcel-lang/anthology/a-game-of-polo-with-a-headless-goat',
        board: 'edexcel-igcse-lang',
      },
    ],
  ],
  [
    'a-passage-to-africa',
    [{ href: '/igcse/edexcel-lang/anthology/a-passage-to-africa', board: 'edexcel-igcse-lang' }],
  ],
  [
    'a-streetcar-named-desire',
    [{ href: '/resources/revision-notes/a-streetcar-named-desire', board: null }],
  ],
  ['an-unknown-girl', [{ href: '/igcse/edexcel/poetry/an-unknown-girl', board: 'edexcel-igcse' }]],
  ['animal-farm', [{ href: '/resources/revision-notes/animal-farm', board: null }]],
  ['anita-and-me', [{ href: '/resources/revision-notes/anita-and-me', board: null }]],
  [
    'antony-and-cleopatra',
    [{ href: '/resources/revision-notes/antony-and-cleopatra', board: null }],
  ],
  [
    'bayonet-charge',
    [{ href: '/revision/poetry/power-and-conflict/bayonet-charge', board: 'aqa' }],
  ],
  [
    'beyond-the-sky-and-the-earth',
    [
      {
        href: '/igcse/edexcel-lang/anthology/beyond-the-sky-and-the-earth',
        board: 'edexcel-igcse-lang',
      },
    ],
  ],
  ['blood-brothers', [{ href: '/resources/revision-notes/blood-brothers', board: null }]],
  [
    'checking-out-me-history',
    [{ href: '/revision/poetry/power-and-conflict/checking-out-me-history', board: 'aqa' }],
  ],
  [
    'chinese-cinderella',
    [{ href: '/igcse/edexcel-lang/anthology/chinese-cinderella', board: 'edexcel-igcse-lang' }],
  ],
  ['christmas-carol', [{ href: '/resources/revision-notes/christmas-carol', board: null }]],
  ['cousin-kate', [{ href: '/igcse/edexcel/poetry/cousin-kate', board: 'edexcel-igcse' }]],
  ['curious-incident', [{ href: '/resources/revision-notes/curious-incident', board: null }]],
  ['disabled', [{ href: '/igcse/edexcel/poetry/disabled', board: 'edexcel-igcse' }]],
  [
    'do-not-go-gentle-into-that-good-night',
    [{ href: '/resources/revision-notes/do-not-go-gentle-into-that-good-night', board: null }],
  ],
  ['essay-plans', [{ href: '/revision/poetry/power-and-conflict/essay-plans', board: 'aqa' }]],
  [
    'explorers-or-boys-messing-about',
    [
      {
        href: '/igcse/edexcel-lang/anthology/explorers-or-boys-messing-about',
        board: 'edexcel-igcse-lang',
      },
    ],
  ],
  ['exposure', [{ href: '/revision/poetry/power-and-conflict/exposure', board: 'aqa' }]],
  ['frankenstein', [{ href: '/resources/revision-notes/frankenstein', board: null }]],
  ['great-expectations', [{ href: '/resources/revision-notes/great-expectations', board: null }]],
  [
    'h-is-for-hawk',
    [{ href: '/igcse/edexcel-lang/anthology/h-is-for-hawk', board: 'edexcel-igcse-lang' }],
  ],
  ['half-caste', [{ href: '/igcse/edexcel/poetry/half-caste', board: 'edexcel-igcse' }]],
  ['half-past-two', [{ href: '/resources/revision-notes/half-past-two', board: null }]],
  ['hamlet', [{ href: '/resources/revision-notes/hamlet', board: null }]],
  ['henry-v', [{ href: '/resources/revision-notes/henry-v', board: null }]],
  ['hide-and-seek', [{ href: '/resources/revision-notes/hide-and-seek', board: null }]],
  ['if', [{ href: '/igcse/edexcel/poetry/if', board: 'edexcel-igcse' }]],
  ['inspector-calls', [{ href: '/resources/revision-notes/inspector-calls', board: null }]],
  ['jane-eyre', [{ href: '/resources/revision-notes/jane-eyre', board: null }]],
  ['jekyll-and-hyde', [{ href: '/resources/revision-notes/jekyll-and-hyde', board: null }]],
  ['julius-caesar', [{ href: '/resources/revision-notes/julius-caesar', board: null }]],
  ['kamikaze', [{ href: '/revision/poetry/power-and-conflict/kamikaze', board: 'aqa' }]],
  ['king-lear', [{ href: '/resources/revision-notes/king-lear', board: null }]],
  [
    'la-belle-dame-sans-merci',
    [{ href: '/igcse/edexcel/poetry/la-belle-dame-sans-merci', board: 'edexcel-igcse' }],
  ],
  ['london', [{ href: '/revision/poetry/power-and-conflict/london', board: 'aqa' }]],
  ['lord-of-the-flies', [{ href: '/resources/revision-notes/lord-of-the-flies', board: null }]],
  ['macbeth', [{ href: '/resources/revision-notes/macbeth', board: null }]],
  ['merchant-of-venice', [{ href: '/resources/revision-notes/merchant-of-venice', board: null }]],
  ['much-ado', [{ href: '/resources/revision-notes/much-ado', board: null }]],
  [
    'much-ado-about-nothing',
    [{ href: '/resources/revision-notes/much-ado-about-nothing', board: null }],
  ],
  [
    'my-last-duchess',
    [{ href: '/revision/poetry/power-and-conflict/my-last-duchess', board: 'aqa' }],
  ],
  ['never-let-me-go', [{ href: '/resources/revision-notes/never-let-me-go', board: null }]],
  ['of-mice-and-men', [{ href: '/resources/revision-notes/of-mice-and-men', board: null }]],
  ['othello', [{ href: '/resources/revision-notes/othello', board: null }]],
  ['out-out', [{ href: '/igcse/edexcel/poetry/out-out', board: 'edexcel-igcse' }]],
  [
    'ozymandias',
    [
      { href: '/igcse/edexcel/poetry/ozymandias', board: 'edexcel-igcse' },
      { href: '/revision/poetry/power-and-conflict/ozymandias', board: 'aqa' },
    ],
  ],
  ['piano', [{ href: '/igcse/edexcel/poetry/piano', board: 'edexcel-igcse' }]],
  ['pigeon-english', [{ href: '/resources/revision-notes/pigeon-english', board: null }]],
  ['poppies', [{ href: '/revision/poetry/power-and-conflict/poppies', board: 'aqa' }]],
  ['pride-and-prejudice', [{ href: '/resources/revision-notes/pride-and-prejudice', board: null }]],
  ['remains', [{ href: '/revision/poetry/power-and-conflict/remains', board: 'aqa' }]],
  ['remember', [{ href: '/igcse/edexcel/poetry/remember', board: 'edexcel-igcse' }]],
  ['romeo-and-juliet', [{ href: '/resources/revision-notes/romeo-and-juliet', board: null }]],
  ['sign-of-four', [{ href: '/resources/revision-notes/sign-of-four', board: null }]],
  ['silas-marner', [{ href: '/resources/revision-notes/silas-marner', board: null }]],
  ['sonnet-116', [{ href: '/igcse/edexcel/poetry/sonnet-116', board: 'edexcel-igcse' }]],
  ['still-i-rise', [{ href: '/igcse/edexcel/poetry/still-i-rise', board: 'edexcel-igcse' }]],
  [
    'storm-on-the-island',
    [{ href: '/revision/poetry/power-and-conflict/storm-on-the-island', board: 'aqa' }],
  ],
  [
    'the-bright-lights-of-sarajevo',
    [{ href: '/igcse/edexcel/poetry/the-bright-lights-of-sarajevo', board: 'edexcel-igcse' }],
  ],
  [
    'the-charge-of-the-light-brigade',
    [{ href: '/revision/poetry/power-and-conflict/the-charge-of-the-light-brigade', board: 'aqa' }],
  ],
  ['the-crucible', [{ href: '/resources/revision-notes/the-crucible', board: null }]],
  [
    'the-danger-of-a-single-story',
    [
      {
        href: '/igcse/edexcel-lang/anthology/the-danger-of-a-single-story',
        board: 'edexcel-igcse-lang',
      },
    ],
  ],
  ['the-door', [{ href: '/resources/revision-notes/the-door', board: null }]],
  ['the-emigree', [{ href: '/revision/poetry/power-and-conflict/the-emigree', board: 'aqa' }]],
  [
    'the-explorers-daughter',
    [{ href: '/igcse/edexcel-lang/anthology/the-explorers-daughter', board: 'edexcel-igcse-lang' }],
  ],
  ['the-great-gatsby', [{ href: '/resources/revision-notes/the-great-gatsby', board: null }]],
  ['the-handmaids-tale', [{ href: '/resources/revision-notes/the-handmaids-tale', board: null }]],
  [
    'the-man-he-killed',
    [{ href: '/igcse/edexcel/poetry/the-man-he-killed', board: 'edexcel-igcse' }],
  ],
  ['the-prelude', [{ href: '/revision/poetry/power-and-conflict/the-prelude', board: 'aqa' }]],
  ['the-tempest', [{ href: '/resources/revision-notes/the-tempest', board: null }]],
  ['the-tyger', [{ href: '/igcse/edexcel/poetry/the-tyger', board: 'edexcel-igcse' }]],
  [
    'the-yellow-wallpaper',
    [{ href: '/resources/revision-notes/the-yellow-wallpaper', board: null }],
  ],
  ['things-fall-apart', [{ href: '/resources/revision-notes/things-fall-apart', board: null }]],
  ['tissue', [{ href: '/revision/poetry/power-and-conflict/tissue', board: 'aqa' }]],
  [
    'to-kill-a-mockingbird',
    [{ href: '/resources/revision-notes/to-kill-a-mockingbird', board: null }],
  ],
  ['twelfth-night', [{ href: '/resources/revision-notes/twelfth-night', board: null }]],
  [
    'view-from-the-bridge',
    [{ href: '/resources/revision-notes/view-from-the-bridge', board: null }],
  ],
  [
    'war-photographer',
    [
      { href: '/igcse/edexcel/poetry/war-photographer', board: 'edexcel-igcse' },
      { href: '/revision/poetry/power-and-conflict/war-photographer', board: 'aqa' },
    ],
  ],
  [
    'when-greek-meets-greek',
    [{ href: '/resources/revision-notes/when-greek-meets-greek', board: null }],
  ],
  ['woman-in-black', [{ href: '/resources/revision-notes/woman-in-black', board: null }]],
  [
    'young-and-dyslexic',
    [{ href: '/igcse/edexcel-lang/anthology/young-and-dyslexic', board: 'edexcel-igcse-lang' }],
  ],
])
