// AUTO-GENERATED by scripts/generate-placeholder-text-map.mjs - do not edit by hand.
// Re-run that script after adding or removing a study guide under
// src/app/revision/texts. It runs in `npm run prebuild`.

/**
 * Set texts whose page renders the "study guide in production" placeholder.
 *
 * Distinct from STUB_SET_TEXT_SLUGS in src/lib/seo/set-text-stubs.ts, which
 * lists the texts that have no directory at all and fall through to the
 * catch-all route. A text can be in one, the other, or neither.
 */
export const PLACEHOLDER_TEXT_SLUGS: ReadonlySet<string> = new Set([
  'a-game-of-polo-with-a-headless-goat',
  'a-passage-to-africa',
  'beyond-the-sky-and-the-earth',
  'chinese-cinderella',
  'explorers-or-boys-messing-about',
  'h-is-for-hawk',
  'the-danger-of-a-single-story',
  'the-door',
  'the-explorers-daughter',
  'the-man-who-loved-flowers',
  'the-pedestrian',
  'the-yellow-wallpaper',
  'when-greek-meets-greek',
  'young-and-dyslexic',
])
