/**
 * settings set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `School Profile`, ar: `ملخص المدرسة` },
  s1: { en: `Basic information about your school`, ar: `معلومات أساسية عن مدرستك` },
  s2: { en: `School Name`, ar: `اسم المدرسة` },
  s3: { en: `Email Address`, ar: `عنوان البريد الإلكتروني` },
  s4: { en: `Phone Number`, ar: `رقم الهاتف` },
  s5: { en: `Save Changes`, ar: `حفظ التغييرات` },
  s6: { en: `Exam Board & Curriculum`, ar: `اللواء التعليمي و المنهاج` },
  s8: { en: `Exam Board`, ar: `اللوحة الامتحانية` },
  s9: { en: `Academic Year`, ar: `السنة الدراسية` },
  s10: { en: `Active Curriculum Areas`, ar: `مناطق المنهج النشطة` },
  s11: { en: `Save Curriculum Settings`, ar: `احفظ إعدادات المنهج الدراسي` },
  s12: { en: `Your current plan and usage`, ar: `خطةك واستخدامك الحينية` },
  s13: { en: `People who can manage this school`, ar: `اللي يمكنه إدارة المدرسة دي` },
  s14: {
    en: `Configure email alerts and updates`,
    ar: `configuré أشعارات البريد الإلكتروني والتحديثات`,
  },
  s15: { en: `New student signups`, ar: `.signups الجديدة للطلبة` },
  s16: {
    en: `Get notified when a student joins via the join code`,
    ar: `اشعرك عندما ينضم طالب عن طريق رمز الانضمام`,
  },
  s17: { en: `Weekly progress report`, ar: `تقرير التقدم الأسبوعي` },
  s19: { en: `At-risk student alerts`, ar: `تحذيرات الطلاب في مخاطر` },
  s20: {
    en: `Immediate alerts when students fall behind`,
    ar: `إحنا نبيين إنذارات فورية إذا إحنا لاحظنا أن الطالب بدأ يتخلف الحين`,
  },
  s21: { en: `Teacher activity updates`, ar: `تحديثات نشاط المعلم` },
  s22: {
    en: `Notifications when teachers create or modify classes`,
    ar: `إشعارات عندما ينشئ المعلمون أو يقومون بتعديل فصولهم`,
  },
  s23: { en: `Save Notification Preferences`, ar: `حفظ تفضيلات الإشعارات` },
  s24: {
    en: `Share this code so students and teachers can join your school`,
    ar: `شاركي هذا الكود حتى يستطيع الطلاب والمعلمات الانضمام لمدرستك`,
  },
}
