/**
 * much-ado set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s1: { en: `Key Moments`, ar: `لحظات حاسمة` },
  s2: {
    en: `Claudio and Don Pedro`,
    ar: `كلوديو و دون بيروedoctype html">
<head>
<meta charset="UTF-8">
</head>
<body>

كلوديو و دون بيرو

</body>
</html>`,
  },
  s3: { en: `Leonato and the Friar`, ar: `ليوناتو والراهب` },
  s5: { en: `Elizabethan Women and Marriage`, ar: `نساء العصر الإليزابيثي والزواج` },
  s6: { en: `Courtship Conventions`, ar: `conventions الزواج` },
  s7: { en: `Conventions of Comedy`, ar: `conventions الكوميديا` },
  s8: { en: `Much Ado About Nothing`, ar: `مUCH ADo Abou NOTHING` },
  s9: { en: `Honour Culture and the Masculine Code`, ar: `` },
  s11: { en: `The Tempest`, ar: `العاصفة` },
  s13: { en: `Orlando Furioso`, ar: `أوراندو فوريوسيو` },
  s14: {
    en: `Paragraph 1: Conventional love - Claudio and Hero`,
    ar: `الحب التقليدي - كلوديو وهايرو`,
  },
  s15: {
    en: `Paragraph 2: Unconventional love - Beatrice and Benedick`,
    ar: `حب غير تقليدي - بيترسكي وبنيدكت`,
  },
  s16: {
    en: `Paragraph 3: Love tested - “Kill Claudio”`,
    ar: `الحب مختبر - "اقتل كلوديو`,
  },
  s17: { en: `Paragraph 4: Love and vulnerability`, ar: `الحب والضعف` },
  s18: { en: `Paragraph 1: Hero as the patriarchal ideal`, ar: `الهيرو كالمثال الأبوي المثالي` },
  s19: {
    en: `Paragraph 2: The shaming scene - patriarchy's violence`,
    ar: ``,
  },
  s20: { en: `Paragraph 3: Beatrice as resistance`, ar: `برتيس كResistance` },
  s22: {
    en: `Paragraph 1: Benign deception - the gulling plots`,
    ar: `الخداع اللطيف - مؤامرات الغulling_plots (الكلمة الأصلية "gulling plots" غير مترجمة)`,
  },
  s23: {
    en: `Paragraph 2: Malicious deception - Don John's plot`,
    ar: `الخداع الشرير - مؤامرة دون جون`,
  },
  s24: { en: `Paragraph 3: Self-deception`, ar: `الخداع الذاتي` },
  s25: {
    en: `Paragraph 4: “Nothing” / “noting” - the title's significance`,
    ar: ``,
  },
  s26: { en: `Paragraph 1: Female honour as male property`, ar: `` },
  s27: {
    en: `Hero's honour (chastity) belongs to Leonato and then Claudio. When it is questioned, both men feel`,
    ar: ``,
  },
  s28: { en: `Paragraph 2: Claudio's honour code`, ar: `` },
  s30: { en: `Paragraph 4: The restoration of honour`, ar: `إعادة الشرف` },
  s31: { en: `Scene-by-Scene Plot Summary`, ar: `ملخص القصة مشهراً مشهراً` },
  s32: { en: `Character Profiles`, ar: `Profiles للشخصيات` },
  s33: { en: `Major Themes`, ar: `ال THEMES principleentes الرئيسية` },
  s34: { en: `Key Quotations with Analysis`, ar: `اقتباسات رئيسية مع تحليل` },
  s35: { en: `Historical Context`, ar: `السياق التاريخي` },
  s36: { en: `Essay Planning Templates`, ar: `قوالب التخطيط للESSAY` },
}
