// ─── IELTS Academic Writing Task 1 · Chart set 14 ───────────────────────────
// A fourteenth bank of five Academic Task 1 prompts, each paired with a REAL
// chart spec (a `WritingChartSpec`, see src/lib/ielts/types.ts) rendered by
// src/app/ielts/writing/_components/WritingChart.tsx - so the candidate sees an
// actual bar / line / pie / table / process visual, the way the exam presents
// it, rather than a textual data dump.
//
// Authoring rules followed throughout (mirroring chart sets 1-9 and the
// committed worked examples in writing-prompts.ts):
//   • `prompt` is INSTRUCTION ONLY - it never quotes the numbers, because the
//     data lives entirely in `chart` (one source of truth).
//   • bar / line - every series.values length === categories.length, and each
//     carries `unit` + `yAxisLabel`;
//   • pie '%' slices sum to ~100 (parts of one whole);
//   • table - every row.cells length === columns.length − 1 (first column is
//     the row header);
//   • every spec sets a `caption`;
//   • numbers are realistic, internally consistent and tell a clear story
//     (a trend, a comparison, a dominant category) so a 150-word report is
//     achievable.
//
// Five fresh, original topics, deliberately distinct from every existing prompt
// across the whole chart bank:
//   1 overseas tourists by world region of origin, two years (multi-series bar)
//   2 number of internet users in three countries over time (multi-series line)
//   3 average monthly rainfall by season in four cities (table)
//   4 electricity generated by source in two years (two pies)
//   5 how wool is produced, from sheep to finished cloth (linear process)
// All content is original and written for IELTS preparation (Academic track).
// ────────────────────────────────────────────────────────────────────────────

import type { WritingPrompt } from '@/lib/ielts/types'

export const WRITING_CHARTS_14: WritingPrompt[] = [
  // ── 1 · bar (overseas tourists by region of origin, two years) ────────────
  {
    id: 'wt1-c14-tourists-region',
    task: 'writing-task-1',
    track: 'academic',
    title: 'Overseas tourists by region of origin',
    prompt: [
      'The bar chart below shows the number of overseas tourists, in thousands, who visited one country from four world regions in 2015 and in 2020.',
      '',
      'Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
      '',
      'Write at least 150 words.',
    ].join('\n'),
    chart: {
      kind: 'bar',
      unit: 'thousands',
      yAxisLabel: 'Tourists (thousands)',
      caption: 'Overseas tourist arrivals by region of origin (thousands), 2015 vs 2020.',
      categories: ['Europe', 'Asia', 'North America', 'Africa'],
      series: [
        { name: '2015', values: [620, 410, 280, 95] },
        { name: '2020', values: [740, 690, 320, 160] },
      ],
    },
    minWords: 150,
    suggestedMinutes: 20,
  },

  // ── 2 · multi-series line (internet users in three countries over time) ───
  {
    id: 'wt1-c14-internet-users',
    task: 'writing-task-1',
    track: 'academic',
    title: 'Number of internet users in three countries',
    prompt: [
      'The line graph below shows the number of internet users, in millions, in three countries between 2005 and 2025.',
      '',
      'Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
      '',
      'Write at least 150 words.',
    ].join('\n'),
    chart: {
      kind: 'line',
      unit: 'millions',
      yAxisLabel: 'Internet users (millions)',
      caption: 'Number of internet users by country (millions), 2005-2025.',
      categories: ['2005', '2010', '2015', '2020', '2025'],
      series: [
        { name: 'Brazil', values: [22, 65, 118, 150, 178] },
        { name: 'Nigeria', values: [5, 24, 76, 126, 165] },
        { name: 'Canada', values: [21, 27, 31, 34, 36] },
      ],
    },
    minWords: 150,
    suggestedMinutes: 20,
  },

  // ── 3 · table (city × average monthly rainfall by season) ─────────────────
  {
    id: 'wt1-c14-rainfall',
    task: 'writing-task-1',
    track: 'academic',
    title: 'Average monthly rainfall by season in four cities',
    prompt: [
      'The table below shows the average monthly rainfall, in millimetres, in four cities during each of the four seasons.',
      '',
      'Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
      '',
      'Write at least 150 words.',
    ].join('\n'),
    chart: {
      kind: 'table',
      unit: 'mm',
      caption: 'Average monthly rainfall by season (mm), by city.',
      columns: ['City', 'Spring', 'Summer', 'Autumn', 'Winter'],
      rows: [
        { label: 'London', cells: [50, 45, 68, 60] },
        { label: 'Cairo', cells: [3, 0, 4, 9] },
        { label: 'Mumbai', cells: [12, 540, 95, 5] },
        { label: 'Singapore', cells: [180, 165, 175, 255] },
      ],
    },
    minWords: 150,
    suggestedMinutes: 20,
  },

  // ── 4 · two pie charts (electricity by source; each totals 100%) ──────────
  {
    id: 'wt1-c14-electricity-source',
    task: 'writing-task-1',
    track: 'academic',
    title: 'Electricity generated by source in one country',
    prompt: [
      'The two pie charts below show the proportion of electricity generated by each source in one country in 2010 and in 2024.',
      '',
      'Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
      '',
      'Write at least 150 words.',
    ].join('\n'),
    chart: {
      kind: 'pie',
      unit: '%',
      caption: 'Proportion of electricity generated by source (%), 2010 vs 2024.',
      datasets: [
        {
          name: '2010',
          slices: [
            { label: 'Coal', value: 46 },
            { label: 'Natural gas', value: 24 },
            { label: 'Nuclear', value: 16 },
            { label: 'Hydro', value: 9 },
            { label: 'Wind & solar', value: 5 },
          ],
        },
        {
          name: '2024',
          slices: [
            { label: 'Coal', value: 22 },
            { label: 'Natural gas', value: 27 },
            { label: 'Nuclear', value: 14 },
            { label: 'Hydro', value: 10 },
            { label: 'Wind & solar', value: 27 },
          ],
        },
      ],
    },
    minWords: 150,
    suggestedMinutes: 20,
  },

  // ── 5 · process · LINEAR (how wool is produced, sheep to cloth) ───────────
  {
    id: 'wt1-c14-wool-production',
    task: 'writing-task-1',
    track: 'academic',
    title: 'How wool is produced, from sheep to finished cloth',
    prompt: [
      'The diagram below shows the stages involved in producing woollen cloth, from the raising of sheep to the finished material.',
      '',
      'Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
      '',
      'Write at least 150 words.',
    ].join('\n'),
    chart: {
      kind: 'process',
      caption: 'The stages by which raw fleece from sheep is turned into finished woollen cloth.',
      steps: [
        {
          label: 'Rearing & shearing',
          detail:
            'Sheep are raised on farms, and once a year their thick woollen coats are removed in one piece by an electric shearer to give the raw fleece.',
        },
        {
          label: 'Sorting & scouring',
          detail:
            'The fleece is graded by quality, then washed in warm soapy water to remove dirt, grease and other natural oils.',
        },
        {
          label: 'Carding',
          detail:
            'The clean wool is passed between rollers covered in fine wire teeth, which untangle the fibres and lay them out in the same direction.',
        },
        {
          label: 'Spinning',
          detail:
            'The combed fibres are drawn out and twisted tightly together by a spinning machine, forming long, strong lengths of woollen yarn.',
        },
        {
          label: 'Weaving',
          detail:
            'The yarn is fed onto a loom, where it is woven over and under crossing threads to build up a continuous sheet of cloth.',
        },
        {
          label: 'Dyeing & finishing',
          detail:
            'Finally the woven cloth is dyed the required colour, then pressed and inspected before being rolled up ready for sale.',
        },
      ],
    },
    minWords: 150,
    suggestedMinutes: 20,
  },
]
