// ─── IELTS Academic Writing Task 1 · Chart set 2 ────────────────────────────
// A second bank of Academic Task 1 prompts that render a REAL visual via the
// structured `chart` spec (see src/lib/ielts/types.ts → WritingChartSpec,
// drawn by src/app/ielts/writing/_components/WritingChart.tsx). Unlike the
// older text-embedded sets, the prompt text here is INSTRUCTION ONLY — it
// never quotes the numbers, because the data lives entirely in `chart` and is
// shown to the candidate as a chart, graph, table or diagram.
//
// Authoring rules followed throughout:
//   • bar / line — every series.values length === categories.length, and each
//     carries `unit` + `yAxisLabel`;
//   • pie '%' slices sum to ~100 (parts of one whole);
//   • every spec sets a `caption`;
//   • numbers are realistic, internally consistent and tell a clear story.
//
// Six distinct, original topics deliberately chosen to differ from the four
// committed worked examples (online grocery, paper recycling, museum visitors,
// household energy): household spending by income group (table), electricity
// generation by source (multi-series line), university enrolment by subject
// (grouped bar), the make-up of recycled material (single pie), the life cycle
// of a butterfly (cyclical process) and how coffee is produced (linear
// process). All content is original and written for IELTS preparation
// (Academic track).
// ────────────────────────────────────────────────────────────────────────────

import type { WritingPrompt } from '@/lib/ielts/types'

export const WRITING_CHARTS_2: WritingPrompt[] = [
  // ── A — table (4 columns: category + three income groups) ─────────────────
  {
    id: 'wt1c2-household-spending',
    task: 'writing-task-1',
    track: 'academic',
    title: 'Household spending by income group',
    prompt: [
      'The table below shows the average percentage of monthly household income that lower-income, middle-income and higher-income households in one country spent on five categories of goods and services in 2023.',
      '',
      'Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
      '',
      'Write at least 150 words.',
    ].join('\n'),
    chart: {
      kind: 'table',
      unit: '%',
      caption: 'Share of monthly household income spent by category and income group, 2023 (%).',
      columns: ['Spending category', 'Lower-income', 'Middle-income', 'Higher-income'],
      rows: [
        { label: 'Housing & utilities', cells: [38, 29, 21] },
        { label: 'Food & groceries', cells: [27, 19, 12] },
        { label: 'Transport', cells: [14, 17, 15] },
        { label: 'Leisure & travel', cells: [6, 14, 26] },
        { label: 'Savings & investment', cells: [3, 11, 19] },
      ],
    },
    minWords: 150,
    suggestedMinutes: 20,
  },

  // ── B — multi-series line (three sources over time) ───────────────────────
  {
    id: 'wt1c2-electricity-sources',
    task: 'writing-task-1',
    track: 'academic',
    title: 'Electricity generation by source',
    prompt: [
      'The line graph below shows the amount of electricity generated from three different sources in one country between 2000 and 2024, measured in terawatt-hours.',
      '',
      'Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
      '',
      'Write at least 150 words.',
    ].join('\n'),
    chart: {
      kind: 'line',
      unit: 'TWh',
      yAxisLabel: 'Electricity (TWh)',
      caption: 'Electricity generated by source (terawatt-hours), 2000–2024.',
      categories: ['2000', '2006', '2012', '2018', '2024'],
      series: [
        { name: 'Coal', values: [210, 198, 165, 112, 58] },
        { name: 'Natural gas', values: [60, 95, 130, 148, 141] },
        { name: 'Renewables', values: [12, 24, 58, 119, 196] },
      ],
    },
    minWords: 150,
    suggestedMinutes: 20,
  },

  // ── C — grouped bar (two years across five subjects) ──────────────────────
  {
    id: 'wt1c2-university-enrolment',
    task: 'writing-task-1',
    track: 'academic',
    title: 'University enrolment by subject area',
    prompt: [
      'The bar chart below shows the number of students, in thousands, enrolled in five subject areas at universities in one country in 2010 and 2023.',
      '',
      'Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
      '',
      'Write at least 150 words.',
    ].join('\n'),
    chart: {
      kind: 'bar',
      unit: 'thousands',
      yAxisLabel: 'Students (000s)',
      caption: 'University enrolment by subject area (thousands), 2010 vs 2023.',
      categories: [
        'Engineering',
        'Business',
        'Health sciences',
        'Arts & humanities',
        'Computer science',
      ],
      series: [
        { name: '2010', values: [82, 124, 76, 138, 41] },
        { name: '2023', values: [97, 131, 118, 95, 152] },
      ],
    },
    minWords: 150,
    suggestedMinutes: 20,
  },

  // ── D — single pie (parts of one whole; slices total 100%) ────────────────
  {
    id: 'wt1c2-recycled-materials',
    task: 'writing-task-1',
    track: 'academic',
    title: 'What recycled household waste is made of',
    prompt: [
      'The pie chart below shows the proportion of each type of material in the household waste collected for recycling in one city in 2023.',
      '',
      'Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
      '',
      'Write at least 150 words.',
    ].join('\n'),
    chart: {
      kind: 'pie',
      unit: '%',
      caption: 'Composition of household waste collected for recycling, 2023 (% of total weight).',
      datasets: [
        {
          name: '2023',
          slices: [
            { label: 'Paper & card', value: 41 },
            { label: 'Glass', value: 22 },
            { label: 'Plastic', value: 16 },
            { label: 'Metal', value: 12 },
            { label: 'Garden & food waste', value: 9 },
          ],
        },
      ],
    },
    minWords: 150,
    suggestedMinutes: 20,
  },

  // ── E — process · CYCLICAL (a natural life cycle that repeats) ────────────
  {
    id: 'wt1c2-butterfly-life-cycle',
    task: 'writing-task-1',
    track: 'academic',
    title: 'The life cycle of a butterfly',
    prompt: [
      'The diagram below illustrates the life cycle of a butterfly.',
      '',
      'Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
      '',
      'Write at least 150 words.',
    ].join('\n'),
    chart: {
      kind: 'process',
      cyclical: true,
      caption: 'The four stages in the life cycle of a butterfly (the cycle then repeats).',
      steps: [
        {
          label: 'Egg',
          detail:
            'A female butterfly lays tiny eggs on the underside of a leaf, where they remain for several days.',
        },
        {
          label: 'Larva (caterpillar)',
          detail:
            'Each egg hatches into a caterpillar, which feeds on leaves and grows quickly, shedding its skin as it does so.',
        },
        {
          label: 'Pupa (chrysalis)',
          detail:
            'The fully grown caterpillar attaches itself to a stem and forms a hard case called a chrysalis.',
        },
        {
          label: 'Adult butterfly',
          detail:
            'Inside the chrysalis the body changes shape, and after about two weeks an adult butterfly emerges and flies away.',
        },
      ],
    },
    minWords: 150,
    suggestedMinutes: 20,
  },

  // ── F — process · LINEAR (an industrial production process) ───────────────
  {
    id: 'wt1c2-coffee-production',
    task: 'writing-task-1',
    track: 'academic',
    title: 'How coffee is produced',
    prompt: [
      'The diagram below shows the stages in the production of coffee, from the picking of the berries to the packing of the roasted beans.',
      '',
      'Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
      '',
      'Write at least 150 words.',
    ].join('\n'),
    chart: {
      kind: 'process',
      caption: 'The main stages in producing coffee, from harvesting to packaging.',
      steps: [
        {
          label: 'Harvesting',
          detail: 'Ripe red coffee berries are picked by hand from the bushes on the plantation.',
        },
        {
          label: 'Pulping',
          detail:
            'A machine removes the outer skin and pulp, leaving the beans inside a sticky layer.',
        },
        {
          label: 'Fermenting & washing',
          detail:
            'The beans are soaked in tanks to loosen the remaining layer, then washed clean with water.',
        },
        {
          label: 'Drying',
          detail:
            'The wet beans are spread out in the sun, or placed in dryers, until their moisture is low.',
        },
        {
          label: 'Roasting',
          detail:
            'The dried green beans are heated in a roaster until they turn brown and develop their flavour.',
        },
        {
          label: 'Grinding & packing',
          detail:
            'The roasted beans are ground and sealed in bags or tins, ready to be sent to shops.',
        },
      ],
    },
    minWords: 150,
    suggestedMinutes: 20,
  },
]
