/**
 * grade-boundaries set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Grade Boundaries`, ar: `حدود الدرجات` },
  s1: { en: `Important note`, ar: `ملاحظة مهمة` },
  s2: { en: `Approx. mark (/160)`, ar: `تقريبي (/160)_mark_/160_]` },
  s4: {
    en: `Critical, exploratory, conceptualised response to texts.`,
    ar: `ردّ كритيقي واستكشافي ومفهومي على النصوص.`,
  },
  s5: {
    en: `Judicious use of precise references to support interpretation.`,
    ar: `استخدام حكيم لreferences دقيق لدعم التفسير.`,
  },
  s6: {
    en: `Analysis of the writer&rsquo;s methods with subject terminology used judiciously.`,
    ar: `تحليل أساليب الكاتب مع استخدام مصطلحات الموضوع بحكمة وايد.`,
  },
  s7: {
    en: `Exploration of the effects of the writer&rsquo;s methods on the reader.`,
    ar: `استكشاف تأثيرات طرق الكاتب على القارئ.`,
  },
  s8: {
    en: `Exploration of ideas, perspectives, and contextual factors shown across the task.`,
    ar: `استكشاف الأفكار والمناظر والظروف السياقية المبينة في المهمة.`,
  },
  s9: {
    en: `Convincing, critical analysis and exploration in the Shakespeare extract and wider play.`,
    ar: `تحليل مقنع وкритический استكشاف فيtract من شكسبير والمسرحية الشاملة. 

(Note: There seems to be a typo or unintended word ".kr" in the middle of the translation which doesn't fit. The intended translation should read as follows without any interruptions):

تحليل مقنع ونقدي واستكشافي فيtract من شكسبير والمسرحية الشاملة.

For accuracy, here is the corrected version:

تحليل مقنع ونقدي واستكشافي فيtract من شكسبير والمسرحية الشاملة.

Since "tract" seems out of place and might be a typo for "النص", I'll correct it to fit context better:

تحليل مقنع ونقدي واستكشافي للنص من شكسبير والمسرحية الشاملة.`,
  },
  s10: {
    en: `Sophisticated comparison of poems from the AQA anthology with a clear personal response.`,
    ar: `مقارنة مهذبة للقصائد من الأنثولوجيا الخاصة بأQA مع رد شخصي واضح.`,
  },
  s11: { en: `Grades 7-8 &mdash; Strong`, ar: `المستوى السابع والثامن وش قوي` },
  s12: {
    en: `Thoughtful, developed response to texts with a clear personal voice.`,
    ar: `ردّ Thoughtful ومُرَبًّى مع صوت شخصي واضح.`,
  },
  s13: {
    en: `Apt references integrated into interpretations.`,
    ar: `مراجع مناسبة مدمجة في التفسيرات.`,
  },
  s14: {
    en: `Examination of the writer&rsquo;s methods with subject terminology used effectively.`,
    ar: `’examination’ta الأسلوب اللي استخدمه الكاتب و terminologies ’الخاضع للدرس‘ used بشكل فعال.`,
  },
  s15: {
    en: `Understanding of the effects of the writer&rsquo;s methods on the reader.`,
    ar: `فهم تأثيرات طرق الكاتب على القارئ.`,
  },
  s19: { en: `Grades 5-6 &mdash; Secure`, ar: `الصفوف fifth إلى sixth &mdash; موثوق` },
  s20: {
    en: `Clear, explained response to texts with relevant ideas.`,
    ar: `رد واضح مع شرح ومعاودة الأفكار ذات الصلة`,
  },
  s21: {
    en: `References used effectively to support explanations.`,
    ar: `المراجع المستخدمة Effectively لدعم التفسيرات.`,
  },
  s22: {
    en: `Clear explanation of writer&rsquo;s methods with appropriate use of subject terminology.`,
    ar: `توضيح واضح لطرق الكاتب مع استخدام مناسب للمصطلحات الخاصة بالTopic_terms`,
  },
  s23: {
    en: `Understanding of some effects of the writer&rsquo;s methods.`,
    ar: `فهم بعض آثار طرق الكاتب`,
  },
  s24: {
    en: `Some understanding of ideas, perspectives, and contextual factors.`,
    ar: `فهماً للأفكار والمناهج والعوامل السياقية.`,
  },
  s25: {
    en: `Clear response to the 19th-century novel with relevant textual references.`,
    ar: `CLEAR رده واضحة على الرواية من القرن التاسع عشر مع إشارات نصوصية ذات صلة.`,
  },
  s26: {
    en: `Competent response to unseen poetry with some analysis of language and structure.`,
    ar: `رد مناسب ومدروس لشعر غير معروف مع تحليل للغة والStructure (البناء)`,
  },
  s27: { en: `Grade 4 &mdash; Standard pass`, ar: `الدرجة الرابعة &ndash; المعيار المعتمد للنجاح` },
  s28: {
    en: `Some explained response to texts, though may lack consistency.`,
    ar: `بعض التفسيرات للمواضيع موضحة، لكنها قد تفتقر إلىconsistency. 

(Note: The word "consistency" is kept as it's a key term and doesn't have a direct translation that fits the context better in Khaleeji Arabic without losing its meaning.)

البعض من التفسيرات للمواضيع موضحة، لكنها قد تفتقر للدقة والثبات.`,
  },
  s29: {
    en: `References used to support some points, though not always well-selected.`,
    ar: `المراجع المستخدمة لدعم بعض النقاط، رغم أنها لا تكون مختارة دائمًا بشكل جيد.`,
  },
  s30: {
    en: `Some awareness of the writer&rsquo;s methods; some subject terminology used.`,
    ar: `بعض الوعي بطرق الكاتب؛ بعض المصطلح الموضوعي مستخدم.`,
  },
  s31: {
    en: `Some comment on the effects of the writer&rsquo;s choices.`,
    ar: `بعض التعليقات حول آثار خيارات الكاتب.`,
  },
  s32: {
    en: `Some awareness of contextual factors, though may be superficial.`,
    ar: `بعض الوعي بالعوامل السياقية رغم أنها قد تكون سطحية.`,
  },
  s33: {
    en: `Some response to the modern text with basic understanding of themes and characters.`,
    ar: `بعض الردود على النص الحديث مع فهم أساسي للموضوعات والشخصيات.`,
  },
  s34: {
    en: `Some response to unseen poetry with basic identification of features.`,
    ar: `بعض الردود على الشعر غير المعروف مع تحديد أساسي لل caractèresdistinctifs. 

(_correction_: بعض الردود على الشعر غير المعروف مع تحديد أساسي للميزات.)`,
  },
  s35: {
    en: `Grades 1-3 &mdash; Below standard pass`,
    ar: `المستوى الأول حتى الثالث &mdash; دون المعدل للنجاح`,
  },
  s36: {
    en: `Simple, limited comments on texts with little development.`,
    ar: `تعليقات سهلة ومعكوسة على النصوص مع قليل من التطوير.`,
  },
  s37: {
    en: `References may be general or paraphrased rather than specific.`,
    ar: `المرجعيات قد تكون عامة أو ملخصة بدلاً من أن تكون دقيقة.`,
  },
  s39: {
    en: `May retell the plot or describe events rather than analyse.`,
    ar: `يمكن إعادة سرد القصة أو وصف الأحداث بدلاً من التحليل.`,
  },
  s40: { en: `Little or no reference to context.`, ar: `قليل أو لا يوجد مرجع للسياق` },
  s41: {
    en: `Limited engagement with the poetry anthology or unseen poetry.`,
    ar: `تفاعل محدود مع ديواني الشعر أو شعر غير المعروف.`,
  },
  s42: {
    en: `Simple comments on unseen poetry with little analysis.`,
    ar: `تعليقات سهلة على الشعر غير المعروف مع قليل من التحليل.`,
  },
  s43: { en: `Grade 4 &rarr; Grade 5`, ar: `الصف الرابع إلى الصف الخامس` },
  s44: { en: `Grade 5 &rarr; Grade 7`, ar: `الصف الخامس إلى الصف السابع` },
  s45: { en: `Analysis depth:`, ar: `عمق التحليل:` },
  s46: { en: `Poetry anthology:`, ar: `مختارات الشعر:` },
  s47: { en: `Unseen poetry:`, ar: `شعر غير المعهود:` },
  s48: { en: `Grade 7 &rarr; Grade 9`, ar: `السابع&rarr;الثامن والتاسع` },
  s49: {
    en: `Conceptualised response:`,
    ar: `مفهوم الرد: شلونك؟ أبغى أعرف شنو فهمت من الدرس الحين. إذا كان عندك أي سؤال، روح ودوّر في الفيديوهات اللي نشروها إحنا على القناة، أو سكّر الشاشة وانشر السؤال في المجموعة`,
  },
  s50: { en: `Alternative interpretations:`, ar: `تفسيرات بديلة:` },
  s51: { en: `Writer&rsquo;s craft:`, ar: `craftsmanship of the writer:` },
  s52: { en: `Wider reading:`, ar: `قراءة أوسع:` },
  s53: {
    en: `Paper 1 &mdash; Shakespeare and the 19th-century novel (40%)`,
    ar: `ورقية 1 &ndash; شكسبير والرواية من القرن التاسع عشر (40%)`,
  },
  s54: { en: `Extract + essay`, ar: `استخرج واستعمرEssay` },
  s55: {
    en: `Shakespeare play (extract-based essay)`,
    ar: `مقطع من مسرحية شكسبير (مقال مستند إلى المقطع)`,
  },
  s56: { en: `Paper 1 Total`, ar: `ورقة 1 الإجمالي` },
  s57: {
    en: `Paper 2 &mdash; Modern texts, Poetry anthology and Unseen poetry (60%)`,
    ar: `ورق الامتحان 2 &ndash; النصوص الحديثة، مجموعات الشعر والأدب الغير مشهود له (60%)`,
  },
  s58: { en: `Essay question`, ar: `سؤال للمقالة` },
  s59: {
    en: `Modern prose or drama (essay from choice of two)`,
    ar: `النثر الحديث أو المسرحية (مقالة من بين اثنين للاختيار)`,
  },
  s60: {
    en: `One named poem compared with one of your choice`,
    ar: `شوف شعرية محددة مع إحدى اختيارك`,
  },
  s61: { en: `Analysis of one unseen poem`, ar: `تحليل شعر غير معروف واحد` },
  s62: { en: `Comparison of two unseen poems`, ar: `مقارنة بين قصتين غير معروفتين` },
  s63: { en: `Paper 2 Total`, ar: `ورقة 2 الإجمالي` },
  s64: {
    en: `Overall grade boundaries (combined Paper 1 + Paper 2)`,
    ar: `حدود الدرجات الكلية (ورقة الإجابة الأولى + ورقة الإجابة الثانية)`,
  },
  s65: { en: `What each grade looks like in practice`, ar: `كيف تبدو كل درجة في الممارسة` },
  s67: { en: `Paper breakdown at a glance`, ar: `محة عن توزيع الأوراق` },
}
