/**
 * the-tempest set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s1: { en: `Key Moments`, ar: `لحظات حاسمة` },
  s2: { en: `Miranda &amp; Ferdinand`, ar: `ميراندا و فرناند` },
  s3: { en: `Other Characters`, ar: `شخصيات أخرى` },
  s4: { en: `Colonialism and the New World`, ar: `الاستعمار والعالم الجديد` },
  s5: { en: `The Tempest`, ar: `العاصفة` },
  s6: { en: `Sea Venture`, ar: `سفينة البحر` },
  s7: { en: `Shakespeare&apos;s Farewell to the Theatre`, ar: `وداع شكسبير للمسرح` },
  s8: { en: `Henry VIII`, ar: `هنري الثامن` },
  s9: { en: `The Two Noble Kinsmen`, ar: `الرجلين الكريمين` },
  s10: { en: `The Jacobean Masque`, ar: `الماسك الياكوبية` },
  s11: { en: `The Great Chain of Being and Hierarchy`, ar: `سلسلة الوجود والهرمية` },
  s12: { en: `Magic and Science in the Renaissance`, ar: `السحر والعلم في العصور الوسطى الراقية` },
  s13: { en: `How to approach:`, ar: `كيف تتعامل مع:` },
  s14: { en: `Scene-by-Scene Plot Summary`, ar: `ملخص القصة مشهراً مشهراً` },
  s15: { en: `Character Profiles`, ar: `Profiles للشخصيات` },
  s16: { en: `Major Themes`, ar: `ال THEMES الرئيسيين` },
  s17: { en: `Key Quotations`, ar: `الاقتباسات الرئيسية` },
  s18: { en: `Historical and Literary Context`, ar: `السياق التاريخي والأدبي` },
  s19: { en: `Essay Planning`, ar: `hoạchtlة المقال` },
}
