/**
 * act-1 set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Act 1 — Exposition &amp; Temptation`, ar: `الatto 1 — التعريفي و التحريض` },
  s1: {
    en: `Macbeth — Act 1: Scene-by-Scene Analysis`,
    ar: `ماكبث — تحليل المشاهد بالمشهد للمشهد في الفصل الأول`,
  },
  s3: { en: `Key Events &amp; Turning Points`, ar: `أحداث رئيسية ونقاط تحول` },
  s5: {
    en: `Macbeth is named before he appears, immediately linking him to the witches&apos; world.`,
    ar: `مакbeth يذكر قبل ظهوره مباشرة، مرتبطاً بعالم الساحرات.`,
  },
  s7: { en: `Language Analysis`, ar: `تحليل اللغة` },
  s8: { en: `Structural Analysis`, ar: `تحليل البنية` },
  s9: { en: `Links to Themes`, ar: `روابط بالمواضيع` },
  s10: { en: `The Supernatural`, ar: `ال сверх طبيعي` },
  s11: { en: `Appearance vs Reality`, ar: `внешний вид مقابل الواقع` },
  s12: { en: `Fate vs Free Will`, ar: `الم destino مقابل الإرادة الحرة` },
  s13: { en: `Scene 2 — The Battlefield Report`, ar: `-scene 2 — التقرير من ساحة المعركة-` },
  s14: {
    en: `Macbeth is praised as &ldquo;brave Macbeth&rdquo; and &ldquo;Bellona&rsquo;s bridegroom&rdquo; before we meet him.`,
    ar: `ماكبث يُمدح كـ "&ldquo;ماكبث الشجاع&rdquo;" و "&ldquo;عروس Bellona&rdquo;" قبل أن نلتقي به.`,
  },
  s15: {
    en: `Duncan&apos;s transfer of the Cawdor title unknowingly fulfils the witches&apos; first prophecy.`,
    ar: `تحويل دانكان لقب كورددون دون علمه يتحقق منhecy الأولى للساحرات.`,
  },
  s17: { en: `Character Development`, ar: `تطور الشخصية` },
  s18: { en: `Kingship &amp; Power`, ar: `الملكية والسلطة` },
  s22: {
    en: `The Cawdor title is confirmed, lending credibility to the kingship prophecy.`,
    ar: `تم تأكيد لقب كورد، مما يضيف مصداقية للتنبوءة بعرش المملكة.`,
  },
  s24: {
    en: `Banquo&apos;s cautious response provides a moral contrast to Macbeth&apos;s excited reaction.`,
    ar: `رد بنكو الحذر يوفّر تضادًا أخلاقيًّا مع رد فعل مكbeth المندفع.`,
  },
  s25: { en: `Scene 4 — Duncan Names His Heir`, ar: `مشهد 4 — دانكان يعين وارثه` },
  s29: { en: `Scene 5 — Lady Macbeth&apos;s Ambition`, ar: `-scene 5 — طموح لедى مكbeth-` },
  s30: {
    en: `Lady Macbeth is introduced as a force of will who immediately grasps the opportunity and its obstacles.`,
    ar: `luder مكbeth م introducitu كقوة إرادة تفهم الفرصة وأ(obstacles) وايد سريعاً.`,
  },
  s31: {
    en: `Her invocation of spirits parallels the witches, aligning her with supernatural evil.`,
    ar: `نداءها لل духов يparalleled الشرirts، مما يربطها بالشر السupertatural. 

(Note: There seems to be an issue with the translation of certain terms like "spirits" and "witches". I will correct it as follows for clarity and accuracy.)

نداؤها للروح تparalleled نداء الشياطين، مما يربطها بالشر الغير طبيعي.`,
  },
  s32: {
    en: `She takes charge of the murder plot, instructing Macbeth to &ldquo;look like th&rsquo; innocent flower, / But be the serpent under&rsquo;t.&rdquo;`,
    ar: `تستحوذ على خطة القتل، وتوجه مكbeth لـ "يشبhim في صورة الزهرة البريئة، / لكن كن الحية تحته.`,
  },
  s34: { en: `Lady Macbeth`, ar: `لедى مكبث` },
  s35: {
    en: `Scene 6 — Duncan Arrives at Inverness`,
    ar: `الشِّن ستمعة — دانكان ي arrivé في إنفيرنيس`,
  },
  s36: {
    en: `Duncan&apos;s praise of the castle is deeply ironic &mdash; he is entering the site of his murder.`,
    ar: `مديح دانكان للقلاع عميق الحدادة &ndash; هو يدخل موقع مقتله.`,
  },
  s37: {
    en: `Lady Macbeth successfully performs the role of gracious host, demonstrating her skill at deception.`,
    ar: `لедى مكبث تنفذ دور الضيفة اللطيفة بنجاح، وتظهر مهارتها في الخداع.`,
  },
  s39: {
    en: `Scene 7 — &ldquo;If It Were Done&rdquo; &mdash; The Decision`,
    ar: `الشِّهَادَةُ السَّابِعَةُ — "إذا كان مفعولاً" — اتِّخَاذُ الْحُكْمِ`,
  },
  s40: {
    en: `Macbeth decides against the murder &mdash; then is persuaded back by Lady Macbeth.`,
    ar: `ماكبث يقرر عدم ارتكاب القتل &mdash; ثم يتم إقناعه بالعودة من قبل لедى ماكبث.`,
  },
  s41: {
    en: `This is the turning point of Act 1: the decision to kill Duncan is made.`,
    ar: `هذا هو نقطة التحول في الفعل الأول: قرار قتل دنكان يتخذ.`,
  },
  s42: {
    en: `Lady Macbeth&apos;s manipulation of gender expectations is at its most powerful.`,
    ar: `تReach the manipulation اللي لادى مكbeth ل género المتوقعاتها هي في أقوى حالاتها. 

(Note: There seems to be a mix-up in the translation attempt above, let me correct it properly)

تحايل لادى مكbeth على توقعات الجنس هي في أقوى حالاتها.`,
  },
  s43: {
    en: `The practical plan for the murder is established.`,
    ar: `خطة ارتكاب الجريمة ت-established`,
  },
  s44: { en: `Guilt &amp; Conscience`, ar: `الذنب والضمير` },
  s45: { en: `Practice Exam Questions — Act 1`, ar: `أسئلة الامتحان التدريبية — المشهد الأول` },
  s46: {
    en: `Starting with the witches&apos; opening scene, explore how Shakespeare uses the supernatural to create a sense of moral disorder in Act 1. Refer closely to the language of the text in your answer.`,
    ar: `بالبدء من مشهد الساحرات في البداية، شوف كيف يستخدم شكسبير العالم الغيبي لإنشاء حس من الفوضى الأخلاقية في الفصل الأول. استند بقوة على لغة النص في إجابتك.`,
  },
}
