// ─── AI Disclaimer ──────────────────────────────────────────────────────
// Standard disclaimer text appended to all AI-generated feedback.

export const AI_DISCLAIMER =
  "This feedback is generated by AI and is for practice purposes only. " +
  "It does not represent an official exam board assessment. " +
  "Actual exam results may differ.";

export const AI_DISCLAIMER_HTML = `<p class="ai-disclaimer">${AI_DISCLAIMER}</p>`;

/**
 * Returns the disclaimer text, optionally including the exam board name
 * for additional clarity.
 */
export function getDisclaimer(examBoard?: string): string {
  if (examBoard) {
    return (
      `This feedback is generated by AI and is for practice purposes only. ` +
      `It does not represent an official ${examBoard} assessment. ` +
      `Actual exam results may differ.`
    );
  }
  return AI_DISCLAIMER;
}
