import type { LessonPlan } from "@/types"

/**
 * Converts a LessonPlan object into a nicely formatted plain-text document
 * covering every section: objectives, activities with differentiation,
 * worksheet questions, homework, and teacher notes.
 */
export function generateLessonPlanText(lesson: LessonPlan): string {
  const lines: string[] = []
  const rule = "=".repeat(60)
  const thinRule = "-".repeat(40)

  lines.push(rule)
  lines.push(lesson.title.toUpperCase())
  lines.push(rule)
  lines.push("")
  lines.push(`Text:        ${lesson.text}`)
  lines.push(`Board:       ${lesson.board}`)
  lines.push(`Year Group:  ${lesson.yearGroup}`)
  lines.push(`Duration:    ${lesson.duration}`)
  lines.push("")

  // Objectives
  lines.push(thinRule)
  lines.push("LEARNING OBJECTIVES")
  lines.push(thinRule)
  lesson.objectives.forEach((obj, i) => {
    lines.push(`  ${i + 1}. ${obj}`)
  })
  lines.push("")

  // Success Criteria
  lines.push(thinRule)
  lines.push("SUCCESS CRITERIA")
  lines.push(thinRule)
  lesson.successCriteria.forEach((sc, i) => {
    lines.push(`  ${i + 1}. ${sc}`)
  })
  lines.push("")

  // Keywords
  lines.push(thinRule)
  lines.push("KEY VOCABULARY")
  lines.push(thinRule)
  lines.push(`  ${lesson.keywords.join(", ")}`)
  lines.push("")

  // Targeted Skills
  if (lesson.targetedSkills.length > 0) {
    lines.push(thinRule)
    lines.push("TARGETED SKILLS")
    lines.push(thinRule)
    lesson.targetedSkills.forEach((skill) => {
      lines.push(`  - ${skill}`)
    })
    lines.push("")
  }

  // Starter Activity
  lines.push(thinRule)
  lines.push("STARTER ACTIVITY")
  lines.push(thinRule)
  lines.push(...formatActivity(lesson.starterActivity))
  lines.push("")

  // Main Activities
  lines.push(thinRule)
  lines.push("MAIN ACTIVITIES")
  lines.push(thinRule)
  lesson.mainActivities.forEach((activity, i) => {
    lines.push(`  Activity ${i + 1}:`)
    lines.push(...formatActivity(activity))
    lines.push("")
  })

  // Plenary Activity
  lines.push(thinRule)
  lines.push("PLENARY ACTIVITY")
  lines.push(thinRule)
  lines.push(...formatActivity(lesson.plenaryActivity))
  lines.push("")

  // Homework
  if (lesson.homework) {
    lines.push(thinRule)
    lines.push("HOMEWORK")
    lines.push(thinRule)
    lines.push(`  ${lesson.homework}`)
    lines.push("")
  }

  // Worksheet Questions
  if (lesson.worksheetQuestions.length > 0) {
    lines.push(thinRule)
    lines.push("WORKSHEET QUESTIONS")
    lines.push(thinRule)
    lesson.worksheetQuestions.forEach((q, i) => {
      const marksLabel = q.marks ? ` [${q.marks} mark${q.marks > 1 ? "s" : ""}]` : ""
      lines.push(`  ${i + 1}. ${q.question}${marksLabel}`)
      lines.push(`     (${q.lines} line${q.lines > 1 ? "s" : ""} for answer)`)
      if (q.modelAnswer) {
        lines.push(`     Model answer: ${q.modelAnswer}`)
      }
      lines.push("")
    })
  }

  // Teacher Notes
  if (lesson.teacherNotes.length > 0) {
    lines.push(thinRule)
    lines.push("TEACHER NOTES")
    lines.push(thinRule)
    lesson.teacherNotes.forEach((note) => {
      lines.push(`  - ${note}`)
    })
    lines.push("")
  }

  lines.push(rule)
  lines.push("Generated by The English Hub | theenglishhub.app")
  lines.push(rule)

  return lines.join("\n")
}

/**
 * Extracts just the worksheet questions from a lesson plan, formatted as a
 * standalone student worksheet with marks and model answers.
 */
export function generateWorksheetText(lesson: LessonPlan): string {
  const lines: string[] = []
  const rule = "=".repeat(60)
  const thinRule = "-".repeat(40)

  lines.push(rule)
  lines.push(`WORKSHEET: ${lesson.title.toUpperCase()}`)
  lines.push(rule)
  lines.push("")
  lines.push(`Text:  ${lesson.text}`)
  lines.push(`Name:  ____________________________    Date: __________`)
  lines.push("")

  if (lesson.worksheetQuestions.length === 0) {
    lines.push("No worksheet questions available for this lesson.")
    return lines.join("\n")
  }

  let totalMarks = 0

  lines.push(thinRule)
  lines.push("QUESTIONS")
  lines.push(thinRule)
  lines.push("")

  lesson.worksheetQuestions.forEach((q, i) => {
    const marksLabel = q.marks ? ` [${q.marks} mark${q.marks > 1 ? "s" : ""}]` : ""
    if (q.marks) totalMarks += q.marks
    lines.push(`${i + 1}. ${q.question}${marksLabel}`)
    lines.push("")
    for (let l = 0; l < q.lines; l++) {
      lines.push("   ___________________________________________________________")
    }
    lines.push("")
  })

  if (totalMarks > 0) {
    lines.push(thinRule)
    lines.push(`TOTAL MARKS: _____ / ${totalMarks}`)
    lines.push(thinRule)
    lines.push("")
  }

  // Model answers section
  const answeredQuestions = lesson.worksheetQuestions.filter((q) => q.modelAnswer)
  if (answeredQuestions.length > 0) {
    lines.push("")
    lines.push(rule)
    lines.push("MODEL ANSWERS (TEACHER COPY)")
    lines.push(rule)
    lines.push("")
    lesson.worksheetQuestions.forEach((q, i) => {
      if (q.modelAnswer) {
        lines.push(`${i + 1}. ${q.modelAnswer}`)
        lines.push("")
      }
    })
  }

  lines.push(rule)
  lines.push("Generated by The English Hub | theenglishhub.app")
  lines.push(rule)

  return lines.join("\n")
}

/**
 * Creates a text/plain Blob from the given content string and triggers a
 * browser download with the specified filename.
 */
export function downloadAsTextFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ─── Internal helpers ────────────────────────────────────────────────────────

function formatActivity(activity: {
  title: string
  duration: string
  instructions: string
  differentiation?: { support: string; core: string; stretch: string }
  resources?: string[]
}): string[] {
  const lines: string[] = []
  lines.push(`  Title:        ${activity.title}`)
  lines.push(`  Duration:     ${activity.duration}`)
  lines.push(`  Instructions: ${activity.instructions}`)

  if (activity.differentiation) {
    lines.push("  Differentiation:")
    lines.push(`    Support:  ${activity.differentiation.support}`)
    lines.push(`    Core:     ${activity.differentiation.core}`)
    lines.push(`    Stretch:  ${activity.differentiation.stretch}`)
  }

  if (activity.resources && activity.resources.length > 0) {
    lines.push("  Resources:")
    activity.resources.forEach((r) => {
      lines.push(`    - ${r}`)
    })
  }

  return lines
}
