import type { LessonPlan } from "@/types"

/**
 * Converts a LessonPlan object into a nicely formatted plain-text document
 * covering every section: objectives, activities with differentiation,
 * worksheet questions, homework, and teacher notes.
 */
export function generateLessonPlanText(lesson: LessonPlan): string {
  const lines: string[] = []
  const rule = "=".repeat(60)
  const thinRule = "-".repeat(40)

  lines.push(rule)
  lines.push(lesson.title.toUpperCase())
  lines.push(rule)
  lines.push("")
  lines.push(`Text:        ${lesson.text}`)
  lines.push(`Board:       ${lesson.board}`)
  lines.push(`Year Group:  ${lesson.yearGroup}`)
  lines.push(`Duration:    ${lesson.duration}`)
  lines.push("")

  // Objectives
  lines.push(thinRule)
  lines.push("LEARNING OBJECTIVES")
  lines.push(thinRule)
  lesson.objectives.forEach((obj, i) => {
    lines.push(`  ${i + 1}. ${obj}`)
  })
  lines.push("")

  // Success Criteria
  lines.push(thinRule)
  lines.push("SUCCESS CRITERIA")
  lines.push(thinRule)
  lesson.successCriteria.forEach((sc, i) => {
    lines.push(`  ${i + 1}. ${sc}`)
  })
  lines.push("")

  // Keywords
  lines.push(thinRule)
  lines.push("KEY VOCABULARY")
  lines.push(thinRule)
  lines.push(`  ${lesson.keywords.join(", ")}`)
  lines.push("")

  // Targeted Skills
  if (lesson.targetedSkills.length > 0) {
    lines.push(thinRule)
    lines.push("TARGETED SKILLS")
    lines.push(thinRule)
    lesson.targetedSkills.forEach((skill) => {
      lines.push(`  - ${skill}`)
    })
    lines.push("")
  }

  // Starter Activity
  lines.push(thinRule)
  lines.push("STARTER ACTIVITY")
  lines.push(thinRule)
  lines.push(...formatActivity(lesson.starterActivity))
  lines.push("")

  // Main Activities
  lines.push(thinRule)
  lines.push("MAIN ACTIVITIES")
  lines.push(thinRule)
  lesson.mainActivities.forEach((activity, i) => {
    lines.push(`  Activity ${i + 1}:`)
    lines.push(...formatActivity(activity))
    lines.push("")
  })

  // Plenary Activity
  lines.push(thinRule)
  lines.push("PLENARY ACTIVITY")
  lines.push(thinRule)
  lines.push(...formatActivity(lesson.plenaryActivity))
  lines.push("")

  // Homework
  if (lesson.homework) {
    lines.push(thinRule)
    lines.push("HOMEWORK")
    lines.push(thinRule)
    lines.push(`  ${lesson.homework}`)
    lines.push("")
  }

  // Worksheet Questions
  if (lesson.worksheetQuestions.length > 0) {
    lines.push(thinRule)
    lines.push("WORKSHEET QUESTIONS")
    lines.push(thinRule)
    lesson.worksheetQuestions.forEach((q, i) => {
      const marksLabel = q.marks ? ` [${q.marks} mark${q.marks > 1 ? "s" : ""}]` : ""
      lines.push(`  ${i + 1}. ${q.question}${marksLabel}`)
      lines.push(`     (${q.lines} line${q.lines > 1 ? "s" : ""} for answer)`)
      if (q.modelAnswer) {
        lines.push(`     Model answer: ${q.modelAnswer}`)
      }
      lines.push("")
    })
  }

  // Teacher Notes
  if (lesson.teacherNotes.length > 0) {
    lines.push(thinRule)
    lines.push("TEACHER NOTES")
    lines.push(thinRule)
    lesson.teacherNotes.forEach((note) => {
      lines.push(`  - ${note}`)
    })
    lines.push("")
  }

  lines.push(rule)
  lines.push("Generated by The English Hub | theenglishhub.app")
  lines.push(rule)

  return lines.join("\n")
}

/**
 * Extracts just the worksheet questions from a lesson plan, formatted as a
 * standalone student worksheet with marks and model answers.
 */
export function generateWorksheetText(lesson: LessonPlan): string {
  const lines: string[] = []
  const rule = "=".repeat(60)
  const thinRule = "-".repeat(40)

  lines.push(rule)
  lines.push(`WORKSHEET: ${lesson.title.toUpperCase()}`)
  lines.push(rule)
  lines.push("")
  lines.push(`Text:  ${lesson.text}`)
  lines.push(`Name:  ____________________________    Date: __________`)
  lines.push("")

  if (lesson.worksheetQuestions.length === 0) {
    lines.push("No worksheet questions available for this lesson.")
    return lines.join("\n")
  }

  let totalMarks = 0

  lines.push(thinRule)
  lines.push("QUESTIONS")
  lines.push(thinRule)
  lines.push("")

  lesson.worksheetQuestions.forEach((q, i) => {
    const marksLabel = q.marks ? ` [${q.marks} mark${q.marks > 1 ? "s" : ""}]` : ""
    if (q.marks) totalMarks += q.marks
    lines.push(`${i + 1}. ${q.question}${marksLabel}`)
    lines.push("")
    for (let l = 0; l < q.lines; l++) {
      lines.push("   ___________________________________________________________")
    }
    lines.push("")
  })

  if (totalMarks > 0) {
    lines.push(thinRule)
    lines.push(`TOTAL MARKS: _____ / ${totalMarks}`)
    lines.push(thinRule)
    lines.push("")
  }

  // Model answers section
  const answeredQuestions = lesson.worksheetQuestions.filter((q) => q.modelAnswer)
  if (answeredQuestions.length > 0) {
    lines.push("")
    lines.push(rule)
    lines.push("MODEL ANSWERS (TEACHER COPY)")
    lines.push(rule)
    lines.push("")
    lesson.worksheetQuestions.forEach((q, i) => {
      if (q.modelAnswer) {
        lines.push(`${i + 1}. ${q.modelAnswer}`)
        lines.push("")
      }
    })
  }

  lines.push(rule)
  lines.push("Generated by The English Hub | theenglishhub.app")
  lines.push(rule)

  return lines.join("\n")
}

/**
 * Creates a text/plain Blob from the given content string and triggers a
 * browser download with the specified filename.
 */
export function downloadAsTextFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

/**
 * Opens a formatted HTML document in a new window with print styling,
 * allowing the user to save it as a PDF using the browser's native
 * "Save as PDF" print option.
 *
 * @param title - Document title shown in the print header and tab
 * @param htmlBody - Inner HTML content (headings, paragraphs, tables, etc.)
 * @param options - Optional branding and layout settings
 */
export function openPrintableDocument(
  title: string,
  htmlBody: string,
  options?: {
    subtitle?: string
    footer?: string
  }
): void {
  const subtitle = options?.subtitle ?? ""
  const footer = options?.footer ?? "Generated by The English Hub | theenglishhub.app"

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${escapeHtml(title)}</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    font-size: 11pt;
    line-height: 1.55;
    color: #1a1a1a;
    padding: 40px;
    max-width: 800px;
    margin: 0 auto;
  }
  .doc-header {
    border-bottom: 3px solid #1a1a1a;
    padding-bottom: 16px;
    margin-bottom: 24px;
  }
  .doc-header h1 {
    font-size: 22pt;
    font-weight: 700;
    line-height: 1.2;
    margin-bottom: 4px;
  }
  .doc-header .subtitle {
    font-size: 11pt;
    color: #555;
  }
  h2 {
    font-size: 14pt;
    font-weight: 700;
    margin-top: 28px;
    margin-bottom: 10px;
    padding-bottom: 4px;
    border-bottom: 1px solid #ccc;
  }
  h3 {
    font-size: 12pt;
    font-weight: 600;
    margin-top: 20px;
    margin-bottom: 8px;
  }
  p, li { margin-bottom: 6px; }
  ul, ol { padding-left: 24px; margin-bottom: 12px; }
  .section { margin-bottom: 20px; }
  .activity-box {
    border: 1px solid #ccc;
    border-radius: 6px;
    padding: 14px;
    margin-bottom: 14px;
    background: #fafafa;
  }
  .activity-box .label {
    font-weight: 700;
    font-size: 10pt;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: #555;
    margin-bottom: 6px;
  }
  .diff-grid {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    gap: 8px;
    margin-top: 10px;
  }
  .diff-box {
    border: 1px solid #ddd;
    border-radius: 4px;
    padding: 8px;
    font-size: 9pt;
  }
  .diff-box .diff-label {
    font-weight: 700;
    margin-bottom: 3px;
    font-size: 9pt;
  }
  .diff-box.support .diff-label { color: #2563eb; }
  .diff-box.core .diff-label { color: #059669; }
  .diff-box.stretch .diff-label { color: #7c3aed; }
  .badge {
    display: inline-block;
    background: #f0f0f0;
    border: 1px solid #ddd;
    border-radius: 4px;
    padding: 2px 8px;
    font-size: 9pt;
    margin-right: 6px;
    margin-bottom: 4px;
  }
  .answer-line {
    border-bottom: 1px solid #999;
    height: 28px;
    margin-bottom: 4px;
  }
  .quote-block {
    border-left: 3px solid #666;
    padding-left: 12px;
    margin: 8px 0;
    font-style: italic;
  }
  .quote-speaker { font-style: normal; font-weight: 600; color: #333; }
  .quote-sig { font-style: normal; font-size: 9pt; color: #666; margin-top: 2px; }
  table {
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0;
    font-size: 10pt;
  }
  table th, table td {
    border: 1px solid #ccc;
    padding: 6px 10px;
    text-align: left;
  }
  table th {
    background: #f5f5f5;
    font-weight: 600;
  }
  .doc-footer {
    margin-top: 40px;
    padding-top: 12px;
    border-top: 1px solid #ccc;
    font-size: 9pt;
    color: #888;
    text-align: center;
  }
  .no-print { margin-bottom: 20px; text-align: center; }
  .no-print button {
    background: #1a1a1a;
    color: white;
    border: none;
    padding: 10px 28px;
    font-size: 11pt;
    font-weight: 600;
    border-radius: 6px;
    cursor: pointer;
    margin: 0 6px;
  }
  .no-print button:hover { background: #333; }
  .no-print .hint {
    font-size: 9pt;
    color: #888;
    margin-top: 8px;
  }
  @media print {
    body { padding: 0; }
    .no-print { display: none !important; }
    .activity-box { break-inside: avoid; }
    .diff-grid { break-inside: avoid; }
  }
</style>
</head>
<body>
  <div class="no-print">
    <button onclick="window.print()">Save as PDF / Print</button>
    <p class="hint">Tip: In the print dialog, select "Save as PDF" as the destination to download a PDF file.</p>
  </div>
  <div class="doc-header">
    <h1>${escapeHtml(title)}</h1>
    ${subtitle ? `<p class="subtitle">${escapeHtml(subtitle)}</p>` : ""}
  </div>
  ${htmlBody}
  <div class="doc-footer">${escapeHtml(footer)}</div>
</body>
</html>`

  const w = window.open("", "_blank")
  if (w) {
    w.document.write(html)
    w.document.close()
  }
}

/** Escape HTML special characters to prevent XSS in generated documents. */
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;")
}

// ─── Internal helpers ────────────────────────────────────────────────────────

function formatActivity(activity: {
  title: string
  duration: string
  instructions: string
  differentiation?: { support: string; core: string; stretch: string }
  resources?: string[]
}): string[] {
  const lines: string[] = []
  lines.push(`  Title:        ${activity.title}`)
  lines.push(`  Duration:     ${activity.duration}`)
  lines.push(`  Instructions: ${activity.instructions}`)

  if (activity.differentiation) {
    lines.push("  Differentiation:")
    lines.push(`    Support:  ${activity.differentiation.support}`)
    lines.push(`    Core:     ${activity.differentiation.core}`)
    lines.push(`    Stretch:  ${activity.differentiation.stretch}`)
  }

  if (activity.resources && activity.resources.length > 0) {
    lines.push("  Resources:")
    activity.resources.forEach((r) => {
      lines.push(`    - ${r}`)
    })
  }

  return lines
}
