-- ============================================================
-- THE ENGLISH HUB — NEW AFFILIATE PROGRAMME (percentage-tier)
-- Migration: 002_affiliates (PENDING — DO NOT APPLY WITHOUT REVIEW)
-- ============================================================
--
-- This migration introduces a NEW affiliate system that lives ALONGSIDE the
-- existing Rewardful-backed system defined in
--   supabase/migrations/002_affiliate_system.sql
-- The old system uses integer tiers (1/2/3) with flat GBP rates per plan.
-- This new system uses percentage tiers (Bronze 10%, Silver 15%, Gold 25%)
-- keyed on total confirmed referral count.
--
-- All tables are namespaced under `affiliate_*` (singular) and do NOT touch
-- the legacy `affiliates` / `affiliate_referrals` / `affiliate_payouts` tables
-- from the prior migration, which have been renamed here by prefixing — the
-- migration author MUST choose between:
--   (a) dropping the legacy tables before applying this file, or
--   (b) renaming the tables below to namespaced equivalents (e.g. affiliate_accounts_v2).
-- See `src/app/api/affiliate/README.md` for the rollout checklist.
--
-- NOTE: This file lives in `migrations-pending/` and is NOT auto-applied by
-- Supabase CLI. Move to `migrations/` only after resolving the naming
-- conflict with the existing Rewardful migration.
-- ============================================================

-- Extension for gen_random_uuid() — should already be enabled in production
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ------------------------------------------------------------
-- affiliate_accounts — one row per affiliate (applicant or active)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.affiliate_accounts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,

  -- Public referral code used in ?ref=<code>. Short, URL-safe, unique.
  code TEXT UNIQUE NOT NULL DEFAULT substr(replace(gen_random_uuid()::text, '-', ''), 1, 10),

  -- Applicant details
  full_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  website TEXT,
  social_handle TEXT,
  audience_size BIGINT,
  audience_description TEXT NOT NULL,
  promo_strategy TEXT NOT NULL,

  -- Programme state
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'active', 'suspended', 'terminated', 'rejected')),
  tier TEXT NOT NULL DEFAULT 'bronze'
    CHECK (tier IN ('bronze', 'silver', 'gold')),

  -- Cached counter — recomputed by a trigger/cron. Used for tier-gating fast path.
  confirmed_referral_count INTEGER NOT NULL DEFAULT 0,

  -- Payout details (PII — guarded by RLS)
  payout_method TEXT NOT NULL DEFAULT 'bank_transfer'
    CHECK (payout_method IN ('bank_transfer', 'paypal', 'stripe_connect')),
  payout_email TEXT,
  bank_account_name TEXT,
  bank_sort_code TEXT,
  bank_account_number TEXT,
  stripe_connect_account_id TEXT,

  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  approved_at TIMESTAMPTZ,
  terminated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_affiliate_accounts_user_id
  ON public.affiliate_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_accounts_status
  ON public.affiliate_accounts(status);
CREATE INDEX IF NOT EXISTS idx_affiliate_accounts_code
  ON public.affiliate_accounts(code);

-- ------------------------------------------------------------
-- affiliate_links — trackable links generated by affiliates
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.affiliate_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  affiliate_id UUID NOT NULL REFERENCES public.affiliate_accounts(id) ON DELETE CASCADE,

  -- Short token used in short URLs (/r/<token>)
  token TEXT UNIQUE NOT NULL DEFAULT substr(replace(gen_random_uuid()::text, '-', ''), 1, 8),

  target_path TEXT NOT NULL DEFAULT '/',
  campaign TEXT,
  medium TEXT,
  label TEXT,

  click_count INTEGER NOT NULL DEFAULT 0,
  conversion_count INTEGER NOT NULL DEFAULT 0,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_clicked_at TIMESTAMPTZ,
  archived_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_affiliate_links_affiliate_id
  ON public.affiliate_links(affiliate_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_links_token
  ON public.affiliate_links(token);

-- ------------------------------------------------------------
-- affiliate_clicks — append-only click log
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.affiliate_clicks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  affiliate_id UUID NOT NULL REFERENCES public.affiliate_accounts(id) ON DELETE CASCADE,
  link_id UUID REFERENCES public.affiliate_links(id) ON DELETE SET NULL,

  -- Salted hash only — never store raw IPs
  ip_hash TEXT,
  user_agent TEXT,
  referrer TEXT,
  landing_path TEXT,

  -- Resolved attribution metadata for debugging
  country TEXT,
  device TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_affiliate_id
  ON public.affiliate_clicks(affiliate_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_link_id
  ON public.affiliate_clicks(link_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_created_at
  ON public.affiliate_clicks(created_at DESC);

-- ------------------------------------------------------------
-- affiliate_conversions — paid conversions linked to an affiliate
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.affiliate_conversions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  affiliate_id UUID NOT NULL REFERENCES public.affiliate_accounts(id) ON DELETE RESTRICT,
  link_id UUID REFERENCES public.affiliate_links(id) ON DELETE SET NULL,

  -- Idempotency key — typically the Stripe checkout session ID
  external_id TEXT UNIQUE NOT NULL,

  -- Amounts (minor units to avoid floating point)
  order_value_pence BIGINT NOT NULL CHECK (order_value_pence >= 0),
  commission_pence BIGINT NOT NULL CHECK (commission_pence >= 0),
  commission_rate NUMERIC(5,4) NOT NULL CHECK (commission_rate >= 0 AND commission_rate <= 1),
  tier_at_conversion TEXT NOT NULL CHECK (tier_at_conversion IN ('bronze', 'silver', 'gold')),
  currency TEXT NOT NULL DEFAULT 'gbp',

  product_type TEXT CHECK (product_type IN ('subscription', 'one_time', 'course')),
  referred_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,

  -- Attribution context (snapshot at conversion time)
  attribution_model TEXT NOT NULL DEFAULT 'last-touch'
    CHECK (attribution_model IN ('first-touch', 'last-touch')),
  touched_at TIMESTAMPTZ,

  -- Lifecycle: pending -> confirmed -> paid, or -> voided/refunded
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'confirmed', 'paid', 'voided', 'refunded')),
  voided_reason TEXT,

  -- Payout batch linkage (nullable until included in a payout)
  payout_id UUID,

  metadata JSONB,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  confirmed_at TIMESTAMPTZ,
  paid_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_affiliate_conversions_affiliate_id
  ON public.affiliate_conversions(affiliate_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_conversions_link_id
  ON public.affiliate_conversions(link_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_conversions_status
  ON public.affiliate_conversions(status);
CREATE INDEX IF NOT EXISTS idx_affiliate_conversions_external_id
  ON public.affiliate_conversions(external_id);

-- ------------------------------------------------------------
-- affiliate_payouts — one row per payout batch per affiliate
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.affiliate_payouts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  affiliate_id UUID NOT NULL REFERENCES public.affiliate_accounts(id) ON DELETE RESTRICT,

  period_start DATE NOT NULL,
  period_end DATE NOT NULL CHECK (period_end >= period_start),

  conversion_count INTEGER NOT NULL DEFAULT 0,
  amount_pence BIGINT NOT NULL DEFAULT 0 CHECK (amount_pence >= 0),
  currency TEXT NOT NULL DEFAULT 'gbp',

  status TEXT NOT NULL DEFAULT 'calculated'
    CHECK (status IN ('calculated', 'approved', 'paid', 'failed', 'cancelled')),
  payment_method TEXT,
  payment_reference TEXT,

  approved_by TEXT,
  approved_at TIMESTAMPTZ,
  paid_at TIMESTAMPTZ,
  failed_reason TEXT,

  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_affiliate_payouts_affiliate_id
  ON public.affiliate_payouts(affiliate_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_payouts_status
  ON public.affiliate_payouts(status);
CREATE INDEX IF NOT EXISTS idx_affiliate_payouts_period
  ON public.affiliate_payouts(period_start, period_end);

-- FK from conversions to payouts now that the table exists
ALTER TABLE public.affiliate_conversions
  DROP CONSTRAINT IF EXISTS fk_affiliate_conversions_payout,
  ADD CONSTRAINT fk_affiliate_conversions_payout
    FOREIGN KEY (payout_id) REFERENCES public.affiliate_payouts(id)
    ON DELETE SET NULL;

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.affiliate_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_clicks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_conversions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_payouts ENABLE ROW LEVEL SECURITY;

-- affiliate_accounts ---------------------------------------------------------
-- Affiliates can read their own row (PII excluded from anon policies)
DROP POLICY IF EXISTS "affiliate_accounts_select_own" ON public.affiliate_accounts;
CREATE POLICY "affiliate_accounts_select_own"
  ON public.affiliate_accounts FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "affiliate_accounts_update_own" ON public.affiliate_accounts;
CREATE POLICY "affiliate_accounts_update_own"
  ON public.affiliate_accounts FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Service role bypasses RLS automatically, but keeping an explicit ALL policy
-- makes intent clear to auditors.
DROP POLICY IF EXISTS "affiliate_accounts_service_all" ON public.affiliate_accounts;
CREATE POLICY "affiliate_accounts_service_all"
  ON public.affiliate_accounts FOR ALL
  USING ((SELECT current_setting('role', true)) = 'service_role')
  WITH CHECK ((SELECT current_setting('role', true)) = 'service_role');

-- affiliate_links ------------------------------------------------------------
DROP POLICY IF EXISTS "affiliate_links_select_own" ON public.affiliate_links;
CREATE POLICY "affiliate_links_select_own"
  ON public.affiliate_links FOR SELECT
  USING (
    affiliate_id IN (SELECT id FROM public.affiliate_accounts WHERE user_id = auth.uid())
  );

DROP POLICY IF EXISTS "affiliate_links_insert_own" ON public.affiliate_links;
CREATE POLICY "affiliate_links_insert_own"
  ON public.affiliate_links FOR INSERT
  WITH CHECK (
    affiliate_id IN (SELECT id FROM public.affiliate_accounts WHERE user_id = auth.uid())
  );

DROP POLICY IF EXISTS "affiliate_links_service_all" ON public.affiliate_links;
CREATE POLICY "affiliate_links_service_all"
  ON public.affiliate_links FOR ALL
  USING ((SELECT current_setting('role', true)) = 'service_role')
  WITH CHECK ((SELECT current_setting('role', true)) = 'service_role');

-- affiliate_clicks -----------------------------------------------------------
DROP POLICY IF EXISTS "affiliate_clicks_select_own" ON public.affiliate_clicks;
CREATE POLICY "affiliate_clicks_select_own"
  ON public.affiliate_clicks FOR SELECT
  USING (
    affiliate_id IN (SELECT id FROM public.affiliate_accounts WHERE user_id = auth.uid())
  );

DROP POLICY IF EXISTS "affiliate_clicks_service_all" ON public.affiliate_clicks;
CREATE POLICY "affiliate_clicks_service_all"
  ON public.affiliate_clicks FOR ALL
  USING ((SELECT current_setting('role', true)) = 'service_role')
  WITH CHECK ((SELECT current_setting('role', true)) = 'service_role');

-- affiliate_conversions ------------------------------------------------------
DROP POLICY IF EXISTS "affiliate_conversions_select_own" ON public.affiliate_conversions;
CREATE POLICY "affiliate_conversions_select_own"
  ON public.affiliate_conversions FOR SELECT
  USING (
    affiliate_id IN (SELECT id FROM public.affiliate_accounts WHERE user_id = auth.uid())
  );

DROP POLICY IF EXISTS "affiliate_conversions_service_all" ON public.affiliate_conversions;
CREATE POLICY "affiliate_conversions_service_all"
  ON public.affiliate_conversions FOR ALL
  USING ((SELECT current_setting('role', true)) = 'service_role')
  WITH CHECK ((SELECT current_setting('role', true)) = 'service_role');

-- affiliate_payouts ----------------------------------------------------------
DROP POLICY IF EXISTS "affiliate_payouts_select_own" ON public.affiliate_payouts;
CREATE POLICY "affiliate_payouts_select_own"
  ON public.affiliate_payouts FOR SELECT
  USING (
    affiliate_id IN (SELECT id FROM public.affiliate_accounts WHERE user_id = auth.uid())
  );

DROP POLICY IF EXISTS "affiliate_payouts_service_all" ON public.affiliate_payouts;
CREATE POLICY "affiliate_payouts_service_all"
  ON public.affiliate_payouts FOR ALL
  USING ((SELECT current_setting('role', true)) = 'service_role')
  WITH CHECK ((SELECT current_setting('role', true)) = 'service_role');

-- ============================================================
-- updated_at triggers — assumes public.update_updated_at() exists from 001
-- ============================================================

DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'update_updated_at') THEN
    EXECUTE 'DROP TRIGGER IF EXISTS affiliate_accounts_updated_at ON public.affiliate_accounts';
    EXECUTE 'CREATE TRIGGER affiliate_accounts_updated_at BEFORE UPDATE ON public.affiliate_accounts FOR EACH ROW EXECUTE FUNCTION public.update_updated_at()';

    EXECUTE 'DROP TRIGGER IF EXISTS affiliate_links_updated_at ON public.affiliate_links';
    EXECUTE 'CREATE TRIGGER affiliate_links_updated_at BEFORE UPDATE ON public.affiliate_links FOR EACH ROW EXECUTE FUNCTION public.update_updated_at()';

    EXECUTE 'DROP TRIGGER IF EXISTS affiliate_conversions_updated_at ON public.affiliate_conversions';
    EXECUTE 'CREATE TRIGGER affiliate_conversions_updated_at BEFORE UPDATE ON public.affiliate_conversions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at()';

    EXECUTE 'DROP TRIGGER IF EXISTS affiliate_payouts_updated_at ON public.affiliate_payouts';
    EXECUTE 'CREATE TRIGGER affiliate_payouts_updated_at BEFORE UPDATE ON public.affiliate_payouts FOR EACH ROW EXECUTE FUNCTION public.update_updated_at()';
  END IF;
END $$;

-- ============================================================
-- Helper: recompute confirmed_referral_count for a given affiliate
-- ============================================================

CREATE OR REPLACE FUNCTION public.recount_affiliate_referrals(p_affiliate_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*)::INTEGER
  INTO v_count
  FROM public.affiliate_conversions
  WHERE affiliate_id = p_affiliate_id
    AND status IN ('confirmed', 'paid');

  UPDATE public.affiliate_accounts
  SET confirmed_referral_count = v_count,
      tier = CASE
        WHEN v_count >= 25 THEN 'gold'
        WHEN v_count >= 5 THEN 'silver'
        ELSE 'bronze'
      END
  WHERE id = p_affiliate_id;

  RETURN v_count;
END;
$$;
