-- Remove old values no longer used
ALTER TYPE "ExamBoard" RENAME VALUE 'CAMBRIDGE' TO 'CAMBRIDGE_0500';
ALTER TYPE "ExamBoard" RENAME VALUE 'CAIE' TO 'CAMBRIDGE_0990';

-- Add new values
ALTER TYPE "ExamBoard" ADD VALUE IF NOT EXISTS 'EDUQAS';
ALTER TYPE "ExamBoard" ADD VALUE IF NOT EXISTS 'EDEXCEL_IGCSE';
