/**
 * EAL Mock Exam — A2 (A2 Key for Schools).
 *
 * Format anchor: Cambridge English Qualifications A2 Key for Schools —
 *   Reading & Use of English, Writing, Listening, Speaking sections,
 *   with the standard task counts and timings.
 * https://www.cambridgeenglish.org/exams-and-tests/qualifications/
 *
 * CEFR anchor: Council of Europe — Common European Framework of
 *   Reference for Languages — A2 band descriptors.
 * https://www.coe.int/en/web/common-european-framework-reference-languages/level-descriptions
 *
 * Scaffold rendered today. Practice content is generated by
 * generate_eal_mock_exam.py in Wave 6.
 */
import Link from 'next/link'
import { headers } from 'next/headers'

export default async function EALMockExamA2() {
  const lang = (await headers()).get('x-lang') === 'ar' ? 'ar' : 'en'

  const sections = [
    {
      slug: 'reading-use-of-english',
      en: 'Reading & Use of English',
      ar: 'القراءة والاستخدام',
      desc_en: 'Multi-task paper testing reading comprehension and grammar.',
      desc_ar: 'ورقة متعددة المهام تختبر فهم القراءة والقواعد.',
    },
    {
      slug: 'writing',
      en: 'Writing',
      ar: 'الكتابة',
      desc_en:
        'Extended-response writing tasks marked against task achievement, organisation, language.',
      desc_ar: 'مهام كتابة موسّعة تُقيَّم بحسب تحقيق المهمة، التنظيم، اللغة.',
    },
    {
      slug: 'listening',
      en: 'Listening',
      ar: 'الاستماع',
      desc_en: 'Audio comprehension across familiar and unfamiliar contexts.',
      desc_ar: 'فهم صوتي في سياقات مألوفة وغير مألوفة.',
    },
    {
      slug: 'speaking',
      en: 'Speaking',
      ar: 'المحادثة',
      desc_en: 'Paired and individual speaking tasks assessed against Cambridge speaking bands.',
      desc_ar: 'مهام محادثة فردية وثنائية تُقيَّم بمعايير كامبردج.',
    },
  ]

  return (
    <main className="mx-auto max-w-4xl px-6 py-12">
      <p className="font-mono text-[11px] tracking-[0.14em] uppercase text-teal-600 mb-3">
        <Link href="/eal">EAL · {lang === 'ar' ? 'الامتحانات التجريبية' : 'Mock exams'}</Link>
      </p>
      <h1 className="font-serif text-3xl sm:text-4xl font-bold tracking-tight mb-3">
        A2 {lang === 'ar' ? 'امتحان تجريبي' : 'Mock Exam'}
      </h1>
      <p className="text-sm rounded-lg border border-teal-300/30 bg-teal-500/[0.04] px-4 py-3 mb-6">
        <span className="font-mono text-[10px] uppercase tracking-wider text-teal-700">
          {lang === 'ar' ? 'النموذج' : 'Modelled on'}:{' '}
        </span>
        <span className="font-medium">Cambridge English A2 Key for Schools</span>
      </p>

      <div className="rounded-xl border border-amber-400/30 bg-amber-500/[0.04] p-5 mb-8">
        <p className="font-mono text-[10px] uppercase tracking-wider text-amber-700 mb-1">
          {lang === 'ar' ? 'قريباً' : 'Coming soon'}
        </p>
        <p className="text-sm text-foreground leading-relaxed">
          {lang === 'ar'
            ? 'الامتحان التجريبي قيد البناء — يولّد بواسطة سلسلة الموجات الذكية المحلية.'
            : 'This mock exam is being generated by the local AI wave pipeline. Check back in 6–48 hours.'}
        </p>
      </div>

      <h2 className="text-lg font-semibold mb-3">{lang === 'ar' ? 'الأقسام' : 'Sections'}</h2>
      <div className="grid sm:grid-cols-2 gap-3">
        {sections.map((s) => (
          <div key={s.slug} className="rounded-xl border border-border bg-card p-4">
            <p className="font-semibold text-foreground">{lang === 'ar' ? s.ar : s.en}</p>
            <p className="text-xs text-muted-foreground mt-1">
              {lang === 'ar' ? s.desc_ar : s.desc_en}
            </p>
          </div>
        ))}
      </div>

      <p className="mt-10 text-sm text-muted-foreground">
        <Link href="/eal" className="underline">
          ← {lang === 'ar' ? 'كل مواضيع EAL' : 'All EAL topics'}
        </Link>
      </p>
    </main>
  )
}

export const metadata = {
  title: `EAL Mock Exam — A2 — The English Hub`,
}
