/**
 * Year 9 — Mastery.
 *
 * Set text in T1: Robert Louis Stevenson's *The Strange Case of Dr
 * Jekyll and Mr Hyde* (1886). Deliberately a GCSE set text already,
 * so students entering Y10 have deep textual knowledge of a likely
 * exam text. Late-Victorian prose pushes vocabulary stamina; the
 * thematic range (duality, repression, Darwinism, urban Gothic,
 * reputation, the unconscious) gives space for conceptual readings
 * and contextual framing.
 *
 * Sentence-stem progression: Y9 moves to "This suggests… which
 * reflects…" — methods analysed across texts, conceptual
 * interpretations, evaluation.
 */

import type { Year, Lesson, LessonFocus } from './types'

type Quick = {
  focus: LessonFocus
  skills: string[]
  do: string
  task: string
  success: string
  doAr?: string
  taskAr?: string
  successAr?: string
}
const lesson = (q: Quick): Lesson => ({
  focus: q.focus,
  skillCodes: q.skills,
  whatStudentsDo: { en: q.do, ...(q.doAr ? { ar: q.doAr } : {}) },
  task: { en: q.task, ...(q.taskAr ? { ar: q.taskAr } : {}) },
  successCriteria: { en: q.success, ...(q.successAr ? { ar: q.successAr } : {}) },
})

const Y9_T1: Year['terms'][number] = {
  number: 1,
  label: { en: 'Term 1 — Autumn', ar: 'الفصل الدراسي الأول — الخريف' },
  overview: {
    en: "Year 9 opens with Stevenson's *Jekyll and Hyde* — a GCSE set text in its own right. Students write full literature essays by the end of Term 1: thesis-driven, embedded fluent quotations, methods analysis (language + structure + form), conceptual interpretations, evaluation. The novella's themes (duality, repression, Darwinism, urban Gothic) feed every Y9 reading skill simultaneously.",
    ar: 'تبدأ السنة التاسعة برواية ستيفنسون *Jekyll and Hyde* — نص مقرّر في GCSE. يكتب الطلاب مقالات أدبية كاملة بنهاية الفصل الأول.',
  },
  setText: { en: 'The Strange Case of Dr Jekyll and Mr Hyde by Robert Louis Stevenson (1886)' },
  vocabularyThemes: [
    { en: 'gothic, zeitgeist, duality, repression, fin-de-siècle, atavistic, juggernaut' },
    { en: 'allegory, microcosm, paradigm, subversion, anxiety, hubris, dichotomy' },
  ],
  bigSkillJump: {
    en: 'Students arrive writing analytical paragraphs; they exit writing full thesis-driven literature essays with sustained conceptual readings — the core GCSE Literature skill, embedded a year early.',
  },
  halfTerms: [
    {
      id: '1.1',
      label: { en: 'Term 1.1 — First half', ar: 'الفصل 1.1 — النصف الأول' },
      assessment: {
        en: 'Analytical essay 35-40 mins: "Starting with this extract, explore how Stevenson presents the duality of human nature in *Jekyll and Hyde*." Full essay structure: thesis-driven intro, 2-3 conceptual body paragraphs, brief conclusion.',
      },
      weeks: [
        {
          number: 2,
          pages: 'Pre-reading context pack + "Story of the Door" pp. 1-3',
          keyVocabulary: [
            { en: 'gothic', ar: 'قوطي' },
            { en: 'zeitgeist', ar: 'روح العصر' },
            { en: 'duality', ar: 'الازدواجية' },
            { en: 'repression', ar: 'الكبت' },
            { en: 'fin-de-siècle', ar: 'نهاية القرن' },
          ],
          contextNote: {
            en: 'Gothic conventions and Victorian zeitgeist.',
            ar: 'التقاليد القوطية وروح العصر الفيكتوري.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.7'],
              do: "Annotate context pack; map Gothic conventions onto Stevenson's London.",
              doAr: 'علِّق على ملف السياق، واربط التقاليد القوطية بصورة لندن عند Stevenson.',
              task: 'Identify 6 Gothic conventions in opening; cite 3 with textual evidence.',
              taskAr: 'حدِّد ٦ تقاليد قوطية في الافتتاح، واستشهد بثلاثة منها بدليل من النص.',
              success: 'Cites 3 conventions; uses *gothic*, *zeitgeist* accurately.',
              successAr: 'يستشهد بثلاثة تقاليد، ويوظِّف *gothic* و*zeitgeist* بدقّة.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.1'],
              do: 'Socratic seminar: "Why is the city itself a character?"',
              doAr: 'حلقة نقاش سقراطية: "لماذا تُعدّ المدينة نفسها شخصية؟"',
              task: 'Build, challenge, extend peer interpretations across 4+ minute discussion.',
              taskAr: 'ابنِ تفسيرات الزملاء وتحدَّها وطوِّرها خلال نقاش يتجاوز ٤ دقائق.',
              success: 'Develop AND challenge a peer idea; sustained 4+ minute discussion.',
              successAr: 'يطوِّر فكرة زميل ويتحدّاها معًا، ويُديم النقاش لأكثر من ٤ دقائق.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9W.5'],
              do: 'Deconstruct exemplar topic sentences; identify conceptual framing verbs.',
              doAr: 'فكِّك جُمل موضوع نموذجية، وحدِّد الأفعال التي تُؤطِّر المفهوم.',
              task: 'Rewrite 5 weak topic sentences using "Stevenson presents… in order to…".',
              taskAr:
                'أعِد كتابة ٥ جُمل موضوع ضعيفة باستخدام صيغة "Stevenson presents… in order to…".',
              success: 'Topic sentences foreground writer intent, not plot.',
              successAr: 'تُبرز جُمل الموضوع نيّة الكاتب، لا الحبكة.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.4', '9W.3'],
              do: "Annotate Utterson's introduction; draft conceptual topic sentence + supporting analysis.",
              doAr: 'علِّق على مقدّمة Utterson، واكتب جملة موضوع مفاهيمية مع تحليل مُساند.',
              task: 'Paragraph: How does Stevenson present Utterson as the embodiment of Victorian respectability?',
              taskAr: 'فقرة: كيف يقدّم Stevenson شخصية Utterson تجسيدًا للاحترام الفيكتوري؟',
              success: 'One conceptual paragraph with embedded quotation and "This reflects…".',
              successAr: 'فقرة مفاهيمية واحدة باقتباس مُدمج وعبارة "This reflects…".',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9R.4', '9W.3', '9W.10'],
              do: '25-minute independent extended paragraph, no scaffold.',
              doAr: 'فقرة مُوسَّعة مستقلّة في ٢٥ دقيقة، دون سقالة.',
              task: 'Explore how Stevenson establishes a Gothic atmosphere in the opening.',
              taskAr: 'استكشِف كيف يُرسي Stevenson أجواءً قوطية في الافتتاح.',
              success: '200+ words; two embedded quotations; conceptual reading articulated.',
              successAr: '٢٠٠ كلمة فأكثر، اقتباسان مُدمجان، وقراءة مفاهيمية واضحة.',
            }),
          ],
        },
        {
          number: 3,
          pages: '"Story of the Door" — Enfield\'s account of Hyde trampling the girl (pp. 4-8)',
          keyVocabulary: [
            { en: 'atavistic', ar: 'ارتدادي' },
            { en: 'juggernaut', ar: 'قوة جارفة' },
            { en: 'trampled', ar: 'مَداس' },
            { en: 'deformity', ar: 'تشوُّه' },
            { en: 'simian', ar: 'شبيه بالقرد' },
          ],
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.7'],
              do: "Close-read Enfield's description with word-class colour coding.",
              doAr: 'اقرأ وصف Enfield قراءةً دقيقة مع ترميز أقسام الكلام بالألوان.',
              task: 'Lexical-field analysis grid: animalistic / mechanical / supernatural.',
              taskAr: 'جدول تحليل الحقول الدلالية: حيواني / آلي / خارق للطبيعة.',
              success: 'Three semantic fields identified; link to Darwinian zeitgeist.',
              successAr: 'يُحدِّد ثلاثة حقول دلالية، ويربطها بروح العصر الداروينية.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.3'],
              do: 'Three-way reading: literal / Darwinian / colonial readings of "juggernaut".',
              doAr: 'قراءة ثلاثية لكلمة "juggernaut": حرفية / داروينية / استعمارية.',
              task: 'Structured debate: which reading is most powerful and why?',
              taskAr: 'مناظرة منظَّمة: أيّ القراءات أقوى ولماذا؟',
              success: 'Articulate two distinct interpretations; structured analytical register.',
              successAr: 'يصوغ تفسيرين متمايزين بسجلّ تحليلي منظَّم.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.4', '9R.2'],
              do: 'Compare clunky vs fluent quotation integration; transformation exercise.',
              doAr: 'قارن بين دمج الاقتباس المُتعثّر والمنساب، ثم تمرين تحويل.',
              task: 'Rewrite 8 sentences embedding quotations within syntax.',
              taskAr: 'أعِد كتابة ٨ جُمل بدمج الاقتباسات داخل التركيب النحوي.',
              success: 'All quotations embedded without "the quote says"; punctuation accurate.',
              successAr: 'كلّ الاقتباسات مُدمجة دون عبارة "the quote says"، والترقيم دقيق.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.4', '9W.3', '9W.10'],
              do: "Build PETAL paragraph on Hyde's dehumanisation; teacher live-models then fades.",
              doAr: 'ابنِ فقرة PETAL عن تجريد Hyde من إنسانيّته؛ يُجسّد المعلّم النموذج ثم يتراجع.',
              task: "Paragraph: how Stevenson dehumanises Hyde through Enfield's narration.",
              taskAr: 'فقرة: كيف يُجرِّد Stevenson شخصية Hyde من إنسانيّته عبر سرد Enfield.',
              success: 'Method named precisely; effect explored across two layers.',
              successAr: 'الأسلوب مُسمّى بدقّة، وأثره مستكشَف عبر طبقتين.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9R.4', '9W.3', '9W.7'],
              do: '30-minute timed paragraph, no scaffold.',
              doAr: 'فقرة مُحدَّدة بوقت ٣٠ دقيقة، دون سقالة.',
              task: 'How does Stevenson present Hyde as monstrous in "Story of the Door"?',
              taskAr: 'كيف يقدّم Stevenson شخصية Hyde بوصفها وحشية في "Story of the Door"؟',
              success: '250+ words; three embedded quotations; conceptual reading sustained.',
              successAr: '٢٥٠ كلمة فأكثر، ثلاثة اقتباسات مُدمجة، وقراءة مفاهيمية مُتواصلة.',
            }),
          ],
        },
        {
          number: 4,
          pages: '"Search for Mr Hyde" — Utterson\'s nightmare (pp. 9-17)',
          keyVocabulary: [
            { en: 'premonition', ar: 'هاجس' },
            { en: 'repression', ar: 'الكبت' },
            { en: 'foreshadowing', ar: 'التمهيد للأحداث' },
            { en: 'troglodytic', ar: 'كهفي بدائي' },
            { en: 'urbane', ar: 'مهذَّب' },
          ],
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.4', '9R.7'],
              do: 'Map narrative structure; identify proleptic imagery.',
              doAr: 'ارسم خريطة البنية السردية، وحدِّد الصور الاستباقية.',
              task: 'Storyboard the dream sequence; label structural devices.',
              taskAr: 'ارسم مشاهد الحلم، وضع تسميات للأدوات البنيوية.',
              success: 'Identifies *foreshadowing*, *prolepsis*, *symbolic dreaming*.',
              successAr: 'يُحدِّد *foreshadowing* و*prolepsis* و*symbolic dreaming*.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.1'],
              do: 'Mini-lecture on repression; Utterson as repressed Victorian.',
              doAr: 'محاضرة مصغّرة عن الكبت، وUtterson بوصفه فيكتوريًا مكبوتًا.',
              task: 'Talking-points carousel: 4 conceptual readings rotated.',
              taskAr: 'دوّامة نقاط نقاش: تداول ٤ قراءات مفاهيمية.',
              success: 'Engages with conceptual lens; challenges with textual evidence.',
              successAr: 'يتفاعل مع العدسة المفاهيمية، ويتحدّى بدليل من النص.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.2', '9W.4'],
              do: 'Combine simple sentences using subordination, parenthesis, semicolons.',
              doAr: 'ادمج جُمل بسيطة بالتبعية، والاعتراض، والفاصلة المنقوطة.',
              task: 'Rewrite 6 paragraphs using varied sentence forms deliberately.',
              taskAr: 'أعِد كتابة ٦ فقرات بأشكال جُملية متنوّعة قصدًا.',
              success: 'Demonstrates semi-colons, dashes, embedded clauses for effect.',
              successAr: 'يُظهر الفاصلة المنقوطة والشَّرطات والجُمل المُدمجة لإحداث أثر.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.4', '9W.3', '9W.10'],
              do: 'Write paragraph analysing structure AND language together.',
              doAr: 'اكتب فقرة تحلِّل البنية واللغة معًا.',
              task: 'How does Stevenson build dread in the chapter?',
              taskAr: 'كيف يبني Stevenson شعور الرّهبة في الفصل؟',
              success: 'One paragraph covering 2 methods with linked analysis.',
              successAr: 'فقرة واحدة تُغطّي أسلوبَين بتحليل مترابط.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9R.4', '9W.1', '9W.3'],
              do: 'Independent two-paragraph response with linking sentence.',
              doAr: 'استجابة مستقلّة من فقرتين مع جملة وصل.',
              task: "Explore how Stevenson presents Utterson's growing fear.",
              taskAr: 'استكشِف كيف يقدّم Stevenson خوف Utterson المتنامي.',
              success: 'Two paragraphs that genuinely link; conceptual framing throughout.',
              successAr: 'فقرتان مرتبطتان فعليًّا، بتأطير مفاهيمي طوال النص.',
            }),
          ],
        },
        {
          number: 5,
          pages: '"The Carew Murder Case" (pp. 21-25)',
          keyVocabulary: [
            { en: 'brandished', ar: 'لوَّح بـ' },
            { en: 'ape-like', ar: 'شبيه بالقرد' },
            { en: 'picturesque', ar: 'خلَّاب' },
            { en: 'savagery', ar: 'وحشية' },
            { en: 'gentility', ar: 'رقيّ الطبقة' },
          ],
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.4', '9R.7'],
              do: "Tone-mapping the maid's perspective; identify pathetic fallacy and irony.",
              doAr: 'ارسم خريطة نبرة منظور الخادمة، وحدِّد المغالطة العاطفية والسخرية.',
              task: 'Two-column contrast: aesthetic frame / brutal content.',
              taskAr: 'مقارنة من عمودين: الإطار الجمالي / المضمون الوحشي.',
              success: 'Names *juxtaposition*, *pathetic fallacy*; explains destabilising effect.',
              successAr: 'يُسمّي *juxtaposition* و*pathetic fallacy*، ويُفسِّر الأثر المُزعزِع.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.1'],
              do: "Group discussion: what does the victim's status add to Victorian horror?",
              doAr: 'نقاش جماعي: ما الذي تُضيفه مكانة الضحية إلى الرّعب الفيكتوري؟',
              task: 'Build a class conceptual reading on a shared doc.',
              taskAr: 'ابنوا قراءة مفاهيمية صفّية على مستند مشترك.',
              success: "Develops a peer's idea; cites social-historical context.",
              successAr: 'يُطوِّر فكرة زميل، ويستشهد بسياق اجتماعي-تاريخي.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.4', '9W.10'],
              do: 'Study Stevenson\'s short-sentence punch ("And next moment…"); imitation drills.',
              doAr: 'ادرس وَقْع الجُمل القصيرة عند Stevenson ("And next moment…")، ثم تمارين محاكاة.',
              task: 'Rewrite a paragraph deliberately varying sentence length.',
              taskAr: 'أعِد كتابة فقرة مع تنويع طول الجُمل قصدًا.',
              success: 'Uses deliberate short sentences; explains choice in margin annotation.',
              successAr: 'يُوظِّف جُملًا قصيرة مقصودة، ويُبرِّر اختياره في هامش التعليق.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.5', '9W.3'],
              do: 'Introduce evaluation: how powerful and why?',
              doAr: 'تقديم التقييم: ما مدى قوّة الأثر، ولماذا؟',
              task: "Paragraph evaluating murder scene's impact on a Victorian reader.",
              taskAr: 'فقرة تُقيِّم أثر مشهد الجريمة على قارئ فيكتوري.',
              success: 'Uses "Stevenson\'s choice is particularly effective because…".',
              successAr: 'يُوظِّف صيغة "Stevenson\'s choice is particularly effective because…".',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9R.5', '9W.3', '9W.7'],
              do: '30-minute timed evaluative paragraph.',
              doAr: 'فقرة تقييمية مُحدَّدة بوقت ٣٠ دقيقة.',
              task: 'Evaluate how Stevenson shocks the reader in the murder scene.',
              taskAr: 'قيِّم كيف يصدم Stevenson القارئ في مشهد الجريمة.',
              success: 'Evaluative stance sustained; conceptual; 280+ words.',
              successAr: 'موقف تقييمي مُتواصل، مفاهيمي، و٢٨٠ كلمة فأكثر.',
            }),
          ],
        },
        {
          number: 6,
          pages: 'Cross-referenced extracts from Chapters 1-4',
          keyVocabulary: [
            { en: 'parallel', ar: 'تَوازٍ' },
            { en: 'contrast', ar: 'تباين' },
            { en: 'motif', ar: 'رمز متكرّر' },
            { en: 'characterisation', ar: 'رسم الشخصية' },
            { en: 'antithesis', ar: 'تضادّ' },
          ],
          contextNote: {
            en: 'Comparative skills — half-term consolidation.',
            ar: 'مهارات المقارنة — مراجعة منتصف الفصل.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.6', '9R.7'],
              do: 'Construct a motif tracker: animal imagery across 4 chapters.',
              doAr: 'أنشئ متتبِّع رموز: الصور الحيوانية عبر ٤ فصول.',
              task: 'Evidence grid: chapter / quotation / pattern / development.',
              taskAr: 'جدول أدلّة: الفصل / الاقتباس / النّمط / التطوُّر.',
              success: 'Identifies development of motif, not just repetition.',
              successAr: 'يُحدِّد تطوُّر الرمز، لا مجرّد تكراره.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.6', '9SL.3'],
              do: 'Structured comparative talk: similarity AND difference.',
              doAr: 'حوار مقارن منظَّم: التشابه والاختلاف معًا.',
              task: 'Comparative speaking frame: "Both… however… ultimately…"',
              taskAr: 'صيغة كلام مقارنة: "Both… however… ultimately…"',
              success: 'Sustained analytical register; structured comparison.',
              successAr: 'سجلّ تحليلي مُتواصل، ومقارنة منظَّمة.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.1', '9W.3'],
              do: 'Study comparative discourse markers; teach "Whereas… Conversely… Both writers…"',
              doAr: 'ادرس روابط الخطاب المقارن، وعلِّم "Whereas… Conversely… Both writers…".',
              task: 'Rewrite weak comparisons using sophisticated connectives.',
              taskAr: 'أعِد كتابة المقارنات الضعيفة بروابط راقية.',
              success: 'At least 5 sophisticated comparative connectives used accurately.',
              successAr: 'لا يقلّ عن ٥ روابط مقارنة راقية مُوظَّفة بدقّة.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.6', '9W.1', '9W.3'],
              do: 'Plan a comparative paragraph using two extracts.',
              doAr: 'خطِّط فقرة مقارنة باستخدام مقتطفين.',
              task: "Comparative paragraph: Jekyll's house vs Hyde's Soho door.",
              taskAr: 'فقرة مقارنة: منزل Jekyll مقابل باب Hyde في Soho.',
              success: 'Paragraph holds both extracts in tension throughout.',
              successAr: 'تُبقي الفقرة المقتطفين في توتُّر طوال الوقت.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9R.6', '9W.1', '9W.3'],
              do: '30-minute independent comparative response.',
              doAr: 'استجابة مقارنة مستقلّة في ٣٠ دقيقة.',
              task: "Compare how Stevenson presents Jekyll's and Hyde's living spaces.",
              taskAr: 'قارِن كيف يقدّم Stevenson فضاءَي معيشة Jekyll وHyde.',
              success: 'Comparative throughout; not split into separate analyses.',
              successAr: 'مُقارن طوال الوقت، لا يُقسَّم إلى تحليلَين منفصلَين.',
            }),
          ],
        },
        {
          number: 7,
          pages: '"Incident of the Letter" + "Remarkable Incident of Dr Lanyon" (pp. 26-34)',
          keyVocabulary: [
            { en: 'forgery', ar: 'تزوير' },
            { en: 'ostracised', ar: 'مَنبوذ' },
            { en: 'hypocrisy', ar: 'نِفاق' },
            { en: 'façade', ar: 'واجهة' },
            { en: 'conscience', ar: 'ضمير' },
          ],
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.3', '9R.7'],
              do: 'Teach *characterisation* as authorial choice; analyse Lanyon as foil.',
              doAr: 'علِّم *characterisation* بوصفه خيارًا للمؤلِّف، وحلِّل Lanyon بوصفه نقيضًا.',
              task: 'Foil-chart: Lanyon vs Jekyll — beliefs, language, function.',
              taskAr: 'جدول النقيض: Lanyon مقابل Jekyll — المعتقدات واللغة والوظيفة.',
              success: "Frames characters as Stevenson's tools, not autonomous figures.",
              successAr: 'يُؤطِّر الشخصيات بوصفها أدوات Stevenson، لا كيانات مستقلّة.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.1'],
              do: "Discussion: Lanyon's death as commentary on what?",
              doAr: 'نقاش: موت Lanyon تعليق على ماذا؟',
              task: 'Four-corners debate: science / faith / repression / hubris.',
              taskAr: 'مناظرة الزوايا الأربع: العلم / الإيمان / الكبت / الكِبر.',
              success: 'Takes and defends a conceptual position; revises on evidence.',
              successAr: 'يتبنّى موقفًا مفاهيميًّا ويُدافع عنه، ويُراجعه بالأدلّة.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9W.8'],
              do: 'Teach tentative critical voice: "perhaps, arguably, this might suggest…"',
              doAr: 'علِّم الصوت النقدي المُحترِس: "perhaps, arguably, this might suggest…".',
              task: 'Rewrite assertive sentences as critically tentative.',
              taskAr: 'أعِد كتابة الجُمل القاطعة بصوت نقدي مُحترِس.',
              success: 'Demonstrates tentative critical register.',
              successAr: 'يُظهر سجلًّا نقديًّا مُحترِسًا.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.4', '9W.3', '9W.8'],
              do: 'Apply tentative critical voice to Lanyon analysis.',
              doAr: 'وظِّف الصوت النقدي المُحترِس في تحليل Lanyon.',
              task: 'Paragraph: how Stevenson uses Lanyon to critique scientific hubris.',
              taskAr: 'فقرة: كيف يُوظِّف Stevenson شخصية Lanyon لنقد كِبر العِلم.',
              success: 'Two methods, tentative voice, conceptual framing.',
              successAr: 'أسلوبان، وصوت مُحترِس، وتأطير مفاهيمي.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9R.3', '9R.4', '9W.3'],
              do: '30-minute timed paragraph.',
              doAr: 'فقرة مُحدَّدة بوقت ٣٠ دقيقة.',
              task: 'How does Stevenson use Lanyon to explore Victorian anxieties?',
              taskAr: 'كيف يُوظِّف Stevenson شخصية Lanyon لاستكشاف القلق الفيكتوري؟',
              success: 'Character framed as authorial device throughout; 300+ words.',
              successAr: 'الشخصية مُؤطَّرة بوصفها أداة للمؤلِّف طوال الوقت، و٣٠٠ كلمة فأكثر.',
            }),
          ],
        },
      ],
    },
    {
      id: '1.2',
      label: { en: 'Term 1.2 — Second half', ar: 'الفصل 1.2 — النصف الثاني' },
      assessment: { en: 'Term 1.2 formal essay — full multi-paragraph response.' },
      weeks: [
        {
          number: 8,
          pages: '"Incident at the Window" + opening of "The Last Night" (pp. 35-47)',
          keyVocabulary: [
            { en: 'transgression', ar: 'تجاوُز' },
            { en: 'climax', ar: 'ذروة' },
            { en: 'tension', ar: 'توتُّر' },
            { en: 'suspense', ar: 'تشويق' },
            { en: 'denouement', ar: 'حلّ العقدة' },
          ],
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.4', '9R.7'],
              do: "Pacing-graph Stevenson's prose; identify withheld information.",
              doAr: 'ارسم خريطة إيقاع نثر Stevenson، وحدِّد المعلومات المحجوبة.',
              task: 'Annotate "The Last Night" opening for structural choices.',
              taskAr: 'علِّق على افتتاحية "The Last Night" مع التركيز على الاختيارات البنيوية.',
              success: 'Identifies *climax*, *suspense*, *withholding* with effect explained.',
              successAr: 'يُحدِّد *climax* و*suspense* و*withholding* مع تفسير الأثر.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.1'],
              do: 'Discussion: the door as motif throughout the novella.',
              doAr: 'نقاش: الباب بوصفه رمزًا متكرّرًا في الرواية القصيرة.',
              task: 'Build a thematic argument: "Doors and what they hide".',
              taskAr: 'ابنِ حجّة موضوعية: "الأبواب وما تُخفيه".',
              success: 'Sustained analytical register; threads evidence across novella.',
              successAr: 'سجلّ تحليلي مُتواصل، يُمرِّر الأدلّة عبر الرواية.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.1', '9W.3'],
              do: 'Study and write thesis statements that govern a whole essay.',
              doAr: 'ادرس واكتب جُمل أطروحة تحكم المقال كاملًا.',
              task: 'Draft 3 thesis statements for different essay questions.',
              taskAr: 'صِغ ٣ أطروحات لأسئلة مقالات مختلفة.',
              success: 'Theses are conceptual, arguable, specific.',
              successAr: 'الأطروحات مفاهيمية، قابلة للنقاش، ومحدّدة.',
            }),
            lesson({
              focus: 'application',
              skills: ['9W.1', '9W.3'],
              do: 'Plan a full essay on tension in "Last Night".',
              doAr: 'خطِّط مقالًا كاملًا حول التوتُّر في "Last Night".',
              task: 'Essay plan: thesis, 3 conceptual topic sentences, evidence map.',
              taskAr: 'خطّة المقال: أطروحة، و٣ جُمل موضوع مفاهيمية، وخريطة أدلّة.',
              success: 'Plan demonstrates cohesion; each topic sentence supports thesis.',
              successAr: 'الخطّة تُظهر تماسكًا، وكلّ جملة موضوع تُسانِد الأطروحة.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9R.4', '9W.1', '9W.3'],
              do: '40-minute 2-paragraph response from plan.',
              doAr: 'استجابة من فقرتين في ٤٠ دقيقة انطلاقًا من الخطّة.',
              task: 'How does Stevenson build tension in "The Last Night"?',
              taskAr: 'كيف يبني Stevenson التوتُّر في "The Last Night"؟',
              success: 'Two paragraphs governed by a thesis; embedded quotations throughout.',
              successAr: 'فقرتان تحكمهما أطروحة واحدة، باقتباسات مُدمجة طوال الوقت.',
            }),
          ],
        },
        {
          number: 9,
          pages: '"Dr Lanyon\'s Narrative" (pp. 48-55)',
          keyVocabulary: [
            { en: 'epistolary', ar: 'رسائلي' },
            { en: 'polyphonic', ar: 'متعدّد الأصوات' },
            { en: 'testimony', ar: 'شهادة' },
            { en: 'transformation', ar: 'تحوُّل' },
            { en: 'sublime', ar: 'سامٍ مُهيب' },
          ],
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.4', '9R.7'],
              do: 'Analyse the epistolary form; effects of voice-shift.',
              doAr: 'حلِّل الشكل الرسائلي، وأثَر تبدُّل الصوت.',
              task: 'Voice-comparison table: Utterson narration vs Lanyon testimony.',
              taskAr: 'جدول مقارنة الأصوات: سرد Utterson مقابل شهادة Lanyon.',
              success: 'Uses *epistolary*, *polyphonic*; explains effect of form.',
              successAr: 'يُوظِّف *epistolary* و*polyphonic*، ويُفسِّر أثر الشكل.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9R.6', '9SL.1'],
              do: 'Compare Victorian and modern readings of the transformation.',
              doAr: 'قارن القراءة الفيكتورية بالقراءة الحديثة للتحوُّل.',
              task: '"What did this mean in 1886? What does it mean now?"',
              taskAr: '"ماذا كان معنى ذلك عام ١٨٨٦؟ وماذا يعني اليوم؟"',
              success: 'Articulates culturally-situated readings; develops peer ideas.',
              successAr: 'يصوغ قراءات مُموضَعة ثقافيًّا، ويُطوِّر أفكار الزملاء.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.6', '9W.10'],
              do: "Imitative writing: craft a paragraph of Gothic horror in Stevenson's mode.",
              doAr: 'كتابة محاكاة: صُغ فقرة رعب قوطي على نَسَق Stevenson.',
              task: 'Pastiche paragraph: Gothic transformation in their own setting.',
              taskAr: 'فقرة محاكاة: تحوُّل قوطي في بيئة الطالب نفسه.',
              success: 'Deliberate imagery, controlled syntax, sustained register.',
              successAr: 'صور مقصودة، وتركيب نحوي مضبوط، وسجلّ مُتواصل.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.4', '9W.3', '9W.10'],
              do: "Three-method paragraph: how Lanyon's narrative works.",
              doAr: 'فقرة بثلاثة أساليب: كيف يعمل سرد Lanyon.',
              task: "Paragraph: Stevenson's use of form to deepen horror in Lanyon's account.",
              taskAr: 'فقرة: توظيف Stevenson للشكل في تعميق الرعب في رواية Lanyon.',
              success: 'Three methods integrated, not listed; conceptual frame.',
              successAr: 'ثلاثة أساليب مدمجة، لا مَسرودة، ضمن إطار مفاهيمي.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9R.4', '9W.3', '9W.7'],
              do: '30-minute analytical paragraph.',
              doAr: 'فقرة تحليلية في ٣٠ دقيقة.',
              task: 'How does Stevenson use form, structure and language to present the transformation?',
              taskAr: 'كيف يُوظِّف Stevenson الشكل والبنية واللغة لتقديم التحوُّل؟',
              success: 'All three methods analysed; sustained conceptual reading; 320+ words.',
              successAr: 'تحليل الأساليب الثلاثة، وقراءة مفاهيمية مُتواصلة، و٣٢٠ كلمة فأكثر.',
            }),
          ],
        },
        {
          number: 10,
          pages: '"Henry Jekyll\'s Full Statement" (pp. 56-70)',
          keyVocabulary: [
            { en: 'confession', ar: 'اعتراف' },
            { en: 'hubris', ar: 'كِبر' },
            { en: 'dichotomy', ar: 'انقسام ثنائي' },
            { en: 'conscience', ar: 'ضمير' },
            { en: 'oblivion', ar: 'نسيان مُطلَق' },
          ],
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.3', '9R.7'],
              do: "Identify Jekyll's evasions, justifications, contradictions.",
              doAr: 'حدِّد تهرُّبات Jekyll وتبريراته وتناقضاته.',
              task: "Highlight Jekyll's deflective language; label rhetorical moves.",
              taskAr: 'لوِّن لغة Jekyll المراوِغة، وضع تسميات للحركات البلاغية.',
              success: 'Identifies *unreliable narrator*; explains self-deception.',
              successAr: 'يُحدِّد *unreliable narrator*، ويُفسِّر خداع الذات.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9R.5', '9SL.1'],
              do: 'Whole-class debate with structured turn-taking.',
              doAr: 'مناظرة صفّية كاملة بتعاقُب أدوار منظَّم.',
              task: 'Take and defend a conceptual position with textual evidence.',
              taskAr: 'تبنَّ موقفًا مفاهيميًّا ودافع عنه بدليل من النص.',
              success: 'Develops AND challenges ideas; sustains analytical register.',
              successAr: 'يُطوِّر الأفكار ويتحدّاها معًا، ويُديم السجلّ التحليلي.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.10', '9W.8'],
              do: 'Replace weak verbs with precise critical verbs: *exposes, undermines, complicates*.',
              doAr: 'استبدل الأفعال الضعيفة بأفعال نقدية دقيقة: *exposes, undermines, complicates*.',
              task: 'Verb-replacement drill on a paragraph; quality not quantity.',
              taskAr: 'تمرين استبدال الأفعال في فقرة: الجودة قبل الكمّ.',
              success: 'Deliberate, varied verbs of interpretation throughout writing.',
              successAr: 'أفعال تفسيرية مقصودة ومتنوّعة في كامل الكتابة.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.3', '9W.1', '9W.3'],
              do: "Plan a 3-paragraph response on Jekyll's culpability.",
              doAr: 'خطِّط استجابة من ثلاث فقرات حول مسؤولية Jekyll.',
              task: 'Plan + open paragraph: "Jekyll is a self-deceiver, not a victim".',
              taskAr: 'خطّة + فقرة افتتاحية: "Jekyll is a self-deceiver, not a victim".',
              success: 'Plan governs argument; opening paragraph holds a clear line.',
              successAr: 'الخطّة تحكم الحجّة، والفقرة الافتتاحية تُمسِك خطًّا واضحًا.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9R.3', '9W.1', '9W.3', '9W.7'],
              do: '40-minute full 3-paragraph response.',
              doAr: 'استجابة كاملة من ثلاث فقرات في ٤٠ دقيقة.',
              task: 'How far does Stevenson present Jekyll as responsible for his own downfall?',
              taskAr: 'إلى أيّ حدّ يقدّم Stevenson شخصية Jekyll مسؤولًا عن سقوطه؟',
              success: 'Sustained line of argument; 3 paragraphs; conceptual throughout.',
              successAr: 'خطّ حجّة مُتواصل، ثلاث فقرات، ومفاهيمي طوال الوقت.',
            }),
          ],
        },
        {
          number: 11,
          pages: 'Cross-text revisiting; thematic synthesis',
          keyVocabulary: [
            { en: 'allegory', ar: 'رمزية' },
            { en: 'microcosm', ar: 'نموذج مُصغَّر' },
            { en: 'paradigm', ar: 'نَمَط مرجعي' },
            { en: 'subversion', ar: 'تقويض' },
            { en: 'anxiety', ar: 'قلق' },
          ],
          contextNote: {
            en: 'Whole-text synthesis.',
            ar: 'تركيب شامل للنص.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.3', '9R.7'],
              do: 'Map allegorical readings: Darwinism, urban decay, repression, addiction.',
              doAr: 'ارسم خريطة القراءات الرمزية: الداروينية، تدهور المدينة، الكبت، الإدمان.',
              task: 'Allegory grid linking theme to 3 textual moments each.',
              taskAr: 'جدول الرمزية يربط كلّ موضوع بثلاثة مواضع نصّية.',
              success: 'Articulates the novella as allegorical; cites from across the text.',
              successAr: 'يصوغ الرواية بوصفها رمزية، ويستشهد من عموم النص.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9R.5', '9SL.3'],
              do: 'Structured discussion with rotating chairs.',
              doAr: 'نقاش منظَّم بتناوُب رئاسة الحلقة.',
              task: 'Reach a class consensus on the strongest conceptual reading.',
              taskAr: 'صوغ توافق صفّي على أقوى قراءة مفاهيمية.',
              success: 'Sustains analytical register; engages with at least 3 readings.',
              successAr: 'يُديم السجلّ التحليلي، ويتفاعل مع ثلاث قراءات على الأقل.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.9', '9W.10'],
              do: 'Self-edit a Week 8 paragraph against mark scheme.',
              doAr: 'حرِّر فقرتك من الأسبوع ٨ ذاتيًّا وفق سُلَّم التصحيح.',
              task: 'Edit a Week 8 paragraph: precision, embedding, conceptual depth.',
              taskAr: 'حرِّر فقرة من الأسبوع ٨: الدقّة، ودمج الاقتباس، والعمق المفاهيمي.',
              success: 'Three substantive edits per paragraph; justify in margin.',
              successAr: 'ثلاث تعديلات جوهرية لكلّ فقرة، مع تبرير في الهامش.',
            }),
            lesson({
              focus: 'application',
              skills: ['9W.1', '9W.3'],
              do: 'Plan a full essay in 10 minutes on an unseen question.',
              doAr: 'خطِّط مقالًا كاملًا في ١٠ دقائق على سؤال غير مرئيّ مسبقًا.',
              task: 'Plan: thesis + 3 topic sentences + evidence map.',
              taskAr: 'الخطّة: أطروحة + ٣ جُمل موضوع + خريطة أدلّة.',
              success: 'Plan is exam-viable; demonstrates cohesion and conceptual line.',
              successAr: 'الخطّة صالحة للاختبار، وتُظهر تماسكًا وخطًّا مفاهيميًّا.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9R.4', '9W.1', '9W.3', '9W.7'],
              do: '35-minute practice essay under exam conditions.',
              doAr: 'مقال تدريبي في ٣٥ دقيقة ضمن ظروف الاختبار.',
              task: 'How does Stevenson present duality in *Jekyll and Hyde*?',
              taskAr: 'كيف يقدّم Stevenson الازدواجية في *Jekyll and Hyde*؟',
              success: 'Full essay structure: intro, 2-3 body paragraphs, brief conclusion.',
              successAr: 'بنية مقال كاملة: مقدّمة، و٢-٣ فقرات متن، وخاتمة مختصرة.',
            }),
          ],
        },
        {
          number: 12,
          pages: 'Whole novella; assessment-focused revisiting',
          keyVocabulary: [
            { en: 'thesis' },
            { en: 'cohesion' },
            { en: 'judicious' },
            { en: 'integrated' },
            { en: 'critical' },
          ],
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Question-deconstruction drills on past sample questions.',
              task: 'Annotate 5 questions for focus, command word, conceptual angle.',
              success: 'Identifies question type and conceptual angle in under 2 minutes.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9SL.1', '9SL.3', '9W.9'],
              do: 'Peer-mark Week 11 practice essays using a Y9 mastery-band rubric.',
              task: 'Identify one strength and one precise improvement per essay.',
              success: 'Peer feedback is specific, actionable, criteria-anchored.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.1', '9W.3', '9W.10'],
              do: 'Teacher live-models a 3-paragraph essay opening with metacognitive commentary.',
              task: 'Annotate the model for the moves that earn top-band marks.',
              success: 'Identifies 5 transferable moves from the model.',
            }),
            lesson({
              focus: 'application',
              skills: ['9W.9', '9W.3'],
              do: 'Rewrite weakest paragraph from Week 11 essay using model strategies.',
              task: 'Rewrite with explicit application of 3 modelled moves.',
              success: 'Rewrite demonstrably stronger than original; moves identified.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9R.4', '9W.1', '9W.7'],
              do: 'Write a strong opening (intro + first body paragraph) in 15 mins.',
              task: 'How does Stevenson use Hyde to represent Victorian fears?',
              success: 'Opening shows thesis, conceptual framing, embedded evidence.',
            }),
          ],
        },
        {
          number: 13,
          pages: 'Unseen extract from *Jekyll and Hyde* with whole-text reach',
          keyVocabulary: [
            { en: 'analytical' },
            { en: 'sustained' },
            { en: 'conceptual' },
            { en: 'evaluative' },
            { en: 'judgement' },
          ],
          contextNote: { en: 'Term 1.2 assessment week.' },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4', '9R.7'],
              do: '15-minute timed annotation of a Jekyll and Hyde extract.',
              task: 'Annotate for methods, effects, conceptual reading.',
              success: 'Annotation usable as plan; identifies 3 methods minimum.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.1', '9SL.3'],
              do: 'Final synthesis discussion: "Stevenson\'s most important message".',
              task: 'Collaborative talk that consolidates conceptual readings.',
              success: 'Sustained analytical register; reference across the novella.',
            }),
            lesson({
              focus: 'assessment',
              skills: ['9R.1', '9R.2', '9R.3', '9R.4', '9R.7', '9W.1', '9W.3', '9W.7', '9W.10'],
              do: '35-40 minute closed-book analytical essay.',
              task: 'Starting with this extract, explore how Stevenson presents the duality of human nature in *Jekyll and Hyde*.',
              success:
                'Full essay: thesis-driven intro, 2-3 conceptual body paragraphs, brief conclusion. Embedded quotations, integrated method analysis, conceptual reading sustained.',
            }),
            lesson({
              focus: 'consolidation-discussion',
              skills: ['9W.9'],
              do: 'Whole-class feedback and individual targets.',
              task: 'Set 2 personal targets for Term 1.2 based on assessment evidence.',
              success: 'Targets are specific, skill-coded, actionable.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.9', '9W.3', '9W.10'],
              do: 'DIRT (Dedicated Improvement Reflection Time): rewrite weakest paragraph.',
              task: 'Improved paragraph with annotated improvements in margin.',
              success: 'Rewrite shows clear progress against the 2 personal targets.',
            }),
          ],
        },
      ],
    },
  ],
}

const Y9_T2: Year['terms'][number] = {
  number: 2,
  label: {
    en: 'Term 2 — Macbeth: Ambition and Conscience',
    ar: 'الفصل الدراسي الثاني — ماكبث: الطموح والضمير',
  },
  overview: {
    en: 'Compulsory KS3 Shakespeare. Whole play study + Jacobean context (Gunpowder Plot, divine right, witchcraft). Critical extracts on Lady Macbeth and the supernatural. By end of term students write thesis-driven literature essays on a whole text with context — the core GCSE Literature skill, embedded a year early.',
  },
  setText: { en: '*Macbeth* (whole play) + Jacobean context + critical extracts' },
  vocabularyThemes: [
    { en: 'ambition, regicide, tyranny, divine right, Jacobean' },
    { en: 'guilt, conscience, hubris, nemesis, catharsis' },
  ],
  bigSkillJump: {
    en: 'Students write a thesis-driven literature essay on a whole text with context — core GCSE Lit skill.',
  },
  halfTerms: [
    {
      id: '2.1',
      label: { en: 'Term 2.1' },
      assessment: { en: 'Analytical essay on a key scene/character.' },
      weeks: [
        {
          number: 2,
          pages: 'Macbeth context pack',
          keyVocabulary: [
            { en: 'zeitgeist' },
            { en: 'divine-right' },
            { en: 'regicide' },
            { en: 'Jacobean' },
            { en: 'succession' },
          ],
          contextNote: {
            en: 'Jacobean England (1603-25): James I survives the Gunpowder Plot, believes in divine right and witchcraft (Daemonologie 1597). Macbeth (c.1606) flatters the king and warns regicides.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.7'],
              do: 'Read three context extracts: divine right, Daemonologie, Gunpowder Plot.',
              task: 'Annotate each extract with two precise terms (zeitgeist, regicide).',
              success: 'Can define five Jacobean terms accurately.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9SL.1', '9R.3'],
              do: 'Seminar: would a 1606 audience read Macbeth as politically loyal or subversive?',
              task: 'Defend a position using one piece of contextual evidence.',
              success: 'Contributes a thoughtful, evidence-anchored point.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9W.7'],
              do: 'Model thesis: "Shakespeare presents Jacobean anxieties about regicide which reflects James I\'s post-Gunpowder politics."',
              task: 'Write your own thesis on context shaping the play.',
              success: 'Thesis is conceptual and historically grounded.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.4', '9W.10'],
              do: 'Mini-research on the North Berwick witch trials (1590).',
              task: 'Produce a 200-word contextual brief using all five vocab items.',
              success: 'Deploys Jacobean vocabulary precisely.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.1', '9W.3'],
              do: 'Synthesise a contextual introduction for a Macbeth essay.',
              task: 'Write an opening paragraph linking Jacobean anxieties to the play.',
              success: 'Intro frames an argument with context.',
            }),
          ],
        },
        {
          number: 3,
          pages: 'Macbeth 1.1-1.3',
          keyVocabulary: [
            { en: 'prophecy' },
            { en: 'ambition' },
            { en: 'supernatural' },
            { en: 'equivocation' },
            { en: 'hubris' },
          ],
          contextNote: {
            en: 'The witches open with paradox ("fair is foul") and seed Macbeth\'s ambition through equivocal prophecy.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: "Close read 1.1 and witches' chant in 1.3 for trochaic rhythm and paradox.",
              task: 'Annotate metre, paradox, and triadic structure.',
              success: 'Identifies form and rhythm precisely.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.1'],
              do: "Debate: do the witches cause or merely reveal Macbeth's ambition?",
              task: 'Take a position with two textual moments.',
              success: 'Weighs multiple interpretations.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9R.2', '9W.7'],
              do: 'Model embedded quotation: Macbeth "starts" at the prophecy, suggesting latent ambition.',
              task: 'Write three sentences embedding quotations fluently.',
              success: 'Quotations integrated mid-sentence.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.4', '9R.7'],
              do: "Analyse equivocation in the witches' speech.",
              task: 'Write an analytical paragraph using "Shakespeare presents… which reflects…".',
              success: 'Uses precise terminology (equivocation, trochaic).',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.3', '9W.1'],
              do: "Develop a thesis on the witches' dramatic function.",
              task: 'Write a thesis + one analytical paragraph.',
              success: 'Paragraph is method-led and conceptual.',
            }),
          ],
        },
        {
          number: 4,
          pages: 'Macbeth 1.5-1.7',
          keyVocabulary: [
            { en: 'invocation' },
            { en: 'agency' },
            { en: 'gender' },
            { en: 'manipulation' },
            { en: 'conscience' },
          ],
          contextNote: {
            en: 'Lady Macbeth\'s "unsex me here" invokes dark spirits, inverting Jacobean gender hierarchies in a play obsessed with masculinity.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Close read 1.5 soliloquy: imperatives, semantic field of cruelty.',
              task: 'Map verbs of invocation and their effects.',
              success: 'Links method to meaning.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.1'],
              do: 'Discuss: is Lady Macbeth a feminist disruptor or a Jacobean warning?',
              task: 'Argue using context and quotation.',
              success: 'Holds multiple interpretations.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9W.10'],
              do: 'Model conceptual topic sentence: "Lady Macbeth weaponises gender to seize agency."',
              task: 'Draft three conceptual topic sentences on agency.',
              success: 'Sentences are abstract and arguable.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.2', '9W.7'],
              do: 'Analyse 1.7 manipulation ("screw your courage").',
              task: 'Write a paragraph on manipulation using embedded quotation.',
              success: 'Sustains analytical control.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.3', '9R.3'],
              do: 'Plan a feminist vs psychological reading of Lady Macbeth.',
              task: 'Write a comparative paragraph weighing both.',
              success: 'Synthesises critical perspectives.',
            }),
          ],
        },
        {
          number: 5,
          pages: 'Macbeth Act 2',
          keyVocabulary: [
            { en: 'regicide' },
            { en: 'hallucination' },
            { en: 'guilt' },
            { en: 'omen' },
            { en: 'divine-order' },
          ],
          contextNote: {
            en: "Duncan's murder ruptures the Great Chain of Being; nature revolts (horses eat each other); Macbeth hallucinates the dagger.",
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Close read 2.1 dagger soliloquy: questions, vision, broken metre.',
              task: 'Annotate fragmented syntax and its meaning.',
              success: 'Links structure to psychology.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.5', '9SL.3'],
              do: 'Evaluate: is Macbeth a willing villain or a victim of conscience?',
              task: 'Build a structured argument.',
              success: 'Evaluation is balanced.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9W.4'],
              do: 'Model varied sentence forms in analysis (short for impact, complex for nuance).',
              task: 'Rewrite a paragraph using three sentence forms.',
              success: 'Sentences serve effect.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.2', '9R.7'],
              do: 'Analyse 2.2 ("Will all great Neptune\'s ocean wash this blood").',
              task: 'Paragraph using terminology (hyperbole, biblical imagery).',
              success: 'Uses precise terms.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.1', '9W.3'],
              do: 'Plan a thesis essay on guilt in Act 2.',
              task: 'Write thesis + two paragraphs.',
              success: 'Essay shows whole-text cohesion.',
            }),
          ],
        },
        {
          number: 6,
          pages: 'Macbeth Act 3',
          keyVocabulary: [
            { en: 'tyranny' },
            { en: 'paranoia' },
            { en: 'supernatural-retribution' },
            { en: 'descent' },
            { en: 'isolation' },
          ],
          contextNote: {
            en: "Macbeth becomes tyrant: Banquo's murder, the ghost at the banquet, growing isolation. James I claimed descent from Banquo.",
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Close read 3.1 soliloquy: fear of Banquo, syntactic control.',
              task: "Annotate paranoia's linguistic markers.",
              success: 'Reads for psychological state.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.2'],
              do: 'Discuss: is the ghost real or psychological?',
              task: 'Argue using staging evidence.',
              success: 'Sustains a fluent contribution.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9R.6'],
              do: "Model linking across acts: \"Macbeth's descent from Act 1's hesitation to Act 3's tyranny reflects…\".",
              task: 'Write a cross-act analytical sentence.',
              success: 'Tracks development.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.2', '9W.7'],
              do: "Analyse the banquet scene's dramatic structure.",
              task: 'Paragraph on isolation, embedded quotation.',
              success: 'Quotations integrated.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.1', '9W.3'],
              do: 'Plan HT1 assessment: tyranny vs ambition.',
              task: 'Produce a full essay plan with thesis and 3 points.',
              success: 'Plan is conceptual.',
            }),
          ],
        },
        {
          number: 7,
          pages: 'Macbeth Acts 1-3 revision + HT1 assessment',
          keyVocabulary: [
            { en: 'ambition' },
            { en: 'regicide' },
            { en: 'tyranny' },
            { en: 'conscience' },
            { en: 'supernatural' },
          ],
          contextNote: {
            en: 'HT1 assessment: 45-minute analytical essay on a key scene/character from Acts 1-3.',
          },
          lessons: [
            lesson({
              focus: 'consolidation-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Revisit three "anchor" scenes (1.3, 1.7, 2.2).',
              task: 'Build a quotation bank of 12 quotations with methods.',
              success: 'Bank covers method and meaning.',
            }),
            lesson({
              focus: 'consolidation-discussion',
              skills: ['9R.3', '9SL.3'],
              do: 'Walk-through: critic A says ambition; critic B says manipulation. Which?',
              task: 'Frame an evaluation.',
              success: 'Structures an argument.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9W.1'],
              do: 'Model a thesis-driven essay opening.',
              task: 'Write thesis + first analytical paragraph for HT1 question.',
              success: 'Opening is conceptual.',
            }),
            lesson({
              focus: 'paragraph-rehearsal',
              skills: ['9W.7', '9W.9'],
              do: "Peer-edit a partner's thesis using a checklist.",
              task: 'Annotate two improvements per essay.',
              success: 'Critiques constructively.',
            }),
            lesson({
              focus: 'assessment',
              skills: ['9W.1', '9W.3', '9R.2'],
              do: '45-minute assessment.',
              task: 'Write a thesis-driven essay on a key scene/character.',
              success: 'Sustains a thesis-led argument.',
            }),
          ],
        },
      ],
    },
    {
      id: '2.2',
      label: { en: 'Term 2.2' },
      assessment: { en: 'Full essay on a play-wide theme (60-min GCSE-style response).' },
      weeks: [
        {
          number: 8,
          pages: 'Macbeth 4.1',
          keyVocabulary: [
            { en: 'apparition' },
            { en: 'irony' },
            { en: 'false-security' },
            { en: 'fate' },
            { en: 'free-will' },
          ],
          contextNote: {
            en: 'The witches return with three apparitions. Their equivocations give Macbeth false security: dramatic irony foreshadows his fall.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Close read the apparitions: staging, symbolism, equivocation.',
              task: 'Annotate dramatic irony in each apparition.',
              success: 'Reads for theatrical effect.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.1'],
              do: 'Debate: fate or free will? Are the witches manipulators or mirrors?',
              task: 'Argue with two textual moments.',
              success: 'Weighs interpretations.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9W.4'],
              do: 'Model dramatic-irony analysis: "Shakespeare\'s irony exposes the limits of mortal certainty."',
              task: 'Write a paragraph on false security.',
              success: 'Writing tracks dramatic effect.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.2', '9R.7'],
              do: 'Analyse the show of kings (a flattery of James I).',
              task: 'Paragraph on Jacobean political function.',
              success: 'Links text to context.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.3', '9W.1'],
              do: 'Draft a thesis on fate vs free will.',
              task: 'Write thesis + analytical paragraph.',
              success: 'Thesis is conceptual.',
            }),
          ],
        },
        {
          number: 9,
          pages: 'Macbeth 4.3',
          keyVocabulary: [
            { en: 'kingship' },
            { en: 'virtue' },
            { en: 'restoration' },
            { en: 'loyalty' },
            { en: 'redemption' },
          ],
          contextNote: {
            en: "Malcolm tests Macduff in England, listing kingly virtues. News of Macduff's family galvanises rebellion.",
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Close read Malcolm\'s list of "king-becoming graces".',
              task: "Map virtues against Macbeth's tyranny.",
              success: 'Reads structurally.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.3'],
              do: 'Discuss: why does Malcolm need to test Macduff? Is this scene dramatically weak?',
              task: 'Frame a structured response.',
              success: 'Argues analytically.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9R.6'],
              do: "Model contrast paragraphs: Macbeth's tyranny vs Malcolm's virtue.",
              task: 'Draft a comparative paragraph across scenes.',
              success: 'Links Acts 3 and 4.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.2', '9W.7'],
              do: 'Analyse Macduff\'s grief ("he has no children").',
              task: 'Paragraph on masculinity and grief.',
              success: 'Sustains analytical control.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.3', '9W.1'],
              do: 'Plan a paragraph on kingship as moral category.',
              task: 'Write a developed paragraph using Y9 stems.',
              success: 'Argues conceptually.',
            }),
          ],
        },
        {
          number: 10,
          pages: 'Macbeth 5.1',
          keyVocabulary: [
            { en: 'madness' },
            { en: 'conscience' },
            { en: 'repetition' },
            { en: 'fragmentation' },
            { en: 'undoing' },
          ],
          contextNote: {
            en: 'Lady Macbeth sleepwalks ("Out, damned spot"). Her prose, fragmented, marks total psychological collapse.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Close read 5.1: prose vs verse, repetition, broken syntax.',
              task: 'Annotate form and structure shifts.',
              success: 'Reads for form precisely.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.1'],
              do: 'Discuss: does she deserve sympathy now? Does the play punish ambition itself or female ambition?',
              task: 'Argue with evidence.',
              success: 'Weighs feminist reading.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9W.10'],
              do: 'Model: "Shakespeare\'s broken prose enacts psychic disintegration."',
              task: 'Paragraph on form mirroring mind.',
              success: 'Links form to meaning.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.6', '9R.2'],
              do: 'Compare 1.5 and 5.1 Lady Macbeths.',
              task: 'Comparative paragraph on arc and undoing.',
              success: 'Tracks across the play.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.3', '9W.1'],
              do: "Plan a thesis on Lady Macbeth's arc.",
              task: 'Write thesis + two paragraphs.',
              success: 'Essay shows cohesion.',
            }),
          ],
        },
        {
          number: 11,
          pages: 'Macbeth 5.5-5.8',
          keyVocabulary: [
            { en: 'nihilism' },
            { en: 'fall' },
            { en: 'nemesis' },
            { en: 'restoration' },
            { en: 'cyclical' },
          ],
          contextNote: {
            en: '"Tomorrow and tomorrow" soliloquy = nihilism. Macduff (not "of woman born") kills Macbeth; Malcolm restores order, but the cycle could recur.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Close read 5.5 soliloquy: metaphor (candle, walking shadow), iambic exhaustion.',
              task: 'Annotate the philosophy of futility.',
              success: 'Reads for tone.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.5', '9SL.3'],
              do: 'Evaluate: is the restoration genuine, or does the cycle of usurpation continue?',
              task: 'Structured argument.',
              success: 'Evaluates effects.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9W.6'],
              do: 'Model conclusion craft: link to thesis, broaden out.',
              task: 'Write a conceptual conclusion to a Macbeth essay.',
              success: 'Conclusion is conceptual.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.2', '9W.7'],
              do: 'Analyse the final couplet rhyme and order restored.',
              task: 'Paragraph on closure and form.',
              success: 'Sustains control.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.1', '9W.3'],
              do: 'Draft a full essay opening + conclusion on "tomorrow" speech.',
              task: 'Produce thesis-conclusion pair.',
              success: 'Argument frames a play-wide reading.',
            }),
          ],
        },
        {
          number: 12,
          pages: 'Macbeth criticism',
          keyVocabulary: [
            { en: 'feminist' },
            { en: 'psychological' },
            { en: 'patriarchy' },
            { en: 'agency' },
            { en: 'interpretation' },
          ],
          contextNote: {
            en: "Critical lenses: feminist (Lady M as patriarchy's victim), psychological (Macbeth ambitious from the start). Y9 holds multiple readings.",
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.3', '9R.1'],
              do: 'Read short critical extracts (feminist + psychological).',
              task: 'Summarise each in one sentence.',
              success: 'Grasps critical positions.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9SL.3', '9R.3'],
              do: 'Debate: which lens better fits the play?',
              task: 'Argue with three textual moments.',
              success: 'Synthesises critical perspectives.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9R.6'],
              do: 'Model integrated critical view: "While a feminist reading… a psychological reading…".',
              task: 'Write a paragraph weighing both.',
              success: 'Synthesises two readings.',
            }),
            lesson({
              focus: 'application',
              skills: ['9W.3', '9R.2'],
              do: 'Apply a critical lens to a chosen scene.',
              task: 'Analytical paragraph from one lens.',
              success: 'Deploys critical framing.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.1', '9W.3'],
              do: 'Plan HT2 essay using critical lenses.',
              task: 'Produce a full essay plan: thesis + 4 paragraphs + counter-reading.',
              success: 'Plan is GCSE-ready.',
            }),
          ],
        },
        {
          number: 13,
          pages: 'Macbeth full play + HT2 assessment',
          keyVocabulary: [
            { en: 'ambition' },
            { en: 'guilt' },
            { en: 'kingship' },
            { en: 'tyranny' },
            { en: 'order' },
          ],
          contextNote: {
            en: 'HT2 assessment: 60-minute thesis-driven essay on a play-wide theme. GCSE-style.',
          },
          lessons: [
            lesson({
              focus: 'consolidation-reading',
              skills: ['9R.1', '9R.6'],
              do: 'Whole-play overview: track one theme across five acts.',
              task: 'Build a theme tracker with eight quotations.',
              success: 'Reads across the text.',
            }),
            lesson({
              focus: 'consolidation-discussion',
              skills: ['9R.3', '9SL.3'],
              do: "Walking debate: ambition is/isn't the play's central concern.",
              task: 'Defend a position with evidence.',
              success: 'Structures an argument.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.1', '9W.3'],
              do: 'Model thesis-driven essay structure with conceptual signposting.',
              task: 'Plan + write opening of HT2 essay.',
              success: 'Structure is cohesive.',
            }),
            lesson({
              focus: 'paragraph-rehearsal',
              skills: ['9W.7', '9W.9'],
              do: 'Self-edit a draft using mark-scheme criteria.',
              task: 'Annotate three improvements.',
              success: 'Edits critically.',
            }),
            lesson({
              focus: 'assessment',
              skills: ['9W.1', '9W.3', '9R.2', '9R.4'],
              do: '60-minute assessment.',
              task: 'Write a full thesis-driven essay on a play-wide theme.',
              success: 'Sustains a thesis-led, cohesive argument.',
            }),
          ],
        },
      ],
    },
  ],
}

const Y9_T3: Year['terms'][number] = {
  number: 3,
  label: {
    en: 'Term 3 — Conflict: Poetry and Modern Drama',
    ar: 'الفصل الدراسي الثالث — الصراع: الشعر والمسرح الحديث',
  },
  overview: {
    en: 'GCSE-bridging term. Conflict poetry anthology (Owen "Dulce et Decorum Est", Sassoon, Brian Patten, Carol Ann Duffy, Imtiaz Dharker, Armitage "Remains") in HT1. Modern play (*Blood Brothers* or *An Inspector Calls* extracts) in HT2. Students exit KS3 GCSE-ready.',
  },
  setText: {
    en: 'Conflict poetry anthology + Russell *Blood Brothers* or Priestley *An Inspector Calls*',
  },
  vocabularyThemes: [
    { en: 'conflict, futility, propaganda, trauma, jingoism' },
    { en: 'class, responsibility, generation, capitalism, socialism' },
  ],
  bigSkillJump: {
    en: 'Students compare two texts in a structured essay AND deliver an assessed formal presentation — both core GCSE skills.',
  },
  halfTerms: [
    {
      id: '3.1',
      label: { en: 'Term 3.1' },
      assessment: { en: 'Comparative poetry essay: "Compare how two poets present conflict".' },
      weeks: [
        {
          number: 2,
          pages: 'Owen, "Dulce et Decorum Est"',
          keyVocabulary: [
            { en: 'futility' },
            { en: 'propaganda' },
            { en: 'trauma' },
            { en: 'jingoism' },
            { en: 'irony' },
          ],
          contextNote: {
            en: 'Owen wrote from the Western Front (1917); the Latin tag ("It is sweet and fitting to die for one\'s country") is exposed as "the old Lie".',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Close read for simile ("like old beggars"), gas-attack syntax, broken sonnet form.',
              task: 'Annotate form, imagery, structure.',
              success: 'Reads methods precisely.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.1'],
              do: 'Discuss: is the poem propaganda in reverse, or testimony?',
              task: 'Position yourself with evidence.',
              success: 'Weighs interpretations.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9R.2'],
              do: 'Model: "Owen presents the futility of war which reflects his disillusionment with jingoistic propaganda."',
              task: 'Draft three Y9-stem topic sentences.',
              success: 'Stems are conceptual.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.4', '9R.7'],
              do: 'Analyse the drowning metaphor and trauma imagery.',
              task: 'Analytical paragraph using terminology.',
              success: 'Uses precise terms.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.3', '9W.1'],
              do: 'Draft a thesis on Owen\'s exposure of "the old Lie".',
              task: 'Thesis + paragraph.',
              success: 'Thesis is conceptual.',
            }),
          ],
        },
        {
          number: 3,
          pages: 'Sassoon, "Suicide in the Trenches"',
          keyVocabulary: [
            { en: 'indictment' },
            { en: 'naive' },
            { en: 'contrast' },
            { en: 'soldiers' },
            { en: 'callous' },
          ],
          contextNote: {
            en: 'Sassoon\'s three quatrains move from a naive boy to his suicide to a direct indictment of "smug-faced crowds" who cheer soldiers home.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Close read tercet structure and ballad-like rhyme.',
              task: 'Annotate the structural pivot at stanza 3.',
              success: 'Reads structurally.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.3'],
              do: 'Discuss: who is the real target — soldiers, generals, or civilians?',
              task: 'Structured response.',
              success: 'Argues analytically.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9R.6'],
              do: 'Model comparison with Owen on tone (savage vs anguished).',
              task: 'Write a comparative paragraph.',
              success: 'Compares methods.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.2', '9W.7'],
              do: 'Analyse direct address ("You smug-faced crowds").',
              task: 'Paragraph on accusation as method.',
              success: 'Sustains analysis.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.3', '9R.6'],
              do: 'Plan comparative thesis: Sassoon vs Owen on conflict.',
              task: 'Thesis + first comparative paragraph.',
              success: 'Thesis compares.',
            }),
          ],
        },
        {
          number: 4,
          pages: 'Duffy, "War Photographer"',
          keyVocabulary: [
            { en: 'detached' },
            { en: 'ethical' },
            { en: 'gaze' },
            { en: 'complicit' },
            { en: 'indifferent' },
          ],
          contextNote: {
            en: "Duffy explores the photographer's ethical paralysis: documenting suffering for readers who flip past it. The poem itself is contained, ordered.",
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Close read religious imagery ("spools of suffering set out in ordered rows").',
              task: 'Annotate the conceit of priest/photographer.',
              success: 'Reads conceits.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.1'],
              do: 'Discuss: is the photographer ethical observer or complicit?',
              task: 'Take a position with evidence.',
              success: 'Argues with nuance.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9R.6'],
              do: 'Model contrast with Owen: physical violence vs mediated violence.',
              task: 'Comparative paragraph.',
              success: 'Compares modes.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.2', '9R.7'],
              do: 'Analyse the ending ("they do not care").',
              task: 'Paragraph on civilian indifference.',
              success: 'Deploys terminology.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.3', '9R.3'],
              do: 'Plan a paragraph weighing two readings of the photographer.',
              task: 'Comparative paragraph.',
              success: 'Weighs interpretations.',
            }),
          ],
        },
        {
          number: 5,
          pages: 'Dharker, "Honour Killing"',
          keyVocabulary: [
            { en: 'identity' },
            { en: 'autonomy' },
            { en: 'transformation' },
            { en: 'defiance' },
            { en: 'anaphora' },
          ],
          contextNote: {
            en: 'Dharker reframes "conflict" as internal/cultural: a woman strips off religious, national, gendered identities to declare autonomy. Anaphora ("At last…") structures liberation.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Close read anaphora and stripping imagery (chador, coat, skin).',
              task: 'Annotate structural unfolding.',
              success: 'Reads structurally.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.3'],
              do: 'Discuss: is "conflict" only war, or also identity-conflict?',
              task: 'Argue for an expanded definition.',
              success: 'Argues conceptually.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9R.6'],
              do: 'Model: "Dharker presents internal conflict which reflects diasporic and gendered struggle."',
              task: 'Write a Y9-stem topic sentence.',
              success: 'Stems are conceptual.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.2', '9W.7'],
              do: 'Analyse the body imagery and skin metaphor.',
              task: 'Paragraph on autonomy.',
              success: 'Sustains control.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.3', '9R.6'],
              do: 'Plan a comparison: Dharker vs Sassoon on what conflict means.',
              task: 'Comparative paragraph.',
              success: 'Compares across forms.',
            }),
          ],
        },
        {
          number: 6,
          pages: 'Armitage, "Remains"',
          keyVocabulary: [
            { en: 'trauma' },
            { en: 'intrusion' },
            { en: 'PTSD' },
            { en: 'monologue' },
            { en: 'ambivalence' },
          ],
          contextNote: {
            en: 'Armitage uses a soldier\'s monologue (from "The Not Dead", 2008) to dramatise PTSD: the looter "bursts again through the doors of the bank" of memory.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Close read enjambment, colloquial register, intrusion structure.',
              task: 'Annotate dramatic monologue form.',
              success: 'Reads voice precisely.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.1'],
              do: 'Discuss: how does PTSD become a kind of conflict in itself?',
              task: 'Position with textual evidence.',
              success: 'Extends interpretation.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9R.6'],
              do: 'Model contrast with Owen: trench trauma vs domestic trauma.',
              task: 'Comparative paragraph.',
              success: "Compares trauma's forms.",
            }),
            lesson({
              focus: 'application',
              skills: ['9R.2', '9R.7'],
              do: 'Analyse the present-tense intrusion ("his bloody life in my bloody hands").',
              task: 'Paragraph on PTSD as form.',
              success: 'Uses precise terms.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.3', '9R.6'],
              do: 'Plan a thesis comparing two conflict poems.',
              task: 'Thesis + first comparative paragraph.',
              success: 'Thesis compares.',
            }),
          ],
        },
        {
          number: 7,
          pages: 'Anthology revision + HT1 assessment',
          keyVocabulary: [
            { en: 'comparative' },
            { en: 'methods' },
            { en: 'effect' },
            { en: 'context' },
            { en: 'thesis' },
          ],
          contextNote: {
            en: 'HT1 assessment: 45-min comparative poetry essay "Compare how two poets present conflict". GCSE-style.',
          },
          lessons: [
            lesson({
              focus: 'consolidation-reading',
              skills: ['9R.6', '9R.4'],
              do: 'Build comparison grids across all five poems (theme, method, form, tone).',
              task: 'Complete a comparison grid.',
              success: 'Sees comparative patterns.',
            }),
            lesson({
              focus: 'consolidation-discussion',
              skills: ['9R.3', '9SL.3'],
              do: 'Walking debate: which poem most powerfully presents conflict?',
              task: 'Frame an evaluation.',
              success: 'Evaluates effects.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.1', '9W.3'],
              do: 'Model GCSE-style comparative thesis and conceptual link words ("similarly", "by contrast").',
              task: 'Draft thesis and first comparative paragraph.',
              success: 'Structure compares.',
            }),
            lesson({
              focus: 'paragraph-rehearsal',
              skills: ['9W.7', '9W.9'],
              do: 'Peer-edit comparative drafts.',
              task: 'Annotate three improvements.',
              success: 'Edits comparatively.',
            }),
            lesson({
              focus: 'assessment',
              skills: ['9W.1', '9W.3', '9R.6', '9R.2'],
              do: '45-minute assessment.',
              task: 'Compare how two poets present conflict.',
              success: 'Sustains comparison throughout.',
            }),
          ],
        },
      ],
    },
    {
      id: '3.2',
      label: { en: 'Term 3.2' },
      assessment: {
        en: 'Spoken language presentation (graded) + short analytical response on the modern play.',
      },
      weeks: [
        {
          number: 8,
          pages: 'An Inspector Calls Act 1',
          keyVocabulary: [
            { en: 'capitalism' },
            { en: 'complacency' },
            { en: 'hubris' },
            { en: 'dramatic-irony' },
            { en: 'hierarchy' },
          ],
          contextNote: {
            en: 'Priestley sets the play in 1912 (Titanic, complacent capitalism) but writes in 1945 (post-war socialism). Dramatic irony exposes Birling\'s "fact" claims.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Close read Birling\'s "unsinkable" Titanic speech.',
              task: 'Annotate dramatic irony and hubris.',
              success: 'Reads for irony.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.1'],
              do: 'Discuss: is Birling a caricature or a real warning?',
              task: 'Argue with evidence.',
              success: 'Weighs interpretations.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9W.10'],
              do: 'Model: "Priestley presents capitalist complacency which reflects post-war critique of 1912 values."',
              task: 'Y9-stem topic sentence.',
              success: 'Stems are conceptual.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.2', '9R.7'],
              do: 'Analyse stage directions (lighting "pink and intimate" to "brighter and harder").',
              task: 'Paragraph on staging as method.',
              success: 'Deploys dramatic terms.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.3', '9W.1'],
              do: 'Plan paragraph on Birling as embodiment of capitalism.',
              task: 'Thesis + paragraph.',
              success: 'Thesis is conceptual.',
            }),
          ],
        },
        {
          number: 9,
          pages: 'An Inspector Calls Act 2',
          keyVocabulary: [
            { en: 'responsibility' },
            { en: 'solidarity' },
            { en: 'conscience' },
            { en: 'transformation' },
            { en: 'generational' },
          ],
          contextNote: {
            en: 'Eva\'s story unfolds via each Birling. Sheila ("we really must stop these silly pretences") emerges as Priestley\'s generational hope.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: "Close read Sheila's arc in Act 2 (interruptions, sharper language).",
              task: 'Annotate her transformation markers.',
              success: 'Reads character arc.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.3'],
              do: 'Discuss: is generational hope realistic or didactic?',
              task: 'Structured argument.',
              success: 'Argues analytically.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9R.6'],
              do: 'Model contrast: Sheila vs her parents.',
              task: 'Comparative paragraph.',
              success: 'Compares characters.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.2', '9W.7'],
              do: "Analyse Mrs Birling's refusal of responsibility.",
              task: "Paragraph on solidarity's refusal.",
              success: 'Sustains control.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.3', '9W.1'],
              do: "Plan a thesis on Sheila as Priestley's mouthpiece.",
              task: 'Thesis + paragraph.',
              success: 'Thesis is conceptual.',
            }),
          ],
        },
        {
          number: 10,
          pages: 'An Inspector Calls Act 3',
          keyVocabulary: [
            { en: 'socialism' },
            { en: 'allegory' },
            { en: 'didactic' },
            { en: 'prophecy' },
            { en: 'communal' },
          ],
          contextNote: {
            en: 'The Inspector\'s final speech ("fire and blood and anguish") is a socialist prophecy. The final phone call cycles the moral lesson.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.1', '9R.4'],
              do: 'Close read the final speech: triadic structure, biblical register.',
              task: 'Annotate rhetoric and form.',
              success: 'Reads rhetorically.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9R.3', '9SL.3'],
              do: 'Discuss: is Goole an allegory, a ghost, or a moral agent?',
              task: 'Argue with textual support.',
              success: 'Weighs interpretations.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.3', '9R.6'],
              do: 'Model: "Priestley presents socialism as moral necessity which reflects post-war hopes for collective responsibility."',
              task: 'Y9-stem topic sentence.',
              success: 'Stems are conceptual.',
            }),
            lesson({
              focus: 'application',
              skills: ['9R.2', '9R.7'],
              do: 'Analyse the cyclical structure (final phone call).',
              task: 'Paragraph on cyclical form.',
              success: 'Deploys terminology.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9W.1', '9W.3'],
              do: 'Plan thesis essay: how does Priestley critique capitalism?',
              task: 'Thesis + plan.',
              success: 'Plan is GCSE-ready.',
            }),
          ],
        },
        {
          number: 11,
          pages: 'Spoken Language prep',
          keyVocabulary: [
            { en: 'rhetoric' },
            { en: 'audience' },
            { en: 'register' },
            { en: 'pathos' },
            { en: 'thesis' },
          ],
          contextNote: {
            en: 'Plan GCSE-style spoken language presentation: argue a position, build rhetorical structure, rehearse.',
          },
          lessons: [
            lesson({
              focus: 'explicit-reading',
              skills: ['9R.3', '9SL.2'],
              do: 'Watch a model spoken presentation; identify three rhetorical moves.',
              task: 'Annotate the model.',
              success: 'Identifies rhetoric.',
            }),
            lesson({
              focus: 'reading-discussion',
              skills: ['9SL.1', '9R.3'],
              do: 'Pitch your topic and thesis to a partner.',
              task: 'Refine thesis through feedback.',
              success: 'Contributes thoughtfully.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.1', '9W.6', '9W.8'],
              do: 'Model presentation script: hook, thesis, three points, call to action.',
              task: 'Draft full script (4-5 mins).',
              success: 'Script is structured.',
            }),
            lesson({
              focus: 'application',
              skills: ['9W.4', '9W.8', '9SL.2'],
              do: 'Rehearse with pace, pause, emphasis. Edit script for spoken register.',
              task: 'Rehearse twice, edit script.',
              success: 'Controls register.',
            }),
            lesson({
              focus: 'independent-outcome',
              skills: ['9SL.2', '9SL.3', '9W.1'],
              do: 'Final rehearsal with peer feedback.',
              task: 'Deliver dry run; act on one piece of feedback.',
              success: 'Responds to feedback.',
            }),
          ],
        },
        {
          number: 12,
          pages: 'Spoken Language assessment',
          keyVocabulary: [
            { en: 'fluency' },
            { en: 'rhetoric' },
            { en: 'analytical' },
            { en: 'response' },
            { en: 'evaluation' },
          ],
          contextNote: {
            en: 'Deliver GCSE-style spoken language presentation. Assessed on fluency, structure, range, Q&A response.',
          },
          lessons: [
            lesson({
              focus: 'consolidation-reading',
              skills: ['9R.3', '9SL.1'],
              do: 'Review GCSE Spoken Language mark scheme as a class.',
              task: 'Annotate the criteria.',
              success: 'Understands criteria.',
            }),
            lesson({
              focus: 'consolidation-discussion',
              skills: ['9SL.1', '9R.3'],
              do: 'Pre-presentation Q&A practice in pairs.',
              task: 'Generate three likely questions for each topic.',
              success: 'Anticipates questions.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.8', '9W.6'],
              do: 'Final script edits: cut filler, sharpen openers.',
              task: 'Submit polished script.',
              success: 'Script is honed.',
            }),
            lesson({
              focus: 'application',
              skills: ['9SL.2', '9SL.3'],
              do: 'First half of class delivers presentations.',
              task: 'Deliver presentation; answer two questions.',
              success: 'Fluent and analytical.',
            }),
            lesson({
              focus: 'assessment',
              skills: ['9SL.2', '9SL.3'],
              do: 'Second half of class delivers presentations (assessed).',
              task: 'Deliver presentation; answer two questions.',
              success: 'Sustains a structured, analytical contribution.',
            }),
          ],
        },
        {
          number: 13,
          pages: 'An Inspector Calls full play + end-of-KS3 assessment',
          keyVocabulary: [
            { en: 'responsibility' },
            { en: 'socialism' },
            { en: 'allegory' },
            { en: 'generational' },
            { en: 'didactic' },
          ],
          contextNote: {
            en: 'End-of-KS3 assessment: 45-min analytical response on Inspector Calls. Students are now GCSE-ready, with thesis-driven essay habits.',
          },
          lessons: [
            lesson({
              focus: 'consolidation-reading',
              skills: ['9R.1', '9R.6'],
              do: 'Whole-play recap: trace responsibility across three acts.',
              task: 'Build a theme tracker.',
              success: 'Reads across the text.',
            }),
            lesson({
              focus: 'consolidation-discussion',
              skills: ['9R.3', '9SL.3'],
              do: "Final seminar: which character best embodies Priestley's message?",
              task: 'Defend a position.',
              success: 'Structures a final argument.',
            }),
            lesson({
              focus: 'explicit-writing',
              skills: ['9W.1', '9W.3'],
              do: 'Model GCSE-style essay opening on Inspector Calls.',
              task: 'Draft thesis and opening paragraph.',
              success: 'Structure is cohesive.',
            }),
            lesson({
              focus: 'paragraph-rehearsal',
              skills: ['9W.7', '9W.9'],
              do: 'Self-edit using mark-scheme criteria; KS3 reflection.',
              task: 'Annotate three improvements and write a half-page reflection on your KS3 journey.',
              success: 'Edits critically and reflects.',
            }),
            lesson({
              focus: 'assessment',
              skills: ['9W.1', '9W.3', '9R.2', '9R.4'],
              do: 'End-of-KS3 assessment (45 mins).',
              task: 'Write a thesis-driven analytical response on the modern play.',
              success: 'GCSE-ready: thesis-led, method-analytical, conceptually framed.',
            }),
          ],
        },
      ],
    },
  ],
}

export const YEAR_9: Year = {
  number: 9,
  name: { en: 'Year 9 — Mastery', ar: 'السنة التاسعة — الإتقان' },
  overview: {
    en: 'Year 9 is the bridge to GCSE. Students move from "This suggests… because…" to "This suggests… which reflects…" — methods analysed across texts, conceptual interpretations, evaluation. The year covers pre-1914 prose (Jekyll and Hyde, T1), Shakespeare (Macbeth, T2), and conflict poetry + modern drama (T3). Students exit writing full thesis-driven literature essays.',
  },
  yearlyExpectations: {
    reading: [
      { en: '9R.1 — Interpret explicit and implicit meanings in complex texts.' },
      { en: '9R.2 — Select, embed and integrate quotations fluently.' },
      { en: '9R.3 — Analyse developed inferences, exploring multiple interpretations.' },
      { en: '9R.4 — Analyse how writers use language, structure and form to shape meaning.' },
      { en: "9R.5 — Evaluate the effects of writer's choices on the reader." },
      { en: '9R.6 — Analyse and evaluate similarities and differences across texts.' },
      { en: '9R.7 — Use precise subject terminology confidently and accurately.' },
    ],
    writing: [
      { en: '9W.1 — Structure writing cohesively and logically across whole texts.' },
      { en: '9W.2 — Use a wide range of punctuation accurately and deliberately.' },
      { en: '9W.3 — Develop ideas in depth with clear, critical explanation.' },
      { en: '9W.4 — Use varied sentence structures deliberately for effect.' },
      { en: '9W.5 — Manipulate perspective, viewpoint and voice confidently.' },
      { en: '9W.6 — Craft structure, tone and imagery to shape reader response.' },
      { en: '9W.7 — Write with sustained control for a range of purposes and audiences.' },
    ],
    language: [
      { en: '9W.8 — Control register and adapt style for different audiences and purposes.' },
      { en: '9W.9 — Edit, refine and improve writing independently and critically.' },
      { en: '9W.10 — Manipulate vocabulary and syntax deliberately for effect.' },
    ],
    speaking: [
      { en: '9SL.1 — Contribute thoughtfully to discussions, developing and challenging ideas.' },
      { en: '9SL.2 — Speak clearly, confidently and fluently in a range of contexts.' },
      { en: '9SL.3 — Present structured, analytical ideas using appropriate register.' },
    ],
  },
  rubric: [],
  terms: [Y9_T1, Y9_T2, Y9_T3],
}
