'use client'

import { useEffect, useRef, useState, useSyncExternalStore } from 'react'
import type { Ref } from 'react'

import type { PlateRef } from '@/lib/comics/types'

import { useHoldMotion } from './play-on-view'

/**
 * A linocut plate, fetched from its own file when it is about to be seen and
 * inlined into the page.
 *
 * WHY (26 September 2026). The drawings used to be rendered into the page, and
 * every panel of a text was sent with it whether or not the student ever opened
 * that moment: A Christmas Carol's page was 3.3 MB of HTML, 672 KB on the wire,
 * against 476 KB and 58 KB for a text with no comics. Now each plate is a file,
 * /comics/<slug>/<key>.<hash>.svg, written at build time by
 * scripts/generate-comic-plates.mjs, and the page carries only its PlateRef.
 *
 * WHY INLINE IT, AND NOT SHOW THE <img>. The motion is page CSS: LinocutStyles'
 * rules, switched by PlayOnView's lc-armed and lc-play classes on an ancestor,
 * and switched off by prefers-reduced-motion. An SVG shown through <img> is a
 * separate document the page's CSS cannot reach, so it would be a still. The
 * files are generated by our own code and served from our own origin (the CSP
 * allows the fetch under connect-src 'self', and the plates' inline style
 * attributes under style-src 'unsafe-inline'), which is why inlining them with
 * dangerouslySetInnerHTML is safe; `loadPlate` refuses anything that is not a
 * plate.
 *
 * WHAT A READER GETS AT EVERY MOMENT.
 * - Server HTML, scripts off, crawlers, and before the file arrives: an <img>
 *   of the same file, the finished print (the file carries PLATE_CSS for this),
 *   lazy-loaded by the browser. One limit that is not this module's: on the
 *   text pages the whole visuals block streams in inside a Suspense boundary,
 *   which React reveals with a script, so a reader with scripts off does not
 *   see the block at all (checked 26 September 2026 on the dev server and on
 *   production, where the same was true before plates were files). The <img>
 *   is in the HTML for crawlers that read it without running scripts.
 * - Once the box is within PLATE_LOAD_MARGIN of the screen: the file is fetched,
 *   kept in a module cache, and inlined in place of the <img>, where the page's
 *   motion rules reach it.
 * - The box around it is the one accessible image throughout: role="img" with
 *   the alt text, from the first byte of HTML, so assistive technology meets
 *   the same node whether the drawing is loading, an <img> or inlined, and the
 *   swap announces nothing. The <img> keeps its alt for crawlers; the inlined
 *   plate keeps its own role and label, and the children of role="img" are
 *   presentational, so neither is read twice.
 * - No layout shift: the box's aspect ratio is the drawing's, set before
 *   anything loads.
 * - The motion waits for the drawing: while the file is on its way, the piece
 *   around it is held armed (useHoldMotion, in play-on-view.tsx), so it plays
 *   with its drawing rather than over an empty sheet. A failed load, or
 *   PLATE_WAIT_MS in view, lets it play with whatever the <img> shows.
 *
 * Ahead of the reader, prefetchPlate() fills the same cache: the key-moments
 * player fetches the next moment's plate, so pressing Next, or autoplay, shows
 * a drawing that is already here, with its motion from the first frame.
 */

/** How far off screen a plate starts loading: about a screen ahead of the reader. */
export const PLATE_LOAD_MARGIN = '800px 0px'

const texts = new Map<string, string>()
const pending = new Map<string, Promise<string>>()

/**
 * The plate at `src`, fetched once per page however many times it is asked
 * for. Rejects anything that is not one of our plates: an error page or a
 * redirect must never be inlined.
 */
export function loadPlate(src: string): Promise<string> {
  const have = texts.get(src)
  if (have !== undefined) return Promise.resolve(have)
  let p = pending.get(src)
  if (!p) {
    p = fetch(src)
      .then((r) => {
        if (!r.ok) throw new Error(`${src}: HTTP ${r.status}`)
        return r.text()
      })
      .then((text) => {
        if (!/^<svg [^>]*class="lc-plate"/.test(text)) throw new Error(`${src}: not a plate`)
        texts.set(src, text)
        return text
      })
      .finally(() => pending.delete(src))
    pending.set(src, p)
  }
  return p
}

/** Fetch a plate ahead of need. A failure is left for the <img> to show. */
export function prefetchPlate(src: string): void {
  loadPlate(src).catch(() => {})
}

const noop = () => () => {}

/**
 * A served plate, inlined: what a LazyPlate becomes once its file arrives. The
 * preview script renders pieces through this with the file's own text, so an
 * artist's preview is the markup a student's browser ends up with.
 */
export function InlinedPlate({ svg }: { svg: string }) {
  return <div dangerouslySetInnerHTML={{ __html: svg }} />
}

/** The accessible box a plate sits in, the drawing's shape before it arrives. */
export function PlateBox({
  plate,
  svg,
  boxRef,
}: {
  plate: PlateRef
  /** The plate file's text, once it has arrived. */
  svg?: string
  boxRef?: Ref<HTMLDivElement>
}) {
  return (
    <div
      ref={boxRef}
      className="lc-art"
      role="img"
      aria-label={plate.alt}
      style={{ aspectRatio: `${plate.width} / ${plate.height}` }}
    >
      {svg !== undefined ? (
        <InlinedPlate svg={svg} />
      ) : (
        // A plain <img>, not next/image: the file is an SVG served as it is,
        // which the image optimiser refuses, and it is replaced by the inlined
        // plate as soon as the file is fetched.
        // eslint-disable-next-line @next/next/no-img-element
        <img
          className="lc-plate"
          src={plate.src}
          alt={plate.alt}
          width={plate.width}
          height={plate.height}
          loading="lazy"
          decoding="async"
        />
      )}
    </div>
  )
}

export function LazyPlate({ plate }: { plate: PlateRef }) {
  // False while hydrating, so the first client render matches the server's
  // <img> even if the cache already holds the file; true for a plate mounted
  // later (the next moment in the player), which then draws at once from the
  // cache with no <img> in between.
  const hydrated = useSyncExternalStore(
    noop,
    () => true,
    () => false,
  )
  const [arrived, setArrived] = useState<{ src: string; svg: string } | null>(null)
  const [failed, setFailed] = useState<string | null>(null)
  const svg = arrived?.src === plate.src ? arrived.svg : hydrated ? texts.get(plate.src) : undefined
  const box = useRef<HTMLDivElement>(null)

  // Hold the piece's motion until the drawing is here, so it plays with it
  // rather than over an empty sheet (see PlayOnView). A failed load releases
  // it: the <img> is what the reader gets then.
  useHoldMotion(svg === undefined && failed !== plate.src)

  useEffect(() => {
    if (svg !== undefined) return
    const el = box.current
    if (!el) return
    let live = true
    const load = () =>
      loadPlate(plate.src).then(
        (text) => {
          if (live) setArrived({ src: plate.src, svg: text })
        },
        (e: unknown) => {
          // The <img> stays, so the reader still has the finished print (or,
          // if the file itself is missing, the alt text). Said out loud, so a
          // missing file is seen in development rather than shrugged off.
          console.error('Linocut plate could not be loaded:', e)
          if (live) setFailed(plate.src)
        },
      )
    if (typeof IntersectionObserver === 'undefined') {
      load()
      return () => {
        live = false
      }
    }
    const io = new IntersectionObserver(
      (entries) => {
        if (entries.some((e) => e.isIntersecting)) {
          io.disconnect()
          load()
        }
      },
      { rootMargin: PLATE_LOAD_MARGIN },
    )
    io.observe(el)
    return () => {
      live = false
      io.disconnect()
    }
  }, [plate.src, svg])

  return <PlateBox plate={plate} svg={svg} boxRef={box} />
}
