/**
 * paper-1 set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Set-text notice`, ar: `تنبيه النص المحدد` },
  s1: { en: `Songs of Ourselves`, ar: `أناشيد أنفسنا` },
  s2: { en: `The Thought-Fox`, ar: `الفأرة فيthoughts` },
  s3: { en: `Hawk Roosting`, ar: `هوك روستינג` },
  s4: { en: `Things Fall Apart`, ar: `تتساقط الأمور` },
  s5: { en: `To Kill a Mockingbird`, ar: `To Kill a Mockingbird` },
  s6: { en: `Cluster rights:`, ar: `حقوق التجمعات` },
  s7: { en: `Section A &mdash; Poetry`, ar: `SECTION A &mdash; الشعر` },
  s8: { en: `Section B &mdash; Prose`, ar: `SECTION B &mdash; نثر` },
  s9: { en: `Approaching a Poetry Question`, ar: `اقتراب من سؤال الشعر` },
  s10: { en: `Passage-Based Questions`, ar: `أسئلة مبنية على النصوص` },
  s11: { en: `What to do:`, ar: `شيء تفعله:` },
  s12: { en: `Common mistake:`, ar: `خطيئة شائعة:` },
  s13: { en: `Essay Questions`, ar: `أسئلة مقالة` },
  s14: {
    en: `Model Paragraph Structure (PEAL)`,
    ar: `بنية المقاطع النموذجية (دليل، نقطة، أمثلة، liên kết lại)`,
  },
}
