/**
 * unseen-poetry set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Common Mistake`, ar: `خطيئة شائعة` },
  s1: { en: `Unseen Poetry`, ar: `الشعر غير المعروف` },
  s2: { en: `What + How + Why`, ar: `شنو + شلون + ليش` },
  s3: { en: `Key questions:`, ar: `أسئلة رئيسية:` },
  s4: { en: `Weak (Separate)`, ar: `ضعيف (منفصل)` },
  s5: { en: `Strong (Integrated)`, ar: `قوي (متكامل)` },
  s6: { en: `Comparison Structure`, ar: `هياكل المقارنة` },
  s7: { en: `Showing Similarity`, ar: `การแสดง الشبهات` },
  s8: { en: `Similarly, both poets...`, ar: `بالمقابل، كلا الشاعرين...` },
  s9: {
    en: `In the same way, Poem B also...`,
    ar: `على نفس الشاية، القصيدة ب тоже... 

(Note: There's a small error in the Khaleeji Arabic phrase "القصيدة ب" which should be corrected to fit properly. The correct translation would be:)

على نفس الشاية، القصيدة الثانية тоже...`,
  },
  s10: {
    en: `This idea is echoed in Poem B, where...`,
    ar: `هذا الفكرة متعودة في القصيدة ب، حيث...`,
  },
  s11: {
    en: `Like Poem A, the second poem presents...`,
    ar: `مثل القصيدة أ، ت présentent القصيدة الثانية... 

(Note: There seems to be a French word "présentent" in the translation which should not be there. Let's correct it.)

مثل القصيدة أ، القصيدة الثانية ت present...`,
  },
  s13: { en: `In contrast, Poem B...`, ar: `في المقابل، القصيدة ب...` },
  s16: {
    en: `While both poems explore [theme], their methods diverge...`,
    ar: `بينما تستكشف كلا من القصائد [ال chủة]، تختلف أساليبهما...`,
  },
  s17: { en: `Feature spotting without analysis.`, ar: `البحث عن الخصائص بدون تحليل` },
  s18: { en: `Retelling the poem.`, ar: `إعادة إلREADINGień the poemień` },
  s19: { en: `Ignoring structure.`, ar: `IGNORING STRUCTURE` },
  s20: { en: `Quoting entire lines.`, ar: `اقتباس كامل السطور.` },
  s21: {
    en: `Writing about Poem A then Poem B separately.`,
    ar: `كتابة عن القصيدة أ ثم القصيدة ب منفصلة عن بعضهما`,
  },
  s24: { en: `What to Do`, ar: `شي ماذا تفعل؟` },
  s25: { en: `Key Technical Terms`, ar: `مصطلحات فنية رئيسية` },
  s26: { en: `Storm on the Island`, ar: `عاصفة على الجزيرة` },
  s27: { en: `The Émigrée`, ar: `الهجرة` },
}
