/**
 * writing-skills set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Article Writing`, ar: `كتابة المقالة` },
  s1: { en: `Essential Conventions`, ar: `ال conventions الأساسية` },
  s2: { en: `Subheading (optional)`, ar: `عنوان فرعي (اختياري)` },
  s3: { en: `Byline (optional)`, ar: `(بال_optional_)` },
  s4: { en: `Engaging Opening`, ar: `افتتاحية جذابة` },
  s5: { en: `Structured Body`, ar: `` },
  s6: { en: `Strong Conclusion`, ar: `استنتاج قوي` },
  s7: {
    en: `Example Article Opening`,
    ar: `المقالة الافتتاحية في The English Hub تبدأ بالترحيب بطلابنا إحنا وتذكيرهم بأهمية الاستعداد للامتحانات(gcse, igcse). إحنا نشجع الطلاب على مراجعة المنهج والتدرب على الأسئلة السابقة. ا`,
  },
  s8: { en: `By J. Carter`, ar: `ج. كارتر` },
  s9: { en: `Letter Writing`, ar: `كتابة الرسائل` },
  s10: { en: `Formal Letter Format`, ar: `صيغة الرسالة الرسمية` },
  s11: { en: `Dear Mr/Mrs/Ms [Surname],`, ar: `عزيزي السيد/السيدة [اسم العائلة]،` },
  s12: { en: `Yours sincerely,`, ar: `بو طيبة خاطر،` },
  s13: {
    en: `Key rules:`,
    ar: ``,
  },
  s14: { en: `Informal Letter Format`, ar: `Shape الرسالة غير الرسمية` },
  s15: { en: `Dear [First name],`, ar: `عزيزي [اسم الأول]،` },
  s16: { en: `Best wishes / Love / See you soon,`, ar: `besten التوفيق / Liebe / أشوفك بعد الحين` },
  s17: {
    en: `Example Formal Letter Opening`,
    ar: `عزيزي الطالب،

تحية طيبة وبعد،

أنا أكتب إليك اليوم لمناقشة بعض النقاط الهامة المتعلقة بتحضيرك للامتحانات. يرجى قراءة هذه الرسالة بعناية وتطبيق النصائح المقدمة لك.

إذا كان لديك أي أسئلة أو استفسارات، فلا تتردد في التواصل معي. أنا هنا لمساعدتك`,
  },
  s18: { en: `Dear Ms Thornton,`, ar: `عزيزة السيدة ثورnton،` },
  s19: { en: `Speech Writing`, ar: `كتابة الخطابات` },
  s21: { en: `Example Speech Opening`, ar: `مثال لبداية خطبة` },
  s22: {
    en: `And I think it is time we talked about why.`,
    ar: `وأنا أعتقد أنه حان الوقت لنتحدث عن شلون.`,
  },
  s23: { en: `Review Writing`, ar: `راجع الكتابة` },
  s24: { en: `Review Structure`, ar: `راجع structure` },
  s25: { en: `Detailed Evaluation`, ar: `تقييم مفصل` },
  s26: { en: `Personal Voice`, ar: `الصوت الشخصي` },
  s27: { en: `Conclusion &amp; Recommendation`, ar: `خاتمة وتقديرات` },
  s29: { en: `Rating: 3/5`, ar: `تقييم: 3 من 5` },
  s30: { en: `The problem is, it tastes ordinary.`, ar: `المشكلة إنها طعمها عادي.` },
  s31: { en: `Essay Writing`, ar: `كتابة المقالات` },
  s32: { en: `Essay Structure`, ar: `STRUCTURE المقال` },
  s33: { en: `Body Paragraphs (3-4)`, ar: `فقرات الجسم (3-4)` },
  s34: {
    en: `Example Essay Opening`,
    ar: `مثال لبداية مقال: شلون بدء أطروحتي؟ أبغى أقول إن موضوعنا اليوم هو عن شخصية ماكبث في مسرحية ماكبث لووليم شكسبير. إحنا رح نشوف كيف ماكبث يتحول من قائد`,
  },
  s35: { en: `Universal Writing Tips`, ar: `نصائح كتابة عالمية` },
  s37: { en: `Vocabulary (Technical accuracy)`, ar: `` },
  s38: { en: `Sentence Variety (Technical accuracy)`, ar: `تنوع الجمل (دقة تقنية)` },
  s39: { en: `Punctuation Variety (Technical accuracy)`, ar: `تنوع الترقيم (دقة تقنية)` },
  s40: {
    en: `Writing skills for Pearson Edexcel GCSE English Language: structure, vocabulary, sentence variety, and creative/transactional writing models.`,
    ar: `مهارات الكتابة لاختباراتPearson Edexcel للغة الإنجليزية(gcse): الهيكل، المفردات، تنوع الجمل، ونماذج الكتابة الإبداعية والعملية.`,
  },
}
