/**
 * inspector-calls set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Paper 2: Exploring Effects and Impact`, ar: `ورقية 2: استكشاف التأثيرات والتأثيرات` },
  s1: { en: `Assessment Objectives`, ar: `أهداف التقييم` },
  s2: { en: `Reading and response:`, ar: `قراءة ورد فعل:` },
  s3: { en: `Language, form and structure:`, ar: `لغة، شكل وStructure` },
  s4: { en: `Contextual understanding:`, ar: `الفهم السياقي` },
  s5: { en: `Written accuracy:`, ar: `دقة الكتابة:` },
  s6: {
    en: `Act 1: The Engagement and the Inspector&rsquo;s Arrival`,
    ar: `الatto 1: خطبة العروس ووصول المفتش`,
  },
  s7: { en: `Act 2: Gerald and Mrs Birling Exposed`, ar: `الatto 2: جيرالد وستيدة بيرلين عرّيوا` },
  s8: {
    en: `Act 3: Eric&rsquo;s Confession and the Aftermath`,
    ar: `الatto الثالث: اعتراف إريك والنتائج التي تبعته`,
  },
  s9: { en: `Inspector Goole`, ar: `Inspector Goole` },
  s10: { en: `Mr Birling`, ar: `mr بريلينج` },
  s11: { en: `Key character arc`, ar: `arc شخصية رئيسية` },
  s12: { en: `Mrs Birling`, ar: `مrs بريرلين` },
  s13: { en: `Sheila Birling`, ar: `شيليا برلين` },
  s14: { en: `Eric Birling`, ar: `إريك برلينج` },
  s15: { en: `Gerald Croft`, ar: `جيرالد كروفت` },
  s16: { en: `Eva Smith / Daisy Renton`, ar: `إيفا سميث / دايسي رينتون` },
  s17: {
    en: `Written in 1945, Set in 1912`,
    ar: `المكتوبة في عام 1945، والم setLocationedin عام 1912`,
  },
  s18: {
    en: `The Welfare State and Post-War Britain`,
    ar: `الدولة التأمينية وبريطانيا بعد الحرب العالمية الثانية`,
  },
  s19: {
    en: `Edwardian Class System (1912 setting)`,
    ar: `نظام الطبقات في عهد إدوارديان ( SETTINGS 1912 )`,
  },
  s20: { en: `Priestley&rsquo;s Socialism`, ar: `اشتراكية برستلي` },
  s21: { en: `The Titanic and Dramatic Irony`, ar: `الطينيتك وحمق العذراية` },
  s22: { en: `Women&rsquo;s Rights`, ar: `حقوق المرأة` },
  s23: { en: `Introduction (3&ndash;4 sentences)`, ar: `مقدمة (ثلاثة إلى أربع جمل)` },
  s24: { en: `Paragraph 1: Beginning of the play`, ar: `بداية المسرحية` },
  s25: { en: `Paragraph 2: Middle of the play`, ar: `منتصف اللعبה` },
  s26: { en: `Paragraph 3: End of the play`, ar: `نهاية المسرحية` },
  s28: { en: `OCR Exam Technique Tips`, ar: `نصائح تقنية للاختبارات من OCR` },
  s29: { en: `No extract:`, ar: `لا يوجد نص لترجمته councillorspeaks` },
  s30: { en: `Time management:`, ar: `إدارة الوقت:` },
}
