// ─── IELTS Academic Reading - practice item bank (Set 38) ──────────────────
// ORIGINAL content written for The English Hub. These passages and questions are
// invented purely to practise the Academic Reading question formats. They are
// NOT reproductions of any official IELTS past paper, and no official
// affiliation is implied. Academic track. Topic domains: desalination (turning
// seawater into fresh water) / the chemistry of fireworks / how honey bees make
// honey.
//
// This test is MATCHING-RICH. It contains three matching questions across three
// different variants: Matching Headings (Passage 1), Matching Information /
// which-paragraph (Passage 2) and Matching Features - statements to components
// (Passage 3), alongside the usual mix of True/False/Not Given, multiple choice
// and sentence/summary completion.
//
// One complete, carefully-checked test: 3 passages, 40 marks (each matching item
// counts as one mark). Every answer is verifiable from the passage text and is
// justified in the explanation. Marks: P1 = 6 (matching) + 7 = 13; P2 = 5
// (matching) + 8 = 13; P3 = 5 (matching) + 9 = 14. Total = 40.
// ────────────────────────────────────────────────────────────────────────────

import type { ReadingTest } from '@/lib/ielts/types'

export const READING_SET_38: ReadingTest[] = [
  {
    id: 'rd-academic-038',
    title: 'Academic Reading - Practice Test 38',
    track: 'academic',
    estimatedMinutes: 60,
    passages: [
      // ───────────────────────────── PASSAGE 1 ─────────────────────────────
      {
        id: 'rd-academic-038-p1',
        title: 'Making Fresh Water from the Sea',
        body: `More than two-thirds of the Earth is covered by water, yet almost none of it can be drunk. The oceans hold the overwhelming bulk of the planet's water, but their salt content is far too high for human beings, crops or most industry to use directly. As populations grow and rivers and aquifers come under strain, the temptation to tap that vast salty reservoir has become hard to resist. The process of removing salt and other dissolved minerals from seawater, so that what remains is fit to drink, is called desalination, and for the driest and richest nations it has moved from a curiosity to a mainstay of the water supply.

The idea is far from new. Sailors and natural philosophers knew centuries ago that if seawater is boiled, the steam that rises carries no salt with it; collect and cool that steam and it condenses into fresh water, leaving the salt behind in the pot. This is the principle of distillation, and it remains the heart of the older family of desalination methods, known as thermal processes. Modern thermal plants are vastly more elaborate than a kettle, using a series of chambers held at progressively lower pressures so that the seawater boils at ever cooler temperatures, and recovering much of the heat at each stage to warm the incoming water. Even so, boiling water on an industrial scale demands an enormous amount of energy, and for that reason thermal desalination has flourished mainly where fuel is cheap and plentiful.

A quite different approach now dominates new construction around the world. Instead of boiling the water, it is forced under great pressure against a thin plastic membrane whose pores are so fine that water molecules can squeeze through while the larger salt ions are held back. Because the flow of water runs opposite to the direction it would naturally take, the method is called reverse osmosis. Left to itself, water moves across such a membrane from the fresher side towards the saltier side, an effect known as osmosis; reverse osmosis overcomes and reverses this tendency by applying a pressure greater than the natural pull. The membranes are delicate and easily clogged, so the seawater must be carefully filtered before it reaches them, but the energy needed is markedly lower than for boiling, and it is this saving that has made reverse osmosis the method of choice.

Whichever route is taken, desalination is not cheap, and its costs are not only financial. The single largest expense is energy, which is why the price of desalinated water rises and falls with the price of power, and why engineers work constantly to squeeze more fresh water from every unit of electricity. Where that electricity is generated by burning fossil fuels, the plants also add to the carbon dioxide warming the planet, a paradox for technology often promoted as a response to a changing climate. Increasingly, operators are pairing desalination with solar or wind power to soften both the cost and the environmental toll.

The waste left behind raises a further difficulty. For every litre of fresh water produced, the plant must dispose of a roughly equal or greater volume of brine, a concentrated solution far saltier than the sea it came from and often warm and laden with the chemicals used to clean the membranes. Most coastal plants return this brine to the ocean, but because it is dense it tends to sink and spread along the seabed, where it can smother slow-moving creatures and disturb the communities of the shallow sea floor. Careful design can lessen the harm by diluting the brine rapidly or releasing it through diffusers that mix it quickly with seawater, yet the problem cannot be made to vanish altogether.

For all these drawbacks, the spread of desalination seems certain to continue. In parts of the Gulf and in other arid regions, a large share of the drinking water already comes from the sea, and cities that once depended wholly on rainfall and rivers now treat the ocean as a reserve against drought. The hope of many engineers is that cheaper membranes, better recovery of energy and a shift to renewable power will, in time, turn desalination from an expensive last resort into an affordable and genuinely sustainable source of the water that a thirsty world increasingly demands.`,
        questions: [
          // ── Matching Headings (6 items, 8 options -> 2 distractors) = 6 marks ──
          {
            id: 'rd-038-p1-q1',
            type: 'matching',
            variant: 'headings',
            prompt:
              'The passage has six paragraphs, A-F. Choose the correct heading for each paragraph from the list of headings below. There are more headings than paragraphs, so you will not use them all. Write the correct number (i-viii) for each paragraph.',
            options: [
              { key: 'i', label: 'Boiling the sea: the oldest method' },
              { key: 'ii', label: 'A salty waste that is hard to dispose of' },
              { key: 'iii', label: 'Vast oceans, almost no drinkable water' },
              { key: 'iv', label: 'Pushing water through a membrane' },
              { key: 'v', label: 'The high cost of energy and its climate price' },
              { key: 'vi', label: 'Why salt is essential to ocean life' },
              { key: 'vii', label: 'A growing reliance and the hope of cheaper supply' },
              { key: 'viii', label: 'Storing fresh water in underground tanks' },
            ],
            items: [
              { id: 'p1-h-a', text: 'Paragraph A', answer: 'iii' },
              { id: 'p1-h-b', text: 'Paragraph B', answer: 'i' },
              { id: 'p1-h-c', text: 'Paragraph C', answer: 'iv' },
              { id: 'p1-h-d', text: 'Paragraph D', answer: 'v' },
              { id: 'p1-h-e', text: 'Paragraph E', answer: 'ii' },
              { id: 'p1-h-f', text: 'Paragraph F', answer: 'vii' },
            ],
            explanation:
              'A stresses that the oceans hold most of the planet’s water yet "almost none of it can be drunk" (iii). B describes boiling seawater so the steam leaves the salt behind, the oldest thermal method (i). C explains forcing water through a fine membrane by reverse osmosis (iv). D focuses on energy being the largest expense and its carbon dioxide cost (v). E covers the disposal of concentrated brine waste (ii). F notes a growing reliance on the sea and the hope of cheaper, sustainable supply (vii). Heading vi (why salt is essential to ocean life) is a distractor never discussed; heading viii (underground storage tanks) is a distractor not mentioned anywhere.',
          },
          {
            id: 'rd-038-p1-q2',
            type: 'tfng',
            prompt: 'Most of the water on Earth is suitable for people to drink without treatment.',
            answer: 'false',
            explanation:
              'Paragraph A states that the oceans "hold the overwhelming bulk of the planet’s water, but their salt content is far too high for human beings, crops or most industry to use directly." This contradicts the statement, so it is False.',
          },
          {
            id: 'rd-038-p1-q3',
            type: 'gap',
            prompt:
              'Complete the sentence with ONE word from the passage: The thermal method of producing fresh water by boiling seawater and condensing the resulting steam relies on the principle of _______.',
            acceptableAnswers: ['distillation'],
            explanation:
              'Paragraph B says of boiling and condensing steam: "This is the principle of distillation, and it remains the heart of the older family of desalination methods." The required word is "distillation".',
          },
          {
            id: 'rd-038-p1-q4',
            type: 'mcq',
            prompt:
              'According to paragraph B, why do modern thermal plants hold their chambers at progressively lower pressures?',
            options: [
              'So that the seawater boils at ever cooler temperatures',
              'So that the salt can be collected more easily from the steam',
              'So that the membranes inside are not damaged by heat',
              'So that the plants can run without any electricity',
            ],
            correctIndex: 0,
            explanation:
              'Paragraph B explains that modern thermal plants use "a series of chambers held at progressively lower pressures so that the seawater boils at ever cooler temperatures." Option A matches; membranes belong to reverse osmosis, not thermal plants.',
          },
          {
            id: 'rd-038-p1-q5',
            type: 'mcq',
            prompt: 'Why is the dominant new method described as "reverse" osmosis?',
            options: [
              'Because the water is heated before it reaches the membrane',
              'Because the salt, rather than the water, is pushed through the membrane',
              'Because the water is forced to flow opposite to the direction it would naturally take',
              'Because the membrane is run backwards to clean it between uses',
            ],
            correctIndex: 2,
            explanation:
              'Paragraph C states that "because the flow of water runs opposite to the direction it would naturally take, the method is called reverse osmosis," overcoming the natural pull of osmosis. Option C matches.',
          },
          {
            id: 'rd-038-p1-q6',
            type: 'tfng',
            prompt: 'Reverse osmosis generally requires less energy than boiling seawater.',
            answer: 'true',
            explanation:
              'Paragraph C says that with reverse osmosis "the energy needed is markedly lower than for boiling, and it is this saving that has made reverse osmosis the method of choice." This supports the statement, so it is True.',
          },
          {
            id: 'rd-038-p1-q7',
            type: 'gap',
            prompt:
              'Complete the sentence with ONE word from the passage: For every litre of fresh water made, a plant must dispose of a concentrated, salty waste solution known as _______.',
            acceptableAnswers: ['brine'],
            explanation:
              'Paragraph E describes the waste as "a roughly equal or greater volume of brine, a concentrated solution far saltier than the sea it came from." The required word is "brine".',
          },
          {
            id: 'rd-038-p1-q8',
            type: 'tfng',
            prompt:
              'Desalination is now the cheapest way for arid regions to obtain drinking water.',
            answer: 'not-given',
            explanation:
              'The passage repeatedly stresses that desalination "is not cheap" and hopes it may one day become "affordable", but it never compares its cost with that of other ways arid regions could obtain water. There is no information to confirm or contradict the statement, so it is Not Given.',
          },
        ],
      },
      // ───────────────────────────── PASSAGE 2 ─────────────────────────────
      {
        id: 'rd-academic-038-p2',
        title: 'The Chemistry Behind a Firework',
        body: `A firework display looks like pure magic, but every burst of colour and every thunderous crack is the product of careful chemistry. Beneath the spectacle lies a controlled and rather violent reaction, designed to release a great deal of energy, light and sound in a very short time. To understand how a single shell paints a shape across the night sky, it helps to take the mixture apart and look at the job each ingredient is asked to do.

At the most basic level, a firework needs two things in order to burn fiercely: a fuel and a supply of the oxygen that lets the fuel react. The clever part is that a firework cannot rely on the air around it, which delivers oxygen far too slowly for the rapid burn that an explosion demands. Instead the mixture carries its own oxygen, locked inside a chemical compound called an oxidiser. When the firework is lit, the oxidiser breaks down and floods the fuel with oxygen from within, allowing the whole charge to burn in a fraction of a second. Common oxidisers are compounds rich in oxygen, such as nitrates and the more energetic perchlorates, while the fuels are substances that burn readily, among them charcoal, sulphur and fine metal powders.

The oldest of all such mixtures is gunpowder, sometimes called black powder, which combines charcoal and sulphur as fuels with saltpetre, a nitrate, as the oxidiser. For more than a thousand years this single recipe did almost all the work of fireworks, providing both the force that hurls a shell into the air and the charge that bursts it apart at the top of its flight. Black powder still performs these lifting and bursting duties in many modern fireworks, even though the dazzling colours rely on quite different chemistry packed alongside it.

Colour is where the chemistry becomes most beautiful, and it depends on a property of metals. When certain metal compounds are heated to a high enough temperature, their atoms absorb energy and then release it again as light of a very particular colour, a colour fixed by the identity of the metal itself. Strontium compounds glow a deep red, barium burns green, copper yields blue, and sodium produces an intense yellow. The firework maker therefore chooses metal salts the way a painter chooses pigments, blending them to obtain a desired hue. Blue has always been the hardest colour to achieve, because the copper compounds that produce it are easily spoilt by too much heat, and a true, deep blue is quietly regarded within the trade as the mark of a skilled manufacturer.

These coloured ingredients are not simply poured in loose. The light-producing chemicals are pressed into small, firm pellets known as stars, each one a carefully made parcel of oxidiser, fuel and colour-giving salt, bound together so that it burns steadily rather than all at once. It is the stars that streak outward as the bright points of light a watcher sees; a single star may burn for a second or two as it arcs across the sky, tracing one line of the pattern.

The way these stars are arranged inside the shell decides the shape of the burst. A typical aerial shell is a sphere or cylinder of stiff paper or plastic, and the stars are laid out against its inner wall in a deliberate pattern, with a charge of black powder at the centre. A fuse, timed to the height the shell will reach, sets off that central charge, which explodes outward and ignites the stars, flinging them away from the centre in every direction at once. Because the stars were positioned in, say, a ring or a heart before launch, they spread into that same figure as they fly apart, so that the design is in a real sense built on the workbench long before it blossoms overhead. From the ground it appears that the sky has been painted in an instant, yet the picture was assembled, ingredient by ingredient, in the quiet of the factory.`,
        questions: [
          // ── Matching Information / which-paragraph (5 items) = 5 marks ──
          {
            id: 'rd-038-p2-q1',
            type: 'matching',
            variant: 'information',
            prompt:
              'The passage has six paragraphs, A-F. Which paragraph contains the following information? Write the correct letter, A-F. (You may use any letter more than once, but each statement here is found in only one paragraph.)',
            options: [
              { key: 'A', label: 'Paragraph A' },
              { key: 'B', label: 'Paragraph B' },
              { key: 'C', label: 'Paragraph C' },
              { key: 'D', label: 'Paragraph D' },
              { key: 'E', label: 'Paragraph E' },
              { key: 'F', label: 'Paragraph F' },
            ],
            items: [
              {
                id: 'p2-i-1',
                text: 'an explanation of why a firework cannot depend on oxygen from the surrounding air',
                answer: 'B',
              },
              {
                id: 'p2-i-2',
                text: 'a statement that the colour produced depends on which metal is used',
                answer: 'D',
              },
              {
                id: 'p2-i-3',
                text: 'a description of how the layout of the stars determines the shape of the burst',
                answer: 'F',
              },
              {
                id: 'p2-i-4',
                text: 'the naming of an ancient mixture that both launches and bursts a shell',
                answer: 'C',
              },
              {
                id: 'p2-i-5',
                text: 'a description of the firm pellets into which the light-producing chemicals are pressed',
                answer: 'E',
              },
            ],
            explanation:
              'Item 1 -> B, which says the firework "cannot rely on the air around it, which delivers oxygen far too slowly", so it carries an oxidiser. Item 2 -> D: heated metal atoms release light of "a colour fixed by the identity of the metal itself." Item 3 -> F: "The way these stars are arranged inside the shell decides the shape of the burst." Item 4 -> C, which names gunpowder/black powder as providing "both the force that hurls a shell into the air and the charge that bursts it apart." Item 5 -> E, describing the chemicals "pressed into small, firm pellets known as stars."',
          },
          {
            id: 'rd-038-p2-q2',
            type: 'tfng',
            prompt:
              'A firework relies on oxygen drawn from the surrounding air to burn at the speed an explosion needs.',
            answer: 'false',
            explanation:
              'Paragraph B states the firework "cannot rely on the air around it, which delivers oxygen far too slowly for the rapid burn that an explosion demands," and instead carries its own oxygen in an oxidiser. This contradicts the statement, so it is False.',
          },
          {
            id: 'rd-038-p2-q3',
            type: 'gap',
            prompt:
              'Complete the sentence with ONE word from the passage: Rather than using the air, a firework carries its own oxygen locked inside a compound called an _______.',
            acceptableAnswers: ['oxidiser'],
            explanation:
              'Paragraph B says the mixture "carries its own oxygen, locked inside a chemical compound called an oxidiser." The required word is "oxidiser".',
          },
          {
            id: 'rd-038-p2-q4',
            type: 'mcq',
            prompt:
              'According to paragraph C, what role does black powder still play in many modern fireworks?',
            options: [
              'It provides the bright colours seen in the burst',
              'It lifts the shell into the air and bursts it apart',
              'It binds the metal salts into firm pellets',
              'It replaces the need for any oxidiser',
            ],
            correctIndex: 1,
            explanation:
              'Paragraph C says black powder "still performs these lifting and bursting duties in many modern fireworks, even though the dazzling colours rely on quite different chemistry." Option B matches; the colours come from other chemistry.',
          },
          {
            id: 'rd-038-p2-q5',
            type: 'mcq',
            prompt: 'How does a firework produce a particular colour, according to paragraph D?',
            options: [
              'By burning fuels of different colours mixed together',
              'By heating metal compounds whose atoms release light of a colour fixed by the metal',
              'By adding coloured dyes to the outer casing of the shell',
              'By controlling the pressure inside the sealed shell',
            ],
            correctIndex: 1,
            explanation:
              'Paragraph D explains that when metal compounds are heated, "their atoms absorb energy and then release it again as light of a very particular colour, a colour fixed by the identity of the metal itself." Option B matches.',
          },
          {
            id: 'rd-038-p2-q6',
            type: 'tfng',
            prompt: 'Blue is regarded as the most difficult firework colour to produce well.',
            answer: 'true',
            explanation:
              'Paragraph D states that "Blue has always been the hardest colour to achieve, because the copper compounds that produce it are easily spoilt by too much heat." This supports the statement, so it is True.',
          },
          {
            id: 'rd-038-p2-q7',
            type: 'gap',
            prompt:
              'Complete the sentence with ONE word from the passage: The light-producing chemicals are pressed into small, firm pellets called _______, which streak outward as the bright points of light.',
            acceptableAnswers: ['stars'],
            explanation:
              'Paragraph E says the chemicals are "pressed into small, firm pellets known as stars," and that "It is the stars that streak outward as the bright points of light." The required word is "stars".',
          },
          {
            id: 'rd-038-p2-q8',
            type: 'tfng',
            prompt:
              'Sodium compounds are the most widely used colour-giving salt in modern fireworks.',
            answer: 'not-given',
            explanation:
              'Paragraph D lists sodium as producing "an intense yellow" alongside several other metals, but the passage never states which salt is used most widely. There is no information to confirm or contradict the statement, so it is Not Given.',
          },
          {
            id: 'rd-038-p2-q9',
            type: 'gap',
            prompt:
              'Complete the sentence with ONE word from the passage: In gunpowder, the nitrate that acts as the oxidiser is called _______.',
            acceptableAnswers: ['saltpetre'],
            explanation:
              'Paragraph C says gunpowder "combines charcoal and sulphur as fuels with saltpetre, a nitrate, as the oxidiser." The required word is "saltpetre".',
          },
        ],
      },
      // ───────────────────────────── PASSAGE 3 ─────────────────────────────
      {
        id: 'rd-academic-038-p3',
        title: 'How Honey Bees Turn Nectar into Honey',
        body: `Honey is one of the very few foods that human beings eat almost exactly as another creature makes it, and the process by which a honey bee turns a thin, watery flower juice into the thick golden store in the comb is a small marvel of biology and teamwork. It begins far from the hive, among the flowers, and ends in a sealed cell that may keep its contents wholesome for years.

The journey starts with the foragers, the older worker bees whose task is to leave the hive and search the surrounding countryside for flowers in bloom. What they are seeking is nectar, a sugary liquid that plants secrete deep within their blossoms precisely in order to attract such visitors. A foraging bee draws the nectar up through a long tongue and stores it in a special pouch inside its body, often called the honey stomach, which is kept separate from the stomach used for the bee's own digestion. Having filled this pouch at flower after flower, the forager flies back to the hive carrying a load that may weigh almost as much as the bee itself.

Back at the hive the nectar changes hands, and this transfer is the first step in turning it into honey. The returning forager passes the liquid, mouth to mouth, to one of the younger house bees that remain indoors. As the nectar moves from bee to bee it is mixed with enzymes from their bodies, and these enzymes begin to break the complex sugar of the nectar into simpler sugars that are easier to store and to digest. The nectar is also still far too watery at this stage to keep, for a thin sugar solution would soon ferment and spoil, and so the bees must now drive off most of its water.

The removal of water is achieved in a way that is strikingly simple. The house bees spread the partly ripened nectar in thin films across the walls of the wax cells, and then thousands of bees beat their wings to fan a steady current of warm air through the hive. Helped by the heat of the densely packed colony, this draught causes much of the water to evaporate, until the watery nectar thickens into the syrupy substance we recognise as honey. Only when the moisture has fallen low enough that the honey can no longer ferment do the bees regard it as finished.

The final act is to put the honey into storage. Each full cell is capped with a thin lid of fresh wax, sealing the honey away from the air and from moisture so that it will keep almost indefinitely; honey recovered from ancient tombs has been found still edible after thousands of years. This sealed store is not a luxury but a lifeline, for it is the food on which the colony survives the winter or any long spell when no flowers are open and fresh nectar cannot be gathered.

Yet the importance of all this industry reaches far beyond the hive. As a forager pushes into one flower after another in search of nectar, fine grains of pollen cling to the dense hairs that cover its body, and some of this pollen is brushed off onto the next flower it visits. In carrying pollen from bloom to bloom the bee fertilises the plants, a service known as pollination, without which a great many flowering plants could not set seed or fruit. A large share of the crops that feed the world, from apples and almonds to many vegetables, depend on this unintended assistance. The honey bee, then, does two jobs at once: it lays up a sweet store for itself, and in the very act of doing so it quietly sustains much of the living world around it.`,
        questions: [
          // ── Matching Features - statements to components (5 items) = 5 marks ──
          {
            id: 'rd-038-p3-q1',
            type: 'matching',
            variant: 'features',
            prompt:
              'Look at the following statements and the list of things below. Match each statement to the thing it relates to in the passage. Write the correct letter, A, B, C or D. NB You may use any letter more than once.',
            options: [
              { key: 'A', label: 'Nectar' },
              { key: 'B', label: 'The honey stomach' },
              { key: 'C', label: 'Enzymes' },
              { key: 'D', label: 'Pollen' },
            ],
            items: [
              {
                id: 'p3-f-1',
                text: 'is a sugary liquid that plants make in order to attract visitors.',
                answer: 'A',
              },
              {
                id: 'p3-f-2',
                text: 'is a pouch kept separate from the bee’s own digestive stomach.',
                answer: 'B',
              },
              {
                id: 'p3-f-3',
                text: 'breaks the complex sugar down into simpler sugars.',
                answer: 'C',
              },
              {
                id: 'p3-f-4',
                text: 'clings to the hairs on a bee and is carried from flower to flower.',
                answer: 'D',
              },
              {
                id: 'p3-f-5',
                text: 'is still too watery to keep and would soon ferment in its raw state.',
                answer: 'A',
              },
            ],
            explanation:
              'Item 1 -> A (nectar): "a sugary liquid that plants secrete... in order to attract such visitors." Item 2 -> B (the honey stomach): "a special pouch... which is kept separate from the stomach used for the bee’s own digestion." Item 3 -> C (enzymes): they "begin to break the complex sugar of the nectar into simpler sugars." Item 4 -> D (pollen): "fine grains of pollen cling to the dense hairs that cover its body" and are carried on. Item 5 -> A (nectar): it "is also still far too watery at this stage to keep, for a thin sugar solution would soon ferment."',
          },
          {
            id: 'rd-038-p3-q2',
            type: 'gap',
            prompt:
              'Complete the sentence with ONE word from the passage: The older worker bees that leave the hive to search for flowers are known as _______.',
            acceptableAnswers: ['foragers'],
            explanation:
              'Paragraph B says the journey "starts with the foragers, the older worker bees whose task is to leave the hive and search the surrounding countryside for flowers." The required word is "foragers".',
          },
          {
            id: 'rd-038-p3-q3',
            type: 'tfng',
            prompt:
              'A forager can return to the hive carrying a load of nectar nearly as heavy as itself.',
            answer: 'true',
            explanation:
              'Paragraph B says the forager "flies back to the hive carrying a load that may weigh almost as much as the bee itself." This supports the statement, so it is True.',
          },
          {
            id: 'rd-038-p3-q4',
            type: 'mcq',
            prompt:
              'According to paragraph C, what happens first when a forager returns to the hive?',
            options: [
              'It seals the nectar inside a wax cell straight away',
              'It passes the nectar, mouth to mouth, to a younger house bee',
              'It fans the nectar with its wings to remove the water',
              'It flies straight back out to gather more nectar',
            ],
            correctIndex: 1,
            explanation:
              'Paragraph C states that "The returning forager passes the liquid, mouth to mouth, to one of the younger house bees that remain indoors," and calls this "the first step in turning it into honey." Option B matches.',
          },
          {
            id: 'rd-038-p3-q5',
            type: 'mcq',
            prompt: 'Why must the bees drive most of the water out of the nectar?',
            options: [
              'Because a thin sugar solution would soon ferment and spoil',
              'Because nectar is poisonous to bees until it is dried',
              'Because the wax cells cannot hold any liquid at all',
              'Because the enzymes only work in completely dry conditions',
            ],
            correctIndex: 0,
            explanation:
              'Paragraph C explains the nectar "is also still far too watery at this stage to keep, for a thin sugar solution would soon ferment and spoil, and so the bees must now drive off most of its water." Option A matches.',
          },
          {
            id: 'rd-038-p3-q6',
            type: 'gap',
            prompt:
              'Complete the sentence with ONE word from the passage: Thousands of bees beat their wings to fan warm air through the hive, causing much of the water to _______.',
            acceptableAnswers: ['evaporate'],
            explanation:
              'Paragraph D says the warm draught "causes much of the water to evaporate, until the watery nectar thickens into... honey." The required word is "evaporate".',
          },
          {
            id: 'rd-038-p3-q7',
            type: 'tfng',
            prompt: 'Honey sealed in a capped cell can remain edible for an extremely long time.',
            answer: 'true',
            explanation:
              'Paragraph E says capped honey "will keep almost indefinitely; honey recovered from ancient tombs has been found still edible after thousands of years." This supports the statement, so it is True.',
          },
          {
            id: 'rd-038-p3-q8',
            type: 'tfng',
            prompt: 'Honey bees gather pollen deliberately in order to help plants reproduce.',
            answer: 'false',
            explanation:
              'Paragraph F describes pollination as "unintended assistance": pollen merely clings to the bee while it seeks nectar, and the bee "quietly sustains" plant life in "the very act" of feeding itself. The deliberate intention in the statement is contradicted, so it is False.',
          },
          {
            id: 'rd-038-p3-q9',
            type: 'gap',
            prompt:
              'Complete the sentence with ONE word from the passage: By carrying pollen from one bloom to another, the bee fertilises the plants, a service known as _______.',
            acceptableAnswers: ['pollination'],
            explanation:
              'Paragraph F says the bee "fertilises the plants, a service known as pollination, without which a great many flowering plants could not set seed or fruit." The required word is "pollination".',
          },
          {
            id: 'rd-038-p3-q10',
            type: 'tfng',
            prompt:
              'The honey stored in the comb is the colony’s food when no flowers are in bloom.',
            answer: 'true',
            explanation:
              'Paragraph E says the sealed store "is the food on which the colony survives the winter or any long spell when no flowers are open and fresh nectar cannot be gathered." This supports the statement, so it is True.',
          },
        ],
      },
    ],
  },
]
