/**
 * free-resources set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s1: { en: `Complete Lesson Plan`, ar: `خطة الدرس الكاملة` },
  s2: { en: `Success Criteria`, ar: `معايير النجاح` },
  s3: { en: `Teacher Notes`, ar: `ملاحظات المعلم` },
  s4: { en: `An Inspector Calls -- Act 1`, ar: `مأمور يزور -- فصل الأول` },
  s5: { en: `Model Answer:`, ar: `نموذج الجواب:` },
  s6: { en: `Teaching Guide Excerpt`, ar: `دليل التدريس مقتبس` },
  s7: { en: `Context Notes`, ar: `ملاحظات السياق` },
  s8: { en: `Key Themes`, ar: `ال THEMES الرئيسيين` },
  s9: { en: `Key Characters`, ar: `الشخصيات الرئيسية` },
  s10: { en: `Key Quotes`, ar: `ال citas الرئيسية` },
  s11: { en: `Assessment Criteria (AQA GCSE)`, ar: `معايير التقييم (AQA GCSE)` },
  s12: { en: `Key Quotes Worksheet`, ar: `Worksheet للعبارات الرئيسية` },
  s13: { en: `Mark Scheme`, ar: `جدول الدرجات` },
  s14: {
    en: `What Else You Get With a Subscription`,
    ar: `شلونك تبغى تعرف إيش راح تحصل عليه مع الاشتراك؟ دوّر بالمواضيع التالية عشان تفهم أكثر: اقرأ النصوص، حلِّل القصص والأعمال الأدبية، واطلع على الاستراتيجيات الخاصة بالامتحانات. وايد الطلاب بيستفدو من المميزات دي عشان يحسوا إنهم مستعدين للامتحانات. الحين، روح شوف ماكو إيش جديد`,
  },
  s15: { en: `Ready to Transform Your Teaching?`, ar: `جاهز لتغيير تعليمك؟` },
}
