/**
 * revision-builder set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s1: { en: `Language Analysis`, ar: `تحليل اللغة` },
  s2: { en: `Structure Analysis`, ar: `تحليل الهيكل` },
  s3: { en: `Reading Comprehension`, ar: `الفهم من خلال القراءة` },
  s5: { en: `Unseen Poetry`, ar: `الشعر غير المعروف` },
  s6: { en: `Poetry Comparison`, ar: `مقارنة الشعر` },
  s7: { en: `Power and Conflict Poetry`, ar: `شعر عن القوة والصراع` },
  s8: {
    en: `Literary Techniques`,
    ar: `TECHNIQUES litteraire (ال Tecnikat littéraire) 

(Note: The term "literary techniques" is kept in English as it's a specific terminology and there isn't an exact equivalent phrase in Khaleeji Arabic that would be commonly used in educational contexts. However, the closest translation provided`,
  },
  s9: { en: `Structural Devices`, ar: `الأدوات البنائية` },
  s10: { en: `Creative Writing`, ar: `الكتابة الإبداعية` },
  s11: { en: `Descriptive Writing`, ar: `الكتابة الوصفية` },
  s12: {
    en: `Narrative Writing`,
    ar: `كتابة القصةNarrated by the rules provided, the term "Narrative Writing" doesn't directly translate to a phrase in Khaleeji Arabic that captures its exact meaning while adhering strictly to the given instructions. However, a fitting translation would be:

كتابة القصة

This maintains the formal tone required for instructional content`,
  },
  s13: { en: `Persuasive Writing`, ar: `الكتابة الإقناعية` },
  s14: { en: `Transactional Writing`, ar: `الكتابة التبادلية` },
  s15: { en: `Analytical Writing`, ar: `الكتابة التحليلية` },
  s16: { en: `Show Don&apos;t Tell`, ar: `أظهر ولا تخبر` },
  s17: { en: `Sensory Language`, ar: `لغة الحواس` },
  s18: { en: `Dialogue and Voice`, ar: `حوار وصوت` },
  s19: { en: `Story Openings and Endings`, ar: `openings والختامات في القصص` },
  s20: { en: `Essay Structure`, ar: `STRUCTURE المقال` },
  s21: { en: `PEEL Paragraphs`, ar: `مقدمة - نقطة - دليل - خاتمة` },
  s22: {
    en: `Comparison Essay Structure`,
    ar: `Structure الت comparatif:

1. المقدمة: شنو اللي هدفك من القصة؟ إحنا نبغى نوضح رؤيتنا عن الموضوعين اللي بنقارن بينهم.

2. الجسد:
   - الجزء الأول: تفاصيل عن العمل الأول وشو مميز فيه.
   - الجزء الثاني: تفاصيل عن العمل`,
  },
  s23: { en: `Question Types`, ar: `أنواع الأسئلة` },
  s24: { en: `Time Management`, ar: `إدارة الوقت` },
  s25: { en: `Common Mistakes`, ar: `أخطاء شائعة` },
  s26: { en: `Grade 9 Secrets`, ar: `أسرار الصف التاسع` },
  s27: { en: `Mark Scheme Mastery`, ar: `دليل.scheme للتفوق` },
  s28: { en: `Exam Day Strategy`, ar: `استراتيجية يوم الامتحان` },
}
