/**
 * to-kill-a-mockingbird set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `The Jim Crow South`, ar: `جنوب جيم كرو` },
  s1: { en: `The Great Depression`, ar: `الكساد العظيم` },
  s2: { en: `The Scottsboro Boys (1931)`, ar: `البنات والولد من سكوتزBORO (1931)` },
  s3: {
    en: `The Civil Rights Movement (1950s-60s)`,
    ar: `حركة الحقوق المدنية (الخمسينيات والستينيات)`,
  },
  s4: { en: `Harper Lee&rsquo;s Biography`, ar: `BIOGRAPHY هاربر لي` },
  s5: { en: `How to approach:`, ar: `كيف تتعامل مع:` },
  s6: { en: `Skills demonstrated:`, ar: `مهارات مبينة:` },
  s7: { en: `Textual Knowledge:`, ar: `المعرفة النصية:` },
  s8: { en: `Writer's Methods:`, ar: `طرائق الكاتب:` },
  s9: { en: `Personal Response:`, ar: `رد شخصي:` },
  s10: { en: `Passage-based (a) questions:`, ar: `أسئلة نوعية (أ) بناءً على النص:` },
  s11: { en: `Essay (b) questions:`, ar: `أسئلة الواجب (ب):` },
  s12: { en: `Always use the author&rsquo;s name:`, ar: `استخدم دائمًا اسم الكاتب:` },
  s13: {
    en: `The 1930s setting and 1960 publication:`,
    ar: ``,
  },
  s14: { en: `Quote precisely:`, ar: `اقتبس بدقة:` },
  s15: { en: `Link everything to Lee&rsquo;s purpose:`, ar: `ربط كل شيء بأهداف لاي์` },
  s16: { en: `Page sections`, ar: `صفحات)sectionص` },
}
