/**
 * the-crucible set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Modern Drama`, ar: `الدراما الحديثة` },
  s2: { en: `Key Moments`, ar: `لحظات حاسمة` },
  s3: { en: `John Proctor`, ar: `جون بروكتر` },
  s4: { en: `Abigail Williams`, ar: `أبيجيل وليامز` },
  s6: {
    en: `Reverend Hale`,
    ar: `الرجل حايل Reverend Hale يقال باسم الرجل حايل في العربية، لكن الاسم الرسمي يبقى كما هو في النص الأدبي.`,
  },
  s7: { en: `Deputy Governor Danforth`, ar: `نائب الحاكم دانفورث` },
  s8: { en: `Reverend Parris`, ar: `القس باريس` },
  s9: { en: `Rebecca Nurse`, ar: `ريبيكا نيرس` },
  s10: { en: `Giles Corey`, ar: `جليس كوري` },
  s11: { en: `Other Characters`, ar: `شخصيات أخرى` },
  s12: {
    en: `McCarthyism and the Red Scare (1950s)`,
    ar: `McCarthyism والرعب الأحمر (الخمسينيات)`,
  },
  s13: { en: `The Crucible`, ar: `الكرسيبيل` },
  s14: { en: `The Salem Witch Trials (1692)`, ar: `تجربة سalem من سحر (1692)` },
  s15: { en: `Puritanism and Theocracy`, ar: `البروتستانتية والطغيان الديني` },
  s16: { en: `The Title: &ldquo;The Crucible&rdquo;`, ar: `العنوان: &ldquo;القِداحة&rdquo;` },
  s17: { en: `General Tips for The Crucible`, ar: `نصائح عامة للكواسح` },
  s18: { en: `Always link to McCarthyism:`, ar: `دائماً اربطه بمكارثية:` },
  s19: { en: `Refer to Miller as the dramatist:`, ar: `أ refere إلى ميلر كالمؤلف المسرحي:` },
  s21: { en: `Explore the stage directions:`, ar: `استكشف توجيهات المسرح:` },
  s22: { en: `Multiple interpretations:`, ar: `تفسيرات متعددة` },
  s23: { en: `Use dramatic terminology:`, ar: `استخدم مصطلحات درامية:` },
  s24: { en: `Closed book:`, ar: `كتاب مغلق:` },
  s25: { en: `Question 1`, ar: `السؤال الأول` },
  s26: { en: `Question 2`, ar: `سؤال 2` },
  s27: { en: `Question 3`, ar: `السؤال الثالث` },
  s28: { en: `Act-by-Act Plot Summary`, ar: `ملخص القصة مشهداً بعد مشهد` },
  s29: { en: `Character Profiles`, ar: `Profiles للشخصيات` },
  s30: { en: `Key Themes`, ar: `ال THEMES الرئيسيين` },
  s31: { en: `Key Quotations`, ar: `اقتباسات رئيسية` },
  s32: { en: `Historical Context`, ar: `السياق التاريخي` },
  s33: { en: `Practice Questions`, ar: `أسئلة للتمرين` },
  s34: { en: `Write your response here...`, ar: `اكتب ردك هنا...` },
}
