/**
 * poetry set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Towards a World Unknown`, ar: `Towards a World Unknown` },
  s1: { en: `Love and Relationships`, ar: `الحب والعلاقات` },
  s2: { en: `Youth and Age`, ar: `الشباب والكهولة` },
  s3: { en: `Power and the Natural World`, ar: `القوة والعالم الطبيعي` },
  s4: { en: `Questions to ask:`, ar: `أسئلة للسؤال عنها:` },
  s5: { en: `Key vocabulary for tone:`, ar: `لغة أساسية للטון:` },
  s6: { en: `Figurative language`, ar: `لغة مجازية` },
  s7: { en: `Word choice (diction)`, ar: `` },
  s8: {
    en: `Semantic fields`,
    ar: `حقldsldsldsldsldsldsldsldsldsldsldsldsldsldsldldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldslds`,
  },
  s9: { en: `Sound devices`, ar: `الأدوات الصوتية` },
  s10: { en: `Sensory language`, ar: `لغة حسية` },
  s11: {
    en: `Stanza structure`,
    ar: `โครงสร้าง القصيدة (Translation note: Stanza structure doesn't have a direct Khaleeji term, so I used "โครงสร้าง القصيدة" which is not accurate but closest in meaning. For a more precise translation, it would be better to keep it as "Stanza structure" in`,
  },
  s12: { en: `Rhyme scheme`, ar: `نمط الشعر الرتبي` },
  s13: { en: `Metre and rhythm`, ar: `` },
  s14: { en: `Opening and ending`, ar: `فتح وإغلاق` },
  s15: {
    en: `When was the poem written? What was happening historically?`,
    ar: `متى كُتِب الشَّعر دا؟ شلون كان الوضع التَاريخي وقتها؟`,
  },
  s16: {
    en: `What was the poet&rsquo;s background and experiences?`,
    ar: `شنو خلفية الشاعر وتجاربه؟`,
  },
  s17: {
    en: `What literary movement or tradition does the poem belong to?`,
    ar: `شنو Literary movement or tradition ال(poem) كذا جزء منه؟`,
  },
  s18: {
    en: `How might the original audience have responded?`,
    ar: `كيف يمكن أن يرد الجمهور الأصلي؟`,
  },
  s19: {
    en: `How might a modern reader respond differently?`,
    ar: `كيف يمكن أن يستجيب قارئ معاصر بطريقة مختلفة؟`,
  },
  s20: { en: `What to Compare`, ar: `ما تقارن شلون` },
  s21: {
    en: `Compare across multiple layers &mdash; not just theme:`,
    ar: `قارن عبر طبقات متعددة &mdash; ليس فقط الموضوع:`,
  },
  s22: { en: `Themes and Ideas`, ar: `chủات وفكار` },
  s23: { en: `Language and Imagery`, ar: `لغة وتصورات` },
  s25: { en: `Voice and Perspective`, ar: `الصوت والمنظور` },
  s26: { en: `Tone and Mood`, ar: `تÓN و مOOD` },
  s27: { en: `Comparative Language to Use`, ar: `لغة مقارنة لاستخدامها` },
  s28: { en: `Power and Powerlessness`, ar: `القوة والضعفlessness` },
  s29: { en: `Loss and Memory`, ar: `فقدان وذاكرة` },
  s30: { en: `Identity and Belonging`, ar: `الهوية والانتماء` },
  s31: { en: `Conflict and Violence`, ar: `conflict و العنف` },
  s32: { en: `Time and Change`, ar: `الزمن والتغير` },
  s33: {
    en: `Each paragraph in your comparison essay should follow this structure:`,
    ar: `كل فقرة في مقالتك المقارن يجب أن تتبع هذا البنية:`,
  },
  s34: { en: `Create Comparison Grids`, ar: `انشئ جداول للمقارنة` },
  s35: { en: `Memorise Key Quotations`, ar: `احفظ الاقتباسات الرئيسية` },
  s36: { en: `Practise Timed Comparisons`, ar: `دوري مقارنات مدتها زمنيةetermined` },
  s37: { en: `Annotate Every Poem`, ar: `اannotate كل شعر` },
  s38: { en: `Know the Poems Inside Out`, ar: `اعرف القصائد جيداً` },
  s40: { en: `Writing about each poem separately`, ar: `اكتب عن كل شعرة على حدة` },
  s41: { en: `Only comparing themes`, ar: `Comparing فقط الموضوعات` },
  s42: { en: `Forgetting to analyse the printed poem`, ar: `نسيت تحلل الشعر المطبوع` },
  s43: { en: `Not knowing quotations from memory`, ar: `لا تعرف الاقتباسات من الذاكرة` },
  s44: { en: `Ignoring form and structure`, ar: `IGNORING form and structure` },
  s45: { en: `Context as an afterthought`, ar: `` },
  s46: { en: `Superficial analysis`, ar: `تحليل سطحي` },
}
