/**
 * poetry set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Key Quotes`, ar: `ال citas الرئيسية` },
  s1: { en: `On this page`, ar: `في هذه الصفحة` },
  s2: { en: `Relationships Cluster`, ar: `` },
  s3: { en: `Conflict Cluster`, ar: `` },
  s4: { en: `How the Poetry Anthology Works`, ar: `كيف يعمل ديوان الشعر` },
  s5: { en: `Conflict Cluster - Full Analysis`, ar: `تحليل مجموعة النزاعات` },
  s6: { en: `How to Write a Poetry Comparison`, ar: `كيفية كتابة مقارنة شعرية` },
  s7: { en: `Recommended Structure`, ar: `ال STRUCTURE الموصى بها` },
  s8: { en: `Comparative paragraphs (3-4)`, ar: `مقارنات (3-4)` },
  s9: { en: `Analyse methods`, ar: `` },
  s10: {
    en: `Include context where relevant`,
    ar: `أضف السياق حيث يكون ضروريًا وايد شلون تقدر تفهم better:

بالنسبة للترجمة، إذا كان النص يحتاج إلى سياق إضافي لفهمه بشكل أفضل، فيجب عليك إضافة هذا السياق في الترجمة. مثلاً، إذا كانت هناك معلومات مهمة لم تذكر في النص الأصلي ولكنها ضرورية لفهم`,
  },
  s11: { en: `Brief conclusion`, ar: `خاتمة قصيرة` },
  s12: { en: `Useful Comparison Connectives`, ar: `ربطات مفيدة للمقارنة` },
  s13: { en: `Similarly, [poet] also...`, ar: `مثلًا، [الشاعر] أيضًا...` },
  s14: { en: `Both poets present...`, ar: `يقدّم الشاعران...` },
  s15: {
    en: `Like [poem A], [poem B] also...`,
    ar: `مثل [القصيدة أ], [القصيدة ب] тоже... 

(Note: The phrase "ت тоже..." is not in Khaleeji Arabic, so I'll adjust it to fit the style.)

مثل [القصيدة أ], [القصيدة ب] كمان...`,
  },
  s16: { en: `In the same way...`, ar: `على نفس الطريقة...` },
  s18: { en: `In contrast, [poet]...`, ar: `في المقابل، [الشاعر]...` },
  s19: { en: `Whereas [poem A]..., [poem B]...`, ar: `بينما [القصيدة أ]..., [القصيدة ب]...` },
  s21: { en: `Unlike [poem A]...`, ar: `عكس [القصيدة أ]...` },
  s22: { en: `On the other hand...`, ar: `من ناحية أخرى...` },
}
