/**
 * analytics set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: {
    en: `Needs Support`,
    ar: `nhuqqud tawliyyah mnthoodhatha min al-hisab wal-mudhakkirat li-istimra3 al-tanbeeg bil-inglizi fi al-markaz al-aalami li-l-inglizi (The English Hub). ikhfa' al-w`,
  },
  s1: { en: `School Analytics`, ar: `تحليلات المدرسة` },
  s2: { en: `Active Students`, ar: `طلبة نشطون` },
  s3: { en: `Assignments Submitted`, ar: `assignments التسليماتsubmitted مسلمة` },
  s4: { en: `Average Score`, ar: `النقاط المتوسطة` },
  s5: { en: `At-Risk Students`, ar: `الطلاب في خطر` },
  s6: { en: `Avg Progress`, ar: `` },
  s7: { en: `Completion Rate`, ar: `معدل الإكمال` },
  s8: { en: `Student Progress`, ar: `تقدم الطالب` },
  s9: { en: `Grade Distribution (Latest Mock Exams)`, ar: `توزيع الدرجات (أخر امتحانات المOCK)` },
  s10: { en: `Search students...`, ar: `دوري على الطلاب...` },
}
