/**
 * things-fall-apart set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Chinua Achebe (1930&ndash;2013), 1958`, ar: `تشينوا أچيبه (1930-2013)، 1958` },
  s2: { en: `Chapter 1.`, ar: `الفصل الأول` },
  s3: { en: `Chapter 2.`, ar: `الفصل الثاني` },
  s4: { en: `Chapters 3&ndash;4.`, ar: `الفصول third إلى fourth` },
  s5: { en: `Chapter 5.`, ar: `الفصل الخامس.` },
  s6: { en: `Chapter 6.`, ar: `الفصل السادس` },
  s7: { en: `Chapter 7.`, ar: `الفصل السابع` },
  s8: { en: `Chapter 8.`, ar: `الفصل الثامن.` },
  s9: { en: `Chapters 9&ndash;11.`, ar: `الفصول 9 إلى 11.` },
  s10: { en: `Chapter 12.`, ar: `الفصل الثاني عشر` },
  s11: { en: `Chapter 13.`, ar: `الفصل الثالث عشر.` },
  s12: { en: `Chapter 14.`, ar: `الفصل الرابعteen` },
  s13: { en: `Chapter 15.`, ar: `الفصل الخامس عشر` },
  s14: { en: `Chapter 16.`, ar: `الفصل السادس عشر` },
  s15: { en: `Chapter 17.`, ar: `الفصل السابع عشر.` },
  s16: { en: `Chapter 18.`, ar: `الفصل الثامن عشر` },
  s17: { en: `Chapter 19.`, ar: `الفصل التاسع عشر.` },
  s18: { en: `Chapter 20.`, ar: `الفصل العشرون.` },
  s19: { en: `Chapter 21.`, ar: `الفصل الحادي والعشرون.` },
  s20: { en: `Chapter 22.`, ar: `الفصل twenty-two.` },
  s21: { en: `Reverend James Smith`, ar: `reverend جيمس سميث` },
  s22: { en: `Chapter 23.`, ar: `الفصل twenty-three.` },
  s23: { en: `Chapter 24.`, ar: `الفصل twenty-four.` },
  s24: { en: `Chapter 25.`, ar: `الفصل twenty-five.` },
  s26: { en: `Para 1 (AO1/AO2).`, ar: `` },
  s27: {
    en: `Para 2 (AO2/AO3).`,
    ar: `ال пункт 2 (AO2/AO3). 

*(Please note that the prefix "para" is not directly translatable in this context and was left as is, but marked with a symbol to indicate it should remain distinct. The AO codes are kept in English as per instructions.)*`,
  },
  s28: {
    en: `Para 3 (AO2/AO3).`,
    ar: `ال пункт 3 (AO2/AO3). 

*(Please note that due to instructions and context provided, this seems like an incomplete or incorrectly formatted input. The term "Para 3" is likely a reference to a specific paragraph in the text being translated from English to Khaleeji Arabic with certain assessment`,
  },
  s29: { en: `Para 2 (AO2).`, ar: `` },
  s30: { en: `Para 3 (AO3).`, ar: `` },
  s31: {
    en: `The structural irony of the closing chapter.`,
    ar: `الحاجة من(KP) للسخرية البنائية في الفصل الختامي(KP).`,
  },
  s32: { en: `The novel&rsquo;s argument with Yeats.`, ar: `حجة الرواية مع ييتس.` },
  s33: { en: `The reversal of the chi proverb.`, ar: `عكس حكمة الشيء بالشيء الآخر` },
  s34: {
    en: `Achebe&rsquo;s 1965 essay on language as evidence.`,
    ar: `مقال أتشيبي حول اللغة كدليل في عام 1965`,
  },
  s35: {
    en: `The asymmetry of the three-part structure.`,
    ar: `الASYMMETRY في البنية الثلاثية. (الترجمة الحرفية لـ "asymmetry" لأنها مصطلح أدبي محتمل) 

أو:

 عدم التوازن في البنية الثلاثية. (إذا كان من الممكن استخدام كلمة "عدم التوازن" بدلاً من "ASYMMETRY")`,
  },
  s36: {
    en: `The Mr Brown / James Smith contrast as historical claim.`,
    ar: `الContrast بين Mister Brown و James Smith كادعية تاريخية.`,
  },
  s37: {
    en: `The novel&rsquo;s internal critique of Igbo society.`,
    ar: ``,
  },
  s38: {
    en: `The Earth (Ani) as the novel&rsquo;s ethical centre.`,
    ar: `الأرض (آني) كمركزها الأخلاقي في الرواية.`,
  },
  s39: {
    en: `Things Fall Apart`,
    ar: `أشياء تسقط تبعًا للجزء المطلوب، هذا هو اسم العمل "أشياء تسقط" دون أي تعديلات إضافية أو شروحات.`,
  },
  s40: {
    en: `How does Achebe present the arrival and effect of Christianity in Umuofia?`,
    ar: `كيف ي presente أتشيبي وصول ومفعول المسيحية في أموفيا؟

(Note: There seems to be a slight issue with the verb "present" which doesn't directly translate well into Khaleeji Arabic while maintaining its instructional tone. The word "ي-presente" is used here as an approximation, but in a more natural context it would be better translated using a phrase like "كيف يصف أتشيبي وصول ومفعول المسيحية في أموفيا؟")`,
  },
  s41: {
    en: `How important is the relationship between Okonkwo and his son Nwoye?`,
    ar: `شنو أهمية العلاقة بين أوكونكوا وابنه نوي؟`,
  },
  s42: { en: `Heart of Darkness`, ar: `قلب الظلام` },
  s43: { en: `Use Igbo terms accurately.`, ar: `استخدم مصطلحات الإيغبو بدقة.` },
  s44: {
    en: `Quote the title&rsquo;s source line and explain the irony.`,
    ar: `اقرأ السطر الم.getSource للعنوان وشرح الأدبية.`,
  },
  s45: {
    en: `Cite the closing chapter&rsquo;s point-of-view shift.`,
    ar: `أذكر تحول وجهة النظر في الفصل الأخير.`,
  },
  s46: {
    en: `Don&rsquo;t idealise Igbo society.`,
    ar: `ماتعمرش الأمة الإيبوidealistically.  

(Note: The sentence structure is adjusted to fit natural Khaleeji Arabic expression while adhering to the guidelines provided. The direct translation might sound awkward, so "ماتعمرش" (don't idealize) and adding "بالطريقةidealistically" can be used for better understanding.) 

Corrected version:
لا تعمري الأمة الإيبوidealistically.`,
  },
  s47: { en: `Use Achebe&rsquo;s essays for AO3.`, ar: `` },
  s49: { en: `Copyright notice.`, ar: `الحقوق المحفوظة` },
  s51: { en: `Masculinity and the fear of weakness`, ar: `الرجولة والخوف من الضعف` },
  s52: { en: `Tradition and the question of change`, ar: `التقاليد والسؤال عن التغيير` },
  s53: {
    en: `Colonialism, language, and the &lsquo;civilising&rsquo; story`,
    ar: `الاستعمار، اللغة، والقصة &lsquo;المدنية&rsquo;`,
  },
  s56: { en: `Fate and chi (personal god)`, ar: `القدر والشاي (الإله الشخصي)` },
  s57: { en: `The art of language and the proverb`, ar: `فن اللغة والمثل` },
  s58: { en: `Key Quotations`, ar: `الاقتباسات الرئيسية` },
  s59: { en: `Igbo Culture in the Novel`, ar: `ثقافة الإيغو في الرواية` },
  s60: {
    en: `The man&rsquo;s personal hut within a compound. Each of Okonkwo&rsquo;s wives has her own hut in his compound, with the obi as the household&rsquo;s public-facing room.`,
    ar: `مزرعة الرجل داخل المجمع. كل واحدة من زوجات أوكونكو لها مسكنها الخاص في مجمعه، مع أن الُبي (obi) هو الغرفة التي تواجه الجمهور للم.household`,
  },
  s61: { en: `Historical &amp; Literary Context`, ar: `` },
  s62: { en: `Structure &amp; Narrative Technique`, ar: `ال STRUCTURE وTECHNIQUE السردية` },
  s63: { en: `Essay Planning`, ar: `hoạchtlة المقال` },
  s64: { en: `Grade 9 / A* Points`, ar: `الدرجة التاسعة / النقاط A*` },
  s65: { en: `Practice Questions`, ar: `أسئلة ممارسة` },
}
