/**
 * paper-2 set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Paper Overview`, ar: `محة عن الورقة` },
  s1: { en: `Section A: Reading`, ar: `قسم أ: القراءة` },
  s2: { en: `Section B: Writing for Real Purposes`, ar: `SECTION B: الكتابة لأغراض حقيقية` },
  s3: {
    en: `Section A: Reading &mdash; Question Breakdown`,
    ar: `قسم أ: القراءة &mdash; تحليل الأسئلة`,
  },
  s4: { en: `Short Retrieval &mdash; Text 1 (1 mark)`, ar: `استرجاع قصير 1 ( نقطة )` },
  s5: { en: `Reading and retrieval (AO1)`, ar: `قراءة واسترجاع (AO1)` },
  s6: {
    en: `Short Retrieval &mdash; Text 2 (2 marks)`,
    ar: `استرجاع قصير &mdash; النص 2 (2 نقاط)`,
  },
  s7: { en: `Language Analysis &mdash; Text 1 (6 marks)`, ar: `تحليل اللغة (6 نقاط)` },
  s8: { en: `Language and structure analysis (AO2)`, ar: `تحليل اللغة والبنية (AO2)` },
  s9: { en: `Example question:`, ar: `مثال على سؤال:` },
  s10: { en: `Marking guide levels:`, ar: `مستويات دليل التقييم:` },
  s11: { en: `Level 1 (1-2):`, ar: `مستوى 1 (1-2)` },
  s12: { en: `Level 2 (3-4):`, ar: `مستوى 2 (3-4)` },
  s13: { en: `Level 3 (5-6):`, ar: `مستوى 3 (5-6)` },
  s14: { en: `Language Analysis &mdash; Text 2 (6 marks)`, ar: `تحليل اللغة (6 نقاط)` },
  s15: { en: `Key difference from Q3:`, ar: `différence الرئيسية من السؤال الثالث:` },
  s16: {
    en: `Critical Evaluation &mdash; Text 2 (15 marks)`,
    ar: `التقييم النقدي &mdash; النص 2 (15 نقاط)`,
  },
  s17: { en: `Critical evaluation (AO4)`, ar: `التقييم النقدي (AO4)` },
  s18: { en: `Level 1 (1-3):`, ar: `مستوى 1 (1-3)` },
  s19: { en: `Level 2 (4-6):`, ar: `مستوى 2 (4-6)` },
  s20: { en: `Level 3 (7-9):`, ar: `مستوى 3 (7-9)` },
  s21: { en: `Level 4 (10-12):`, ar: `المستوى الرابع (10-12)` },
  s22: { en: `Level 5 (13-15):`, ar: `المستوى الخامس (١٣-١٥)` },
  s24: { en: `Comparing writers (AO3)`, ar: `مقارنة الكتاب (AO3)` },
  s26: {
    en: `Identify each writer&rsquo;s viewpoint clearly (&ldquo;Writer 1 believes... whereas Writer 2 argues...&rdquo;)`,
    ar: `ا indentify رؤية كل كاتب بوضوح (يعتقد الكاتب الأول... بينما ي)argue) الكاتب الثاني...).`,
  },
  s27: {
    en: `Compare using connectives: &ldquo;Similarly,&rdquo; &ldquo;In contrast,&rdquo; &ldquo;However,&rdquo; &ldquo;Conversely&rdquo;`,
    ar: `قارن باستخدام الرابطات: "بالمثل"، "في المقابل"، "ومع ذلك"، "على العكس`,
  },
  s28: { en: `Support each point with evidence from`, ar: `أدعم كل نقطة bằng أدلة من` },
  s29: {
    en: `Analyse how each writer&rsquo;s methods differ (e.g., one uses emotive language while the other uses statistics)`,
    ar: `انализ كيف تختلف طرائق كل كاتب (مثلًا، يستخدم أحدهم لغة عاطفية في حين يستخدم الآخر أرقامًا وحقائق)`,
  },
  s31: { en: `Level 4 (7-8):`, ar: `مستوى 4 (7-8)` },
  s32: { en: `Level 5 (9-10):`, ar: `المستوى الخامس (9-10)` },
  s33: {
    en: `Section B: Writing for Real Purposes (40 marks)`,
    ar: `SECTION B: الكتابة لأغراض حقيقية (40 نقطة)`,
  },
  s34: { en: `Content and organisation (AO5, 24)`, ar: `المحتوى والتنظيم (AO5، 24)` },
  s35: { en: `Technical accuracy (AO6, 16)`, ar: `دقة فنية (AO6، 16)` },
  s36: {
    en: `Simple awareness of purpose and audience; limited structural features; basic vocabulary.`,
    ar: `وعي بسيط بالغرض والجمهور؛ ميزات بنائية محدودة؛ قاموس أساسي.`,
  },
  s37: {
    en: `Simple vocabulary; limited sentence structures; frequent errors.`,
    ar: `لغة سهلة؛ بنية جمل بسيطة؛ أخطاء متكررة.`,
  },
  s38: {
    en: `Attempts to match purpose and audience; some use of form conventions; developing paragraphs.`,
    ar: `محاولات لتناسق الغرض والجمهور؛ استخدام بعض قواعد الصيغة؛ فقرات في تطور.`,
  },
  s39: {
    en: `Some varied vocabulary; attempts at sentence variety; mostly accurate basic spelling.`,
    ar: `بعض الكلمات المتنوعة؛ محاولات لتنويع الجمل؛ كتابة دقيقة بشكل أساسي.`,
  },
  s40: {
    en: `Clear, sustained awareness of purpose and audience; effective use of form conventions; coherent paragraphing with discourse markers.`,
    ar: `واضحة ومستمرة على بينة من الغرض والعهد؛ استعمال فعال لقواعد الشكل litterary؛ تهذيب في تقسيم الفقرات باستخدام علامات الخطاب.`,
  },
  s41: {
    en: `Varied vocabulary chosen for effect; secure sentence control; generally accurate spelling and punctuation.`,
    ar: `لغة متنوعة اختيرت للتأثير؛ ضبط جيد لsentences؛ إملاء وتصحيح علامات ترقيم دقيقان بشكل عام.`,
  },
  s42: {
    en: `Compelling, convincing writing fully matched to purpose and audience; sophisticated use of form; assured, distinctive voice.`,
    ar: `كتابة مقنعة ومتميزة تتناسب تمامًا مع الغرض والجمهور؛ استخدام متطور لأشكال الكتابة؛ صوت موثوق ومتفرد.`,
  },
  s43: {
    en: `Extensive, ambitious vocabulary; full range of sentence forms; virtually faultless accuracy.`,
    ar: `لغة واسعة الطموح؛ تنوع كامل في أشكال الجمل؛ دقة تقريبًا لا عيب فيها.`,
  },
  s44: {
    en: `Example Responses`,
    ar: `مثال على ردود أفعال الطلاب عند طرح أسئلة معينة:

لو سألتك عن شخصية ما في رواية، ممكن ترد مثل كذا: "يقول هاملت في هذا المشهد إنه..."

إذا كنت تريد شرح شيء بطريقة بسيطة، يمكنك استخدام أم`,
  },
  s45: {
    en: `Question 6 &mdash; Comparison (Level 4-5 / 9-10 marks)`,
    ar: `سؤال 6 &ndash; المقارنة (المستوى 4-5 / 9-10 نقاط)`,
  },
  s46: {
    en: `Example paragraph:`,
    ar: `مثال: إحنا في الحين ندور على نصوص من روميو وكايلا لفهم كيف يستخدم الكتاب الألفاظ والأدوات اللغوية. اقرأ المشهد اللي بينه وبين جولييت ويحلل استخدام الكلمات والصور الشعرية. وايد مهم إنك تركز`,
  },
  s47: {
    en: `Why this works:`,
    ar: `شنو اللي ماعندش حظ يفهم، هذا الشي ماكو لازم يعمل الناس انطباع إيجابي. الحين إحنا نبي نشرح شنو هذا العمل كده ومفيد كيف.`,
  },
  s48: {
    en: `Section B &mdash; Speech Writing (Level 4 opening)`,
    ar: `SECTION B &mdash; كتابة الخطاب (بداية مستوى 4)`,
  },
  s49: { en: `Example opening:`, ar: `مثال لبداية:` },
  s51: { en: `Direct address:`, ar: `المراسلة المباشرة:` },
  s52: { en: `Sensory imagery:`, ar: `صور حسية:` },
  s53: { en: `Short sentence for impact:`, ar: `Sentence قصيرة لتأثير مباشِر:` },
  s54: { en: `Counter-argument acknowledged`, ar: `الرأي المضاد مقبول` },
  s55: { en: `Emotive language:`, ar: `لغة عاطفية:` },
  s56: { en: `Exam Strategy &amp; Timing`, ar: `استراتيجية الامتحان و التوقيت` },
  s57: { en: `Suggested Time`, ar: `الوقت المقترح` },
  s58: { en: `Key Advice`, ar: `نصائح مهمة` },
  s60: { en: `Two separate points. No analysis needed.`, ar: `نقطتين منفصلين. لا داعي للتحليل.` },
  s61: {
    en: `What-How-Why. 2-3 points with terminology.`,
    ar: `شنو - شلون - ليش. 2-3 نقاط مع مصطلحات.`,
  },
  s62: {
    en: `Same approach. Note modern language features.`,
    ar: `استخدم نفس الأسلوب. ملاحظة الميزات اللغوية الحديثة.`,
  },
  s63: {
    en: `Evaluate effectiveness. Address the statement. Balanced.`,
    ar: `سلي شلون تقدر تقيم فعالية الشي. روح ل.Statement وت-addressها. كون отзывك متوازن. 

(Note: There was an error in maintaining consistency with Khaleeji Arabic and incorporating instructional markers correctly. Here is a revised version that adheres strictly to the guidelines provided.)

سلي شلون بتقدر تقيم فعالية الشي. روح لـ statement وت-addressها. كون отзывك متوازن. 

(Revised for clarity and adherence:)

سلي شلون بتقدر تقيم فعالية الشي. دوّر على statement وت-addressها. كون رأيك متوازٍ.`,
  },
  s64: {
    en: `Compare throughout. Evidence from both texts. Context.`,
    ar: `сравنة خلالًا. بيّن أدلة من كلا النصوص. أذكر السياق.`,
  },
  s65: {
    en: `Content, organisation, and accuracy (AO5/AO6)`,
    ar: `المحتوى والتنظيم والدقة (AO5/AO6)`,
  },
  s66: {
    en: `Common Mistakes to Avoid on Paper 2`,
    ar: `أخطاء شائعة يجب تجنبها في ورقة الامتحان الثانية`,
  },
  s67: { en: `Section B:`, ar: `قسم ب:` },
  s68: { en: `Continue studying`, ar: `استمر في الدراسة` },
}
