/**
 * paper-2 set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Exam Structure`, ar: `هيكل الامتحان` },
  s1: { en: `Section A: 19th-Century Novel`, ar: `SECTION A: رواية من القرن التاسع عشر` },
  s2: { en: `Section B: Poetry Anthology`, ar: `` },
  s3: { en: `Section C: Unseen Poetry`, ar: `SECTION C: شعر غير مشاهد` },
  s4: { en: `Relationships Cluster`, ar: `` },
  s5: {
    en: `Conflict Cluster`,
    ar: ``,
  },
  s6: { en: `Step-by-step approach:`, ar: `خطوات منهجية:` },
  s7: {
    en: `Identify the poem&apos;s subject matter, tone, and overall message.`,
    ar: `ا indentify موضوع القصيدة، وتونها، ورسالتها الكلية.`,
  },
  s8: { en: `Tips for comparison:`, ar: `نصائح للمقارنة:` },
  s9: { en: `Metaphor and simile`, ar: `المétaphore والشِّبهة` },
  s11: { en: `Sensory language`, ar: `لغة حسية` },
  s12: { en: `Tone and register`, ar: `توني وRegistro` },
  s14: { en: `Symbolism and imagery`, ar: `simbolية والتصوير الحسي` },
  s15: { en: `Repetition and listing`, ar: `التكرار وال liệtsts` },
  s16: { en: `Structure &amp; Form`, ar: `الهيئة والشكل` },
  s17: { en: `Stanza arrangement`, ar: `ترتيب الأبيات` },
  s18: { en: `Enjambment and caesura`, ar: `anjeimant و قيصرة` },
  s19: { en: `Rhyme scheme`, ar: `النظام الشعري` },
  s20: { en: `Rhythm and metre`, ar: `النغم والوزن` },
  s21: { en: `Volta (a shift or turn)`, ar: `volta (تحول أو انعطاف)` },
  s22: { en: `Opening and closing lines`, ar: `السطر الأول والأخير` },
  s23: { en: `Form (sonnet, ballad, free verse)`, ar: `الشكل (.sonnet، ballad، free verse)` },
  s25: { en: `Timing Guide`, ar: `دليل التوقيت` },
  s26: {
    en: `Compare named poem with your choice`,
    ar: ``,
  },
  s27: { en: `Read twice, 3-4 PEA paragraphs`, ar: `` },
  s28: { en: `Paper 2 Exam Technique`, ar: `TECHNIQUE امتحان الورق الثاني` },
  s29: { en: `Memorise short, versatile quotes`, ar: `أبغى ت memorise قصيرة ومتعددة الاستخدامات` },
  s30: { en: `Context is crucial`, ar: `السياق مهم جداً` },
  s31: { en: `SPaG matters`, ar: `SPELLING و GRAMMAR مهمان` },
  s32: { en: `Show awareness of the whole text`, ar: `كن على معرفة بالنص كله` },
}
