/**
 * julius-caesar set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `William Shakespeare, c.1599`, ar: `ويليام شكسبير، circa 1599` },
  s2: { en: `The Wolf and Animal Imagery`, ar: `الذئب والصور الحيوانية` },
  s4: { en: `Omens and Prophecies`, ar: `omens وال.prophecies` },
  s5: { en: `Parallel Lives`, ar: `الحياة المتوازية` },
  s6: {
    en: `The Lives of the Noble Grecians and Romans`,
    ar: `حياة الرجال الأشراف من اليونانيين والرومان`,
  },
  s7: { en: `Elizabethan Succession Anxieties`, ar: `قلق إلizabethan بشأن التSuccession` },
  s8: { en: `Richard II`, ar: `ريتشارد الثانى` },
  s9: { en: `Stoicism and Classical Philosophy`, ar: `` },
  s11: { en: `Soliloquy and Public Speech`, ar: `منولوج وخطاب علني` },
  s12: { en: `The Crowd as Character`, ar: `الجمهور كشخصية` },
  s13: { en: `Doubling, Mirroring, and Foils`, ar: `التكرار، التماثل، وال álزاز` },
  s14: { en: `Ghostly Return`, ar: `عودة شبحية` },
  s15: { en: `Exam Tips for Julius Caesar`, ar: `نصائح للامتحان حول يوليوس قيصر` },
  s16: { en: `Always link to context.`, ar: `` },
  s17: { en: `Use Shakespeare&apos;s methods.`, ar: `استخدم طرق شكسبير.` },
  s18: { en: `Refer to the writer&apos;s intentions.`, ar: `انظر إلى نوايا الكاتب.` },
  s19: { en: `Acknowledge ambiguity.`, ar: `اعترف بالغموض.` },
  s20: { en: `Use precise terminology.`, ar: `استخدم لغة دقيقة.` },
  s21: {
    en: `Address the whole play.`,
    ar: `ا.address the whole play. ا.read the entire play. 

(Note: The instruction seems to be incomplete or unclear in English. If "Address the whole play" is a command or directive, it would translate more appropriately as an instructional imperative verb like "اقرأ المسرحية كلها" which means "Read the entire play." Please`,
  },
  s22: { en: `Julius Caesar`, ar: `يوليوس قيصر` },
  s23: { en: `Act-by-Act Summary`, ar: `ملخص مشاهدًا مشاهدًا` },
  s24: { en: `Character Profiles`, ar: `Profiles للشخصيات` },
  s25: { en: `The conspiracy`, ar: `المؤامرة` },
  s27: { en: `Key Themes`, ar: `الموضوعات الرئيسية` },
  s28: { en: `Honour vs Ambition`, ar: `` },
  s29: {
    en: `The central moral conflict of the play. Brutus values honour above all and is celebrated for it; Caesar is killed for ambition. Yet Shakespeare problematises both. Brutus`,
    ar: `الصراع الأخلاقي الرئيسي في المسرحية. بروتس يقدر الشرف فوق كل شيء ويحتفل به؛ قيصر يقتل بسبب الطموح. ومع ذلك، ي.problematises.brutus

(الترجمة الصحيحة لـ "problematises" هي "يشكل مشكلة لها" أو "يطرح تساؤلات حولها". ولكن بما أن الكلمة مذكّر في السياق، يمكن استخدام الشكل الفعلي المناسب:)

يشكل بروتس مشكلة لها`,
  },
  s30: { en: `Fate vs Free Will`, ar: `القدر ضد الإرادة الحرة` },
  s31: {
    en: `The play is saturated with omens, prophecies, and dreams — the Soothsayer, Calpurnia`,
    ar: `المسرحية مaturated بomens، prophecies، وأحلام — الصوفي، كالبورنيا`,
  },
  s32: { en: `Public vs Private Self`, ar: `الذات العامة والخاصة` },
  s33: { en: `Rhetoric and Persuasion`, ar: `الخطابة والإقناع` },
  s34: {
    en: `Julius Caesar is, above all, a play about words. The Republic is founded on debate, and the play stages successive scenes of persuasion: Cassius working on Brutus, Decius reinterpreting Calpurnia`,
    ar: ``,
  },
  s35: { en: `Power and Tyranny`, ar: `القوة والطغيان` },
  s37: { en: `Friendship and Betrayal`, ar: `الصداقة والخيانة` },
  s38: { en: `Key Quotations with Analysis`, ar: `اقتباسات رئيسية مع تحليل` },
  s39: { en: `Symbols and Motifs`, ar: `رموز وعلامات` },
  s40: { en: `Historical and Literary Context`, ar: `` },
  s41: { en: `Dramatic Structure`, ar: `اله"structure"drama اله` },
  s42: { en: `Essay Planning for Common Questions`, ar: `hoạchtlان للأسئلة الشائعة` },
  s43: { en: `Practice Questions`, ar: `أسئلة للتدريب` },
}
