/**
 * spoken-language set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Spoken Language`, ar: `اللغة المنطوقة` },
  s1: {
    en: `Required for all GCSE English Language students`,
    ar: `مطلوب لجميع طلبة اللغة الإنجليزية في الشهادة العامة للتعليم الثانوي`,
  },
  s2: {
    en: `Reported separately &mdash; does`,
    ar: `.reported separately &mdash; يreported separately &mdash; 

(Translation note: The "&mdash;" is kept as-is since it's a formatting element, and "does" was not provided in context for translation.) 

Since the input text seems incomplete, here’s a possible full sentence translation based on common usage:
.reported separately &mdash; يتم الإبلاغ عنهما بشكل منفصل &mdash;`,
  },
  s3: {
    en: `Assessed by your teacher, moderated by your exam board`,
    ar: `مُرَاجَأَة مُعِيدك، مُدَقّق لجنة الامتحانات الخاصة بك`,
  },
  s4: {
    en: `You deliver a presentation, then answer questions`,
    ar: `ت Deliver a presentation, then answer questions ت`,
  },
  s5: {
    en: `Standard English must be used throughout`,
    ar: `يجب استخدام اللغة الإنجليزية القياسية في جميع الأوقات`,
  },
  s6: {
    en: `Outstanding performance across all three strands`,
    ar: `أداء متميز في جميع الثلاثة مسارات`,
  },
  s7: { en: `Competent and clear across all strands`, ar: `متكامل وواضح في جميع الجوانب` },
  s8: { en: `Basic competence demonstrated`, ar: `المهارة الأساسية مDemonstrated` },
  s9: {
    en: `Not Classified`,
    ar: ``,
  },
  s10: { en: `Requirements not met`, ar: `متطلبات ما شافهاش` },
  s11: { en: `Strand 1 &mdash; Presenting`, ar: `السند الأول &mdash; العرض` },
  s12: {
    en: `Strand 2 &mdash; Listening and Responding`,
    ar: `السند الثاني &mdash; الاستماع والرد عليه`,
  },
  s13: {
    en: `Strand 3 &mdash; Using Standard English`,
    ar: `السند الثالث — استخدام الإنجليزية القياسية`,
  },
  s14: { en: `Want more ideas?`, ar: `أبغى أفكار تانية؟` },
  s16: { en: `Research thoroughly`, ar: `دورو وايد researching	thoroughly` },
  s17: { en: `Decide your angle`, ar: `حدّد وجهة نظرك` },
  s18: { en: `Structure your content`, ar: `اstructuring محتواك` },
  s19: { en: `Create cue cards`, ar: `صنّر بطاقات إرشادية` },
  s20: { en: `Anticipate questions`, ar: `توقع أسئلة` },
  s21: { en: `Practise aloud`, ar: `اقرأ بصوت عالي` },
  s22: { en: `Introduction (30&ndash;45 seconds)`, ar: `مقدمة (30 إلى 45 ثانية)` },
  s23: { en: `Main Points (2&ndash;3 minutes)`, ar: `نقاط_principal_(2-3 دقائق)` },
  s24: { en: `Counter-Argument (30&ndash;45 seconds)`, ar: `phản_argument (30 إلى 45 ثانية)` },
  s25: { en: `Conclusion (30&ndash;45 seconds)`, ar: `خاتمة (30 إلى 45 ثانية)` },
  s26: {
    en: `Key words and short phrases, not full sentences`,
    ar: `كلمات رئيسية وعبارات قصيرة، لا جمل كاملة`,
  },
  s28: {
    en: `Clear numbering so you keep track of the order`,
    ar: `سكيّر الترقيم واضحاً حتى تحافظ على الترتيب`,
  },
  s29: {
    en: `One main point per card for easy navigation`,
    ar: ``,
  },
  s30: { en: `Eye Contact`, ar: `` },
  s31: { en: `Volume and Clarity`, ar: `الحجم والوضوح` },
  s32: { en: `Tone and Expression`, ar: `تÓN والتعبير` },
  s33: { en: `Body Language`, ar: `لغة الجسد` },
  s34: { en: `Rhetorical Techniques`, ar: `TECHNIQUES الرتوريële` },
  s35: { en: `Listen to the full question`, ar: `شوف السؤال كله الحين` },
  s36: { en: `Take a moment to think`, ar: `لحظة، دوّر في أفكارك الحين` },
  s37: { en: `Answer in full sentences`, ar: `أجب بالجمل كاملة` },
  s38: { en: `Develop your answers`, ar: `انشر إجاباتك` },
  s39: { en: `If you do not know the answer`, ar: `إذا كنت لا تعرف الجواب` },
  s40: { en: `Refer back to your presentation`, ar: `راجع عرضك` },
  s41: { en: `Engage with challenging questions`, ar: `DEAL WITH COMPLEX QUESTIONS` },
  s43: { en: `Avoid (Non-Standard)`, ar: `` },
  s44: { en: `Use Instead (Standard English)`, ar: `استخدم بدلاً من (ال.Standard English)` },
  s45: {
    en: `Use formal vocabulary: &ldquo;furthermore&rdquo; rather than &ldquo;also&rdquo;; &ldquo;however&rdquo; rather than &ldquo;but&rdquo;`,
    ar: `استخدم لغة.formal: "&laquo;علاوة على ذلك&raquo;" بدلاً من "&laquo;أيضا&raquo;; "&laquo;ومع ذلك&raquo;" بدلاً من "&laquo;لكن&raquo;`,
  },
  s46: {
    en: `Speak in complete sentences, not fragments`,
    ar: `تكلم بالجمل الكاملة، لا التFragmentationragments มกรἀ`,
  },
  s47: {
    en: `Avoid filler words: &ldquo;um&rdquo;, &ldquo;er&rdquo;, &ldquo;like&rdquo;, &ldquo;you know&rdquo;`,
    ar: `تجنب استخدام الكلمات الزائدة: "أمم"، "إر"، "كما"، " знаешь`,
  },
  s48: { en: `Use subject-verb agreement correctly`, ar: `استخدم تماشى الضمير مع الفعل بشكل صحيح` },
  s49: {
    en: `Avoid double negatives: say &ldquo;I do not have any&rdquo; not &ldquo;I don&rsquo;t have none&rdquo;`,
    ar: `تجنب سوءات النفي المزدوج: قول &ldquo;لست عندي أي شيء&rdquo; وليس &ldquo;ما عندي_none&rdquo;`,
  },
  s50: { en: `Point 1: Taxation and representation`, ar: `النقطة الأولى: الضرائب والتمثيل` },
  s51: { en: `Point 2: Legal responsibilities`, ar: `المسؤوليات القانونية` },
  s53: {
    en: `Point 1: Comparison culture and self-esteem`,
    ar: `نقطة أولى: مقارنة الثقافة والذاتية التقديرية`,
  },
  s54: { en: `Point 2: Cyberbullying`, ar: `نقاط 2: التنمر الإلكتروني` },
  s55: { en: `Point 3: Sleep disruption and anxiety`, ar: `نقطة 3: اضطراب النوم والقلق` },
  s56: { en: `Listening &amp; Responding:`, ar: `الاستماع والرد:` },
  s57: { en: `Standard English:`, ar: `المواضيع المعتادة في اللغة الإنجليزية:` },
  s58: {
    en: `Use this checklist to make sure you are fully prepared:`,
    ar: `استخدم هذا القائمة لتأكد من أنك مستعد تمامًا:`,
  },
  s59: { en: `Need a Topic?`, ar: `أبغى موضوع؟` },
}
