// AUTO-GENERATED by scripts/generate-public-domain-guides.mjs - do not edit by hand.
// Re-run that script after adding a study guide or changing a guide's rights.

/**
 * Study guides whose text is in the public domain, read from each guide's own
 * `rights.status` in src/data/study-guides. A statement about rights only:
 * which of these have guided games is decided in
 * src/lib/games/text-games/slugs.ts.
 */
export const PUBLIC_DOMAIN_GUIDE_SLUGS: ReadonlySet<string> = new Set([
  'a-christmas-carol',
  'a-dolls-house',
  'a-midsummer-nights-dream',
  'animal-farm',
  'antony-and-cleopatra',
  'disabled',
  'do-not-go-gentle-into-that-good-night',
  'frankenstein',
  'great-expectations',
  'hamlet',
  'henry-v',
  'if',
  'jane-eyre',
  'jekyll-and-hyde',
  'julius-caesar',
  'king-lear',
  'la-belle-dame-sans-merci',
  'macbeth',
  'much-ado-about-nothing',
  'my-last-duchess',
  'othello',
  'piano',
  'pride-and-prejudice',
  'remember',
  'romeo-and-juliet',
  'silas-marner',
  'sonnet-116',
  'the-great-gatsby',
  'the-merchant-of-venice',
  'the-scarlet-letter',
  'the-sign-of-four',
  'the-story-of-an-hour',
  'the-tempest',
  'the-tyger',
  'the-war-of-the-worlds',
  'the-yellow-wallpaper',
  'twelfth-night',
])
