// AUTO-GENERATED by scripts/generate-study-guide-index.mjs - do not edit by hand.
// Re-run that script after adding or removing a guide in this directory.

/**
 * The register of study-guide files. One lazy loader per text, keyed by the
 * set-text slug in src/lib/board/set-texts.ts. Lazy so that a page loads the one
 * guide it renders; see src/lib/study-guides/load.ts.
 */

import type { StudyGuide } from '@/lib/study-guides/types'

export const STUDY_GUIDE_LOADERS: Record<string, () => Promise<StudyGuide>> = {
  'a-game-of-polo-with-a-headless-goat': () =>
    import('./a-game-of-polo-with-a-headless-goat').then((m) => m.guide),
  'a-passage-to-africa': () => import('./a-passage-to-africa').then((m) => m.guide),
  'an-unknown-girl': () => import('./an-unknown-girl').then((m) => m.guide),
  'between-a-rock-and-a-hard-place': () =>
    import('./between-a-rock-and-a-hard-place').then((m) => m.guide),
  'beyond-the-sky-and-the-earth': () =>
    import('./beyond-the-sky-and-the-earth').then((m) => m.guide),
  blessing: () => import('./blessing').then((m) => m.guide),
  'chinese-cinderella': () => import('./chinese-cinderella').then((m) => m.guide),
  disabled: () => import('./disabled').then((m) => m.guide),
  'do-not-go-gentle-into-that-good-night': () =>
    import('./do-not-go-gentle-into-that-good-night').then((m) => m.guide),
  'explorers-or-boys-messing-about': () =>
    import('./explorers-or-boys-messing-about').then((m) => m.guide),
  'h-is-for-hawk': () => import('./h-is-for-hawk').then((m) => m.guide),
  'half-caste': () => import('./half-caste').then((m) => m.guide),
  'half-past-two': () => import('./half-past-two').then((m) => m.guide),
  'hide-and-seek': () => import('./hide-and-seek').then((m) => m.guide),
  if: () => import('./if').then((m) => m.guide),
  'la-belle-dame-sans-merci': () => import('./la-belle-dame-sans-merci').then((m) => m.guide),
  'my-last-duchess': () => import('./my-last-duchess').then((m) => m.guide),
  night: () => import('./night').then((m) => m.guide),
  'out-out': () => import('./out-out').then((m) => m.guide),
  piano: () => import('./piano').then((m) => m.guide),
  'poem-at-thirty-nine': () => import('./poem-at-thirty-nine').then((m) => m.guide),
  'prayer-before-birth': () => import('./prayer-before-birth').then((m) => m.guide),
  remember: () => import('./remember').then((m) => m.guide),
  'search-for-my-tongue': () => import('./search-for-my-tongue').then((m) => m.guide),
  'significant-cigarettes': () => import('./significant-cigarettes').then((m) => m.guide),
  'sonnet-116': () => import('./sonnet-116').then((m) => m.guide),
  'still-i-rise': () => import('./still-i-rise').then((m) => m.guide),
  'the-bright-lights-of-sarajevo': () =>
    import('./the-bright-lights-of-sarajevo').then((m) => m.guide),
  'the-danger-of-a-single-story': () =>
    import('./the-danger-of-a-single-story').then((m) => m.guide),
  'the-explorers-daughter': () => import('./the-explorers-daughter').then((m) => m.guide),
  'the-necklace': () => import('./the-necklace').then((m) => m.guide),
  'the-story-of-an-hour': () => import('./the-story-of-an-hour').then((m) => m.guide),
  'the-tyger': () => import('./the-tyger').then((m) => m.guide),
  'the-war-of-the-worlds': () => import('./the-war-of-the-worlds').then((m) => m.guide),
  'war-photographer': () => import('./war-photographer').then((m) => m.guide),
  'whistle-and-ill-come-to-you': () => import('./whistle-and-ill-come-to-you').then((m) => m.guide),
  'young-and-dyslexic': () => import('./young-and-dyslexic').then((m) => m.guide),
}
