// AUTO-GENERATED by scripts/generate-study-guide-index.mjs - do not edit by hand.
// Re-run that script after adding or removing a guide in this directory.

/**
 * The register of study-guide files. One lazy loader per text, keyed by the
 * set-text slug in src/lib/board/set-texts.ts. Lazy so that a page loads the one
 * guide it renders; see src/lib/study-guides/load.ts.
 */

import type { StudyGuide } from '@/lib/study-guides/types'

export const STUDY_GUIDE_LOADERS: Record<string, () => Promise<StudyGuide>> = {
  'a-christmas-carol': () => import('./a-christmas-carol').then((m) => m.guide),
  'a-dolls-house': () => import('./a-dolls-house').then((m) => m.guide),
  'a-game-of-polo-with-a-headless-goat': () =>
    import('./a-game-of-polo-with-a-headless-goat').then((m) => m.guide),
  'a-midsummer-nights-dream': () => import('./a-midsummer-nights-dream').then((m) => m.guide),
  'a-passage-to-africa': () => import('./a-passage-to-africa').then((m) => m.guide),
  'a-taste-of-honey': () => import('./a-taste-of-honey').then((m) => m.guide),
  'an-inspector-calls': () => import('./an-inspector-calls').then((m) => m.guide),
  'an-unknown-girl': () => import('./an-unknown-girl').then((m) => m.guide),
  'antony-and-cleopatra': () => import('./antony-and-cleopatra').then((m) => m.guide),
  'between-a-rock-and-a-hard-place': () =>
    import('./between-a-rock-and-a-hard-place').then((m) => m.guide),
  'beyond-the-sky-and-the-earth': () =>
    import('./beyond-the-sky-and-the-earth').then((m) => m.guide),
  blessing: () => import('./blessing').then((m) => m.guide),
  'blues-for-an-alabama-sky': () => import('./blues-for-an-alabama-sky').then((m) => m.guide),
  'boys-dont-cry': () => import('./boys-dont-cry').then((m) => m.guide),
  'chinese-cinderella': () => import('./chinese-cinderella').then((m) => m.guide),
  'coram-boy': () => import('./coram-boy').then((m) => m.guide),
  'curious-incident': () => import('./curious-incident').then((m) => m.guide),
  'death-and-the-kings-horseman': () =>
    import('./death-and-the-kings-horseman').then((m) => m.guide),
  disabled: () => import('./disabled').then((m) => m.guide),
  dna: () => import('./dna').then((m) => m.guide),
  'do-not-go-gentle-into-that-good-night': () =>
    import('./do-not-go-gentle-into-that-good-night').then((m) => m.guide),
  'explorers-or-boys-messing-about': () =>
    import('./explorers-or-boys-messing-about').then((m) => m.guide),
  'fire-on-the-mountain': () => import('./fire-on-the-mountain').then((m) => m.guide),
  frankenstein: () => import('./frankenstein').then((m) => m.guide),
  'great-expectations': () => import('./great-expectations').then((m) => m.guide),
  'h-is-for-hawk': () => import('./h-is-for-hawk').then((m) => m.guide),
  'half-caste': () => import('./half-caste').then((m) => m.guide),
  'half-past-two': () => import('./half-past-two').then((m) => m.guide),
  hamlet: () => import('./hamlet').then((m) => m.guide),
  'henry-v': () => import('./henry-v').then((m) => m.guide),
  'hide-and-seek': () => import('./hide-and-seek').then((m) => m.guide),
  'hobsons-choice': () => import('./hobsons-choice').then((m) => m.guide),
  'hullaballoo-in-the-guava-orchard': () =>
    import('./hullaballoo-in-the-guava-orchard').then((m) => m.guide),
  if: () => import('./if').then((m) => m.guide),
  'im-the-king-of-the-castle': () => import('./im-the-king-of-the-castle').then((m) => m.guide),
  'jane-eyre': () => import('./jane-eyre').then((m) => m.guide),
  'jekyll-and-hyde': () => import('./jekyll-and-hyde').then((m) => m.guide),
  'journeys-end': () => import('./journeys-end').then((m) => m.guide),
  'julius-caesar': () => import('./julius-caesar').then((m) => m.guide),
  kindertransport: () => import('./kindertransport').then((m) => m.guide),
  'king-lear': () => import('./king-lear').then((m) => m.guide),
  'klara-and-the-sun': () => import('./klara-and-the-sun').then((m) => m.guide),
  'la-belle-dame-sans-merci': () => import('./la-belle-dame-sans-merci').then((m) => m.guide),
  'leave-taking': () => import('./leave-taking').then((m) => m.guide),
  macbeth: () => import('./macbeth').then((m) => m.guide),
  'much-ado-about-nothing': () => import('./much-ado-about-nothing').then((m) => m.guide),
  'my-last-duchess': () => import('./my-last-duchess').then((m) => m.guide),
  'my-name-is-leon': () => import('./my-name-is-leon').then((m) => m.guide),
  night: () => import('./night').then((m) => m.guide),
  'of-mice-and-men': () => import('./of-mice-and-men').then((m) => m.guide),
  'oranges-are-not-the-only-fruit': () =>
    import('./oranges-are-not-the-only-fruit').then((m) => m.guide),
  othello: () => import('./othello').then((m) => m.guide),
  'out-out': () => import('./out-out').then((m) => m.guide),
  piano: () => import('./piano').then((m) => m.guide),
  'pigeon-english': () => import('./pigeon-english').then((m) => m.guide),
  'poem-at-thirty-nine': () => import('./poem-at-thirty-nine').then((m) => m.guide),
  'prayer-before-birth': () => import('./prayer-before-birth').then((m) => m.guide),
  'pride-and-prejudice': () => import('./pride-and-prejudice').then((m) => m.guide),
  'princess-and-the-hustler': () => import('./princess-and-the-hustler').then((m) => m.guide),
  'refugee-blues': () => import('./refugee-blues').then((m) => m.guide),
  'refugee-boy': () => import('./refugee-boy').then((m) => m.guide),
  remember: () => import('./remember').then((m) => m.guide),
  'romeo-and-juliet': () => import('./romeo-and-juliet').then((m) => m.guide),
  'search-for-my-tongue': () => import('./search-for-my-tongue').then((m) => m.guide),
  'significant-cigarettes': () => import('./significant-cigarettes').then((m) => m.guide),
  'silas-marner': () => import('./silas-marner').then((m) => m.guide),
  'sonnet-116': () => import('./sonnet-116').then((m) => m.guide),
  'still-i-rise': () => import('./still-i-rise').then((m) => m.guide),
  'telling-tales': () => import('./telling-tales').then((m) => m.guide),
  'the-bright-lights-of-sarajevo': () =>
    import('./the-bright-lights-of-sarajevo').then((m) => m.guide),
  'the-danger-of-a-single-story': () =>
    import('./the-danger-of-a-single-story').then((m) => m.guide),
  'the-door': () => import('./the-door').then((m) => m.guide),
  'the-empress': () => import('./the-empress').then((m) => m.guide),
  'the-explorers-daughter': () => import('./the-explorers-daughter').then((m) => m.guide),
  'the-great-gatsby': () => import('./the-great-gatsby').then((m) => m.guide),
  'the-history-boys': () => import('./the-history-boys').then((m) => m.guide),
  'the-joy-luck-club': () => import('./the-joy-luck-club').then((m) => m.guide),
  'the-man-who-loved-flowers': () => import('./the-man-who-loved-flowers').then((m) => m.guide),
  'the-merchant-of-venice': () => import('./the-merchant-of-venice').then((m) => m.guide),
  'the-necklace': () => import('./the-necklace').then((m) => m.guide),
  'the-pedestrian': () => import('./the-pedestrian').then((m) => m.guide),
  'the-scarlet-letter': () => import('./the-scarlet-letter').then((m) => m.guide),
  'the-sign-of-four': () => import('./the-sign-of-four').then((m) => m.guide),
  'the-story-of-an-hour': () => import('./the-story-of-an-hour').then((m) => m.guide),
  'the-tempest': () => import('./the-tempest').then((m) => m.guide),
  'the-tyger': () => import('./the-tyger').then((m) => m.guide),
  'the-war-of-the-worlds': () => import('./the-war-of-the-worlds').then((m) => m.guide),
  'the-waste-land': () => import('./the-waste-land').then((m) => m.guide),
  'the-whale-rider': () => import('./the-whale-rider').then((m) => m.guide),
  'the-woman-in-black': () => import('./the-woman-in-black').then((m) => m.guide),
  'the-yellow-wallpaper': () => import('./the-yellow-wallpaper').then((m) => m.guide),
  'twelfth-night': () => import('./twelfth-night').then((m) => m.guide),
  'war-photographer': () => import('./war-photographer').then((m) => m.guide),
  'western-lane': () => import('./western-lane').then((m) => m.guide),
  'what-it-means-when-a-man-falls-from-the-sky': () =>
    import('./what-it-means-when-a-man-falls-from-the-sky').then((m) => m.guide),
  'whistle-and-ill-come-to-you': () => import('./whistle-and-ill-come-to-you').then((m) => m.guide),
  'young-and-dyslexic': () => import('./young-and-dyslexic').then((m) => m.guide),
}
