/**
 * cancellation set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Cancellation Policy`, ar: `سياسة الإلغاء` },
  s1: { en: `The English Hub`, ar: `The English Hub` },
  s2: {
    en: `Cancelling is easy: online or by email`,
    ar: `إلغاء الحجز سهل: عبر الإنترنت أو بالبريد الإلكتروني`,
  },
  s3: {
    en: `If you cancel, we will refund you within 14 days`,
    ar: `إذا إلغيت، سنرد مالك خلال 14 يومًا`,
  },
  s4: { en: `We will never make it hard for you to leave`, ar: `ما رح نشيل منك صعوبة تطلع الحين` },
  s5: { en: `What If You Want Immediate Access?`, ar: `شنو لو أبغى الدخول فوراً؟` },
  s6: {
    en: `If you consent and then cancel within 14 days:`,
    ar: `إذا وافقت ثم ألغيت خلال 14 يومًا:`,
  },
  s7: { en: `If you do not consent:`, ar: `إذا لم توافق:` },
  s8: { en: `What you get back`, ar: `ما ترجع عليه شنو؟` },
  s9: {
    en: `Cancel within 14 days (no immediate access)`,
    ar: `ألغي خلال 14 يوماً (لا يوجد دخول فوري)`,
  },
  s10: { en: `Full refund`, ar: `hoàn tiền đầy đủ` },
  s11: { en: `Within 14 days of cancellation`, ar: `` },
  s12: { en: `Refund minus pro-rata charge`, ar: `رد المبلغ بعد خصم نسبة القيمة المتناسبة` },
  s13: {
    en: `Cancel monthly subscription after 14 days`,
    ar: `.cancel الاشتراك الشهري بعد 14 يومًا`,
  },
  s14: { en: `Example: Annual pro-rata refund`, ar: `hoàn trả نسبة سنوية` },
  s15: { en: `Monthly Subscriptions`, ar: `اشتراكات شهرية` },
  s16: { en: `Annual Subscriptions`, ar: `اشتراكات سنوية` },
  s17: { en: `Every renewal reminder will include:`, ar: `كل تذكرة للتجديد ستشمل:` },
  s18: {
    en: `The date your next payment will be taken`,
    ar: `التاريخ اللي هيدور فيه الدفعة الجاية منك`,
  },
  s19: { en: `The amount that will be charged`, ar: `المبلغ الذي سيتم تقاضيه` },
  s20: {
    en: `Any price changes with old and new prices clearly stated`,
    ar: `أي تغييرات في السعر مع الأسعار القديمة والجديدة مذكورة بشكل واضح`,
  },
  s21: { en: `Option A - Cancel Online`, ar: `أختار أOPTION أA - أ_Cancel أOnline` },
  s22: { en: `Log in to your account`, ar: `تسجيل الدخول إلى حسابك` },
  s23: { en: `Account Settings`, ar: `إعدادات الحساب` },
  s24: { en: `Manage Subscription`, ar: `إدارة الاشتراك` },
  s25: { en: `Cancel Subscription`, ar: `إلغِ الاشتراك` },
  s26: { en: `Confirm cancellation`, ar: `أคอนفم إلغاء` },
  s27: {
    en: `Receive confirmation email immediately`,
    ar: `دوري على البريد الإلكتروني التأكيدي فوراً`,
  },
  s28: { en: `Option B - Cancel by Email`, ar: `الخيار بي - إلغِ بواسطة البريد الإلكتروني` },
  s29: { en: `We will never:`, ar: `ما رح نكون أبداً:` },
  s31: {
    en: `Ask you to navigate through multiple confusing screens`,
    ar: `دوري على تمرير اللياقة فيScreens كتيرة ومعقدة الحين`,
  },
  s32: { en: `Charge you a fee for cancelling`, ar: `يكلفك رسومًا لإلغاء` },
  s33: {
    en: `Your access continues until the end of your current paid period`,
    ar: `تواصل حقك في الوصول حتى نهاية الفترة المدفوعة الحالية لك`,
  },
  s34: {
    en: `On the day your paid period ends, premium content access will stop`,
    ar: ``,
  },
  s35: { en: `Any free features remain available to you`, ar: `أي الميزات المجانية تظل متاحة لك` },
  s36: { en: `You can resubscribe at any time`, ar: `يمكنك الاشتراك مجددًا في أي وقت` },
  s37: { en: `Operated by: Upskill Energy Limited`, ar: `OPERATED BY: Upskill Energy Limited` },
  s38: { en: `Model Cancellation Form`, ar: `نموذج إلغاء الحجز` },
  s39: { en: `Date subscription was started:`, ar: `تاريخ بدء الاشتراك:` },
  s40: { en: `Your name:`, ar: `اسمك:` },
  s41: { en: `Your email address:`, ar: `địaادلك البريد الإلكتروني:` },
  s42: { en: `Your address (optional):`, ar: `عنوانك (اختياري):` },
  s43: { en: `Date of this notice:`, ar: `تاريخ هذا الإشعار:` },
}
