/**
 * romeo-and-juliet set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 *
 * Corrected by hand on 2 October 2026, so check these entries again if the
 * file is regenerated. Three Arabic strings broke the convention above: s2 and
 * s3 translated their quotations of the play ("Did my heart love till now?",
 * "All are punish'd.") into Arabic, s2 leaving its quotation mark unclosed and
 * calling the clichés a "joke" (نكتة); and s4 opened with the translator's own
 * note, in Chinese, that its first attempt had failed, before an Arabic
 * "Ancient grudge". Each now carries the English quotation, word for word as
 * the English string has it; s4 keeps the translator's corrected sentence.
 * Quotations stay in English: students quote the play in English in the exam.
 * content.translations.json beside this file holds the same faults, but
 * nothing in the site reads it.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Key Moments:`, ar: `لحظات حاسمة:` },
  s1: {
    en: `Essential quotations to learn. Each connects to multiple themes.`,
    ar: `الاقتباسات الأساسية التي يجب حفظها. كل واحدة منها ترتبط بمواضيع متعددة.`,
  },
  s2: {
    en: `Romeo's shift from Petrarchan clichés to genuine poetry. The shared sonnet (1.5) as collaborative love. “Did my heart love till now?”`,
    ar: `تحول روميو من الكليشيهات البتراركية إلى شعر حقيقي. السوناتا المشتركة (١.٥) كحب تعاوني. "Did my heart love till now?"`,
  },
  s3: {
    en: `The deaths end the feud. “All are punish'd.” Love achieves what authority could not.`,
    ar: `تنتهي الحرب بسبب هذه الوفيات. "All are punish'd." الحب يحقق ما لا يستطيع السلطة تحقيقه.`,
  },
  s4: {
    en: `Opening brawl. Prince's failed authority. “Ancient grudge” -- cause forgotten, hatred persists.`,
    ar: `مباراة قتال في البداية. سلطة الأمير الفاشلة. "Ancient grudge" -- السبب نُسي، لكن الحقد استمر.`,
  },
  s5: {
    en: `Tybalt as honour personified. Mercutio's death. Romeo torn between love and revenge.`,
    ar: ``,
  },
  s6: {
    en: `Juliet's oxymorons. Romeo's conflict between pacifism and revenge. The Friar's conflict between caution and action.`,
    ar: `أوكسيمورونات جولييت. تناقض روميو بين السلمية والثأر. تضارب الكاهن بين الحذر والعمل.`,
  },
  s7: { en: `Question 1`, ar: `السؤال الأول` },
  s8: { en: `Romeo and Juliet`, ar: `روميو و جولييت` },
  s9: { en: `Question 2`, ar: `سؤال 2` },
  s10: { en: `Question 3`, ar: `السؤال الثالث` },
  s11: { en: `Question 4`, ar: `السؤال الرابع` },
  s12: { en: `Act-by-Act Plot Summary`, ar: `ملخص القصة مشاهدًا مشاهد` },
  s13: { en: `Act 1 -- The Feud and the Meeting`, ar: `الatto 1 -- الخصام واللقاء` },
  s14: { en: `Act 2 -- The Balcony and the Wedding`, ar: `الatto 2 -- الشرفة والزفاف` },
  s15: { en: `Act 3 -- The Turning Point`, ar: `الatto 3 -- النقطة الفاصلة` },
  s16: { en: `Act 4 -- The Plan`, ar: `الatto 4 -- الخطة` },
  s17: { en: `Act 5 -- The Tragedy`, ar: `الatto 5 -- المأساة` },
  s18: { en: `Character Profiles`, ar: `Profiles الشخصيات` },
  s19: { en: `Friar Lawrence`, ar: `أخ فرير لورنس` },
  s20: { en: `Lord Capulet`, ar: `لورد كايبulet` },
  s21: { en: `The Prince (Escalus)`, ar: `` },
  s22: { en: `Major Themes`, ar: `ال THEMES الرئيسيين` },
  s23: { en: `Fate and Destiny`, ar: `القدر والمصير` },
  s24: { en: `Conflict and Violence`, ar: `الصراع والعنف` },
  s25: { en: `Family and Duty`, ar: `الأسرة والواجب` },
  s26: { en: `Youth vs Age`, ar: `الشباب ضد الكهولة` },
  s27: { en: `Light and Dark`, ar: `الضوء والظلام` },
  s28: { en: `Honour and Masculinity`, ar: `` },
  s29: { en: `Key Quotations`, ar: `الاقتباسات الرئيسية` },
  s30: { en: `The Prologue`, ar: `ال próلُوجو` },
  s31: { en: `Other Characters`, ar: `شخصيات أخرى` },
  s32: {
    en: `Historical and Social Context`,
    ar: ``,
  },
  s34: { en: `Italian Setting and Honour Culture`, ar: `ثقافة الشرف في setting إيطالي` },
  s35: { en: `The Sonnet Tradition`, ar: `العادة الشعرية القصيدة الرباعية` },
  s36: { en: `Plague in Elizabethan London`, ar: `الوباء في لندن الإليزابيثية` },
  s37: { en: `Dramatic Irony`, ar: `حالة الحيرة الدرامية` },
  s38: { en: `Sonnet Form`, ar: `شكل القصيدة الرباعية (سونت)` },
  s39: { en: `Oxymorons and Paradox`, ar: `أوكسيمورونات وبارادكس` },
  s40: { en: `Light and Dark Imagery`, ar: `صور الضوء والظلام` },
  s41: {
    en: `Compressed Time Structure`,
    ar: ``,
  },
  s42: { en: `Soliloquy and Aside`, ar: `منولوج وجانبي` },
  s43: {
    en: `Comic-Tragic Structure`,
    ar: `البنية الكوميدية التراجيدية`,
  },
  s44: { en: `Patriarchal Language and Power`, ar: `لغة الأبوي والسلطة` },
  s45: {
    en: `Grade 9 Exemplar Points and Interpretations`,
    ar: `نقاط وأinterpretations التمثيلية للصف التاسع`,
  },
  s46: { en: `Essay Planning Templates`, ar: `قوالب التخطيط للكتابة الإنشائية` },
  s47: { en: `Practice Questions`, ar: `أسئلة ممارسة` },
  s48: { en: `Write your essay response here...`, ar: `اكتب ردود فعل مقالتك هنا...` },
}
