/**
 * romeo-and-juliet set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Key Moments:`, ar: `لحظات حاسمة:` },
  s1: {
    en: `Essential quotations to learn. Each connects to multiple themes.`,
    ar: `الاقتباسات الأساسية التي يجب حفظها. كل واحدة منها ترتبط بمواضيع متعددة.`,
  },
  s2: {
    en: `Romeo&apos;s shift from Petrarchan clich&eacute;s to genuine poetry. The shared sonnet (1.5) as collaborative love. &ldquo;Did my heart love till now?&rdquo;`,
    ar: `تحول روميو من نكتة بيتارشية إلى شعر حقيقي. السوناتا المشتركة (١.٥) كحب تعاوني. "هل أحب قلبي قبل الآن؟`,
  },
  s3: {
    en: `The deaths end the feud. &ldquo;All are punish&apos;d.&rdquo; Love achieves what authority could not.`,
    ar: `تنتهي الحرب بسبب هذه الوفيات. "كلهم عذبوا." الحب يحقق ما لا يستطيع السلطة تحقيقه.`,
  },
  s4: {
    en: `Opening brawl. Prince&apos;s failed authority. &ldquo;Ancient grudge&rdquo; -- cause forgotten, hatred persists.`,
    ar: `مباراة قتال في البداية. سلطة الأمير الم失败的翻译结果不正确，我来重新生成正确的翻译。

正确的翻译应该是：

مباراة قتال في البداية. سلطة الأمير الفاشلة. "عداوة قديمة" -- السبب نُسي، لكن الحقد استمر.`,
  },
  s5: {
    en: `Tybalt as honour personified. Mercutio&apos;s death. Romeo torn between love and revenge.`,
    ar: ``,
  },
  s6: {
    en: `Juliet&apos;s oxymorons. Romeo&apos;s conflict between pacifism and revenge. The Friar&apos;s conflict between caution and action.`,
    ar: `أوكسيمورونات جولييت. تناقض روميو بين السلمية والثأر. تضارب الكاهن بين الحذر والعمل.`,
  },
  s7: { en: `Question 1`, ar: `السؤال الأول` },
  s8: { en: `Romeo and Juliet`, ar: `روميو و جولييت` },
  s9: { en: `Question 2`, ar: `سؤال 2` },
  s10: { en: `Question 3`, ar: `السؤال الثالث` },
  s11: { en: `Question 4`, ar: `السؤال الرابع` },
  s12: { en: `Act-by-Act Plot Summary`, ar: `ملخص القصة مشاهدًا مشاهد` },
  s13: { en: `Act 1 -- The Feud and the Meeting`, ar: `الatto 1 -- الخصام واللقاء` },
  s14: { en: `Act 2 -- The Balcony and the Wedding`, ar: `الatto 2 -- الشرفة والزفاف` },
  s15: { en: `Act 3 -- The Turning Point`, ar: `الatto 3 -- النقطة الفاصلة` },
  s16: { en: `Act 4 -- The Plan`, ar: `الatto 4 -- الخطة` },
  s17: { en: `Act 5 -- The Tragedy`, ar: `الatto 5 -- المأساة` },
  s18: { en: `Character Profiles`, ar: `Profiles الشخصيات` },
  s19: { en: `Friar Lawrence`, ar: `أخ فرير لورنس` },
  s20: { en: `Lord Capulet`, ar: `لورد كايبulet` },
  s21: { en: `The Prince (Escalus)`, ar: `` },
  s22: { en: `Major Themes`, ar: `ال THEMES الرئيسيين` },
  s23: { en: `Fate and Destiny`, ar: `القدر والمصير` },
  s24: { en: `Conflict and Violence`, ar: `الصراع والعنف` },
  s25: { en: `Family and Duty`, ar: `الأسرة والواجب` },
  s26: { en: `Youth vs Age`, ar: `الشباب ضد الكهولة` },
  s27: { en: `Light and Dark`, ar: `الضوء والظلام` },
  s28: { en: `Honour and Masculinity`, ar: `` },
  s29: { en: `Key Quotations`, ar: `الاقتباسات الرئيسية` },
  s30: { en: `The Prologue`, ar: `ال próلُوجو` },
  s31: { en: `Other Characters`, ar: `شخصيات أخرى` },
  s32: {
    en: `Historical and Social Context`,
    ar: ``,
  },
  s34: { en: `Italian Setting and Honour Culture`, ar: `ثقافة الشرف في setting إيطالي` },
  s35: { en: `The Sonnet Tradition`, ar: `العادة الشعرية القصيدة الرباعية` },
  s36: { en: `Plague in Elizabethan London`, ar: `الوباء في لندن الإليزابيثية` },
  s37: { en: `Dramatic Irony`, ar: `حالة الحيرة الدرامية` },
  s38: { en: `Sonnet Form`, ar: `شكل القصيدة الرباعية (سونت)` },
  s39: { en: `Oxymorons and Paradox`, ar: `أوكسيمورونات وبارادكس` },
  s40: { en: `Light and Dark Imagery`, ar: `صور الضوء والظلام` },
  s41: {
    en: `Compressed Time Structure`,
    ar: ``,
  },
  s42: { en: `Soliloquy and Aside`, ar: `منولوج وجانبي` },
  s43: {
    en: `Comic-Tragic Structure`,
    ar: `โครงสร้างตลกโศกนาฏikal (Note: The term "comic-tragic" doesn't have a direct equivalent in Khaleeji Arabic that fits naturally into the context provided, and given the instruction to keep technical terms as Latin or transliterated, I've presented it phonetically. However, for a`,
  },
  s44: { en: `Patriarchal Language and Power`, ar: `لغة الأبوي والسلطة` },
  s45: {
    en: `Grade 9 Exemplar Points and Interpretations`,
    ar: `نقاط وأinterpretations التمثيلية للصف التاسع`,
  },
  s46: { en: `Essay Planning Templates`, ar: `قوالب التخطيط للكتابة الإنشائية` },
  s47: { en: `Practice Questions`, ar: `أسئلة ممارسة` },
  s48: { en: `Write your essay response here...`, ar: `اكتب ردود فعل مقالتك هنا...` },
}
