/**
 * grammar-punctuation set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Writing Skills`, ar: `مهارات الكتابة` },
  s1: {
    en: `Grammar &amp; Punctuation`,
    ar: `النحو وال пунктуация

(Note: There's an encoding issue with " Punktuātions" which seems to be a mix-up. The correct translation for "Punctuation" is "النقاط" or simply in the context, it can remain as "ال пунктуация" if referring to specific punctuation marks from English text. However, for general`,
  },
  s2: {
    en: `Furthermore, Moreover, In addition, Similarly, Equally`,
    ar: `فضلاً، بالإضافة إلى ذلك، كماً، سِمَيلارِيْلي، مِيكالِي`,
  },
  s3: {
    en: `However, Nevertheless, On the other hand, Conversely, Yet`,
    ar: `غير ذلك، ومع ذلك، على الجانب الآخر، بالمقابل، يالكن`,
  },
  s4: { en: `Cause / Effect`, ar: `السبب و النتيجة` },
  s5: {
    en: `Therefore, Consequently, As a result, Thus, Hence`,
    ar: `لذلك، كونsequenceً، نتيجةً لذلك، وهكذا، لذا`,
  },
  s6: {
    en: `Ultimately, In conclusion, To summarise, Above all, Fundamentally`,
    ar: `في النهاية، بختام الأمر، لتلخيص، أولاً وأخيراً، أساساً`,
  },
  s7: { en: `Three ways to fix a comma splice:`, ar: `ثلاث طرق لتصحيح تقسيم الفاصلة:` },
  s8: { en: `Use Active For`, ar: `` },
  s9: { en: `Clear, direct persuasive writing`, ar: `كتابة دعائية واضحة و DIRECT` },
  s10: { en: `Assigning blame or responsibility`, ar: `تحديد المسؤولية أو توجيه اللوم` },
  s12: { en: `Making arguments feel confident`, ar: `إجعل حججك تشعر بالثقة` },
  s13: { en: `Use Passive For`, ar: `استخدم الصيغة المبنية ( passive )` },
  s14: { en: `Emphasising the victim or result`, ar: `توكيد المجني عليه أو النتيجة` },
  s15: {
    en: `Formal or scientific tone`,
    ar: `لهجة فصحى أو علميةtone formal or scientifictón عالي أو علمي`,
  },
  s16: { en: `Deliberately concealing responsibility`, ar: `تعمد إخفاء المسؤولية` },
  s17: { en: `Creating distance or detachment`, ar: `خلق مسافة أو ت Detachment (التجرد)` },
  s18: {
    en: `Collective nouns (team, class, government):`,
    ar: `أسماء المجموعات (الفريق، الصف، الحكومة) :`,
  },
  s21: { en: `Always singular: &quot;Each of the students`, ar: `كل طالب من الطلاب` },
  s22: {
    en: `Compound subjects with &quot;or&quot; / &quot;nor&quot;:`,
    ar: `Subjects مركّبين بـ "أو" / "نور":`,
  },
  s23: {
    en: `Verb agrees with the nearest subject: &quot;Neither the teacher nor the students`,
    ar: `&quot; neither the teacher nor the students &quot; يتفق الفعل مع أقرب مושא، يعني لو كان التلاميذ هم الأقرب يكون الفعل مرفوعاً للمذكرين كمثال.`,
  },
  s24: { en: `Phrases between subject and verb:`, ar: `الفصل بين الم.Subject والVerbverb` },
  s25: {
    en: `Ignore the phrase: &quot;The box of chocolates`,
    ar: `.IGNORE THE PHRASE: "The box of chocolates`,
  },
  s26: { en: `Singular possession:`, ar: `الملكية الفردية:` },
  s27: { en: `Plural possession (regular plural):`, ar: `ملاك الجمع العادي:` },
  s28: {
    en: `Plural possession (irregular plural):`,
    ar: `الملكية المتبادلة (المثنى والجمع غير المنتظم)`,
  },
  s29: { en: `Names ending in S:`, ar: `الأسماء التي تنتهي bằng سين:` },
  s30: {
    en: `Both &quot;James&apos;s book&quot; and &quot;James&apos; book&quot; are acceptable. Be consistent.`,
    ar: `كلا &quot;كتاب جيمس&quot; و &quot;كتاب جيمس&quot; هما مقبولان. كوني_consistent.`,
  },
  s32: { en: `Punctuation goes`, ar: `النقاط والفاصلة تروح` },
  s33: { en: `If speech comes`, ar: `إذا جاءت الكلام` },
  s35: { en: `Level 1 (1-4 marks) -- Limited`, ar: `مستوى 1 (من 1 إلى 4 نقاط) -- محدود` },
  s36: { en: `Simple vocabulary; limited sentence forms`, ar: `لغة سهلة؛ صيغ جملية محدودة` },
  s39: { en: `Level 2 (5-8 marks) -- Some Success`, ar: `مستوى 2 (5-8 نقاط) -- بعض النجاح` },
  s40: {
    en: `Some varied vocabulary; some sentence variety`,
    ar: `بعض الكلمات المتنوعة؛ بعض تنوع الجمل`,
  },
  s41: {
    en: `Spelling generally accurate (including some complex words)`,
    ar: `ال spelings معمولاً دقيقة (شاملة بعض الكلمات المعقدة)`,
  },
  s43: { en: `Level 3 (9-12 marks) -- Consistent`, ar: `مستوى 3 (9-12 نقاط) -- مستمر` },
  s44: {
    en: `Increasingly sophisticated vocabulary; variety of sentence forms for effect`,
    ar: `لغة متنوعة ومعقدة؛ تنوع في أشكال الجمل لخلق تأثير`,
  },
  s45: {
    en: `Spelling generally accurate, including complex and irregular words`,
    ar: ``,
  },
  s46: {
    en: `Range of punctuation used with general accuracy`,
    ar: ``,
  },
  s47: { en: `Level 4 (13-16 marks) -- Compelling`, ar: `مستوى 4 (13-16 نقاط) -- مثير` },
  s49: {
    en: `Full range of sentence forms used effectively for purpose`,
    ar: `استخدام أنواع مختلفة من أشكال الجمل بكفاءة لتحقيق الغرض`,
  },
  s50: {
    en: `Spelling consistently accurate throughout, including ambitious vocabulary`,
    ar: `الكتابة دقيقة في الإملاء بشكل مستمر، بما في ذلك المفردات الطموحة`,
  },
  s51: {
    en: `Wide range of punctuation used accurately and deliberately for effect`,
    ar: `مدى واسع من علامات الترقيم يستخدم بدقة ولأجل أثر متعمد`,
  },
  s52: { en: `Ambitious vocabulary:`, ar: `لغة طموحة:` },
  s53: { en: `Sentence variety for effect:`, ar: `التغير في أنواع الجمل لخلق التأثير:` },
  s55: { en: `Consistent accuracy:`, ar: `دقة_consistent` },
  s56: { en: `Paragraphing for effect:`, ar: `تقطيع الفقرات لخلق تأثير` },
  s57: { en: `Simple Sentence`, ar: `جملة سهلة` },
  s58: { en: `Compound Sentence`, ar: `جملة مركبة` },
  s59: { en: `Complex Sentence`, ar: `جملة معقدة` },
  s60: { en: `Minor Sentence / Fragment`, ar: `جملة قصيرة / جزء من الجملة` },
  s61: { en: `Semicolons ( ; )`, ar: `نقطة وفاصلة (؛)` },
  s62: { en: `Colons ( : )`, ar: `نقاط ما بعد الكolon ( : )` },
  s63: { en: `Dashes ( -- )`, ar: `الخطوط (-)` },
  s64: { en: `Ellipsis ( ... )`, ar: `ت pomiطة ( ...)` },
  s65: { en: `Exclamation Marks ( ! )`, ar: `علامات الاستثارة (!)` },
  s66: { en: `Brackets / Parentheses ( )`, ar: `قوسات (واحدة داخلية)` },
  s67: { en: `Topic Sentences`, ar: `عبارات المواضيع` },
  s68: { en: `Discourse Markers`, ar: `علامات للمناظرة` },
  s71: { en: `Affect / Effect`, ar: `أثر / نتيجة` },
  s72: { en: `Who / Whom`, ar: `من / إلى من` },
  s73: { en: `Less / Fewer`, ar: `أقل / أقل من` },
  s74: { en: `Comma Splices`, ar: `ربط الجمل الخطأ باستخدام الفاصلة` },
  s75: { en: `Active Voice`, ar: `صوت النشط` },
  s76: { en: `Passive Voice`, ar: `صوت الفاعل السلبي` },
  s77: { en: `When to Use Each`, ar: `متى استخدم كل واحد منهم` },
  s78: { en: `Past Tense`, ar: `ماضي التذكير` },
  s79: { en: `Present Tense`, ar: `presente tense (في الحين)` },
  s80: { en: `Common Tense Errors`, ar: `أخطاء الشكل الزمني الشائعة` },
  s81: { en: `Deliberate Tense Shifts`, ar: `تحويلات متعمدة في التصريف الزمني` },
  s82: { en: `Basic Rule`, ar: `قاعدة أساسية` },
  s83: { en: `Tricky Cases`, ar: `حالات معقدة` },
  s84: { en: `Apostrophes for Contraction`, ar: `Apostrophات للاختصار` },
  s86: { en: `The Greengrocer`, ar: `` },
  s87: { en: `Correctly Punctuated Example`, ar: `مثال صحيح الترقيم` },
  s88: { en: `What Markers Are Looking For`, ar: `ما هو اللي بيسألو عنه المصححون` },
  s89: { en: `How to Move from Level 3 to Level 4`, ar: `كيف تنتقل من مستوى 3 إلى مستوى 4` },
  s90: {
    en: `Quick Checklist Before Submitting Your Exam Response`,
    ar: `قائمة مراجعة سريعة قبل تقديم ردك في الامتحان`,
  },
}
