/**
 * paper-1 set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Exam Structure`, ar: `هيكل الامتحان` },
  s1: { en: `Key Themes`, ar: `المواضيع الرئيسية` },
  s2: { en: `Key Characters`, ar: `الشخصيات الرئيسية` },
  s4: { en: `Plan 3-4 main points`, ar: `اكتب 3 إلى 4 نقاط رئيسية` },
  s5: {
    en: `Embed quotations`,
    ar: `ضمن الاستشهاداتdirectly in the text استشهد بالاقتباسات من النص الأدبي دون تغيير.`,
  },
  s6: { en: `Analyse language and dramatic techniques`, ar: `تحليل التقنيات اللغوية والدرامية` },
  s8: { en: `Write accurately`, ar: `اكتب بدقة` },
  s9: { en: `Choose your question wisely`, ar: `اختار سؤالك بحكمة` },
  s10: {
    en: `Structure your response`,
    ar: `.Structure روح تدوّر organize ردّر thoughts أفكار you على mind عقلك قبل قبل starting شروع writing الكتابة. Write اكتب in points نقاط or paragraphs فقرات. Use استخدم full sentences جمل كاملة. Be كن clear واضحة and concise موجزة. Stick التزم to the`,
  },
  s11: { en: `Use the writer&apos;s name`, ar: `استخدم اسم الكاتب` },
  s12: { en: `Explore the writer&apos;s purpose`, ar: `استكشف رغبة الكاتب` },
  s13: { en: `Cover the whole text`, ar: `سوي كذا لتغطي النص كله` },
  s14: { en: `Timing Guide`, ar: `دليل التوقيت` },
  s15: { en: `Section A: Shakespeare`, ar: `SECTION A: شكسبير` },
  s16: {
    en: `Spend 5 mins planning. Write 4-5 paragraphs.`,
    ar: `خلي بالك 5 دقائق في التخطيط. اكتب 4 إلى 5 فقرات.`,
  },
  s17: { en: `Section B: Post-1914`, ar: `القسم ب: بعد عام 1914` },
}
