import { describe, it, expect } from 'vitest'
import { findCommentary } from '../../scripts/find-translator-commentary.mjs'

/**
 * The Arabic pages were publishing the translation model's own commentary.
 *
 * FOUND 19 September 2026. The bilingual content.ts files were produced by a
 * local Ollama run, and where the model was unsure it did what chat models do:
 * it explained itself, in English, into the `ar` field. That field is rendered.
 *
 * Live on /ar/analysis/ai-feedback-head-to-head, in the middle of a feature
 * description a Gulf visitor was reading:
 *
 *   "(Note: There seems to be a mix-up in the last part of the translation due
 *    to an untranslated phrase "academic register". Here is the corrected
 *    version without commentary or preamble as per your instructions.)"
 *
 * 63 entries across 33 files. Several also carried Russian, Thai, Vietnamese,
 * French or Spanish where the Arabic should have been - "параграف 3",
 * "โครงสร้างห้าส่วน", "أدعم كل نقطة bằng أدلة من". All 63 were rewritten by hand;
 * scripts/repair-translator-commentary.mjs holds the replacements.
 *
 * WHY A TEST RATHER THAN A ONE-OFF FIX. These files are regenerated by a script
 * outside this repository, so the next run puts the commentary straight back.
 * Nothing in the build reads Arabic, and nobody on the team does either, so the
 * only thing standing between a regenerated file and a live page is this.
 *
 * WHAT IT DOES NOT CHECK. Whether fluent Arabic says the right thing. The wider
 * audit next to it - scripts/audit-machine-translated-content.mjs - still counts
 * 514 strings with Latin words spliced in and 150 that stop mid-sentence. Those
 * need a proper retranslation, which is a decision about budget and register
 * rather than a defect to patch, and they are recorded in the work log for
 * Calum. Zero here means the translator is no longer talking to the reader, not
 * that the translation is good.
 */

describe('the bilingual content files are actually being read', () => {
  it('scans the whole corpus, not an empty directory', () => {
    // The vacuity guard. Every assertion below passes on a walker that matched
    // nothing, which is exactly how this check would go quiet if the content
    // files were ever moved or renamed.
    const { scanned } = findCommentary()
    expect(scanned).toBeGreaterThan(3500)
  })
})

describe('no page publishes the translation model talking about itself', () => {
  it('finds no translator commentary in any ar field', () => {
    const { hits } = findCommentary()
    const named = hits.map(
      (h: { file: string; key: string; ar: string }) =>
        `${h.file}::${h.key} - ${h.ar.slice(0, 60)}`,
    )
    expect(
      named,
      'a regenerated content.ts has put the model commentary back. Rewrite the Arabic by hand; do not strip the note and keep the rest, because the rest is usually in three alphabets.',
    ).toEqual([])
  })
})
