import { describe, it, expect } from 'vitest'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

/**
 * A four-month-old index was being served to AI crawlers, and it pointed them
 * at pages we had told Google not to index.
 *
 * THE DEFECT (20 September 2026). `public/llms-full.txt` said "Last generated:
 * 2026-05-23. 877 public pages indexed" and called itself the full page index.
 * Nothing in the build regenerated it: `prebuild` runs
 * `scripts/generate-llms-txt.mjs`, and that script writes `public/llms.txt` and
 * only that. The other file was written once, by hand or by something since
 * deleted, and then drifted for four months while continuing to be served.
 *
 * Measured, not assumed. All 877 of its URLs were fetched:
 *
 *   - 0 are dead, so nothing would have shown up as an error
 *   - 58 redirect, 45 of them `.ar` filename artefacts (/blog/foo.ar) that were
 *     never URLs - whatever produced the file read MDX filenames, not routes
 *   - 213 current routes are missing from it, including every /a-level page
 *   - three of the posts it lists are held back as drafts and serve
 *     `<meta name="robots" content="noindex">`
 *
 * That last one is the reason this is not merely untidy. The draft posts were
 * pulled from the index on 19 September because they were not fit to publish.
 * llms.txt correctly excludes them. llms-full.txt handed ChatGPT, Claude and
 * Perplexity the links anyway.
 *
 * THE FIX. The file is deleted and /llms-full.txt redirects permanently to
 * /llms.txt, which is regenerated on every build from the same policy-filtered
 * route list the sitemap uses. A genuine llms-full.txt under the llmstxt.org
 * convention carries full page CONTENT, which on this site means handing
 * copyrighted set-text commentary to AI crawlers wholesale. That is a rights
 * decision for the company, not something to generate quietly.
 *
 * THE RULE THIS PINS is deliberately about the whole `public/` directory rather
 * than about one filename. The failure was not "llms-full.txt was stale", it
 * was "a hand-kept file was being served as though the build maintained it".
 * A second such file would repeat it exactly, so any new one has to be argued
 * for here.
 *
 * MUTATIONS RUN, each verified to have altered the tree first: restoring
 * public/llms-full.txt fails 2 of the 6; removing the redirect fails; removing
 * generate-llms-txt.mjs from the prebuild chain fails; and putting a $comment
 * field back inside a redirect rule fails, which is the one a test would
 * normally miss because only the build rejects it.
 */

const PKG = JSON.parse(readFileSync('package.json', 'utf8'))
const REDIRECTS = JSON.parse(readFileSync('src/lib/seo/route-redirects.json', 'utf8'))

/**
 * Text files under public/ that are served to crawlers and are allowed to be
 * checked in by hand. Anything that lists site URLs must be generated instead.
 */
const HAND_KEPT_ALLOWED = new Set(['.well-known/security.txt'])

function textFiles(dir: string, base = ''): string[] {
  const out: string[] = []
  for (const name of readdirSync(join('public', dir), { withFileTypes: true })) {
    const rel = base ? `${base}/${name.name}` : name.name
    if (name.isDirectory()) out.push(...textFiles(join(dir, name.name), rel))
    else if (/\.(txt|md)$/.test(name.name)) out.push(rel)
  }
  return out
}

describe('what we serve to AI crawlers is generated, not kept by hand', () => {
  it('reads a real public directory', () => {
    // Vacuity guard: an empty read passes the sweep below.
    expect(readdirSync('public').length).toBeGreaterThan(5)
    expect(PKG.scripts.prebuild).toBeTruthy()
  })

  it('llms.txt is written by the build', () => {
    expect(PKG.scripts.prebuild).toContain('scripts/generate-llms-txt.mjs')
    expect(readFileSync('scripts/generate-llms-txt.mjs', 'utf8')).toContain(
      "writeFileSync('public/llms.txt'",
    )
  })

  it('the stale llms-full.txt is gone', () => {
    expect(
      existsSync('public/llms-full.txt'),
      'This file is not regenerated by anything. If it comes back it must be ' +
        'written by the build, from the same route list as llms.txt.',
    ).toBe(false)
  })

  it('and its URL still answers, pointing at the index that is current', () => {
    // The counterweight. Deleting the file and leaving the URL dead would
    // satisfy the assertion above and lose four months of crawler familiarity
    // with that address for nothing.
    const rule = REDIRECTS.redirects.find((r: { source: string }) => r.source === '/llms-full.txt')
    expect(rule, '/llms-full.txt has no redirect').toBeTruthy()
    expect(rule.destination).toBe('/llms.txt')
    expect(rule.permanent).toBe(true)
  })

  it('no redirect rule carries a field Next will reject', () => {
    // Next validates every entry and fails the BUILD on an unknown field, which
    // is how the explanation for the rule above ended up in a $notes map rather
    // than inside the rule. Tests would not have caught that; the build would.
    for (const rule of REDIRECTS.redirects) {
      expect(Object.keys(rule).sort()).toEqual(['destination', 'permanent', 'source'])
    }
  })

  it('and no other hand-kept file under public lists site URLs', () => {
    const offenders = textFiles('.')
      .filter((f) => !HAND_KEPT_ALLOWED.has(f))
      .filter((f) => {
        const body = readFileSync(join('public', f), 'utf8')
        return (body.match(/https:\/\/theenglishhub\.app/g) || []).length > 20
      })
      .filter((f) => !PKG.scripts.prebuild.includes(f.replace(/\.txt$/, '')))
      .filter((f) => f !== 'llms.txt')

    expect(
      offenders,
      'A checked-in file that lists site URLs drifts the moment a route ' +
        'changes, and nothing fails when it does. Generate it in the prebuild ' +
        'chain, or do not serve it.',
    ).toEqual([])
  })
})
