/**
 * paper-2 set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Time Guide`, ar: `دليل الوقت` },
  s1: { en: `Shakespeare (extract-based + essay)`, ar: `شكسبير (مبنية على الاستخراجات + مقال)` },
  s2: { en: `Poetry anthology (comparison)`, ar: `مختارات الشعر (المقارنة)` },
  s3: { en: `Unseen poetry`, ar: `شعر غير المعهود` },
  s4: { en: `Key information`, ar: `معلومات رئيسية` },
  s5: { en: `Romeo and Juliet`, ar: `روميو و جولييت` },
  s6: { en: `The Merchant of Venice`, ar: `الMerchant of Venice` },
  s7: { en: `Much Ado About Nothing`, ar: `مUCH ADو About نOTHING` },
  s8: { en: `The Tempest`, ar: `العاصفة` },
  s9: { en: `Analyse the extract in detail`, ar: `حلل الجزء المذكور تفصيلاً` },
  s10: { en: `Explore the wider play`, ar: `دورو في باقي المسرحية` },
  s12: { en: `Iambic Pentameter`, ar: `متتة خمسية` },
  s13: { en: `Soliloquies and Asides`, ar: `منولوجات وهمسات` },
  s14: { en: `Dramatic Irony`, ar: `حالة الحيرة الدرامية` },
  s15: { en: `Paragraph 1: First point of comparison`, ar: `نقطة المقارنة الأولى` },
  s16: { en: `Paragraph 2: Second point of comparison`, ar: `نقطة المقارنة الثانية` },
  s17: { en: `Paragraph 3: Third point of comparison`, ar: `نقطة المقارنة الثالثة` },
  s18: { en: `Read the poem through twice`, ar: `اقرأ القصيدة مرتين` },
  s19: { en: `Identify the subject and theme`, ar: `اعرف الموضوع وال Thema` },
  s21: { en: `Annotate the poem`, ar: `اannotate الشِّعر` },
  s23: {
    en: `Plan your response`,
    ar: `خطط ردهتك شلون ما تحتج لدوّر المعلومات أو تراجعها بعد كذا. أبغىك تركز على إجاباتك تكون واضحة وشافية، وإحنا في The English Hub بنساعدك تكون مستعد جيد لكل أسئلة الاختبار. الح`,
  },
  s24: { en: `Free verse`, ar: `شعر حر` },
  s25: { en: `Rhyme scheme`, ar: `نمط التفعيلة` },
}
