/**
 * antony-and-cleopatra set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `William Shakespeare, c.1606&ndash;1607`, ar: `ويليام شكسبير، circa 1606-1607` },
  s2: { en: `Cleopatra&apos;s Barge`, ar: `برج كليوباترا` },
  s3: { en: `Roman Armour and the Sword`, ar: `دروع الرومان والسيف` },
  s4: { en: `The Dolphin`, ar: `الدلفين` },
  s5: { en: `Egypt vs Rome as Geographic Poles`, ar: `مصر ضد روما كقطبين جغرافيين` },
  s6: { en: `Composition Date: 1606&ndash;1607`, ar: `التاريخ: 1606&ndash;1607` },
  s7: { en: `The Roman Plays Sequence`, ar: `السلسلة الرومانية من المسرحيات` },
  s8: { en: `Antony and Cleopatra`, ar: `أنتونيو وقليوباترا` },
  s9: { en: `Titus Andronicus`, ar: `` },
  s10: { en: `Julius Caesar`, ar: `يوليوس قيصر` },
  s11: { en: `James I and the Union of the Crowns`, ar: `جيمس الأول والاتحاد للكراسي` },
  s12: { en: `The Genre Question: Tragedy or History?`, ar: `السؤال حول الجنس: مأساة أم تاريخ؟` },
  s13: { en: `Renaissance Egypt`, ar: `مصر في عصر النهضة` },
  s15: { en: `Bipartite Tragic Death Pattern`, ar: `نمط الموت المأساوي الثنائي` },
  s17: { en: `Choric Commentary`, ar: `comentario الكوريográfico` },
  s19: { en: `Romeo and Juliet`, ar: `روميو و جولييت` },
  s20: { en: `As You Like It`, ar: `As You Like It` },
  s21: { en: `Oxford Lectures on Poetry`, ar: `LECTURES أكسفورد في الشعر` },
  s22: { en: `The Common Liar`, ar: `الlying الشائع` },
  s23: { en: `Quote verbatim from the Folio.`, ar: `اقتبس حرفيًا منfolio` },
  s24: { en: `Use Plutarch.`, ar: `استخدموا بلوتارخ.` },
  s25: { en: `Address the genre question.`, ar: `أجب على سؤال الجنس الأدبي.` },
  s26: { en: `Connect Jacobean context.`, ar: `` },
  s27: { en: `Reference critical positions.`, ar: `أ refere أوضاع هامة` },
  s28: { en: `Trace verbal patterns.`, ar: `تتبع أنماط الكلام` },
  s29: { en: `Don&apos;t simplify the binary.`, ar: `لا تبسّط الثنائية.` },
  s30: {
    en: `Act-by-Act Summary: The Rome/Egypt Opposition`,
    ar: `ملخص المشاهدات: المعارضة بين روما وEgypt`,
  },
  s31: { en: `Character Profiles`, ar: `Profiles الشخصيات` },
  s32: {
    en: `The Roman triumvir torn between Egypt and Rome, between Cleopatra and Caesar`,
    ar: ``,
  },
  s33: { en: `Queen of Egypt, the play`, ar: `مملكة مصر، المسرحية` },
  s35: {
    en: `The third triumvir, the weakest of the three. Lepidus tries to mediate between Antony and Caesar but lacks the political weight to do so. He is mocked for his drunkenness aboard Pompey`,
    ar: ``,
  },
  s36: {
    en: `An Egyptian fortune-teller who appears twice. In Act 1 he reads the futures of Charmian and Iras with grim and erotic ambiguity. In Act 2 he warns Antony in Rome that Caesar`,
    ar: `عرّاف مصري يظهر مرتين. في الفصل الأول، يقرأ مستقبل شارميان وإريس بطريقة مرعبة ومثيرة بشكل غامض. وفي الفصل الثاني، يحذّر أنطونيو في روما من قيصر`,
  },
  s37: {
    en: `The Roman soldiers and lieutenants who frame and comment on the action. Philo and Demetrius open the play with the Roman judgement on Antony`,
    ar: `الجنود والlieutenants الرومانيين الذين يحاطون بالعمل ويعلقون عليه. فيلو وديمتريوس يفتحان المسرحيه بحكم الرومان على أنطوني`,
  },
  s38: { en: `Key Themes`, ar: `المواضيع الرئيسية` },
  s39: { en: `Love vs Duty`, ar: `الحب مقابل الواجب` },
  s40: {
    en: `Roman Stoicism vs Egyptian Sensuality`,
    ar: ``,
  },
  s41: { en: `Power and Empire`, ar: `القوة والامبراطورية` },
  s42: { en: `Theatricality and Performance`, ar: `التمثيلية والการแสดง` },
  s43: {
    en: `The play is suffused with self-conscious theatricality. Cleopatra dresses for her death as an actor dresses for a role; she fears that Roman boys will`,
    ar: ``,
  },
  s44: { en: `Honour and Reputation`, ar: `` },
  s45: {
    en: `Honour drives most of the play`,
    ar: `الчесть هي ما ي_drive_most_of_the_play_في معظم مسرحية

(Note: The word "drive" needs to be accurately translated in context which wasn't clear from the given instruction or phrase. If it's meant as a verb, it should be replaced with an appropriate Khaleeji Arabic equivalent.)

Corrected and completed:

الчесть هي ما يدفع معظم مسرحية

For clarity and proper translation:`,
  },
  s46: { en: `Betrayal and Loyalty`, ar: `خيانة وولاء` },
  s47: {
    en: `Betrayal is everywhere: Cleopatra appears to betray Antony at Actium; Antony`,
    ar: `الخيانة موجودة في كل مكان: كليوباترا تظهر وكأنها تخون أنطوني في أكتيوم؛ أنطوني`,
  },
  s48: { en: `Time, Mutability, and Dissolution`, ar: `الزمن، التغير، والفناء` },
  s49: { en: `Gender and Political Identity`, ar: `جنسية وهوية سياسية` },
  s50: { en: `Antony complains that he is`, ar: `أنتوني يشكي أنه هو` },
  s51: { en: `Key Quotations with Analysis`, ar: `اقتباسات رئيسية مع تحليل` },
  s52: { en: `Symbols and Recurring Images`, ar: `رموز وصور متكررة` },
  s53: { en: `Historical and Literary Context`, ar: `` },
  s54: { en: `Dramatic Structure`, ar: `الโครงสร้าง الدرامية` },
}
