/**
 * poetry set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Set-text notice`, ar: `تنبيه النص المحدد` },
  s1: { en: `Songs of Ourselves`, ar: `أناشيد أنفسنا` },
  s2: { en: `The Thought-Fox`, ar: `الفأرة فيthoughts` },
  s3: { en: `Hawk Roosting`, ar: `هوك روستינג` },
  s4: { en: `Cluster rights:`, ar: `حقوق التجمعات` },
  s5: { en: `What markers look for`, ar: `ما يبحثون عنه المARKERS` },
  s6: { en: `Close reading:`, ar: `قراءة دقيقة:` },
  s7: { en: `Writer&rsquo;s methods:`, ar: `طرق الكتابة:` },
  s8: {
    en: `Personal response:`,
    ar: `شخصيًا: شنو رأيك في هاد الموضوع؟ وايد مهتم بمعرفة أفكارك. الحين أبغى تدوّر بالكتاب وتراجع النصوص اللي قرأناها وتحللها. إذا حليت التمارين دي، راح`,
  },
  s9: { en: `Structuring a Comparison`, ar: `تنظيم المقارنة` },
  s10: { en: `What to Compare`, ar: `ما تقارن شلون؟` },
  s11: { en: `Tone and mood:`, ar: `تÓN و مOOD:` },
  s12: { en: `Form and structure:`, ar: `الشكل والبنية:` },
  s13: { en: `Language and imagery:`, ar: `لغة وصورmaktish` },
  s14: { en: `Speaker and perspective:`, ar: `المتحدث والمنظور من خلاله:` },
  s15: { en: `Example Comparison Pairings`, ar: `مثال للزوجات المقارنة` },
  s18: { en: `Power and nature:`, ar: `القوة والطبيعة:` },
  s20: { en: `Form &amp; Structure`, ar: `شكل وStructure` },
  s21: { en: `Detailed Analysis`, ar: `تحليل مفصل` },
  s22: { en: `Key Quotes`, ar: `المقاطع الرئيسية` },
}
