/**
 * woman-in-black set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Page rebuilt April 2026`, ar: `صفحة مrebuilt في أبريل 2026` },
  s1: { en: `The Woman in Black`, ar: `المرأة في الظلام` },
  s3: { en: `Isolation and Setting`, ar: `العزلة والمكان` },
  s4: { en: `Fear and the Supernatural`, ar: `` },
  s5: { en: `Grief and Revenge`, ar: `الحزن والثأر` },
  s6: { en: `Arthur&apos;s Transformation`, ar: `Transformation أرثر` },
  s7: { en: `The Gothic Tradition`, ar: `التراث góthic` },
  s8: { en: `The Turn of the Screw`, ar: `The_turn_of_the_screw` },
  s9: { en: `The Role of Women`, ar: `دور المرأة` },
  s10: {
    en: `Rationalism vs the Supernatural`,
    ar: `العقلانية مقابلsupernatural

(Note: The word "supernatural" is kept in English as it's a specific term that may not have an exact equivalent or widely recognized translation in Khaleeji Arabic.)`,
  },
  s12: {
    en: `Structure Your Essay`,
    ar: ``,
  },
  s13: { en: `Each paragraph:`, ar: `كل فقرة:` },
  s14: { en: `Key Techniques to Discuss`, ar: `التقنيات الرئيسية للنقاش عنها` },
  s15: { en: `First-person narration:`, ar: `سرد بصيغة المتكلم` },
  s16: { en: `Frame narrative:`, ar: `قصة داخل قصة` },
  s17: { en: `Pathetic fallacy:`, ar: `خيبات الخرافة` },
  s18: { en: `Sound imagery:`, ar: `صور صوتية:` },
  s19: { en: `Withholding information:`, ar: `إخفاء المعلومات:` },
  s20: { en: `Common Mistakes to Avoid`, ar: `أخطاء شائعة لتجنبها` },
  s21: { en: `Rights notice:`, ar: `حقوق الطبع والنشر:` },
  s22: { en: `Chapter-by-Chapter Plot Summary`, ar: `ملخص فصل تفصيلي للقصة` },
  s23: { en: `Character Profiles`, ar: `Profiles للشخصيات` },
  s24: { en: `Major Themes`, ar: `ال chủات الرئيسية` },
  s25: { en: `Key Moments and Structural Beats`, ar: `لحظات حاسمة وضربات بنائية` },
  s26: { en: `Practice Questions`, ar: `أسئلة ممارسة` },
}
