/**
 * anita-and-me set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s2: { en: `Setting and Frame`, ar: `الإعداد والрамكة` },
  s3: { en: `Anita and Me`, ar: `أنита وменي` },
  s4: { en: `On Identity and Lying`, ar: `حول الهوية والكذب` },
  s5: { en: `On Tollington`, ar: `تونلينغتون` },
  s6: { en: `On Race and Belonging`, ar: `في العرق والانتماء` },
  s7: { en: `On Sam Lowbridge`, ar: `عن سام لوبلدجيز` },
  s8: { en: `On Family and Hospitality`, ar: `حول العائلة والضيافة` },
  s9: { en: `On Nanima and Punjabi Heritage`, ar: `عن نانيمة والتراث الپنجابي` },
  s11: { en: `On Dual Identity`, ar: `عن الهوية المزدوجة` },
  s12: { en: `On Tollington as Place`, ar: `تollington كمكان` },
  s13: { en: `Meera Syal &mdash; Author Biography`, ar: `ميرا سياл &mdash; سيرة ذاتية للكاتبة` },
  s14: { en: `Goodness Gracious Me`, ar: `يا ربي ما هذا` },
  s15: { en: `Post-Powell Anti-Immigrant Politics`, ar: `politics المضادة للمهاجرين بعد باول` },
  s16: { en: `Punjabi Heritage and Partition`, ar: `heritage الپنجابي و تقسيم الحدث` },
  s17: { en: `British Asian Literature`, ar: `الآداب البريطانية الآسيوية` },
  s18: { en: `The Buddha of Suburbia`, ar: `بوذا الضواحي` },
  s19: { en: `Brick Lane`, ar: `بريك لين` },
  s20: { en: `White Teeth`, ar: `أسنان بيضاء` },
  s21: {
    en: `Genre &mdash; The Bildungsroman`,
    ar: `الجنس الأدبي &mdash; الرواية التعليمية (bildungsroman)`,
  },
  s22: { en: `To Kill a Mockingbird`, ar: `To Kill a Mockingbird` },
  s23: { en: `The 1990s of Publication`, ar: `العقد التسعيني من النشر` },
  s24: { en: `Exam Tips for Anita and Me`, ar: `نصائح للامتحانات لآنита وميني` },
  s26: { en: `Refer to Syal&apos;s methods explicitly.`, ar: `أ REFER TO أسلوب سياｌ صراحة.` },
  s27: { en: `Anchor context in 1972.`, ar: `anchoring the context in 1972` },
  s28: {
    en: `Short embedded quotation beats long block-quote.`,
    ar: `اقتباس موجز يتفوق على اقتباس طويل بلوك قوتيات.`,
  },
  s30: {
    en: `Address the whole novel.`,
    ar: `ا.address الكниجة كلها.بلاش تنسى جزء من القصة.اقرأ واكتشف التفاصيل اللي ماكانت واضحة قبل كذا.`,
  },
  s32: { en: `Nine years old at the novel`, ar: `تسعة سنوات في الرواية` },
  s33: {
    en: `Three years older than Meena, the magnetic`,
    ar: `ثلاث سنوات أكبر من مينا، المغناطيسي`,
  },
  s34: {
    en: `The village shopkeeper and chapel collector for missions to`,
    ar: `بائع القرية وجمعية الكنيسة لمissions`,
  },
  s35: {
    en: `Local teenage skinhead, briefly Anita`,
    ar: `Skinhead محلي في عمر المراهقة، كان اسمه آنيتا لفترة قصيرة`,
  },
  s36: { en: `Another village girl, part of Anita`, ar: `فتاة قرية أخرى، جزء من أنита` },
  s37: {
    en: `Identity and Belonging — British-Indian Dual Identity`,
    ar: `الهوية والانتماء — الهوية الثنائية البريطانية الهندية`,
  },
  s39: {
    en: `Race and Racism in 1970s Britain`,
    ar: `عنصرية وрасизм فيBritain في السبعينيات من القرن العشرين`,
  },
  s40: {
    en: `The novel is set in the immediate aftermath of Enoch Powell`,
    ar: `الرواية مSets in the immediate aftermath of Enoch Powellhlenة قصيرة من بعد حديثاً بعد إينوك باولhlen`,
  },
  s42: {
    en: `Family and Cultural Heritage`,
    ar: `العائلة والتراث cultural heritage م-cultural heritage-ultural heritage-ultural heritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageheritageherit`,
  },
  s43: {
    en: `The Kumar household, with its rotating cast of`,
    ar: `عائلة كومار، مع طاقمها الدوار من`,
  },
  s44: { en: `Friendship and Loss of Innocence`, ar: `صداقة وفقدان البراءة` },
  s45: { en: `Anita is Meena`, ar: `أنита هي مينا` },
  s46: { en: `Storytelling and Memory`, ar: `رواية القصص والذاكرة` },
  s48: { en: `Key Quotations`, ar: `اقتباسات رئيسية` },
  s49: {
    en: `Symbols and Motifs`,
    ar: `رموز وotive (please note there seems to be a typo in "motif", it should just be رموز وعلامات without the extra word)`,
  },
  s50: { en: `Essay Planning for Common Questions`, ar: `hoạchtlة المقال لأسئلة م-common` },
  s51: { en: `Practice Questions`, ar: `أسئلة ممارسة` },
}
