/**
 * grade-boundaries set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Grade Boundaries`, ar: `حدود الدرجات` },
  s1: { en: `Important note`, ar: `ملاحظة مهمة` },
  s2: { en: `Extended Tier`, ar: `المستوى الممدود` },
  s4: { en: `Grades available:`, ar: `الدرجات المتاحة:` },
  s5: { en: `Maximum combined mark:`, ar: `النقاط máxima المجمعة:` },
  s6: {
    en: `More challenging reading passages and questions`,
    ar: `م.passages وايد تحديّة مع القراءة والأسئلةPropertyParams{}`,
  },
  s8: {
    en: `Most international schools enter students for Extended`,
    ar: `أغلب المدارس الدولية تسجل طلابها في الامتداد`,
  },
  s9: {
    en: `Paper 1 (Reading) + Paper 3 (Directed Writing &amp; Composition)`,
    ar: `ورقية 1 (القراءة) + ورقة 3 (الكتابة الموجهة والتأليف)`,
  },
  s11: { en: `Maximum achievable grade is C`, ar: `الدرجة القصوى هي جCCCCCC (Grade C)` },
  s12: {
    en: `Suitable for students who find the Extended paper too demanding`,
    ar: `مناسب للي ما يحبسون الورق الممتد صعب عليهم`,
  },
  s13: {
    en: `Exceptional performance across all components`,
    ar: `أداء استثنائي في جميع المكونات`,
  },
  s14: {
    en: `Strong, confident responses with good analysis`,
    ar: `ردود فعل قوية وواثقة مع تحليل جيد`,
  },
  s15: { en: `Good understanding with some strong analysis`, ar: `فهما جيد مع تحليل قوي` },
  s16: { en: `Sound understanding of the basics`, ar: `` },
  s18: {
    en: `Exceptional &mdash; the very highest level of achievement`,
    ar: `استثنائي &mdash; المستوى الأعلى من الإنجاز`,
  },
  s19: { en: `Low A* / High A`, ar: `أ*A / ب*A` },
  s20: {
    en: `Outstanding performance with sophisticated analysis and writing`,
    ar: `أداء متميز مع تحليل وكتابة متطور`,
  },
  s21: {
    en: `Very strong performance across all components`,
    ar: `أداء وايد قوي في جميع المكونات`,
  },
  s23: { en: `Low B / High C`, ar: `دوبلاي ب / هاي سي` },
  s24: {
    en: `Above average &mdash; solid understanding with some analysis`,
    ar: `فوق المعدل - فهم جيد مع بعض التحليلات`,
  },
  s25: {
    en: `Standard pass &mdash; demonstrates basic competence`,
    ar: `يDemonstrate القدرة الأساسية والمقبوليةitori ي(show basic competence and proficiency)itori`,
  },
  s26: {
    en: `Below average &mdash; some understanding but inconsistent`,
    ar: `دون المعدل - بعض الفهم لكن غير مستقر`,
  },
  s27: { en: `Limited understanding and weak expression`, ar: `فهما محدودة وتعبير ضعيف` },
  s28: { en: `Minimal evidence of understanding`, ar: `أدلّة قليلة على الفهم` },
  s29: { en: `Grade A* (9) &mdash; Exceptional`, ar: `درجة أستاذية (9) - استثنائية` },
  s30: { en: `Reading (Paper 2 / Paper 1):`, ar: `قراءة (الورقة 2 / الورقة 1) :` },
  s31: {
    en: `Perceptive, original analysis that goes beyond the surface meaning of the text.`,
    ar: `تحليل ذكي ومبتكر يتجاوز المعنى السطحي للنص.`,
  },
  s32: {
    en: `Precisely selected quotations seamlessly embedded and explored in detail.`,
    ar: `اقتباسات مختارة بدقة ودمجها واستكشافها بالتفصيل`,
  },
  s33: {
    en: `Confident discussion of how language choices create specific effects on the reader.`,
    ar: `حوار ثقة حول كيفية اختيار اللغة لإREATE تأثيرات خاصة على القارئ. 

(_correction applied_)
حوار ثقة حول كيفية اختيار اللغة لخلق تأثيرات خاصة على القارئ.`,
  },
  s35: {
    en: `Sophisticated understanding of how writers use structure, tone, and register for effect.`,
    ar: ``,
  },
  s36: { en: `Writing (Paper 4 / Paper 3):`, ar: `الكتابة (ورقة الامتحان 4 / ورقة الامتحان 3)` },
  s37: {
    en: `Directed writing that is entirely convincing in its adopted voice and format, with ideas that go beyond the passage.`,
    ar: `كتابة موجهة تكون مقنعة تمامًا في الصوت والشكل المتبني، مع أفكار تتجاوز ما في النص.`,
  },
  s39: {
    en: `Extensive, ambitious vocabulary used precisely and naturally &mdash; every word earns its place.`,
    ar: `لغة واسعة وأماني طموحة مستخدمة بدقة وطبيعية &mdash; كل كلمة تستحق مكانها.`,
  },
  s40: {
    en: `Varied, inventive structural choices that shape meaning (e.g., cyclical structure, deliberate shifts in pace).`,
    ar: `اختيارات بنائية متنوعة ومبتكرة التي تشكّل المعنى (مثل الهيكل الدوري، والتغييرات المقصودة في وتيرة السرد)`,
  },
  s42: {
    en: `Grades A&ndash;B (7&ndash;8) &mdash; Strong`,
    ar: `المستوى أ إلى ب (7 إلى 8) &mdash; قوي`,
  },
  s43: {
    en: `Detailed, well-developed analysis with clear explanations of language effects.`,
    ar: `تحليل مفصل ومتطور مع تفسيرات واضحة لتأثيرات اللغة.`,
  },
  s44: {
    en: `Well-chosen quotations with thorough exploration of connotations.`,
    ar: `اقتباسات مختارة بدقة مع استكشاف دقيق للايحاءات.`,
  },
  s46: {
    en: `Some exploration of why writers make specific choices and how techniques work together.`,
    ar: `بعض التحقيق في سبب اختيار الكتاب لخيارات محددة وكيف تعمل التقنيات معًا.`,
  },
  s47: {
    en: `Engaging, well-crafted writing with a clear sense of purpose and audience.`,
    ar: `كتابة جذابة ومصاغة بشكل جيد مع حس واضح بالغرض والجمهور.`,
  },
  s48: {
    en: `Increasingly sophisticated vocabulary and phrasing used naturally.`,
    ar: `لغة وتعبيرات متطوران يستخدمان بطبيعة الحال بشكل طبيعيmaktbCrLf`,
  },
  s49: {
    en: `Effective structural features that contribute to the overall effect.`,
    ar: `مميزات بنائية فعالة تساهم في التأثير العام.`,
  },
  s50: {
    en: `Wide range of sentence structures used for effect.`,
    ar: `مدى واسع من بنية الجمل يستخدم لتحقيق التأثير.`,
  },
  s52: {
    en: `Grades C&ndash;D (4&ndash;5) &mdash; Competent`,
    ar: `المستوى الـC إلى D (4 إلى 5) &mdash; كفوء`,
  },
  s53: {
    en: `Some understanding of language effects, but explanations may be thin or general.`,
    ar: `بعض الفهم لتأثيرات اللغة، لكن التفسيرات قد تكون ضعيفة أو شاملة.`,
  },
  s54: {
    en: `Relevant quotations selected, though not always fully explored.`,
    ar: `اقتباسات مختارة ذات صلة، رغم أنها لم تتم استكشافها بالكامل دائمًا.`,
  },
  s56: {
    en: `May identify techniques without fully explaining their effect (feature-spotting).`,
    ar: `قد ت indentify التقنيات دون شرح تأثيرها بشكل كامل (ملاحظة سطحية).`,
  },
  s57: {
    en: `Writing communicates with some clarity but may drift or lose focus in places.`,
    ar: `الكتابة تتواصل مع بعض الوضوح لكنها قد تتراخى أو تخسر التركيز في بعض الأماكن.`,
  },
  s58: {
    en: `Some attempts at vocabulary for effect, though choices may lack precision.`,
    ar: `بعض المحاولات لاستخدام القاموس للتأثير، رغم أن الاختيارات قد تفتقر إلى الدقة.`,
  },
  s59: {
    en: `Basic structural features present (paragraphs, some variety in openings).`,
    ar: `مميزات بنائية أساسية موجودة (فقرات، بعض التغير في طريقة البدء).`,
  },
  s60: {
    en: `Sentence demarcation mostly secure but some comma splicing or run-on sentences.`,
    ar: `التقسيم النحوي للجملة آمن بشكل كبير ولكن هناك بعض التراكب في استخدام الفواصل أو الجمل الطويلة المفرطة.`,
  },
  s62: {
    en: `Grades E&ndash;F (2&ndash;3) &mdash; Developing`,
    ar: `المستوى دوّر و الروشحة (2-3) - قيد التطور`,
  },
  s63: {
    en: `Simple comments on language with limited or no analysis of effect.`,
    ar: `تعليقات سهلة حول اللغة مع تحليل محدود أو بدون تحليل لتأثيرها.`,
  },
  s64: {
    en: `References that tend to paraphrase rather than quote selectively.`,
    ar: `مراجع تميل إلى التلخيص بدلاً من الاقتباس بانتقاء شديد`,
  },
  s66: {
    en: `May retell the text rather than analyse or evaluate it.`,
    ar: `يمكن إعادة كتابة النص بدلاً من تحليله أو تقديره.`,
  },
  s67: { en: `Simple ideas with limited development.`, ar: `افكار سهلة مع تطور محدود.` },
  s68: {
    en: `Basic, everyday vocabulary with little variety.`,
    ar: `لغة يومية أساسية بدون تنوع وايد.`,
  },
  s69: {
    en: `Limited structural features; may lack clear paragraphing.`,
    ar: `مميزات بنائية محدودة؛ قد تفتقر إلى فقرات واضحة.`,
  },
  s70: {
    en: `Simple sentence forms; frequent errors in spelling and punctuation.`,
    ar: ``,
  },
  s71: { en: `Grade G (1) &mdash; Elementary`, ar: `درجة ج (1) &mdash; أساسية` },
  s72: {
    en: `Minimal engagement with the text; may misunderstand the question.`,
    ar: `ítigation بالحد minimal معاملة مع النص؛ شلون فهمت السؤال وايد خطأ.`,
  },
  s74: {
    en: `Summary attempts may be largely copied or irrelevant.`,
    ar: `محاولات الملخص قد تكون مسروقة بشكل كبير أو غير ذات صلة.`,
  },
  s75: {
    en: `Very basic communication; meaning may be unclear in places.`,
    ar: `تواصلية بسيطة جدًا؛ قد يكون المعنى غير واضح في بعض الأماكن.`,
  },
  s76: { en: `Very limited vocabulary.`, ar: `كلمات قليلة جدًا` },
  s77: {
    en: `No clear structure; errors significantly hinder understanding.`,
    ar: `لا هيكل واضح؛ الأخطاء تعيق الفهم بشكل كبير.`,
  },
  s79: {
    en: `Comprehension, language analysis, summary, writer&rsquo;s effect`,
    ar: `الفهم، تحليل اللغة، الملخص، أثر الكاتب`,
  },
  s80: {
    en: `Paper 4 &mdash; Directed Writing &amp; Composition`,
    ar: `ورق الامتحان 4 &ndash; الكتابة الموجهة والتأليف`,
  },
  s81: {
    en: `Directed writing (from passage), narrative or descriptive composition`,
    ar: `Composition السردية أو الوصفية (من النص)`,
  },
  s82: { en: `Paper 1 &mdash; Reading`, ar: `ورقية الأولى - القراءة` },
  s83: { en: `Comprehension, language analysis, summary`, ar: `الفهم، تحليل اللغة، ملخص` },
  s84: {
    en: `Paper 3 &mdash; Directed Writing &amp; Composition`,
    ar: `ورقية 3 &ndash; الكتابة الموجهة والتأليف`,
  },
  s85: {
    en: `Directed writing, narrative or descriptive composition`,
    ar: `Composition السردية أو الوصفية`,
  },
  s86: { en: `Grade D &rarr; Grade C`, ar: `من الفئة د إلى الفئة سي` },
  s87: { en: `Grade C &rarr; Grade B`, ar: `من درجة ج إلى درجة ب` },
  s88: { en: `Directed writing:`, ar: `كتابة موجهة:` },
  s89: { en: `Grade B &rarr; Grade A`, ar: `من الدرجة ب إلى الدرجة أ` },
  s90: { en: `Writer&rsquo;s effect:`, ar: `تأثير الكاتب:` },
  s92: { en: `Reading widely:`, ar: `قراءة واسعة:` },
  s93: { en: `Reading responses`, ar: `ردود على القراءة` },
  s94: { en: `Retelling the story`, ar: `رواية القصة` },
  s95: {
    en: `Ignoring the question focus`,
    ar: `IGNORING THE QUESTION FOCUS  (Translation note: The phrase is kept in English as it's a specific instructional term used on the platform and doesn't require translation to Khaleeji Arabic.) 

However, if you want this translated into a more natural Khaleeji Arabic equivalent for understanding:
 ignораring thе quеstion focuѕ  could be expressed as:`,
  },
  s96: { en: `Using overlong quotations`, ar: `استخدام اقتباسات طويلة جداً` },
  s97: { en: `Summary responses`, ar: `ردود موجزة` },
  s98: { en: `Copying from the passage`, ar: `دوّر في النص لنسخ ما تحتاجه` },
  s100: { en: `Writing too little`, ar: `تكتبي أو تكتبا قليلًا شديد القلة` },
  s101: { en: `Writing responses`, ar: `كتابة ردود` },
  s102: { en: `Wrong format in directed writing`, ar: `صيغة خاطئة في الكتابة المنظمة` },
  s104: { en: `Weak endings`, ar: `نهايات ضعيفة` },
  s105: { en: `Ignoring SPaG`, ar: `IGNORING SPaG` },
  s106: { en: `Paper 1: Reading (Core)`, ar: `ورقية 1: القراءة (الأساسية)` },
  s107: { en: `Comprehension, summary, and language analysis`, ar: `الفهم، الملخص، وتحليل اللغة` },
  s108: { en: `Paper 2: Reading (Extended)`, ar: `ورقتي 2: القراءة (الموسعة)` },
  s109: {
    en: `Comprehension, summary, language analysis, and writer&rsquo;s effect`,
    ar: `الفهم، الملخص، تحليل اللغة، وتأثير كاتب`,
  },
  s110: { en: `Language Techniques`, ar: `TECHNIQUES AL-LISANIYYAH` },
  s111: { en: `Writing Skills`, ar: `مهارات الكتابة` },
  s112: {
    en: `All formats, summary technique, and composition`,
    ar: `جميع الصيغ، التقنيات الملخصة، والComposition`,
  },
  s113: {
    en: `Core vs Extended tier: which one are you sitting?`,
    ar: `متى رح تختار بين الترتيه الأساسية والتمددية؟ شنو الترتيه اللي رح تقعد فيها؟`,
  },
  s114: {
    en: `Extended tier grade boundaries (Paper 2 + Paper 4)`,
    ar: `حدود الدرجات الموسعة (ورقة الإجابة 2 + ورقة الإجابة 4)`,
  },
  s115: {
    en: `Core tier grade boundaries (Paper 1 + Paper 3)`,
    ar: `حدود الدرجات الأساسية (ورقة الإجابة الأولى + ورقة الإجابة الثالثة)`,
  },
  s116: { en: `What each grade looks like in practice`, ar: `كيف تبدو كل درجة في الممارسة` },
  s117: { en: `Marks per component at a glance`, ar: `درجات كل مكون في نظرة عامة` },
  s118: { en: `How to push your grade higher`, ar: `كيف تPush كفاءتك لأعلى` },
  s119: { en: `Common mistakes that cost marks`, ar: `erreurs الشائعة التي تكلفك نقاطًا` },
  s120: { en: `Continue your revision`, ar: `دوروRevision الحين` },
}
