/**
 * jane-eyre set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s1: { en: `Gateshead (Chapters 1&ndash;4)`, ar: `جيتهد (الفصول 1 إلى 4)` },
  s3: { en: `Chapter 2: The Red Room`, ar: `الفصل الثاني: الغرفة الحمراء` },
  s4: { en: `Chapters 3&ndash;4: Escape from Gateshead`, ar: `الفصول 3 و 4: هروب من غيتزهيد` },
  s5: { en: `Lowood Institution (Chapters 5&ndash;10)`, ar: `مؤسسة لوود (الفصول 5 إلى 10)` },
  s6: {
    en: `Chapters 5&ndash;6: Arrival and Helen Burns`,
    ar: `الفصلين الخامس والسادس: الوصول وهيلن بيرنز`,
  },
  s7: { en: `Chapters 7&ndash;8: Public Humiliation`, ar: `الفصول 7 إلى 8: العار הציבורי` },
  s8: {
    en: `Chapter 9: The Typhus Epidemic and Helen&apos;s Death`,
    ar: `الفصل التاسع: وباء الطاعون وموت هيلين`,
  },
  s9: { en: `Chapter 10: Leaving Lowood`, ar: `الفصل العاشر: مغادرة لوود` },
  s10: { en: `Thornfield Hall (Chapters 11&ndash;27)`, ar: `Thornfield Hall (الفصول 11 إلى 27)` },
  s11: { en: `Chapters 11&ndash;12: Arrival and Restlessness`, ar: `الفصول 11-12: الوصول والضجر` },
  s12: { en: `Chapters 13&ndash;15: Meeting Rochester`, ar: `الفصول 13 إلى 15: لقاؤه برochaester` },
  s13: {
    en: `Chapters 16&ndash;18: Blanche Ingram and Jealousy`,
    ar: `الفصول 16-18: بلانش إنغرام والغيرة`,
  },
  s14: {
    en: `Chapters 19&ndash;20: The Gypsy and Mason&apos;s Attack`,
    ar: `الفصلان التاسع عشر والعشرون: لقاء الجيبي والهجوم المفاجئ لميسون`,
  },
  s15: {
    en: `Chapters 21&ndash;22: Return to Gateshead`,
    ar: `الفصول 21 و 22: العودة إلى غيتزهيد`,
  },
  s16: { en: `Chapter 23: The Proposal`, ar: `الفصل twenty-three: الطلب يد الزواج` },
  s17: {
    en: `Chapters 24&ndash;25: Wedding Preparations and Omens`,
    ar: `الفصول 24-25: تجهيزات الزفاف وعلامات الحظوة`,
  },
  s18: {
    en: `Chapters 26&ndash;27: The Impediment and Departure`,
    ar: `الفصول 26 و 27: العقبة والرحيل`,
  },
  s19: {
    en: `Moor House / Morton (Chapters 28&ndash;35)`,
    ar: `منزل المور / مورتن (الفصول 28-35)`,
  },
  s20: {
    en: `Chapters 28&ndash;29: Destitution and Rescue`,
    ar: `الفصلان twenty-eight و twenty-nine: الفقر والنجدة`,
  },
  s22: {
    en: `Chapters 33&ndash;34: The Inheritance and St John&apos;s Proposal`,
    ar: `الفصول 33 و 34: الميراث وعرض سان جون`,
  },
  s23: {
    en: `Chapter 35: &ldquo;Jane! Jane! Jane!&rdquo;`,
    ar: `الفصل thirty five: " jane! jane! jane!`,
  },
  s24: { en: `Ferndean (Chapters 36&ndash;38)`, ar: `فرندين (الفصول 36-38)` },
  s25: { en: `Chapter 36: Return to Rochester`, ar: `الفصل thirty-six: روح مرة ثانية لروتشستر` },
  s26: { en: `Chapters 37&ndash;38: Reunion and Marriage`, ar: `الفصلان 37 و 38: لقاؤ جديد وزواج` },
  s27: {
    en: `Victorian Women and the &ldquo;Angel in the House&rdquo;`,
    ar: `نساء الفيكتوريين والملائكة في المنزل`,
  },
  s28: { en: `The Governess`, ar: `الأستاذة المتزوجة` },
  s29: { en: `Colonialism and Empire`, ar: `الاستعمار والامبراطورية` },
  s30: {
    en: `Wide Sargasso Sea`,
    ar: `وايد سارجاسو سيز Wasser hier bitte auf Arabisch korrekt: البحر السرغاسو

البحر السرغاسو`,
  },
  s31: { en: `The Bront&euml; Sisters`, ar: `الأخوات برانتون` },
  s32: { en: `Agnes Grey`, ar: `أغنيس جراي` },
  s33: { en: `Religion in Victorian England`, ar: `الدين في إنجلترا الفيكتورية` },
  s34: { en: `The Bildungsroman Tradition`, ar: `التراث الروائي التشكيلي (Bildungsroman)` },
  s35: {
    en: `How does Bront&euml; present the theme of independence in`,
    ar: `كيف ت presente برانتي موضوع الاستقلال في`,
  },
  s36: {
    en: `Paragraph 1: Independence as rebellion (Gateshead)`,
    ar: `Independence كإbellion (غيتسهيد)`,
  },
  s37: {
    en: `Paragraph 2: Moral independence (leaving Rochester)`,
    ar: `Independence الأخلاقية (ترك رochaester)`,
  },
  s38: {
    en: `Paragraph 3: Spiritual independence (rejecting St John)`,
    ar: `Independence الروحية (بالنسبة لرفضه لسان جون)`,
  },
  s39: {
    en: `Paragraph 4: Financial independence (the inheritance)`,
    ar: `الاستقلال المالي (الميراث)`,
  },
  s40: {
    en: `How does Bront&euml; use Gothic elements in`,
    ar: `كيف تستخدم برنت العناصر gothic في`,
  },
  s41: { en: `Paragraph 1: The red room`, ar: `الغرفة الحمراء` },
  s42: {
    en: `Paragraph 2: Bertha Mason and the madwoman in the attic`,
    ar: `برثا ميسون والمرأة المجنونة في القبو`,
  },
  s43: {
    en: `Strange laughter, nocturnal attacks, the ripped veil. Bertha as Gothic double for Jane (uncontrolled passion vs. disciplined self-control). Explore postcolonial readings of Bertha&apos;s confinement.`,
    ar: `ضحك غريب، هجمات ليلاً، الستار المهتريق. برثا كنقيضة جوتيكية لجاني (الشوق غير المسيطر عليه مقابل التحكم بالنفس). استكشف قراءات ما بعدkolonialia لحجز برثا.`,
  },
  s44: { en: `Paragraph 3: Pathetic fallacy and symbolism`, ar: `الغفلة الباثétique والرموز` },
  s45: {
    en: `The split chestnut tree, storms during emotional crises, the fire that destroys Thornfield. Nature reflects and foreshadows the characters&apos; fates. Link to Romantic and Gothic traditions.`,
    ar: `الشجرة الصنوبرية المقسمة، العواصف خلال الأزمات العاطفية، النار التي تدمر ثورنفيلد. الطبيعة تعكس وتلمح إلى مصائر الشخصيات. ربط مع التقاليد الرومانسية والجوثية`,
  },
  s46: { en: `Paragraph 4: Subversion of Gothic conventions`, ar: `نقضventions gothic` },
  s47: {
    en: `How does Bront&euml; present the relationship between Jane and Rochester?`,
    ar: `كيف ت presente برانت العلاقة بين جين وإروينكست؟`,
  },
  s48: { en: `Paragraph 1: Unconventional beginnings`, ar: `بدايات غير تقليدية` },
  s49: { en: `Paragraph 2: Equality of spirit`, ar: `مساواة الروح` },
  s50: { en: `Paragraph 3: Power and deception`, ar: `القوة والخداع` },
  s51: { en: `Paragraph 4: Restored equality`, ar: `إعادة المساواة` },
  s53: {
    en: `Paragraph 1: Brocklehurst &mdash; Evangelical hypocrisy`,
    ar: `بروكليهست — نفاق الإنجيليين`,
  },
  s54: {
    en: `Paragraph 2: Helen Burns &mdash; Christian endurance`,
    ar: `هيلين برنز &___الصبر المسيحي`,
  },
  s56: { en: `Paragraph 4: Jane&apos;s personal faith`, ar: `إيمان جين الشخصي` },
  s57: { en: `Use the Correct Terminology`, ar: `استخدم المصطلحات الصحيحة` },
  s58: { en: `Byronic hero`, ar: `Hero برونيكي` },
  s59: { en: `Gothic conventions`, ar: `conventies القوطي` },
  s60: {
    en: `Structure Your Essay Around the Author&apos;s Intentions`,
    ar: `اstructuring مقالتك حول نوايا الكاتب`,
  },
  s61: { en: `Connect Themes to Context`, ar: `اربط الموضوعات بالسياق` },
  s62: { en: `Compare Characters as Foils`, ar: `قارن الشخصيات كشخصيات معاكسة` },
  s63: { en: `Question 1`, ar: `السؤال الأول` },
  s64: { en: `Question 2`, ar: `سؤال 2` },
  s65: { en: `Question 3`, ar: `السؤال الثالث` },
  s66: { en: `Question 4`, ar: `السؤال الرابع` },
  s67: { en: `Chapter Summary by Location`, ar: `ملخص الفصل حسب الموقع` },
  s68: { en: `Character Analysis`, ar: `تحليل الشخصية` },
  s69: { en: `Key Themes`, ar: `المواضيع الرئيسية` },
  s70: { en: `Independence and Self-Respect`, ar: `الاستقلال والكرامة` },
  s71: {
    en: `Social Class and Inequality`,
    ar: `класс الاجتماعي والINEQUALITY (الطبقة الاجتماعيةและความไม่เท่าเทียมกันในสังคม)`,
  },
  s72: {
    en: `Jane occupies an ambiguous class position throughout: a gentleman`,
    ar: `جاني تحتل وضعًا طبقيًا مبهمًا خلال الرواية: هي جاهلة ولكنها ليست من الطبقة العاملة`,
  },
  s75: { en: `Religion and Morality`, ar: `الدين والأخلاق` },
  s76: {
    en: `Three models of religion are presented and critiqued. Brocklehurst`,
    ar: `ثلاث نماذج للدين تُعرض وتُنتقد. بروكلهيرست`,
  },
  s77: { en: `Love and Passion`, ar: `الحب والشوق` },
  s79: { en: `Morality and Conscience`, ar: `الأخلاق والضمير` },
  s80: { en: `Forgiveness and Redemption`, ar: `العفو والتكفير` },
  s81: {
    en: `Jane forgives Mrs Reed on her deathbed, even though Mrs Reed refuses to reciprocate. She forgives Rochester for his deception, returning to him after he has been punished and humbled. Rochester`,
    ar: `جاني تسامحت مع مدام ريد على فراش الموت، حتى وإن رفضت هي التوبة. وهي تسامحت مع روتشيستر عن خداعه، وعادت إليه بعد أن عوقب وتواضع. روتشيستر`,
  },
  s82: { en: `Gothic Elements`, ar: `عناصر القوطي` },
  s83: { en: `Key Quotations with Analysis`, ar: `المقاطع الرئيسية مع التحليل` },
  s84: { en: `Historical and Literary Context`, ar: `المشهد التاريخي والأدبي` },
  s85: { en: `Essay Planning`, ar: `hoạch التعبير الكتابي` },
  s86: { en: `Practice Questions`, ar: `أسئلة للتمرين` },
  s87: { en: `Write your essay response here...`, ar: `اكتب ردود فعل مقالتك هنا...` },
}
