/**
 * a-streetcar-named-desire set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Tennessee Williams, 1947`, ar: `` },
  s3: { en: `The Glass Menagerie`, ar: `الزجاجية المنسية` },
  s4: { en: `Suddenly Last Summer`, ar: `فجأة في الصيف الماضي` },
  s5: { en: `Southern Gothic Tradition`, ar: `التقاليد الجنوبية القوطية` },
  s6: { en: `The Loss of the Old South`, ar: `خسارة الجنوب القديم` },
  s7: { en: `The Streetcar Lines as Symbol`, ar: `خطوط الترام كرمز` },
  s8: { en: `The 1947 Production and Marlon Brando`, ar: `الإنتاج عام 1947 ومارلون براندو` },
  s9: { en: `The Paper Lantern`, ar: `المنارة الورقية` },
  s10: { en: `The Varsouviana / Polka Music`, ar: `موسيقى البولكا الفارسوبيانا` },
  s11: { en: `Blanche&apos;s Costumes`, ar: `ملابس بلانش` },
  s12: { en: `Bathing and Cleansing`, ar: `الغسل والتنظيف` },
  s14: { en: `The Poker Game`, ar: `اللعبة بالبوكر` },
  s15: { en: `Treat the play as a play.`, ar: `امل العرض على أنه مسرحية.` },
  s16: { en: `Anchor every argument in context.`, ar: `anchور كل حجة في سياقها.` },
  s18: { en: `Use precise dramatic vocabulary.`, ar: `استخدم لغة درامية دقيقة.` },
  s19: { en: `Quote precisely and economically.`, ar: `اقتبس بدقة واقتصادية.` },
  s20: {
    en: `Address the whole play.`,
    ar: `ا.address the whole play. ا.read the entire play. 

(Note: The initial "a." is a placeholder to maintain the instructional format requested. The actual translation focuses on the imperative verb form as per instructions.) 

راجع المسرحية كلها.`,
  },
  s21: { en: `Scene-by-Scene Summary`, ar: `ملخص مشهدًا بعد مشهد` },
  s22: { en: `Character Profiles`, ar: `ملفات الشخصيات` },
  s23: {
    en: `The upstairs neighbours and the Kowalskis`,
    ar: `الجيران اللي في الدور الأعلى والكووالسكيز`,
  },
  s24: { en: `Key Themes`, ar: `المواضيع الرئيسية` },
  s25: { en: `Desire vs Death`, ar: `الرغبة مقابل الموت` },
  s27: {
    en: `Blanche openly champions illusion over fact:`,
    ar: `بلانش تدافع مفتوحةً عن الخيال على حساب الحقيقة:`,
  },
  s28: {
    en: `Class & The Old South vs New America`,
    ar: `الفصل والجنوب القديم مقابل أمريكا الجديدة`,
  },
  s29: { en: `Sexual Violence`, ar: `العنف الجنسي` },
  s32: {
    en: `The play exposes the asymmetric sexual codes of mid-century America. Blanche`,
    ar: `تعرض المسرحية قواعد الجنس غير المتكافئة في أمريكا وسط القرن العشرين. بلانش`,
  },
  s33: { en: `Mental Illness and Trauma`, ar: `` },
  s34: {
    en: `Williams was haunted by his own sister Rose`,
    ar: `ويليامز كان مرعوب من أخته روز نفسها`,
  },
  s35: { en: `Light, Bathing and Cleansing`, ar: `الضوء، الاستحمام والتنظيف` },
  s37: { en: `Historical and Biographical Context`, ar: `السياق التاريخي وال BIOGRAPHICAL` },
  s38: { en: `Key Quotations with Analysis`, ar: `اقتباسات رئيسية مع تحليل` },
  s39: { en: `Key Symbols`, ar: `` },
}
