/**
 * writing-skills set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Dear Mr/Mrs/Ms [Surname],`, ar: `يا أستاذ/أستاذة [اسم العائلة]،` },
  s2: { en: `Dear [First name] / Hi [Name],`, ar: `حبيبتي / مرحبًا يا [اسمك]،` },
  s3: { en: `REPORT ON [TOPIC]`, ar: `تقرير عن [الموضوع]` },
  s4: { en: `By [Your name]`, ar: `بواسطة [اسمك]` },
  s5: {
    en: `Good morning/afternoon, [audience] &mdash;`,
    ar: `صباح الخير / مساء الخير، أيها الجمهور &mdash;`,
  },
  s6: { en: `Thank you.`, ar: `شكوشا` },
  s7: { en: `Content Marks`, ar: `نقاط المحتوى` },
  s8: { en: `Writing Quality Marks`, ar: `كتابة علامات الجودة` },
  s9: { en: `Opening Techniques`, ar: `TECHNIQUES للبدء` },
  s10: { en: `In Medias Res`, ar: `في وسط الأحداث` },
  s11: { en: `Atmospheric Description`, ar: `وصف جوي` },
  s12: { en: `Prolepsis (Flash-forward)`, ar: `بريلبيسيس (مشاهد مستقبلية)` },
  s13: { en: `Show, Don&rsquo;t Tell`, ar: `أظهر، لا تخبر` },
  s14: { en: `Telling (weak)`, ar: `حكي (ضعيف)` },
  s15: { en: `Showing (strong)`, ar: `يشعر (بقوه)` },
  s16: { en: `Varied Pace`, ar: `تغير الوتيرة` },
  s17: { en: `Effective Endings`, ar: `endings فعّال` },
  s18: { en: `Zoom Technique`, ar: `TECHNIQUE الزوم` },
  s19: { en: `Senses Journey`, ar: `رحلة الحواس` },
  s20: { en: `Time Progression`, ar: `تقدم الزمن` },
  s21: {
    en: `Writing skills for Cambridge IGCSE English Language: structure, vocabulary, sentence variety, and creative/transactional writing models.`,
    ar: `مهارات الكتابة لامتحان Cambridge IGCSE في اللغة الإنجليزية: الهيكل، المفردات، تنوع الجمل، ونماذج الكتابة الإبداعية والعملية.`,
  },
}
