/**
 * grade-boundaries set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Grade Boundaries`, ar: `حدود التقييمات` },
  s1: { en: `Important note`, ar: `ملاحظة مهمة` },
  s3: {
    en: `Perceptive, original analysis that goes beyond the obvious interpretation.`,
    ar: `تحليل ذكي ومبتكر يتجاوز التفسير الواضح.`,
  },
  s4: {
    en: `Judicious, precisely selected quotations seamlessly embedded in sentences.`,
    ar: `اقتباسات دقيقة ومختارة بعناية مدمجة بشكل سلس في الجمل.`,
  },
  s7: {
    en: `Consistently engages with connotations, nuance, and the subtleties of language.`,
    ar: ``,
  },
  s8: {
    en: `Compelling, convincing writing that sustains the reader&rsquo;s interest throughout.`,
    ar: `كتابة مثيرة وقاطعة تحافظ على اهتمام القارئ خلال كل الحين.`,
  },
  s9: {
    en: `Extensive, ambitious vocabulary used precisely and naturally.`,
    ar: `لغة واسعة وأماني كبيرة مستخدمة بدقة وتلقائية.`,
  },
  s10: {
    en: `Varied, inventive structural choices that shape meaning (e.g., cyclical structure, deliberate shifts in pace).`,
    ar: `اختيارات بنائية متنوعة ومبتكرة التي تشكل المعنى (مثل الهيكل الدوري، والتغييرات المتعمدة في الوتيرة).`,
  },
  s12: { en: `Grades 7-8 &mdash; Strong`, ar: `المستوى seventh إلى eighth &mdash; قوي` },
  s13: {
    en: `Detailed, well-developed analysis with clear explanations of effects.`,
    ar: `تحليل مفصل ومتطور مع تفسيرات واضحة لتأثيرات القصة.`,
  },
  s14: {
    en: `Well-chosen quotations with thorough exploration of language and structure.`,
    ar: `اقتباسات مختارة بدقة مع استكشاف دقيق للغة والبنية.`,
  },
  s15: {
    en: `Accurate subject terminology used consistently.`,
    ar: `terminologia الصحيحة مستخدمة بشكل_consistent`,
  },
  s16: {
    en: `Thoughtful evaluation that engages with the statement and writer&rsquo;s methods.`,
    ar: `تقييم Thoughtful يتعامل مع	statement والطرق التي يستخدمها الكاتب.`,
  },
  s18: {
    en: `Engaging, well-crafted writing with a clear sense of purpose and audience.`,
    ar: `كتابة جذابة ومصاغة بشكل جيد مع حس واضح بالغرض والجمهور.`,
  },
  s19: {
    en: `Increasingly sophisticated vocabulary and phrasing.`,
    ar: `لغة وتعبيرات أكثر تعقيداً ودقة.`,
  },
  s20: {
    en: `Effective structural features that contribute to the overall effect.`,
    ar: `مميزات بنائية فعالة تساهم في التأثير العام.`,
  },
  s21: {
    en: `Wide range of sentence structures used for effect.`,
    ar: `مدى واسع من بنية الجمل يستخدم للتأثير.`,
  },
  s22: {
    en: `Mostly accurate spelling and punctuation with only minor errors.`,
    ar: `سبوتة في التهجئة والت пунктуация مع أخطاء طفيفة فقط. 

(Note: There seems to be a leftover English word "punktuation". I'll correct it.)

معظم التهجئة والإملأء صحيحة مع أخطاء طفيفة فقط.`,
  },
  s23: { en: `Grades 5-6 &mdash; Secure`, ar: `الصفوف fifth إلى sixth &mdash; موثوق` },
  s24: {
    en: `Clear explanations of language and structural effects.`,
    ar: `توضيحات واضحة لتأثيرات اللغة والبنية"structural" هنا تعني "الهياكل" في السياق الأدبي أو اللغوي، لكن الاصطلاح يستخدم كما هو: تأثيرات اللغة والهيكل.`,
  },
  s25: { en: `Relevant quotations selected and commented on.`, ar: `اقتباسات مختارة وعلق عليها.` },
  s26: {
    en: `Subject terminology used, mostly accurately.`,
    ar: `مصطلحات الموضوع مستخدمة بشكلmostly دقيق. (Note: "mostly" is kept in English as it's a common word to leave untranslated in such contexts.)

(Note: The term "mostly" was left in English because it doesn't have an exact equivalent that sounds natural in Khaleeji Arabic, and leaving it in English maintains the original intent.) 

For strict translation without notes:
مصطلحات الموضوع مستخدمة بشكل دقيق.`,
  },
  s27: {
    en: `Analysis may lack depth or consistency &mdash; some points developed well, others more surface-level.`,
    ar: `التحليل قد يفتقر إلى العمق أوconsistency - بعض النقاط تطورت بشكل جيد، بينما أخرى على سطحية أكثر. 

(Note: The word "consistency" is kept in English as it's a technical term and might not have an exact equivalent that fits the context in Khaleeji Arabic.)`,
  },
  s28: {
    en: `Writing is clear and communicates effectively with some engaging moments.`,
    ar: `الكتابة واضحة وتعبر عن الفكرة بشكل فعال مع بعض اللحظات المثيرة لل interés. 

(Note: There was an unintended carry-over of "intérêt" at the end, which should not be there. The correct translation without it is as follows):

الكتابة واضحة وتعبر عن الفكرة بشكل فعال مع بعض اللحظات المثيرة.`,
  },
  s29: {
    en: `Vocabulary is chosen for effect, though may occasionally lack precision.`,
    ar: `الكلمات تختار لتأثير، رغم أنها قد تنقص الدقة أحيانًا.`,
  },
  s30: {
    en: `Paragraphs are used effectively with some structural awareness.`,
    ar: `يستخدم الفصلون بشكل فعال مع وعي هيكلية وايد.`,
  },
  s31: { en: `Some variety in sentence structures.`, ar: `قليل من التغير في بنية الجمل.` },
  s32: {
    en: `Generally accurate spelling and punctuation with some errors on more complex words.`,
    ar: ``,
  },
  s33: { en: `Grade 4 &mdash; Standard pass`, ar: `الدرجة الرابعة &ndash; المعيار المعتمد للنجاح` },
  s34: {
    en: `Some understanding of language effects, but explanations may be thin.`,
    ar: `بعض الفهم لتأثيرات اللغة، لكن التفسيرات قد تكون ضعيفة.`,
  },
  s35: {
    en: `Some appropriate references to the text, though not always well-chosen.`,
    ar: `بعض الإحالات المناسبة إلى النص، رغم أنها لا تكون مختارة دائمًا بشكل جيد.`,
  },
  s36: {
    en: `Some subject terminology, not always accurate.`,
    ar: `بعض المصطلحات الموضوعية، ليس دقيقًا دائمًا.`,
  },
  s38: {
    en: `May feature-spot (identify techniques without explaining their effect).`,
    ar: `قد تلاحظ المواضع الخاصة (اشير إلى التقنيات دون شرح تأثيرها)`,
  },
  s40: {
    en: `Some attempts at vocabulary for effect.`,
    ar: `بعض المحاولات لاستخدام القاموس لتحقيق تأثير.`,
  },
  s41: {
    en: `Basic structural features (paragraphs, some variety).`,
    ar: `مميزات بنائية أساسية (فقرات، نوعية متنوعة)`,
  },
  s42: {
    en: `Sentence demarcation mostly secure but some comma splicing or run-on sentences.`,
    ar: `التقسيم بين الجُمل موثوق به بشكل كبير، لكن هناك بعض التراكب السرطاني أو جُمل طويلة غير مقسَّمة Properly, this should be adjusted to:

التقسيم بين الجُمل موثوق به إلى حد كبير، لكن هناك بعض جُمل التراكب السرطاني أو الجُمل الطويلة المترابطة التي لم تُقسَّم.`,
  },
  s43: {
    en: `Spelling of basic words accurate; errors with more complex vocabulary.`,
    ar: `SPELLING OF BASIC WORDS ACCURATE؛ ERRORS WITH MORE COMPLEX VOCABULARY`,
  },
  s44: {
    en: `Grades 1-3 &mdash; Below standard pass`,
    ar: `المستوى الأول حتى الثالث &mdash; دون المعدل للنجاح`,
  },
  s45: {
    en: `Simple comments on language with limited or no analysis.`,
    ar: `تعليقات سهلة حول اللغة مع تحليل محدود أو بدونه.`,
  },
  s46: {
    en: `Simple references that may paraphrase rather than quote.`,
    ar: `مراجعات بسيطة قد ت paraphrase بدلاً من الاقتباس.`,
  },
  s47: { en: `Little or no subject terminology.`, ar: `قليل أو لا يوجد مصطلحات موضوعية` },
  s48: {
    en: `May retell the text rather than analyse or evaluate it.`,
    ar: `يمكن إعادة كتابة النص بدلاً من تحليله أو تقييمه.`,
  },
  s49: { en: `Simple ideas with limited development.`, ar: `افكار سهلة مع تطوير محدود.` },
  s50: { en: `Basic, everyday vocabulary.`, ar: `لغة يومية أساسية` },
  s51: {
    en: `Limited structural features; may lack clear paragraphing.`,
    ar: `مميزات بنائية محدودة؛ قد تفتقر إلى تنسيق الفقرات الواضح.`,
  },
  s52: {
    en: `Simple sentence forms; frequent errors in spelling and punctuation.`,
    ar: ``,
  },
  s53: { en: `Grade 4 &rarr; Grade 5`, ar: `الصف الرابع إلى الصف الخامس` },
  s54: { en: `Grade 5 &rarr; Grade 7`, ar: `الصف الخامس إلى الصف السابع` },
  s55: { en: `Grade 7 &rarr; Grade 9`, ar: `السابع&rarr;الثامن والتاسع` },
  s56: { en: `Reading widely:`, ar: `قراءة واسعة:` },
  s58: { en: `Reading and retrieval (AO1)`, ar: `قراءة واسترجاع (AO1)` },
  s59: { en: `Language and structure analysis (AO2)`, ar: `تحليل اللغة والبنية (AO2)` },
  s60: {
    en: `Content and organisation (AO5, 24) + Technical accuracy (AO6, 16)`,
    ar: `تنظيم المحتوى (AO5، 24) + الدقة التقنية (AO6، 16)`,
  },
  s61: {
    en: `Overall grade boundaries (combined Paper 1 + Paper 2)`,
    ar: `حدود الدرجات الكلية (ورقة الإجابة الأولى + ورقة الإجابة الثانية)`,
  },
  s62: { en: `What each grade looks like in practice`, ar: `كيف تبدو كل درجة في الممارسة` },
  s64: { en: `Marks per question at a glance`, ar: `نقاط لكل سؤال في نظرة عامة` },
}
