// AUTO-GENERATED by scripts/generate-comic-plates.mjs - do not edit by hand.
// prebuild, predev and pretest regenerate it; run that script after drawing,
// redrawing or registering a linocut piece.

/**
 * Where each registered linocut plate is served, by piece id (pieceUid). The
 * name carries a hash of the file's contents, so a redrawn plate gets a new
 * URL and is never served stale. Read through src/lib/comics/served.ts.
 */
export const PLATE_SRC: Readonly<Record<string, string>> = {
  'lc-a-christmas-carol-a-raise-for-bob':
    '/comics/a-christmas-carol/a-raise-for-bob.253a7782d9ea.svg',
  'lc-a-christmas-carol-a-vacant-seat': '/comics/a-christmas-carol/a-vacant-seat.566a59da98b8.svg',
  'lc-a-christmas-carol-belle': '/comics/a-christmas-carol/belle.791ad1638f52.svg',
  'lc-a-christmas-carol-belle-releases-him':
    '/comics/a-christmas-carol/belle-releases-him.d92e34f55b78.svg',
  'lc-a-christmas-carol-bob-cratchit': '/comics/a-christmas-carol/bob-cratchit.5641df31b83d.svg',
  'lc-a-christmas-carol-christmas-eve-at-the-counting-house':
    '/comics/a-christmas-carol/christmas-eve-at-the-counting-house.1da1a1393eb4.svg',
  'lc-a-christmas-carol-christmas-morning':
    '/comics/a-christmas-carol/christmas-morning.5e79a43bfe01.svg',
  'lc-a-christmas-carol-ebenezer-scrooge':
    '/comics/a-christmas-carol/ebenezer-scrooge.0b1aae28fc61.svg',
  'lc-a-christmas-carol-fezziwig': '/comics/a-christmas-carol/fezziwig.47c159d4ceb1.svg',
  'lc-a-christmas-carol-fezziwig-s-ball':
    '/comics/a-christmas-carol/fezziwig-s-ball.fc6c6321925f.svg',
  'lc-a-christmas-carol-fred': '/comics/a-christmas-carol/fred.ad1ae66a3963.svg',
  'lc-a-christmas-carol-fred-s-party': '/comics/a-christmas-carol/fred-s-party.6084b6c4ac40.svg',
  'lc-a-christmas-carol-ghost-of-christmas-past':
    '/comics/a-christmas-carol/ghost-of-christmas-past.4bba5f1c08c0.svg',
  'lc-a-christmas-carol-ghost-of-christmas-present':
    '/comics/a-christmas-carol/ghost-of-christmas-present.35e520a4e401.svg',
  'lc-a-christmas-carol-ghost-of-christmas-yet-to-come':
    '/comics/a-christmas-carol/ghost-of-christmas-yet-to-come.f84d96755628.svg',
  'lc-a-christmas-carol-ignorance-and-want':
    '/comics/a-christmas-carol/ignorance-and-want.b8a7227177d4.svg',
  'lc-a-christmas-carol-jacob-marley': '/comics/a-christmas-carol/jacob-marley.0dc8cb290d6f.svg',
  'lc-a-christmas-carol-marley-s-ghost':
    '/comics/a-christmas-carol/marley-s-ghost.0e137d6841eb.svg',
  'lc-a-christmas-carol-one-shadow-more':
    '/comics/a-christmas-carol/one-shadow-more.2573fd2f9251.svg',
  'lc-a-christmas-carol-the-body-on-the-bed':
    '/comics/a-christmas-carol/the-body-on-the-bed.af30eb544260.svg',
  'lc-a-christmas-carol-the-charity-collectors':
    '/comics/a-christmas-carol/the-charity-collectors.df01164fc942.svg',
  'lc-a-christmas-carol-the-cratchits-keep-christmas':
    '/comics/a-christmas-carol/the-cratchits-keep-christmas.45daee557450.svg',
  'lc-a-christmas-carol-the-cratchits-mourn-tiny-tim':
    '/comics/a-christmas-carol/the-cratchits-mourn-tiny-tim.3d356d290cb7.svg',
  'lc-a-christmas-carol-the-dead-man-s-belongings':
    '/comics/a-christmas-carol/the-dead-man-s-belongings.d2a766e342a2.svg',
  'lc-a-christmas-carol-the-gravestone':
    '/comics/a-christmas-carol/the-gravestone.f148c2af775b.svg',
  'lc-a-christmas-carol-the-lonely-schoolboy':
    '/comics/a-christmas-carol/the-lonely-schoolboy.5b05a0cc9971.svg',
  'lc-a-christmas-carol-tiny-tim': '/comics/a-christmas-carol/tiny-tim.2bf71c124276.svg',
  'lc-jekyll-and-hyde-dr-hastie-lanyon':
    '/comics/jekyll-and-hyde/dr-hastie-lanyon.73a56dc5b2f8.svg',
  'lc-jekyll-and-hyde-dr-henry-jekyll': '/comics/jekyll-and-hyde/dr-henry-jekyll.8f2611ebefc9.svg',
  'lc-jekyll-and-hyde-incident-at-the-window':
    '/comics/jekyll-and-hyde/incident-at-the-window.6511c92b5504.svg',
  'lc-jekyll-and-hyde-jekyll-at-ease': '/comics/jekyll-and-hyde/jekyll-at-ease.0f0f414fc526.svg',
  'lc-jekyll-and-hyde-lanyon-s-narrative':
    '/comics/jekyll-and-hyde/lanyon-s-narrative.db6346421b53.svg',
  'lc-jekyll-and-hyde-lanyon-s-shock': '/comics/jekyll-and-hyde/lanyon-s-shock.0cf76523e426.svg',
  'lc-jekyll-and-hyde-losing-control': '/comics/jekyll-and-hyde/losing-control.c507ea9cc77e.svg',
  'lc-jekyll-and-hyde-mr-edward-hyde': '/comics/jekyll-and-hyde/mr-edward-hyde.a20b9df4685d.svg',
  'lc-jekyll-and-hyde-mr-gabriel-john-utterson':
    '/comics/jekyll-and-hyde/mr-gabriel-john-utterson.4666066ae461.svg',
  'lc-jekyll-and-hyde-mr-guest': '/comics/jekyll-and-hyde/mr-guest.e348dc13a2a2.svg',
  'lc-jekyll-and-hyde-poole': '/comics/jekyll-and-hyde/poole.3ef8d0f21a3c.svg',
  'lc-jekyll-and-hyde-richard-enfield': '/comics/jekyll-and-hyde/richard-enfield.7145a053d71b.svg',
  'lc-jekyll-and-hyde-sir-danvers-carew':
    '/comics/jekyll-and-hyde/sir-danvers-carew.05fa882cb2cf.svg',
  'lc-jekyll-and-hyde-soho-in-the-fog': '/comics/jekyll-and-hyde/soho-in-the-fog.42d51f45a74d.svg',
  'lc-jekyll-and-hyde-the-carew-murder':
    '/comics/jekyll-and-hyde/the-carew-murder.3c4cc4bf0a8f.svg',
  'lc-jekyll-and-hyde-the-door-and-enfield-s-story':
    '/comics/jekyll-and-hyde/the-door-and-enfield-s-story.e2b2d94b07ec.svg',
  'lc-jekyll-and-hyde-the-experiment': '/comics/jekyll-and-hyde/the-experiment.c97512dc3dab.svg',
  'lc-jekyll-and-hyde-the-last-night': '/comics/jekyll-and-hyde/the-last-night.1ebf59963728.svg',
  'lc-jekyll-and-hyde-the-letter-and-the-handwriting':
    '/comics/jekyll-and-hyde/the-letter-and-the-handwriting.e6f981fdc629.svg',
  'lc-jekyll-and-hyde-the-will-and-mr-seek':
    '/comics/jekyll-and-hyde/the-will-and-mr-seek.7d79b29e0298.svg',
  'lc-jekyll-and-hyde-utterson-meets-hyde':
    '/comics/jekyll-and-hyde/utterson-meets-hyde.fa2c1defcae2.svg',
  'lc-macbeth-banquo': '/comics/macbeth/banquo.33bcea357019.svg',
  'lc-macbeth-banquo-suspects': '/comics/macbeth/banquo-suspects.a5e32fe0c98d.svg',
  'lc-macbeth-birnam-wood': '/comics/macbeth/birnam-wood.13c8658db606.svg',
  'lc-macbeth-brave-macbeth': '/comics/macbeth/brave-macbeth.fcd5082285b5.svg',
  'lc-macbeth-duncan': '/comics/macbeth/duncan.6ce6492d1423.svg',
  'lc-macbeth-duncan-arrives': '/comics/macbeth/duncan-arrives.d31a46ce20c8.svg',
  'lc-macbeth-lady-macbeth': '/comics/macbeth/lady-macbeth.623ef9369809.svg',
  'lc-macbeth-lady-macbeth-s-invocation':
    '/comics/macbeth/lady-macbeth-s-invocation.34a54b24838f.svg',
  'lc-macbeth-macbeth': '/comics/macbeth/macbeth.da30a296949e.svg',
  'lc-macbeth-macbeth-at-bay': '/comics/macbeth/macbeth-at-bay.ba5dbab634bd.svg',
  'lc-macbeth-macbeth-wavers': '/comics/macbeth/macbeth-wavers.eec29d70a275.svg',
  'lc-macbeth-macduff': '/comics/macbeth/macduff.557c99e26510.svg',
  'lc-macbeth-macduff-and-macbeth': '/comics/macbeth/macduff-and-macbeth.7299bf9199a1.svg',
  'lc-macbeth-macduff-s-family': '/comics/macbeth/macduff-s-family.e98193742042.svg',
  'lc-macbeth-malcolm': '/comics/macbeth/malcolm.1cfe949871d6.svg',
  'lc-macbeth-malcolm-tests-macduff': '/comics/macbeth/malcolm-tests-macduff.668a2ad72346.svg',
  'lc-macbeth-nature-in-disorder': '/comics/macbeth/nature-in-disorder.a71b9d145ccb.svg',
  'lc-macbeth-scorpions-in-the-mind': '/comics/macbeth/scorpions-in-the-mind.b53c7455d1c2.svg',
  'lc-macbeth-the-ambush': '/comics/macbeth/the-ambush.ffe91c6af88a.svg',
  'lc-macbeth-the-apparitions': '/comics/macbeth/the-apparitions.3ca1c45377ea.svg',
  'lc-macbeth-the-banquet': '/comics/macbeth/the-banquet.da9644eba59c.svg',
  'lc-macbeth-the-dagger': '/comics/macbeth/the-dagger.2691b360ffff.svg',
  'lc-macbeth-the-discovery': '/comics/macbeth/the-discovery.ca39e056943d.svg',
  'lc-macbeth-the-murder': '/comics/macbeth/the-murder.ef3b50a861b3.svg',
  'lc-macbeth-the-prince-of-cumberland':
    '/comics/macbeth/the-prince-of-cumberland.3bf9e6e0db64.svg',
  'lc-macbeth-the-prophecies': '/comics/macbeth/the-prophecies.391a31a9214f.svg',
  'lc-macbeth-the-sleepwalking': '/comics/macbeth/the-sleepwalking.f8e10dfe7d13.svg',
  'lc-macbeth-the-witches': '/comics/macbeth/the-witches.589124f7faab.svg',
  'lc-macbeth-the-witches-meet': '/comics/macbeth/the-witches-meet.15c1c1a68696.svg',
  'lc-macbeth-tomorrow': '/comics/macbeth/tomorrow.cc703e9595d7.svg',
  'lc-romeo-and-juliet-a-brawl-in-the-streets':
    '/comics/romeo-and-juliet/a-brawl-in-the-streets.c19f882804bd.svg',
  'lc-romeo-and-juliet-a-glooming-peace':
    '/comics/romeo-and-juliet/a-glooming-peace.e6760b326601.svg',
  'lc-romeo-and-juliet-a-secret-wedding':
    '/comics/romeo-and-juliet/a-secret-wedding.1ece6bc33b0a.svg',
  'lc-romeo-and-juliet-a-suitor-for-juliet':
    '/comics/romeo-and-juliet/a-suitor-for-juliet.4681217f590d.svg',
  'lc-romeo-and-juliet-banished': '/comics/romeo-and-juliet/banished.bc410e5f9a54.svg',
  'lc-romeo-and-juliet-benvolio': '/comics/romeo-and-juliet/benvolio.17577a9b934e.svg',
  'lc-romeo-and-juliet-dawn-and-a-father-s-rage':
    '/comics/romeo-and-juliet/dawn-and-a-father-s-rage.a7047de339a5.svg',
  'lc-romeo-and-juliet-friar-lawrence': '/comics/romeo-and-juliet/friar-lawrence.867151f41235.svg',
  'lc-romeo-and-juliet-juliet': '/comics/romeo-and-juliet/juliet.033e9be57a43.svg',
  'lc-romeo-and-juliet-juliet-drinks-the-potion':
    '/comics/romeo-and-juliet/juliet-drinks-the-potion.b3fb1a242f1a.svg',
  'lc-romeo-and-juliet-juliet-hears-the-news':
    '/comics/romeo-and-juliet/juliet-hears-the-news.43d70ab52fe8.svg',
  'lc-romeo-and-juliet-lady-capulet': '/comics/romeo-and-juliet/lady-capulet.23d750f7a8ef.svg',
  'lc-romeo-and-juliet-lord-capulet': '/comics/romeo-and-juliet/lord-capulet.9e0694a74617.svg',
  'lc-romeo-and-juliet-lord-montague': '/comics/romeo-and-juliet/lord-montague.efe50738cf18.svg',
  'lc-romeo-and-juliet-mercutio': '/comics/romeo-and-juliet/mercutio.9279d944a0a7.svg',
  'lc-romeo-and-juliet-news-in-mantua': '/comics/romeo-and-juliet/news-in-mantua.6133e6912b40.svg',
  'lc-romeo-and-juliet-paris': '/comics/romeo-and-juliet/paris.91b007179257.svg',
  'lc-romeo-and-juliet-prince-escalus': '/comics/romeo-and-juliet/prince-escalus.bf537eec346b.svg',
  'lc-romeo-and-juliet-queen-mab-and-a-warning':
    '/comics/romeo-and-juliet/queen-mab-and-a-warning.1c6a7fb24191.svg',
  'lc-romeo-and-juliet-romeo': '/comics/romeo-and-juliet/romeo.41183198341d.svg',
  'lc-romeo-and-juliet-the-balcony': '/comics/romeo-and-juliet/the-balcony.be68198da3c4.svg',
  'lc-romeo-and-juliet-the-chorus-tells-the-ending':
    '/comics/romeo-and-juliet/the-chorus-tells-the-ending.fdb2b5cc5ffd.svg',
  'lc-romeo-and-juliet-the-feast': '/comics/romeo-and-juliet/the-feast.764b924e815f.svg',
  'lc-romeo-and-juliet-the-friar-agrees':
    '/comics/romeo-and-juliet/the-friar-agrees.4f219dc73ef3.svg',
  'lc-romeo-and-juliet-the-friar-s-plan':
    '/comics/romeo-and-juliet/the-friar-s-plan.49a25fbb9677.svg',
  'lc-romeo-and-juliet-the-letter-that-never-went':
    '/comics/romeo-and-juliet/the-letter-that-never-went.81a05de0404c.svg',
  'lc-romeo-and-juliet-the-nurse': '/comics/romeo-and-juliet/the-nurse.53b90891a5a3.svg',
  'lc-romeo-and-juliet-the-tomb': '/comics/romeo-and-juliet/the-tomb.8570fbbf2e6b.svg',
  'lc-romeo-and-juliet-thursday': '/comics/romeo-and-juliet/thursday.04ce3b031025.svg',
  'lc-romeo-and-juliet-two-deaths-and-a-banishment':
    '/comics/romeo-and-juliet/two-deaths-and-a-banishment.e164ad26f74a.svg',
  'lc-romeo-and-juliet-tybalt': '/comics/romeo-and-juliet/tybalt.3793b9ef8047.svg',
  'lc-romeo-and-juliet-wedding-turned-to-funeral':
    '/comics/romeo-and-juliet/wedding-turned-to-funeral.889fca150359.svg',
}
