// AUTO-GENERATED by scripts/generate-comic-plates.mjs - do not edit by hand.
// prebuild, predev and pretest regenerate it; run that script after drawing,
// redrawing or registering a linocut piece.

/**
 * Where each registered linocut plate is served, by piece id (pieceUid). The
 * name carries a hash of the file's contents, so a redrawn plate gets a new
 * URL and is never served stale. Read through src/lib/comics/served.ts.
 */
export const PLATE_SRC: Readonly<Record<string, string>> = {
  'lc-a-christmas-carol-a-raise-for-bob':
    '/comics/a-christmas-carol/a-raise-for-bob.253a7782d9ea.svg',
  'lc-a-christmas-carol-a-vacant-seat': '/comics/a-christmas-carol/a-vacant-seat.566a59da98b8.svg',
  'lc-a-christmas-carol-belle': '/comics/a-christmas-carol/belle.791ad1638f52.svg',
  'lc-a-christmas-carol-belle-releases-him':
    '/comics/a-christmas-carol/belle-releases-him.d92e34f55b78.svg',
  'lc-a-christmas-carol-bob-cratchit': '/comics/a-christmas-carol/bob-cratchit.5641df31b83d.svg',
  'lc-a-christmas-carol-christmas-eve-at-the-counting-house':
    '/comics/a-christmas-carol/christmas-eve-at-the-counting-house.1da1a1393eb4.svg',
  'lc-a-christmas-carol-christmas-morning':
    '/comics/a-christmas-carol/christmas-morning.5e79a43bfe01.svg',
  'lc-a-christmas-carol-ebenezer-scrooge':
    '/comics/a-christmas-carol/ebenezer-scrooge.0b1aae28fc61.svg',
  'lc-a-christmas-carol-fezziwig': '/comics/a-christmas-carol/fezziwig.47c159d4ceb1.svg',
  'lc-a-christmas-carol-fezziwig-s-ball':
    '/comics/a-christmas-carol/fezziwig-s-ball.fc6c6321925f.svg',
  'lc-a-christmas-carol-fred': '/comics/a-christmas-carol/fred.ad1ae66a3963.svg',
  'lc-a-christmas-carol-fred-s-party': '/comics/a-christmas-carol/fred-s-party.6084b6c4ac40.svg',
  'lc-a-christmas-carol-ghost-of-christmas-past':
    '/comics/a-christmas-carol/ghost-of-christmas-past.4bba5f1c08c0.svg',
  'lc-a-christmas-carol-ghost-of-christmas-present':
    '/comics/a-christmas-carol/ghost-of-christmas-present.35e520a4e401.svg',
  'lc-a-christmas-carol-ghost-of-christmas-yet-to-come':
    '/comics/a-christmas-carol/ghost-of-christmas-yet-to-come.f84d96755628.svg',
  'lc-a-christmas-carol-ignorance-and-want':
    '/comics/a-christmas-carol/ignorance-and-want.b8a7227177d4.svg',
  'lc-a-christmas-carol-jacob-marley': '/comics/a-christmas-carol/jacob-marley.0dc8cb290d6f.svg',
  'lc-a-christmas-carol-marley-s-ghost':
    '/comics/a-christmas-carol/marley-s-ghost.0e137d6841eb.svg',
  'lc-a-christmas-carol-one-shadow-more':
    '/comics/a-christmas-carol/one-shadow-more.2573fd2f9251.svg',
  'lc-a-christmas-carol-the-body-on-the-bed':
    '/comics/a-christmas-carol/the-body-on-the-bed.af30eb544260.svg',
  'lc-a-christmas-carol-the-charity-collectors':
    '/comics/a-christmas-carol/the-charity-collectors.df01164fc942.svg',
  'lc-a-christmas-carol-the-cratchits-keep-christmas':
    '/comics/a-christmas-carol/the-cratchits-keep-christmas.45daee557450.svg',
  'lc-a-christmas-carol-the-cratchits-mourn-tiny-tim':
    '/comics/a-christmas-carol/the-cratchits-mourn-tiny-tim.3d356d290cb7.svg',
  'lc-a-christmas-carol-the-dead-man-s-belongings':
    '/comics/a-christmas-carol/the-dead-man-s-belongings.d2a766e342a2.svg',
  'lc-a-christmas-carol-the-gravestone':
    '/comics/a-christmas-carol/the-gravestone.f148c2af775b.svg',
  'lc-a-christmas-carol-the-lonely-schoolboy':
    '/comics/a-christmas-carol/the-lonely-schoolboy.5b05a0cc9971.svg',
  'lc-a-christmas-carol-tiny-tim': '/comics/a-christmas-carol/tiny-tim.2bf71c124276.svg',
  'lc-animal-farm-animalism': '/comics/animal-farm/animalism.7fd830cdee79.svg',
  'lc-animal-farm-beasts-of-england': '/comics/animal-farm/beasts-of-england.7e4e5907e37a.svg',
  'lc-animal-farm-benjamin': '/comics/animal-farm/benjamin.907e9f116d40.svg',
  'lc-animal-farm-boxer': '/comics/animal-farm/boxer.c1ce0d50060d.svg',
  'lc-animal-farm-boxer-falls': '/comics/animal-farm/boxer-falls.87e9db534ba8.svg',
  'lc-animal-farm-boxer-is-taken-away': '/comics/animal-farm/boxer-is-taken-away.b3166ecb5204.svg',
  'lc-animal-farm-clover': '/comics/animal-farm/clover.415abdea5d10.svg',
  'lc-animal-farm-clover-s-vision': '/comics/animal-farm/clover-s-vision.cc5665e20884.svg',
  'lc-animal-farm-from-pig-to-man': '/comics/animal-farm/from-pig-to-man.b24eae58ab70.svg',
  'lc-animal-farm-major-s-warnings': '/comics/animal-farm/major-s-warnings.106b08a9fd42.svg',
  'lc-animal-farm-mollie': '/comics/animal-farm/mollie.38bb8e7b3448.svg',
  'lc-animal-farm-mollie-leaves': '/comics/animal-farm/mollie-leaves.83c18ad80bcb.svg',
  'lc-animal-farm-moses': '/comics/animal-farm/moses.1680449a0dcb.svg',
  'lc-animal-farm-mr-frederick': '/comics/animal-farm/mr-frederick.58bdcbfae1c4.svg',
  'lc-animal-farm-mr-jones': '/comics/animal-farm/mr-jones.8b10dcb61f0a.svg',
  'lc-animal-farm-mr-pilkington': '/comics/animal-farm/mr-pilkington.aa20ade208a5.svg',
  'lc-animal-farm-mr-whymper': '/comics/animal-farm/mr-whymper.b7becd93a810.svg',
  'lc-animal-farm-napoleon': '/comics/animal-farm/napoleon.3e1e17ef2fa8.svg',
  'lc-animal-farm-napoleon-is-always-right':
    '/comics/animal-farm/napoleon-is-always-right.ff37c6dd7eb3.svg',
  'lc-animal-farm-old-major': '/comics/animal-farm/old-major.cd18aa6d8a15.svg',
  'lc-animal-farm-old-major-s-speech': '/comics/animal-farm/old-major-s-speech.61a9cc22fc84.svg',
  'lc-animal-farm-rations-and-the-republic':
    '/comics/animal-farm/rations-and-the-republic.7e2c1a1b1fc1.svg',
  'lc-animal-farm-reading-and-the-maxim':
    '/comics/animal-farm/reading-and-the-maxim.31249e65564f.svg',
  'lc-animal-farm-snowball': '/comics/animal-farm/snowball.3d6d40babb44.svg',
  'lc-animal-farm-snowball-is-driven-out':
    '/comics/animal-farm/snowball-is-driven-out.33f84aa102b6.svg',
  'lc-animal-farm-snowball-the-traitor':
    '/comics/animal-farm/snowball-the-traitor.5d5249cd5535.svg',
  'lc-animal-farm-squealer': '/comics/animal-farm/squealer.d890b922f5f6.svg',
  'lc-animal-farm-squealer-s-story': '/comics/animal-farm/squealer-s-story.21d9d95c7441.svg',
  'lc-animal-farm-the-battle-of-the-cowshed':
    '/comics/animal-farm/the-battle-of-the-cowshed.a0df923b493d.svg',
  'lc-animal-farm-the-battle-of-the-windmill':
    '/comics/animal-farm/the-battle-of-the-windmill.64cb112c2978.svg',
  'lc-animal-farm-the-confessions': '/comics/animal-farm/the-confessions.1d1f7b5d92e7.svg',
  'lc-animal-farm-the-dogs': '/comics/animal-farm/the-dogs.bb141cdb574c.svg',
  'lc-animal-farm-the-first-harvest': '/comics/animal-farm/the-first-harvest.745e15d083db.svg',
  'lc-animal-farm-the-hens-revolt': '/comics/animal-farm/the-hens-revolt.0295068ed1f0.svg',
  'lc-animal-farm-the-milk-and-the-apples':
    '/comics/animal-farm/the-milk-and-the-apples.1dec42407297.svg',
  'lc-animal-farm-the-news-spreads': '/comics/animal-farm/the-news-spreads.ed3d5174902f.svg',
  'lc-animal-farm-the-rebellion': '/comics/animal-farm/the-rebellion.f0aa83b0bb5a.svg',
  'lc-animal-farm-the-seven-commandments-and-the-milk':
    '/comics/animal-farm/the-seven-commandments-and-the-milk.276b0c108be3.svg',
  'lc-animal-farm-the-single-commandment':
    '/comics/animal-farm/the-single-commandment.437942f3571c.svg',
  'lc-animal-farm-the-whisky': '/comics/animal-farm/the-whisky.e50e9244bd11.svg',
  'lc-animal-farm-the-windmill-falls': '/comics/animal-farm/the-windmill-falls.e88479693def.svg',
  'lc-animal-farm-the-windmill-plans': '/comics/animal-farm/the-windmill-plans.d8b908598212.svg',
  'lc-animal-farm-trade-and-the-farmhouse-beds':
    '/comics/animal-farm/trade-and-the-farmhouse-beds.bc2c3d4d8f16.svg',
  'lc-animal-farm-walking-on-two-legs': '/comics/animal-farm/walking-on-two-legs.dda114439126.svg',
  'lc-animal-farm-without-cause': '/comics/animal-farm/without-cause.cab910dcf077.svg',
  'lc-animal-farm-working-like-slaves': '/comics/animal-farm/working-like-slaves.6bf29ffb7d9d.svg',
  'lc-animal-farm-years-pass': '/comics/animal-farm/years-pass.8ebe1fa88324.svg',
  'lc-frankenstein-a-geneva-childhood-and-a-fatal-subject':
    '/comics/frankenstein/a-geneva-childhood-and-a-fatal-subject.2112965f20b2.svg',
  'lc-frankenstein-alphonse-frankenstein':
    '/comics/frankenstein/alphonse-frankenstein.b9909673f9cf.svg',
  'lc-frankenstein-clerval-s-murder': '/comics/frankenstein/clerval-s-murder.248e701bcf3f.svg',
  'lc-frankenstein-elizabeth-lavenza': '/comics/frankenstein/elizabeth-lavenza.40672f582bee.svg',
  'lc-frankenstein-henry-clerval': '/comics/frankenstein/henry-clerval.403b0ebb4e1d.svg',
  'lc-frankenstein-justine-moritz': '/comics/frankenstein/justine-moritz.26acc5be657b.svg',
  'lc-frankenstein-learning-to-be-human':
    '/comics/frankenstein/learning-to-be-human.5b6a4bf28b62.svg',
  'lc-frankenstein-robert-walton': '/comics/frankenstein/robert-walton.a743fabff179.svg',
  'lc-frankenstein-the-creation-and-the-flight':
    '/comics/frankenstein/the-creation-and-the-flight.f9b5aad6448d.svg',
  'lc-frankenstein-the-creature': '/comics/frankenstein/the-creature.d38e13862538.svg',
  'lc-frankenstein-the-creature-over-victor-s-body':
    '/comics/frankenstein/the-creature-over-victor-s-body.efca382242fb.svg',
  'lc-frankenstein-the-de-lacey-family':
    '/comics/frankenstein/the-de-lacey-family.a13868f0a3e7.svg',
  'lc-frankenstein-the-demand-for-a-companion':
    '/comics/frankenstein/the-demand-for-a-companion.9992adf8ea60.svg',
  'lc-frankenstein-the-meeting-on-the-glacier':
    '/comics/frankenstein/the-meeting-on-the-glacier.2df0a99c61fe.svg',
  'lc-frankenstein-the-pursuit-north-and-victor-s-death':
    '/comics/frankenstein/the-pursuit-north-and-victor-s-death.96fdad8a274d.svg',
  'lc-frankenstein-the-second-creation-destroyed':
    '/comics/frankenstein/the-second-creation-destroyed.87fa8d603b2f.svg',
  'lc-frankenstein-the-secret-toil': '/comics/frankenstein/the-secret-toil.538accb03617.svg',
  'lc-frankenstein-the-stranger-on-the-ice':
    '/comics/frankenstein/the-stranger-on-the-ice.a43006e6db07.svg',
  'lc-frankenstein-the-wedding-night': '/comics/frankenstein/the-wedding-night.c201c06e5558.svg',
  'lc-frankenstein-three-books-and-a-rejection':
    '/comics/frankenstein/three-books-and-a-rejection.7eb641b996b7.svg',
  'lc-frankenstein-victor-frankenstein':
    '/comics/frankenstein/victor-frankenstein.ae7b6dfd0af7.svg',
  'lc-frankenstein-walton-sets-out-for-the-pole':
    '/comics/frankenstein/walton-sets-out-for-the-pole.14542d12abba.svg',
  'lc-frankenstein-war-on-humankind': '/comics/frankenstein/war-on-humankind.4c540a4a11ec.svg',
  'lc-frankenstein-william-frankenstein':
    '/comics/frankenstein/william-frankenstein.50cabb40c004.svg',
  'lc-frankenstein-william-s-murder-and-justine-s-trial':
    '/comics/frankenstein/william-s-murder-and-justine-s-trial.6629a56dc29e.svg',
  'lc-jekyll-and-hyde-dr-hastie-lanyon':
    '/comics/jekyll-and-hyde/dr-hastie-lanyon.73a56dc5b2f8.svg',
  'lc-jekyll-and-hyde-dr-henry-jekyll': '/comics/jekyll-and-hyde/dr-henry-jekyll.8f2611ebefc9.svg',
  'lc-jekyll-and-hyde-incident-at-the-window':
    '/comics/jekyll-and-hyde/incident-at-the-window.6511c92b5504.svg',
  'lc-jekyll-and-hyde-jekyll-at-ease': '/comics/jekyll-and-hyde/jekyll-at-ease.0f0f414fc526.svg',
  'lc-jekyll-and-hyde-lanyon-s-narrative':
    '/comics/jekyll-and-hyde/lanyon-s-narrative.db6346421b53.svg',
  'lc-jekyll-and-hyde-lanyon-s-shock': '/comics/jekyll-and-hyde/lanyon-s-shock.0cf76523e426.svg',
  'lc-jekyll-and-hyde-losing-control': '/comics/jekyll-and-hyde/losing-control.c507ea9cc77e.svg',
  'lc-jekyll-and-hyde-mr-edward-hyde': '/comics/jekyll-and-hyde/mr-edward-hyde.a20b9df4685d.svg',
  'lc-jekyll-and-hyde-mr-gabriel-john-utterson':
    '/comics/jekyll-and-hyde/mr-gabriel-john-utterson.4666066ae461.svg',
  'lc-jekyll-and-hyde-mr-guest': '/comics/jekyll-and-hyde/mr-guest.e348dc13a2a2.svg',
  'lc-jekyll-and-hyde-poole': '/comics/jekyll-and-hyde/poole.3ef8d0f21a3c.svg',
  'lc-jekyll-and-hyde-richard-enfield': '/comics/jekyll-and-hyde/richard-enfield.7145a053d71b.svg',
  'lc-jekyll-and-hyde-sir-danvers-carew':
    '/comics/jekyll-and-hyde/sir-danvers-carew.05fa882cb2cf.svg',
  'lc-jekyll-and-hyde-soho-in-the-fog': '/comics/jekyll-and-hyde/soho-in-the-fog.42d51f45a74d.svg',
  'lc-jekyll-and-hyde-the-carew-murder':
    '/comics/jekyll-and-hyde/the-carew-murder.3c4cc4bf0a8f.svg',
  'lc-jekyll-and-hyde-the-door-and-enfield-s-story':
    '/comics/jekyll-and-hyde/the-door-and-enfield-s-story.e2b2d94b07ec.svg',
  'lc-jekyll-and-hyde-the-experiment': '/comics/jekyll-and-hyde/the-experiment.c97512dc3dab.svg',
  'lc-jekyll-and-hyde-the-last-night': '/comics/jekyll-and-hyde/the-last-night.1ebf59963728.svg',
  'lc-jekyll-and-hyde-the-letter-and-the-handwriting':
    '/comics/jekyll-and-hyde/the-letter-and-the-handwriting.e6f981fdc629.svg',
  'lc-jekyll-and-hyde-the-will-and-mr-seek':
    '/comics/jekyll-and-hyde/the-will-and-mr-seek.7d79b29e0298.svg',
  'lc-jekyll-and-hyde-utterson-meets-hyde':
    '/comics/jekyll-and-hyde/utterson-meets-hyde.fa2c1defcae2.svg',
  'lc-julius-caesar-a-night-of-storms-and-portents':
    '/comics/julius-caesar/a-night-of-storms-and-portents.336c7c7a7598.svg',
  'lc-julius-caesar-antony-alone-with-the-body':
    '/comics/julius-caesar/antony-alone-with-the-body.990e791f5352.svg',
  'lc-julius-caesar-beware-the-ides-of-march':
    '/comics/julius-caesar/beware-the-ides-of-march.991a6b164f88.svg',
  'lc-julius-caesar-brutus-decides-in-the-orchard':
    '/comics/julius-caesar/brutus-decides-in-the-orchard.b89aca8f35c8.svg',
  'lc-julius-caesar-calpurnia': '/comics/julius-caesar/calpurnia.0d23a5ceaf21.svg',
  'lc-julius-caesar-calpurnia-s-dream-and-decius-s-flattery':
    '/comics/julius-caesar/calpurnia-s-dream-and-decius-s-flattery.2ed613e195c2.svg',
  'lc-julius-caesar-cassius': '/comics/julius-caesar/cassius.c05a89e99459.svg',
  'lc-julius-caesar-cassius-s-mistake': '/comics/julius-caesar/cassius-s-mistake.c609000e8090.svg',
  'lc-julius-caesar-cassius-works-on-brutus':
    '/comics/julius-caesar/cassius-works-on-brutus.9aa8ed64a431.svg',
  'lc-julius-caesar-cinna-the-poet': '/comics/julius-caesar/cinna-the-poet.d8ae2486fa9e.svg',
  'lc-julius-caesar-decius': '/comics/julius-caesar/decius.18c2f12948ce.svg',
  'lc-julius-caesar-julius-caesar': '/comics/julius-caesar/julius-caesar.f33682adbe40.svg',
  'lc-julius-caesar-lepidus': '/comics/julius-caesar/lepidus.9223e71fd56a.svg',
  'lc-julius-caesar-lucius': '/comics/julius-caesar/lucius.d7d06b3a40b0.svg',
  'lc-julius-caesar-marcus-brutus': '/comics/julius-caesar/marcus-brutus.592a63e42e89.svg',
  'lc-julius-caesar-mark-antony': '/comics/julius-caesar/mark-antony.5f3aed5bef68.svg',
  'lc-julius-caesar-octavius': '/comics/julius-caesar/octavius.16b1b182013b.svg',
  'lc-julius-caesar-portia': '/comics/julius-caesar/portia.0ff8ce1b43a0.svg',
  'lc-julius-caesar-quarrel-grief-and-a-ghost':
    '/comics/julius-caesar/quarrel-grief-and-a-ghost.2f7eee9587b4.svg',
  'lc-julius-caesar-the-assassination': '/comics/julius-caesar/the-assassination.946d7ce86acd.svg',
  'lc-julius-caesar-the-citizens': '/comics/julius-caesar/the-citizens.10c8ab4e8d57.svg',
  'lc-julius-caesar-the-noblest-roman': '/comics/julius-caesar/the-noblest-roman.499d4c14cf51.svg',
  'lc-julius-caesar-the-proscription-list':
    '/comics/julius-caesar/the-proscription-list.cdf5f47f63d8.svg',
  'lc-julius-caesar-the-tribunes-scold-the-crowd':
    '/comics/julius-caesar/the-tribunes-scold-the-crowd.18e293062290.svg',
  'lc-julius-caesar-two-speeches-in-the-forum':
    '/comics/julius-caesar/two-speeches-in-the-forum.5ada387828b2.svg',
  'lc-julius-caesar-words-before-blows-at-philippi':
    '/comics/julius-caesar/words-before-blows-at-philippi.ec9dd275f7b4.svg',
  'lc-macbeth-banquo': '/comics/macbeth/banquo.33bcea357019.svg',
  'lc-macbeth-banquo-suspects': '/comics/macbeth/banquo-suspects.a5e32fe0c98d.svg',
  'lc-macbeth-birnam-wood': '/comics/macbeth/birnam-wood.13c8658db606.svg',
  'lc-macbeth-brave-macbeth': '/comics/macbeth/brave-macbeth.fcd5082285b5.svg',
  'lc-macbeth-duncan': '/comics/macbeth/duncan.6ce6492d1423.svg',
  'lc-macbeth-duncan-arrives': '/comics/macbeth/duncan-arrives.d31a46ce20c8.svg',
  'lc-macbeth-lady-macbeth': '/comics/macbeth/lady-macbeth.623ef9369809.svg',
  'lc-macbeth-lady-macbeth-s-invocation':
    '/comics/macbeth/lady-macbeth-s-invocation.34a54b24838f.svg',
  'lc-macbeth-macbeth': '/comics/macbeth/macbeth.da30a296949e.svg',
  'lc-macbeth-macbeth-at-bay': '/comics/macbeth/macbeth-at-bay.ba5dbab634bd.svg',
  'lc-macbeth-macbeth-wavers': '/comics/macbeth/macbeth-wavers.eec29d70a275.svg',
  'lc-macbeth-macduff': '/comics/macbeth/macduff.557c99e26510.svg',
  'lc-macbeth-macduff-and-macbeth': '/comics/macbeth/macduff-and-macbeth.7299bf9199a1.svg',
  'lc-macbeth-macduff-s-family': '/comics/macbeth/macduff-s-family.e98193742042.svg',
  'lc-macbeth-malcolm': '/comics/macbeth/malcolm.1cfe949871d6.svg',
  'lc-macbeth-malcolm-tests-macduff': '/comics/macbeth/malcolm-tests-macduff.668a2ad72346.svg',
  'lc-macbeth-nature-in-disorder': '/comics/macbeth/nature-in-disorder.a71b9d145ccb.svg',
  'lc-macbeth-scorpions-in-the-mind': '/comics/macbeth/scorpions-in-the-mind.b53c7455d1c2.svg',
  'lc-macbeth-the-ambush': '/comics/macbeth/the-ambush.ffe91c6af88a.svg',
  'lc-macbeth-the-apparitions': '/comics/macbeth/the-apparitions.3ca1c45377ea.svg',
  'lc-macbeth-the-banquet': '/comics/macbeth/the-banquet.da9644eba59c.svg',
  'lc-macbeth-the-dagger': '/comics/macbeth/the-dagger.2691b360ffff.svg',
  'lc-macbeth-the-discovery': '/comics/macbeth/the-discovery.ca39e056943d.svg',
  'lc-macbeth-the-murder': '/comics/macbeth/the-murder.ef3b50a861b3.svg',
  'lc-macbeth-the-prince-of-cumberland':
    '/comics/macbeth/the-prince-of-cumberland.3bf9e6e0db64.svg',
  'lc-macbeth-the-prophecies': '/comics/macbeth/the-prophecies.391a31a9214f.svg',
  'lc-macbeth-the-sleepwalking': '/comics/macbeth/the-sleepwalking.f8e10dfe7d13.svg',
  'lc-macbeth-the-witches': '/comics/macbeth/the-witches.589124f7faab.svg',
  'lc-macbeth-the-witches-meet': '/comics/macbeth/the-witches-meet.15c1c1a68696.svg',
  'lc-macbeth-tomorrow': '/comics/macbeth/tomorrow.cc703e9595d7.svg',
  'lc-much-ado-about-nothing-at-the-tomb':
    '/comics/much-ado-about-nothing/at-the-tomb.899c42a839db.svg',
  'lc-much-ado-about-nothing-beatrice': '/comics/much-ado-about-nothing/beatrice.6844f5460fd8.svg',
  'lc-much-ado-about-nothing-beatrice-in-the-bower':
    '/comics/much-ado-about-nothing/beatrice-in-the-bower.c97d823e515f.svg',
  'lc-much-ado-about-nothing-benedick': '/comics/much-ado-about-nothing/benedick.d4cefd5668c5.svg',
  'lc-much-ado-about-nothing-benedick-in-the-garden':
    '/comics/much-ado-about-nothing/benedick-in-the-garden.16e4881de17b.svg',
  'lc-much-ado-about-nothing-borachio': '/comics/much-ado-about-nothing/borachio.a74be4a01b12.svg',
  'lc-much-ado-about-nothing-borachio-s-plan':
    '/comics/much-ado-about-nothing/borachio-s-plan.99a4c585ab4a.svg',
  'lc-much-ado-about-nothing-challenges-and-confession':
    '/comics/much-ado-about-nothing/challenges-and-confession.0cd3f10e53f7.svg',
  'lc-much-ado-about-nothing-claudio': '/comics/much-ado-about-nothing/claudio.0a8696ac2fe0.svg',
  'lc-much-ado-about-nothing-dogberry': '/comics/much-ado-about-nothing/dogberry.9f9151a6ce8a.svg',
  'lc-much-ado-about-nothing-don-john': '/comics/much-ado-about-nothing/don-john.778dcdeb1247.svg',
  'lc-much-ado-about-nothing-don-john-s-accusation':
    '/comics/much-ado-about-nothing/don-john-s-accusation.037d470704d5.svg',
  'lc-much-ado-about-nothing-don-john-s-discontent':
    '/comics/much-ado-about-nothing/don-john-s-discontent.e553bf21cb69.svg',
  'lc-much-ado-about-nothing-don-pedro':
    '/comics/much-ado-about-nothing/don-pedro.b9d588ca9ac4.svg',
  'lc-much-ado-about-nothing-hero': '/comics/much-ado-about-nothing/hero.569bacba1d8e.svg',
  'lc-much-ado-about-nothing-kill-claudio':
    '/comics/much-ado-about-nothing/kill-claudio.84daff1ec068.svg',
  'lc-much-ado-about-nothing-leonato': '/comics/much-ado-about-nothing/leonato.98330d888d53.svg',
  'lc-much-ado-about-nothing-margaret': '/comics/much-ado-about-nothing/margaret.e19c820bce81.svg',
  'lc-much-ado-about-nothing-the-examination':
    '/comics/much-ado-about-nothing/the-examination.feb670547f64.svg',
  'lc-much-ado-about-nothing-the-masked-ball':
    '/comics/much-ado-about-nothing/the-masked-ball.6cd5338026b2.svg',
  'lc-much-ado-about-nothing-the-second-wedding':
    '/comics/much-ado-about-nothing/the-second-wedding.4f3a4cabbaa8.svg',
  'lc-much-ado-about-nothing-the-soldiers-come-home':
    '/comics/much-ado-about-nothing/the-soldiers-come-home.daa6589a141c.svg',
  'lc-much-ado-about-nothing-the-watch-overhear':
    '/comics/much-ado-about-nothing/the-watch-overhear.e8cdd22fd3f7.svg',
  'lc-much-ado-about-nothing-the-wedding':
    '/comics/much-ado-about-nothing/the-wedding.5acb1694994d.svg',
  'lc-much-ado-about-nothing-too-busy-to-listen':
    '/comics/much-ado-about-nothing/too-busy-to-listen.0e6e78870288.svg',
  'lc-much-ado-about-nothing-verges': '/comics/much-ado-about-nothing/verges.9bc5c43c7202.svg',
  'lc-othello-ambush-in-the-dark': '/comics/othello/ambush-in-the-dark.20d45fbcc1a8.svg',
  'lc-othello-before-the-senate': '/comics/othello/before-the-senate.953671ca682d.svg',
  'lc-othello-bianca': '/comics/othello/bianca.aa47136f213e.svg',
  'lc-othello-brabantio': '/comics/othello/brabantio.d359374b322b.svg',
  'lc-othello-cassio': '/comics/othello/cassio.7e40f5eebe08.svg',
  'lc-othello-desdemona': '/comics/othello/desdemona.ee8c6b8df1df.svg',
  'lc-othello-emilia': '/comics/othello/emilia.3e42bb9e952c.svg',
  'lc-othello-emilia-speaks': '/comics/othello/emilia-speaks.4b2bba4148b1.svg',
  'lc-othello-iago': '/comics/othello/iago.6909225dd979.svg',
  'lc-othello-iago-s-plan-is-born': '/comics/othello/iago-s-plan-is-born.289d6bb38b1c.svg',
  'lc-othello-iago-wakes-venice': '/comics/othello/iago-wakes-venice.49e3e27e8ff0.svg',
  'lc-othello-lodovico': '/comics/othello/lodovico.b198b7dacf98.svg',
  'lc-othello-othello': '/comics/othello/othello.4d799a1034bf.svg',
  'lc-othello-othello-s-last-words': '/comics/othello/othello-s-last-words.c4433fbb9ae9.svg',
  'lc-othello-othello-will-not-hide': '/comics/othello/othello-will-not-hide.96b232807b2a.svg',
  'lc-othello-roderigo': '/comics/othello/roderigo.41b5b27bf800.svg',
  'lc-othello-storm-and-reunion-on-cyprus':
    '/comics/othello/storm-and-reunion-on-cyprus.9c07115217ca.svg',
  'lc-othello-the-accusation': '/comics/othello/the-accusation.000a4a117e1b.svg',
  'lc-othello-the-drunken-brawl': '/comics/othello/the-drunken-brawl.594a57ffcfa4.svg',
  'lc-othello-the-handkerchief-is-dropped':
    '/comics/othello/the-handkerchief-is-dropped.148c45f530b7.svg',
  'lc-othello-the-magic-in-the-handkerchief':
    '/comics/othello/the-magic-in-the-handkerchief.d425533fd95e.svg',
  'lc-othello-the-murder': '/comics/othello/the-murder.cd3cb80ab9d0.svg',
  'lc-othello-the-temptation-begins': '/comics/othello/the-temptation-begins.873b0655cfee.svg',
  'lc-othello-the-trance-and-the-blow': '/comics/othello/the-trance-and-the-blow.8a2ffa3761ba.svg',
  'lc-othello-the-vow-of-revenge': '/comics/othello/the-vow-of-revenge.335b5276a7fb.svg',
  'lc-othello-the-willow-song': '/comics/othello/the-willow-song.fd72683a017f.svg',
  'lc-romeo-and-juliet-a-brawl-in-the-streets':
    '/comics/romeo-and-juliet/a-brawl-in-the-streets.c19f882804bd.svg',
  'lc-romeo-and-juliet-a-glooming-peace':
    '/comics/romeo-and-juliet/a-glooming-peace.e6760b326601.svg',
  'lc-romeo-and-juliet-a-secret-wedding':
    '/comics/romeo-and-juliet/a-secret-wedding.1ece6bc33b0a.svg',
  'lc-romeo-and-juliet-a-suitor-for-juliet':
    '/comics/romeo-and-juliet/a-suitor-for-juliet.4681217f590d.svg',
  'lc-romeo-and-juliet-banished': '/comics/romeo-and-juliet/banished.bc410e5f9a54.svg',
  'lc-romeo-and-juliet-benvolio': '/comics/romeo-and-juliet/benvolio.17577a9b934e.svg',
  'lc-romeo-and-juliet-dawn-and-a-father-s-rage':
    '/comics/romeo-and-juliet/dawn-and-a-father-s-rage.a7047de339a5.svg',
  'lc-romeo-and-juliet-friar-lawrence': '/comics/romeo-and-juliet/friar-lawrence.867151f41235.svg',
  'lc-romeo-and-juliet-juliet': '/comics/romeo-and-juliet/juliet.033e9be57a43.svg',
  'lc-romeo-and-juliet-juliet-drinks-the-potion':
    '/comics/romeo-and-juliet/juliet-drinks-the-potion.b3fb1a242f1a.svg',
  'lc-romeo-and-juliet-juliet-hears-the-news':
    '/comics/romeo-and-juliet/juliet-hears-the-news.43d70ab52fe8.svg',
  'lc-romeo-and-juliet-lady-capulet': '/comics/romeo-and-juliet/lady-capulet.23d750f7a8ef.svg',
  'lc-romeo-and-juliet-lord-capulet': '/comics/romeo-and-juliet/lord-capulet.9e0694a74617.svg',
  'lc-romeo-and-juliet-lord-montague': '/comics/romeo-and-juliet/lord-montague.efe50738cf18.svg',
  'lc-romeo-and-juliet-mercutio': '/comics/romeo-and-juliet/mercutio.9279d944a0a7.svg',
  'lc-romeo-and-juliet-news-in-mantua': '/comics/romeo-and-juliet/news-in-mantua.6133e6912b40.svg',
  'lc-romeo-and-juliet-paris': '/comics/romeo-and-juliet/paris.91b007179257.svg',
  'lc-romeo-and-juliet-prince-escalus': '/comics/romeo-and-juliet/prince-escalus.bf537eec346b.svg',
  'lc-romeo-and-juliet-queen-mab-and-a-warning':
    '/comics/romeo-and-juliet/queen-mab-and-a-warning.1c6a7fb24191.svg',
  'lc-romeo-and-juliet-romeo': '/comics/romeo-and-juliet/romeo.41183198341d.svg',
  'lc-romeo-and-juliet-the-balcony': '/comics/romeo-and-juliet/the-balcony.be68198da3c4.svg',
  'lc-romeo-and-juliet-the-chorus-tells-the-ending':
    '/comics/romeo-and-juliet/the-chorus-tells-the-ending.fdb2b5cc5ffd.svg',
  'lc-romeo-and-juliet-the-feast': '/comics/romeo-and-juliet/the-feast.764b924e815f.svg',
  'lc-romeo-and-juliet-the-friar-agrees':
    '/comics/romeo-and-juliet/the-friar-agrees.4f219dc73ef3.svg',
  'lc-romeo-and-juliet-the-friar-s-plan':
    '/comics/romeo-and-juliet/the-friar-s-plan.49a25fbb9677.svg',
  'lc-romeo-and-juliet-the-letter-that-never-went':
    '/comics/romeo-and-juliet/the-letter-that-never-went.81a05de0404c.svg',
  'lc-romeo-and-juliet-the-nurse': '/comics/romeo-and-juliet/the-nurse.53b90891a5a3.svg',
  'lc-romeo-and-juliet-the-tomb': '/comics/romeo-and-juliet/the-tomb.8570fbbf2e6b.svg',
  'lc-romeo-and-juliet-thursday': '/comics/romeo-and-juliet/thursday.04ce3b031025.svg',
  'lc-romeo-and-juliet-two-deaths-and-a-banishment':
    '/comics/romeo-and-juliet/two-deaths-and-a-banishment.e164ad26f74a.svg',
  'lc-romeo-and-juliet-tybalt': '/comics/romeo-and-juliet/tybalt.3793b9ef8047.svg',
  'lc-romeo-and-juliet-wedding-turned-to-funeral':
    '/comics/romeo-and-juliet/wedding-turned-to-funeral.889fca150359.svg',
  'lc-silas-marner-aaron-winthrop': '/comics/silas-marner/aaron-winthrop.a44a36339c85.svg',
  'lc-silas-marner-blackmail-at-the-red-house':
    '/comics/silas-marner/blackmail-at-the-red-house.52f057bfde15.svg',
  'lc-silas-marner-dolly-s-lard-cakes': '/comics/silas-marner/dolly-s-lard-cakes.51e01e9d695d.svg',
  'lc-silas-marner-dolly-winthrop': '/comics/silas-marner/dolly-winthrop.1fc28168bb3a.svg',
  'lc-silas-marner-dunstan-cass': '/comics/silas-marner/dunstan-cass.84c597c25ebb.svg',
  'lc-silas-marner-eppie': '/comics/silas-marner/eppie.a19a87badc54.svg',
  'lc-silas-marner-eppie-chooses': '/comics/silas-marner/eppie-chooses.df2745f36bfd.svg',
  'lc-silas-marner-eppie-is-named': '/comics/silas-marner/eppie-is-named.b1dffb040787.svg',
  'lc-silas-marner-fifteen-years-at-the-loom':
    '/comics/silas-marner/fifteen-years-at-the-loom.ad7dd26a00b0.svg',
  'lc-silas-marner-framed-at-lantern-yard':
    '/comics/silas-marner/framed-at-lantern-yard.8bd960467984.svg',
  'lc-silas-marner-godfrey-cass': '/comics/silas-marner/godfrey-cass.1ac41135da44.svg',
  'lc-silas-marner-godfrey-fails-to-confess':
    '/comics/silas-marner/godfrey-fails-to-confess.6cf3a3f08238.svg',
  'lc-silas-marner-godfrey-s-silence': '/comics/silas-marner/godfrey-s-silence.2be9c40bd812.svg',
  'lc-silas-marner-lantern-yard-is-gone':
    '/comics/silas-marner/lantern-yard-is-gone.59988ba22440.svg',
  'lc-silas-marner-molly-farren': '/comics/silas-marner/molly-farren.f902ef21d357.svg',
  'lc-silas-marner-nancy-lammeter': '/comics/silas-marner/nancy-lammeter.6ccb12b9c2b5.svg',
  'lc-silas-marner-nancy-s-sunday': '/comics/silas-marner/nancy-s-sunday.3abff46f3e03.svg',
  'lc-silas-marner-priscilla-lammeter': '/comics/silas-marner/priscilla-lammeter.778b91d418a3.svg',
  'lc-silas-marner-robbed': '/comics/silas-marner/robbed.816781bde5fc.svg',
  'lc-silas-marner-sarah': '/comics/silas-marner/sarah.0f2c8dd8d829.svg',
  'lc-silas-marner-silas-at-the-red-house':
    '/comics/silas-marner/silas-at-the-red-house.6a2c0142ad0a.svg',
  'lc-silas-marner-silas-marner': '/comics/silas-marner/silas-marner.2c03a056d8cd.svg',
  'lc-silas-marner-sixteen-years-later':
    '/comics/silas-marner/sixteen-years-later.22a6882e1836.svg',
  'lc-silas-marner-squire-cass': '/comics/silas-marner/squire-cass.573bdf030287.svg',
  'lc-silas-marner-the-child-in-the-snow':
    '/comics/silas-marner/the-child-in-the-snow.0114177a0f1f.svg',
  'lc-silas-marner-the-new-year-s-eve-dance':
    '/comics/silas-marner/the-new-year-s-eve-dance.427e2941ba7a.svg',
  'lc-silas-marner-the-robbery': '/comics/silas-marner/the-robbery.bce949481406.svg',
  'lc-silas-marner-the-stone-pit-gives-up-its-secret':
    '/comics/silas-marner/the-stone-pit-gives-up-its-secret.1e7616230e5e.svg',
  'lc-silas-marner-the-wedding': '/comics/silas-marner/the-wedding.c1a1e9a321e7.svg',
  'lc-silas-marner-too-late': '/comics/silas-marner/too-late.5c3a29d92342.svg',
  'lc-silas-marner-william-dane': '/comics/silas-marner/william-dane.0721bd9ded4b.svg',
  'lc-the-merchant-of-venice-antonio': '/comics/the-merchant-of-venice/antonio.8419d86baba4.svg',
  'lc-the-merchant-of-venice-antonio-s-sadness':
    '/comics/the-merchant-of-venice/antonio-s-sadness.20fa297111ed.svg',
  'lc-the-merchant-of-venice-arragon-chooses-silver':
    '/comics/the-merchant-of-venice/arragon-chooses-silver.e27ecf32df32.svg',
  'lc-the-merchant-of-venice-bassanio': '/comics/the-merchant-of-venice/bassanio.45ebcc05a31b.svg',
  'lc-the-merchant-of-venice-gratiano': '/comics/the-merchant-of-venice/gratiano.b1e81449d2e0.svg',
  'lc-the-merchant-of-venice-hath-not-a-jew-eyes':
    '/comics/the-merchant-of-venice/hath-not-a-jew-eyes.24374301a2e1.svg',
  'lc-the-merchant-of-venice-i-ll-have-my-bond':
    '/comics/the-merchant-of-venice/i-ll-have-my-bond.47f55ede8a10.svg',
  'lc-the-merchant-of-venice-in-such-a-night':
    '/comics/the-merchant-of-venice/in-such-a-night.d9d838be17d3.svg',
  'lc-the-merchant-of-venice-jessica': '/comics/the-merchant-of-venice/jessica.eba3e467596d.svg',
  'lc-the-merchant-of-venice-jessica-leaves-her-father':
    '/comics/the-merchant-of-venice/jessica-leaves-her-father.c269097c1d2f.svg',
  'lc-the-merchant-of-venice-launcelet-gobbo':
    '/comics/the-merchant-of-venice/launcelet-gobbo.c5c2b9c1a276.svg',
  'lc-the-merchant-of-venice-lead-and-a-letter':
    '/comics/the-merchant-of-venice/lead-and-a-letter.e933723b90a0.svg',
  'lc-the-merchant-of-venice-lorenzo': '/comics/the-merchant-of-venice/lorenzo.6bc06373ddf8.svg',
  'lc-the-merchant-of-venice-morocco-chooses-gold':
    '/comics/the-merchant-of-venice/morocco-chooses-gold.77db7b523d9f.svg',
  'lc-the-merchant-of-venice-my-daughter-my-ducats':
    '/comics/the-merchant-of-venice/my-daughter-my-ducats.ba14cfe2d014.svg',
  'lc-the-merchant-of-venice-nerissa': '/comics/the-merchant-of-venice/nerissa.0ce1cc9b49e1.svg',
  'lc-the-merchant-of-venice-portia': '/comics/the-merchant-of-venice/portia.120c9e36283c.svg',
  'lc-the-merchant-of-venice-portia-and-her-father-s-will':
    '/comics/the-merchant-of-venice/portia-and-her-father-s-will.522d9e0af56f.svg',
  'lc-the-merchant-of-venice-portia-s-plan':
    '/comics/the-merchant-of-venice/portia-s-plan.eafa1b9ef7d1.svg',
  'lc-the-merchant-of-venice-shylock': '/comics/the-merchant-of-venice/shylock.b6c37f2f7852.svg',
  'lc-the-merchant-of-venice-the-merry-bond':
    '/comics/the-merchant-of-venice/the-merry-bond.687602f06485.svg',
  'lc-the-merchant-of-venice-the-prince-of-morocco':
    '/comics/the-merchant-of-venice/the-prince-of-morocco.473645c67ce1.svg',
  'lc-the-merchant-of-venice-the-ring-quarrel':
    '/comics/the-merchant-of-venice/the-ring-quarrel.2dbb1f622845.svg',
  'lc-the-merchant-of-venice-the-rings-given-away':
    '/comics/the-merchant-of-venice/the-rings-given-away.a77e1f81c8de.svg',
  'lc-the-merchant-of-venice-the-trial-mercy-refused':
    '/comics/the-merchant-of-venice/the-trial-mercy-refused.3abf9e3432ce.svg',
  'lc-the-merchant-of-venice-the-trial-the-reversal':
    '/comics/the-merchant-of-venice/the-trial-the-reversal.36f43a940e1b.svg',
  'lc-the-merchant-of-venice-tubal': '/comics/the-merchant-of-venice/tubal.0e75f48ef612.svg',
  'lc-the-sign-of-four-abdullah-khan': '/comics/the-sign-of-four/abdullah-khan.7e84f3ae398c.svg',
  'lc-the-sign-of-four-athelney-jones': '/comics/the-sign-of-four/athelney-jones.8d52b5f1ad9e.svg',
  'lc-the-sign-of-four-captain-arthur-morstan':
    '/comics/the-sign-of-four/captain-arthur-morstan.7867e28ef1ae.svg',
  'lc-the-sign-of-four-dr-john-watson': '/comics/the-sign-of-four/dr-john-watson.d75fc1e7c61a.svg',
  'lc-the-sign-of-four-holmes-gives-a-demonstration':
    '/comics/the-sign-of-four/holmes-gives-a-demonstration.c9bddb54b1b4.svg',
  'lc-the-sign-of-four-into-the-fog': '/comics/the-sign-of-four/into-the-fog.6b2847792730.svg',
  'lc-the-sign-of-four-jonathan-small': '/comics/the-sign-of-four/jonathan-small.fd3c2cb071de.svg',
  'lc-the-sign-of-four-major-john-sholto':
    '/comics/the-sign-of-four/major-john-sholto.be3c8a584e23.svg',
  'lc-the-sign-of-four-mary-morstan': '/comics/the-sign-of-four/mary-morstan.f764b8ef2829.svg',
  'lc-the-sign-of-four-mary-s-indifference-to-the-fortune':
    '/comics/the-sign-of-four/mary-s-indifference-to-the-fortune.b5213c6dc84e.svg',
  'lc-the-sign-of-four-miss-morstan-s-statement':
    '/comics/the-sign-of-four/miss-morstan-s-statement.2818a67f6a5d.svg',
  'lc-the-sign-of-four-mrs-cecil-forrester':
    '/comics/the-sign-of-four/mrs-cecil-forrester.2c9b8db1d0f3.svg',
  'lc-the-sign-of-four-sherlock-holmes':
    '/comics/the-sign-of-four/sherlock-holmes.a50a52548981.svg',
  'lc-the-sign-of-four-sholto-s-betrayal-and-small-s-revenge':
    '/comics/the-sign-of-four/sholto-s-betrayal-and-small-s-revenge.3ae9a7c99caa.svg',
  'lc-the-sign-of-four-small-s-story-of-agra':
    '/comics/the-sign-of-four/small-s-story-of-agra.20145da11288.svg',
  'lc-the-sign-of-four-thaddeus-sholto':
    '/comics/the-sign-of-four/thaddeus-sholto.a79ab42150a2.svg',
  'lc-the-sign-of-four-thaddeus-sholto-s-story':
    '/comics/the-sign-of-four/thaddeus-sholto-s-story.2e4066156509.svg',
  'lc-the-sign-of-four-the-baker-street-irregulars':
    '/comics/the-sign-of-four/the-baker-street-irregulars.4d9c65877bad.svg',
  'lc-the-sign-of-four-the-chase-down-the-thames':
    '/comics/the-sign-of-four/the-chase-down-the-thames.9dc33f66ae7e.svg',
  'lc-the-sign-of-four-the-division-of-rewards':
    '/comics/the-sign-of-four/the-division-of-rewards.691b0acbb0c7.svg',
  'lc-the-sign-of-four-the-empty-box': '/comics/the-sign-of-four/the-empty-box.3b64de8096a1.svg',
  'lc-the-sign-of-four-the-locked-room-at-pondicherry-lodge':
    '/comics/the-sign-of-four/the-locked-room-at-pondicherry-lodge.21a7e4e83e10.svg',
  'lc-the-sign-of-four-the-old-sailor': '/comics/the-sign-of-four/the-old-sailor.d2039459294e.svg',
  'lc-the-sign-of-four-the-seven-per-cent-solution':
    '/comics/the-sign-of-four/the-seven-per-cent-solution.f6fd41d7b84c.svg',
  'lc-the-sign-of-four-the-test-of-the-watch':
    '/comics/the-sign-of-four/the-test-of-the-watch.39d81c34d945.svg',
  'lc-the-sign-of-four-toby-and-the-trail-of-creosote':
    '/comics/the-sign-of-four/toby-and-the-trail-of-creosote.429ef958c1e1.svg',
  'lc-the-sign-of-four-tonga': '/comics/the-sign-of-four/tonga.e3078246c047.svg',
  'lc-the-sign-of-four-wiggins': '/comics/the-sign-of-four/wiggins.905db0c80752.svg',
  'lc-the-tempest-alonso': '/comics/the-tempest/alonso.72b13348c05c.svg',
  'lc-the-tempest-antonio': '/comics/the-tempest/antonio.353916ff92f8.svg',
  'lc-the-tempest-ariel': '/comics/the-tempest/ariel.bb4aeab5f8eb.svg',
  'lc-the-tempest-ariel-asks-for-his-freedom':
    '/comics/the-tempest/ariel-asks-for-his-freedom.f644437b3190.svg',
  'lc-the-tempest-caliban': '/comics/the-tempest/caliban.18f1baef8fee.svg',
  'lc-the-tempest-caliban-curses-his-master':
    '/comics/the-tempest/caliban-curses-his-master.4b79b302ec91.svg',
  'lc-the-tempest-caliban-finds-a-new-master':
    '/comics/the-tempest/caliban-finds-a-new-master.ee197b5b64c0.svg',
  'lc-the-tempest-ferdinand': '/comics/the-tempest/ferdinand.f2e5982d8fff.svg',
  'lc-the-tempest-ferdinand-meets-miranda':
    '/comics/the-tempest/ferdinand-meets-miranda.43af30c8a312.svg',
  'lc-the-tempest-gonzalo': '/comics/the-tempest/gonzalo.3b02811fcfa9.svg',
  'lc-the-tempest-miranda': '/comics/the-tempest/miranda.a816b59734f3.svg',
  'lc-the-tempest-prospero': '/comics/the-tempest/prospero.fc9f8cb98513.svg',
  'lc-the-tempest-prospero-asks-to-be-set-free':
    '/comics/the-tempest/prospero-asks-to-be-set-free.e7604bc38b8c.svg',
  'lc-the-tempest-prospero-tells-miranda-the-past':
    '/comics/the-tempest/prospero-tells-miranda-the-past.9767a4dad1df.svg',
  'lc-the-tempest-sebastian': '/comics/the-tempest/sebastian.f3fb4b260a8a.svg',
  'lc-the-tempest-stephano': '/comics/the-tempest/stephano.1a6013dd389f.svg',
  'lc-the-tempest-the-brave-new-world': '/comics/the-tempest/the-brave-new-world.882fe1827426.svg',
  'lc-the-tempest-the-log-bearer-and-the-lovers-vows':
    '/comics/the-tempest/the-log-bearer-and-the-lovers-vows.928bbf275509.svg',
  'lc-the-tempest-the-masque-broken-off':
    '/comics/the-tempest/the-masque-broken-off.bb80bd5bdf0e.svg',
  'lc-the-tempest-the-plot-against-prospero':
    '/comics/the-tempest/the-plot-against-prospero.1bb76f75722f.svg',
  'lc-the-tempest-the-plot-to-kill-the-king':
    '/comics/the-tempest/the-plot-to-kill-the-king.976efa3b8494.svg',
  'lc-the-tempest-the-storm-at-sea': '/comics/the-tempest/the-storm-at-sea.e8660a6d4007.svg',
  'lc-the-tempest-the-vanishing-banquet':
    '/comics/the-tempest/the-vanishing-banquet.aebd8269fd5f.svg',
  'lc-the-tempest-trinculo': '/comics/the-tempest/trinculo.3da13fd09be7.svg',
  'lc-the-tempest-virtue-not-vengeance':
    '/comics/the-tempest/virtue-not-vengeance.cb160bd7b9bf.svg',
  'lc-twelfth-night-a-duel-and-an-arrest':
    '/comics/twelfth-night/a-duel-and-an-arrest.a03c3b72c49e.svg',
  'lc-twelfth-night-a-pearl-and-a-priest':
    '/comics/twelfth-night/a-pearl-and-a-priest.bda85c24fb23.svg',
  'lc-twelfth-night-antonio': '/comics/twelfth-night/antonio.a9a6c8c3e049.svg',
  'lc-twelfth-night-cakes-and-ale': '/comics/twelfth-night/cakes-and-ale.d89073aa3df1.svg',
  'lc-twelfth-night-cesario-sent-to-woo':
    '/comics/twelfth-night/cesario-sent-to-woo.e8e06070c3fc.svg',
  'lc-twelfth-night-feste': '/comics/twelfth-night/feste.f70c1dae8638.svg',
  'lc-twelfth-night-husband': '/comics/twelfth-night/husband.70d280dfa933.svg',
  'lc-twelfth-night-i-am-not-what-i-am':
    '/comics/twelfth-night/i-am-not-what-i-am.31ff28e6de26.svg',
  'lc-twelfth-night-malvolio': '/comics/twelfth-night/malvolio.86dcbcc2c30a.svg',
  'lc-twelfth-night-maria': '/comics/twelfth-night/maria.dfe6a544814c.svg',
  'lc-twelfth-night-mistaken-for-cesario':
    '/comics/twelfth-night/mistaken-for-cesario.df08cf2e169c.svg',
  'lc-twelfth-night-music-for-a-lovesick-duke':
    '/comics/twelfth-night/music-for-a-lovesick-duke.c5150899f1de.svg',
  'lc-twelfth-night-olivia': '/comics/twelfth-night/olivia.8c1604c9cff5.svg',
  'lc-twelfth-night-olivia-unveiled': '/comics/twelfth-night/olivia-unveiled.a2d0091b544e.svg',
  'lc-twelfth-night-one-face-one-voice':
    '/comics/twelfth-night/one-face-one-voice.c077fa32f1f5.svg',
  'lc-twelfth-night-orsino': '/comics/twelfth-night/orsino.0ea9f2a9416f.svg',
  'lc-twelfth-night-patience-on-a-monument':
    '/comics/twelfth-night/patience-on-a-monument.6d898a7c0975.svg',
  'lc-twelfth-night-revels-at-olivia-s-house':
    '/comics/twelfth-night/revels-at-olivia-s-house.341f5c9f0b2b.svg',
  'lc-twelfth-night-sebastian': '/comics/twelfth-night/sebastian.b29f690fe337.svg',
  'lc-twelfth-night-sebastian-is-alive':
    '/comics/twelfth-night/sebastian-is-alive.0abd805c3a05.svg',
  'lc-twelfth-night-shipwrecked-in-illyria':
    '/comics/twelfth-night/shipwrecked-in-illyria.92f17384dd28.svg',
  'lc-twelfth-night-sir-andrew-aguecheek':
    '/comics/twelfth-night/sir-andrew-aguecheek.f3ceb5820dd1.svg',
  'lc-twelfth-night-sir-toby-belch': '/comics/twelfth-night/sir-toby-belch.44ceeef46f29.svg',
  'lc-twelfth-night-the-dark-room': '/comics/twelfth-night/the-dark-room.ea6c63e117ac.svg',
  'lc-twelfth-night-the-letter-in-the-garden':
    '/comics/twelfth-night/the-letter-in-the-garden.d715ebc544b9.svg',
  'lc-twelfth-night-the-ring': '/comics/twelfth-night/the-ring.40323e084646.svg',
  'lc-twelfth-night-the-whole-pack-of-you':
    '/comics/twelfth-night/the-whole-pack-of-you.f91bc59f4877.svg',
  'lc-twelfth-night-the-wind-and-the-rain':
    '/comics/twelfth-night/the-wind-and-the-rain.b65803c46899.svg',
  'lc-twelfth-night-viola': '/comics/twelfth-night/viola.05a28a242834.svg',
  'lc-twelfth-night-yellow-stockings': '/comics/twelfth-night/yellow-stockings.33c69fa03f1e.svg',
}
