/**
 * EAL Topic — CEFR-banded variant (server-rendered).
 *
 * Source: Common European Framework of Reference for Languages (CEFR),
 *   Council of Europe — language-agnostic descriptors of what a learner
 *   "can do" at each band (A1..C2). The English Hub bands each EAL topic
 *   into A2 / B1 / B2 / C1 so an Arabic L1 student can pick the level
 *   matching their current proficiency.
 * https://www.coe.int/en/web/common-european-framework-reference-languages/level-descriptions
 *
 * Cambridge English Qualifications anchor the test-style assessment
 * shape — A2 Key for Schools, B1 Preliminary for Schools, B2 First for
 * Schools, C1 Advanced.
 * https://www.cambridgeenglish.org/exams-and-tests/qualifications/
 */
import Link from 'next/link'
import { headers } from 'next/headers'
import { notFound } from 'next/navigation'
import { findEALTopic } from '@/lib/eal/curriculum'

const LEVELS = ['a2', 'b1', 'b2', 'c1'] as const
type Cefr = (typeof LEVELS)[number]
const LEVEL_LABEL: Record<Cefr, { en: string; ar: string; desc_en: string; desc_ar: string }> = {
  a2: {
    en: 'A2 — Elementary',
    ar: 'A2 — مبتدئ',
    desc_en: 'Can understand sentences and frequently used expressions related to immediate needs.',
    desc_ar: 'يفهم الجمل والتعبيرات الشائعة المتعلقة بالاحتياجات اليومية المباشرة.',
  },
  b1: {
    en: 'B1 — Intermediate',
    ar: 'B1 — متوسط',
    desc_en:
      'Can deal with most situations likely to arise while travelling in an English-speaking country.',
    desc_ar: 'يقدر يتعامل مع معظم المواقف اللي تواجهه في بلد ناطق بالإنجليزية.',
  },
  b2: {
    en: 'B2 — Upper Intermediate',
    ar: 'B2 — فوق المتوسط',
    desc_en:
      'Can interact with fluency and spontaneity, producing detailed text on a wide range of subjects.',
    desc_ar: 'يتفاعل بطلاقة وعفوية، وينتج نصوص مفصّلة في مواضيع متنوعة.',
  },
  c1: {
    en: 'C1 — Advanced',
    ar: 'C1 — متقدّم',
    desc_en:
      'Can express ideas fluently and spontaneously without much obvious searching for expressions.',
    desc_ar: 'يعبّر عن أفكاره بطلاقة وعفوية، بدون بحث واضح عن التعبيرات.',
  },
}

export default async function EALLevelPage({
  params,
}: {
  params: Promise<{ slug: string; cefr: string }>
}) {
  const { slug, cefr } = await params
  const topic = findEALTopic(slug)
  if (!topic) notFound()
  const level = cefr.toLowerCase() as Cefr
  if (!LEVELS.includes(level)) notFound()

  const lang = (await headers()).get('x-lang') === 'ar' ? 'ar' : 'en'
  const tr = (s: { en: string; ar?: string } | undefined): string =>
    s ? (lang === 'ar' && s.ar ? s.ar : s.en) : ''
  const meta = LEVEL_LABEL[level]

  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      <p className="font-mono text-[11px] tracking-[0.14em] uppercase text-teal-600 mb-3">
        <Link href={`/eal/${slug}`}>EAL · {tr(topic.title)}</Link>
      </p>
      <h1 className="font-serif text-3xl sm:text-4xl font-bold tracking-tight mb-2">
        {tr(topic.title)} — {lang === 'ar' ? meta.ar : meta.en}
      </h1>
      <p className="text-base text-muted-foreground leading-relaxed mb-6">
        {lang === 'ar' ? meta.desc_ar : meta.desc_en}
      </p>

      <div className="rounded-xl border border-amber-400/30 bg-amber-500/[0.04] p-5 mb-8">
        <p className="font-mono text-[10px] uppercase tracking-wider text-amber-700 mb-1">
          {lang === 'ar' ? 'قريباً' : 'Coming soon'}
        </p>
        <p className="text-sm text-foreground leading-relaxed">
          {lang === 'ar'
            ? 'محتوى المستوى التفصيلي قيد البناء — يولّد بواسطة سلسلة الموجات الذكية المحلية. تحقق مرة ثانية خلال 6-48 ساعة.'
            : `Detailed ${level.toUpperCase()}-banded content for this topic is being generated by the local AI wave pipeline. Check back in 6–48 hours.`}
        </p>
      </div>

      {/* Sibling levels */}
      <h2 className="text-sm font-semibold mb-3 text-muted-foreground">
        {lang === 'ar' ? 'مستويات أخرى لهذا الموضوع' : 'Other levels for this topic'}
      </h2>
      <div className="grid grid-cols-4 gap-2">
        {LEVELS.map((l) => (
          <Link
            key={l}
            href={`/eal/${slug}/level/${l}`}
            className={`block rounded-lg border p-3 text-center text-sm font-mono uppercase tracking-wider ${
              l === level
                ? 'border-teal-500 bg-teal-500/10 text-teal-700'
                : 'border-border bg-card hover:border-teal-400/60'
            }`}
          >
            {l}
          </Link>
        ))}
      </div>
    </main>
  )
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string; cefr: string }>
}) {
  const { slug, cefr } = await params
  return {
    title: `EAL ${slug} — ${cefr.toUpperCase()} — The English Hub`,
  }
}
