/**
 * persuasive-writing set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Writing Skills`, ar: `مهارات الكتابة` },
  s1: { en: `Persuasive Writing`, ar: `الكتابة الإقناعية` },
  s3: { en: `Show you understand the opposing view`, ar: `أظهر أنك تفهم الرؤية المخالفة` },
  s4: {
    en: `Explain why it is flawed, limited, or misguided`,
    ar: `شوف ليه هي محدودة، مشوهة، أو مبنية على خطأ`,
  },
  s7: { en: `Useful Counter-Argument Phrases`, ar: `عبارات مفيدة للرد على الأفكار المخالفة` },
  s8: { en: `Typical Tone`, ar: `لهجة عادية` },
  s9: { en: `Key Features`, ar: `مميزات رئيسية` },
  s10: { en: `Common Mistake: One-Note Tone`, ar: `خطيئة شائعة: لحن واحد فقط` },
  s11: { en: `Article Structure (5-6 paragraphs)`, ar: `estructure المقال (5 إلى 6 فقرات)` },
  s12: { en: `Speech Structure (5-6 paragraphs)`, ar: `بنية الخطاب (خمسة إلى ستة فقرات)` },
  s13: { en: `Point-Counterpoint (Debate Style)`, ar: `نقاط مقابل نقاط (أسلوب مناظرة)` },
  s14: { en: `Building Argument (Crescendo)`, ar: `بناء الحجة (الم amplification)` },
  s16: {
    en: `Bold, attention-grabbing, often using alliteration, a pun, or a provocative statement.`,
    ar: `جاذب للانتباه، يستخدم التكرار الصوتي، لعب الكلمات، أو تصريح مثير.`,
  },
  s17: { en: `Strapline / Standfirst`, ar: `خط step_here للسطر الأول / العرض الأول` },
  s18: {
    en: `Break up the text and guide the reader. Should be informative, not vague.`,
    ar: `فكّر في تقسيم النص إلى أجزاء صغيرة وشروحات لكل جزء تكون مفيدة للقارئ. لا تجعلها غامضة بل واضحة ومحددة.`,
  },
  s19: {
    en: `The author&apos;s name. Optional in exams but shows form awareness.`,
    ar: `اسم الكاتب. اختياري في الامتحانات لكن يظهر وعى الشكل.`,
  },
  s20: { en: `Formal Letter`, ar: `carta رسمية` },
  s21: {
    en: `Your address (top right), recipient&apos;s address (left, below yours), date below that.`,
    ar: `عنوانك (في اليمين العلوي)، عنوان المستلم (يسارًا، تحت عنوانك)، التاريخ أسفله.`,
  },
  s23: { en: `Direct Address`, ar: `التحية المباشرة` },
  s24: {
    en: `Address your audience directly throughout. &ldquo;You,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; &ldquo;our.&rdquo;`,
    ar: `إحنا بن.addressكم مباشرة خلال كل شيء. إحنا، أنت، إحنا، إحنا، أونا.`,
  },
  s25: { en: `Rhetorical Pauses`, ar: `تقطيعات رhetorical` },
  s26: {
    en: `Short sentences, fragments, or dashes to create natural pauses for emphasis.`,
    ar: `جمل صغيرة أو شذرات أو إشارات توقف لخلق فواصل طبيعية للتوظيف`,
  },
  s27: { en: `Inclusive Language`, ar: `لغة شاملة` },
  s28: {
    en: `Use &ldquo;we&rdquo; and &ldquo;together&rdquo; to unite the audience with the speaker.`,
    ar: `استخدم &ldquo; إحنا &rdquo; و &ldquo; مع بعض &rdquo; لتوحيد الجمهور مع المتحدث.`,
  },
  s29: { en: `Repetition / Anaphora`, ar: `تكرار / أنانافورا` },
  s30: {
    en: `Repeat a phrase at the start of consecutive sentences for rhythmic, memorable impact.`,
    ar: `ặphta الكلمات في بداية الجمل التالية لتأثير ترتيبي وذاكراني:`,
  },
  s31: {
    en: `Clear and factual: &ldquo;Report on [Topic] for [Audience]&rdquo;`,
    ar: `-&ldquo;تقرير عن [الموضوع] لـ [الجمهور]&rdquo;`,
  },
  s32: {
    en: `Formal Tone`,
    ar: `لهجتك الرسمية شلون؟ ابغى أتأكد إنو ما في مشكلة. إذا كان عندك موضوع معين تحب نتكلم عنه بال لهجة الرسمية، قول لي شنو.`,
  },
  s33: {
    en: `Third person, impersonal, no emotional language. &ldquo;It was observed that...&rdquo;`,
    ar: `شوف إنو ملاحظ إنه...`,
  },
  s34: {
    en: `Organise findings clearly: Introduction, Findings, Conclusion, Recommendations.`,
    ar: `انظم النتائج بشكل واضح: مقدمة، نتائج، خاتمة، توصيات.`,
  },
  s35: {
    en: `End with actionable suggestions: &ldquo;It is recommended that...&rdquo;`,
    ar: `يجب أن تنتهي بتوصيات عملية: "من المستحسن أن... "&ldquo;`,
  },
  s36: { en: `Balanced Opinion`, ar: `رأي متوازن` },
  s37: {
    en: `Present both positives and negatives, but make your overall verdict clear. Avoid fence-sitting.`,
    ar: `أعرض كلاً من الإيجابيات والسلبيات، لكن جعل حكمك النهائي واضحًا. ابتعد عن الحياد.`,
  },
  s38: { en: `Star Rating / Verdict`, ar: `تقييم النجمة / الحكم` },
  s39: {
    en: `Optional but shows form awareness. A clear final verdict: &ldquo;Worth seeing&rdquo; or &ldquo;Give it a miss.&rdquo;`,
    ar: `&wla;&njl; مشهود له بأشكاله&rdquo; أو &wla;&njl; خلوها تعديك&rdquo;.`,
  },
  s40: { en: `Descriptive Detail`, ar: `تفاصيل وصفية` },
  s41: {
    en: `Describe what you are reviewing vividly so the reader can picture or imagine it.`,
    ar: `وصف ما تراجعه بوضوح ليتمكن القارئ من تخيله أو تصويره في خياله.`,
  },
  s42: { en: `Personal Voice`, ar: `الصوت الشخصي` },
  s44: {
    en: `End with a clear recommendation to a specific audience: &ldquo;Perfect for fans of...&rdquo; or &ldquo;Avoid if you...&rdquo;`,
    ar: `Ideal lii lbabati min...`,
  },
  s45: {
    en: `Compare to similar products, films, books, or restaurants to give the reader a frame of reference.`,
    ar: ``,
  },
  s46: { en: `Article Template`, ar: `قالمة المقالة` },
  s47: { en: `By [Your Name]`, ar: `بواسطة [اسمك]` },
  s48: { en: `Key Conventions Checklist`, ar: `قائمة المعايير الأساسية` },
  s49: {
    en: `Example Opening Paragraph`,
    ar: `إحنا في هاي الصفحة راح نستعرض أهم النقاط اللي حابين نذاكرها قبل الامتحان. أبغى منك تقرأ النصوص المهمة وتراجع التمارين اللي عملتها إحنا في الفصل. وايد الطلاب بيقولوا إن الدوران على المواضيع الأساسية والتأكد من ف`,
  },
  s50: { en: `Formal Letter Template`, ar: `قالب خطاب رسمي` },
  s51: {
    en: `Dear [Mr/Mrs/Ms Surname / Sir or Madam],`,
    ar: `عزيزي [سيد أو سيدتي الاسم العائلة]،`,
  },
  s52: { en: `Yours [faithfully/sincerely],`, ar: `مع خالص تحياتي،` },
  s53: { en: `Speech Template`, ar: `قالمemplate` },
  s54: { en: `Report Template`, ar: `نموذج التقرير` },
  s55: { en: `Report on [Topic]`, ar: `تقرير عن [الموضوع]` },
  s56: {
    en: `Prepared for: [Audience] | Date: [Date] | Prepared by: [Your Name]`,
    ar: `مستعد لـ: [الجمهور] | التاريخ: [التاريخ] | مستعد من قبل: [اسمك]`,
  },
  s58: {
    en: `Reviewed by [Your Name] | Rating: [Stars or verdict]`,
    ar: `مراجع بواسطة [اسمك] | التقييم: [نجوم أو حكم]`,
  },
  s59: { en: `Connectives for Persuasion`, ar: `connectors for persuasion` },
  s60: { en: `Word Choice: Weak vs. Strong`, ar: `اختيار الكلمات: الضعيف مقابل القوي` },
  s61: { en: `Weak (avoid)`, ar: `ضعيف (تجنب)` },
  s62: { en: `Strong (use instead)`, ar: `قوي (استخدم بدلاً من)` },
  s63: { en: `Why it works`, ar: `شنو اللي جعله كذا؟` },
  s65: {
    en: `The Screen That Steals: How Social Media Is Robbing a Generation`,
    ar: `الشاشة التي تسرق: كيف وسائل التواصل الاجتماعي تستولي على جيل`,
  },
  s66: {
    en: `As likes replace friendships and scrolling replaces sleeping, experts warn we are sleepwalking into a mental health catastrophe.`,
    ar: `مع تحوّل الإعجابات إلى صداقات وتصفح الشاشة ي remplacer النوم، تحذِر الخبراء من أننا نسير في سبات نحو كارثة صحية نفسية. 

(_correction: replace "يرemplacer" with proper Khaleeji Arabic equivalent for "replaces", which should be "يحل محل")_

مع تحوّل الإعجابات إلى صداقات وتصفح الشاشة يحل محل النوم، تحذِر الخبراء من أننا نسير في سبات نحو كارثة صحية نفسية.`,
  },
  s67: {
    en: `By the time the average British teenager turns 18, they will have spent approximately 35,000 hours staring at a screen.`,
    ar: `بحين ما يوصل المراهق البريطاني العادي eighteen سنة، يكون قعد وايد على راس 35,000 ساعة شايف الشاشة.`,
  },
  s68: { en: `Can we really call this progress?`, ar: `هل يمكننا حقاً أن نسمى هذا التقدم؟` },
  s69: { en: `The Comparison Trap`, ar: `فخ المقارنة` },
  s70: { en: `If you are a parent reading this`, ar: `إذا كنت والدًا تقرأ هذا` },
  s73: {
    en: `Thirty-five thousand hours is four years.`,
    ar: `ثلاثة وثلاثون ألف ساعة هي أربع سنوات.`,
  },
  s74: { en: `Why This Response Works`, ar: `شنو اللي بغى من هالرد؟` },
  s75: {
    en: `Correct article format: headline, strapline, subheading, byline-ready`,
    ar: `صيغة المقال الصحيحة: عنوان، شريط تحت العنوان، فرعي، جاهز لل crédit auteur`,
  },
  s76: {
    en: `All AFOREST techniques deployed naturally (not forced)`,
    ar: `جميع تقنيات AFOREST مستخدمة بشكل طبيعي (لا قسرية)`,
  },
  s77: {
    en: `Counter-argument acknowledged and dismantled`,
    ar: `الم phản_argument معترف به وتم تدميره`,
  },
  s78: {
    en: `Varied tone: authoritative (opening), passionate (middle), urgent (closing)`,
    ar: `لهجتك متنوعة: قوية في البداية، حماسية في الوسط، عاجلة في النهاية`,
  },
  s79: {
    en: `Circular structure: opens and closes with the &ldquo;35,000 hours&rdquo; statistic`,
    ar: `โครงสร้างวงกลม: يبدأ وينتهي بحصيلة &ldquo;35,000 ساعة&rdquo;

(Note: The provided text seems to contain a mix of languages and concepts that don't fit the Khaleeji Arabic style requested. I've translated it literally into another language as an example, but for Khaleeji Arabic specifically:

يبدأ وينتهي بحصيلة "35,000 ساعة" بشكل دوري)`,
  },
  s80: {
    en: `Direct address shifts the argument from abstract to personal`,
    ar: `تحويل الخطاب يhift ال_argument_ منbstract إلى شخصي الحين`,
  },
  s81: {
    en: `Vocabulary is precise and ambitious without being overwrought`,
    ar: `اللغة دقيقة وطموحة دون أن تكون متكلفة`,
  },
  s82: {
    en: `Good morning, teachers, students, and staff.`,
    ar: `صباح الخير، معلمين، طلاب، وموظفين.`,
  },
  s83: { en: `The science is unambiguous.`, ar: `العلم واضح بشكل لا لبس فيه.` },
  s84: { en: `We have all felt it.`, ar: `إحنا كلكم شفناه وحسين عليه.` },
  s85: {
    en: `This is science being ignored because tradition is more convenient than change.`,
    ar: `هاد علم م.ignore لأنه التراث أسهل من التغيير.`,
  },
  s87: { en: `We are not asking for less work.`, ar: `إحنا ما نسألكم على شغل أقل.` },
  s89: {
    en: `Correct speech conventions: direct address, inclusive language, rhetorical devices`,
    ar: ``,
  },
  s90: {
    en: `Clear structure: hook &rarr; evidence &rarr; shared experience &rarr; counter-argument &rarr; anecdote &rarr; call to action`,
    ar: `estructure واضحة: جذب &rarr; دليل &rarr; تجربة مشتركة &rarr; حجة مخالفة &rarr; قصة شخصية &rarr; نداء إلى العملactionDate：2023-10-14 18:15:06 UTC`,
  },
  s91: {
    en: `AFOREST techniques woven in naturally: statistics, rhetorical questions, emotive language, rule of three`,
    ar: `تقنيات AFOREST بشكل طبيعي: الإحصائيات، الأسئلة البليغة، اللغة العاطفية، قاعدة الثلاثة`,
  },
  s92: {
    en: `Counter-argument handled respectfully but firmly`,
    ar: `جواب الم phản علشان وداعة لكن قوي`,
  },
  s93: {
    en: `Personal anecdote provides emotional grounding`,
    ar: `anedoebaat shakhshiyy ta'amuz alshaffafah alshakhsiya`,
  },
  s94: {
    en: `Anaphora and repetition create a speech-like rhythm that works when read aloud`,
    ar: ``,
  },
  s95: {
    en: `Circular structure: &ldquo;I am tired&rdquo; opens and closes the speech, but the meaning deepens`,
    ar: `โครงสร้างวงกลม: "&ldquo;أنا متعب"&rdquo; يفتح ويكمل الخطاب، لكن المعنى يتعمق`,
  },
  s97: { en: `AFOREST Techniques`, ar: `تقنيات أفورست` },
  s98: { en: `Counter-Argument Technique`, ar: `TECHNIQUE للرد على الحجة` },
  s99: { en: `Tone and Register`, ar: `توني و_registro_` },
  s100: { en: `Structural Approaches`, ar: `` },
  s101: { en: `Format Conventions`, ar: `` },
  s102: {
    en: `Format Templates &amp; Example Openings`,
    ar: `قالت المعلمة: «هلاً بيك! شلونك اليوم؟ أبغى أساعدك في أي شيء من دروس الإنجليزي؟»

هنا بعض القوالب اللي يمكن استخدامها:

قوالب الأسئلة:
- شنو اسمك؟
- مين معلمتك بالمدرسة؟
- شلون أول يوم لك في الفصل الجديد؟

قوالب الأجوبة:
- الحين بخير، شكراً.
- أبغى أساعد زميلاتي وزميلي بالواجب المنزلي`,
  },
  s103: { en: `Vocabulary for Persuasion`, ar: `لغة للإقناع` },
  s104: { en: `Model Response: Persuasive Article`, ar: `مقال مقنع` },
  s105: { en: `Model Response: Speech`, ar: `نموذج الجواب: الكلام` },
  s106: { en: `Common Mistakes to Avoid`, ar: `أخطاء شائعة يجب تجنبها` },
}
