import Link from "next/link";

/* ─── Types ──────────────────────────────────────────────────── */

type DisclaimerVariant = "footer" | "content" | "ai-feedback" | "marketing";

interface ExamBoardDisclaimerProps {
  /** @default "content" */
  variant?: DisclaimerVariant;
  className?: string;
  /** @deprecated No longer used — kept for API compatibility */
  selectedBoard?: string | null;
}

/* ─── Shared copy ────────────────────────────────────────────── */

const FULL_DISCLAIMER =
  "The English Hub is an independent educational platform. GCSE is a registered trademark of Ofqual. IGCSE is a registered trademark of Cambridge Assessment International Education.";

const AI_DISCLAIMER =
  "This feedback is generated by AI and is for practice purposes only. It does not represent an official assessment. Actual exam results may differ.";

const COMPACT_DISCLAIMER =
  "The English Hub is an independent educational platform.";

const MARKETING_DISCLAIMER =
  "The English Hub is an independent educational platform.";

/* ─── Info icon (inline SVG to avoid extra dependencies) ─────── */

function InfoIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      className={className ?? "h-4 w-4"}
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
      strokeWidth={2}
      aria-hidden="true"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
      />
    </svg>
  );
}

/* ─── Warning icon for AI feedback ───────────────────────────── */

function WarningIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      className={className ?? "h-4 w-4"}
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
      strokeWidth={2}
      aria-hidden="true"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4.5c-.77-.833-2.694-.833-3.464 0L3.34 16.5c-.77.833.192 2.5 1.732 2.5z"
      />
    </svg>
  );
}

/* ─── Variant renderers ──────────────────────────────────────── */

function FooterDisclaimer({ className }: { className?: string }) {
  return (
    <div
      className={`border-t border-primary/20 pt-4 ${className ?? ""}`}
      role="contentinfo"
      aria-label="Exam board disclaimer"
    >
      <p className="text-xs leading-relaxed text-muted-foreground">
        {FULL_DISCLAIMER}
      </p>
    </div>
  );
}

function ContentDisclaimer({ className }: { className?: string }) {
  return (
    <div
      className={`flex items-start gap-2 rounded-lg border border-border bg-background px-3 py-2 ${className ?? ""}`}
      role="note"
      aria-label="Exam board disclaimer"
    >
      <InfoIcon className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
      <p className="text-xs leading-relaxed text-muted-foreground">
        {COMPACT_DISCLAIMER}{" "}
        <Link
          href="/legal/disclaimer"
          className="font-medium text-primary underline underline-offset-2 hover:text-primary/80 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-1 rounded-sm"
        >
          Full disclaimer
        </Link>
      </p>
    </div>
  );
}

function AiFeedbackDisclaimer({ className }: { className?: string }) {
  return (
    <div
      className={`flex items-start gap-2 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 ${className ?? ""}`}
      role="alert"
      aria-label="AI feedback disclaimer"
    >
      <WarningIcon className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
      <p className="text-xs leading-relaxed text-amber-800">
        {AI_DISCLAIMER}
      </p>
    </div>
  );
}

function MarketingDisclaimer({ className }: { className?: string }) {
  return (
    <p
      className={`text-xs text-muted-foreground ${className ?? ""}`}
      role="note"
      aria-label="Exam board disclaimer"
    >
      {MARKETING_DISCLAIMER}
    </p>
  );
}

/* ─── Main component ─────────────────────────────────────────── */

export function ExamBoardDisclaimer({
  variant = "content",
  className,
  selectedBoard,
}: ExamBoardDisclaimerProps) {
  switch (variant) {
    case "footer":
      return <FooterDisclaimer className={className} />;
    case "content":
      return <ContentDisclaimer className={className} />;
    case "ai-feedback":
      return <AiFeedbackDisclaimer className={className} />;
    case "marketing":
      return <MarketingDisclaimer className={className} />;
  }
}
