import Link from "next/link";

/* ─── Types ──────────────────────────────────────────────────── */

type DisclaimerVariant = "footer" | "content" | "ai-feedback" | "marketing";

interface ExamBoardDisclaimerProps {
  /** @default "content" */
  variant?: DisclaimerVariant;
  className?: string;
  /** When provided, disclaimers reference only this board instead of listing all boards. */
  selectedBoard?: string | null;
}

/* ─── Board display names ────────────────────────────────────── */

const BOARD_DISPLAY_NAMES: Record<string, string> = {
  AQA: "AQA",
  EDEXCEL: "Pearson Edexcel",
  Edexcel: "Pearson Edexcel",
  CAMBRIDGE: "Cambridge International (CAIE)",
  CAIE: "Cambridge International (CAIE)",
  OCR: "OCR",
};

function boardDisplayName(board: string): string {
  return BOARD_DISPLAY_NAMES[board] ?? board;
}

/* ─── Shared copy ────────────────────────────────────────────── */

const FULL_DISCLAIMER =
  "The English Hub is an independent educational platform. We are not affiliated with, endorsed by, or connected to AQA, Pearson Edexcel, Cambridge International (CAIE), OCR, or any other exam board. GCSE is a registered trademark of Ofqual. IGCSE is a registered trademark of Cambridge Assessment International Education.";

function boardSpecificFullDisclaimer(board: string): string {
  const name = boardDisplayName(board);
  return `The English Hub is an independent educational platform. We are not affiliated with, endorsed by, or connected to ${name} or any other exam board. GCSE is a registered trademark of Ofqual. IGCSE is a registered trademark of Cambridge Assessment International Education.`;
}

const AI_DISCLAIMER =
  "This feedback is generated by AI and is for practice purposes only. It does not represent an official exam board assessment. Actual exam results may differ.";

function boardSpecificAiDisclaimer(board: string): string {
  const name = boardDisplayName(board);
  return `This feedback is generated by AI and is for practice purposes only. It does not represent an official ${name} assessment. Actual exam results may differ.`;
}

const COMPACT_DISCLAIMER =
  "The English Hub is independent and not affiliated with any exam board.";

function boardSpecificCompactDisclaimer(board: string): string {
  const name = boardDisplayName(board);
  return `The English Hub is independent and not affiliated with ${name} or any other exam board.`;
}

const MARKETING_DISCLAIMER =
  "The English Hub is an independent platform, not affiliated with or endorsed by any exam board.";

/* ─── Info icon (inline SVG to avoid extra dependencies) ─────── */

function InfoIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      className={className ?? "h-4 w-4"}
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
      strokeWidth={2}
      aria-hidden="true"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
      />
    </svg>
  );
}

/* ─── Warning icon for AI feedback ───────────────────────────── */

function WarningIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      className={className ?? "h-4 w-4"}
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
      strokeWidth={2}
      aria-hidden="true"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4.5c-.77-.833-2.694-.833-3.464 0L3.34 16.5c-.77.833.192 2.5 1.732 2.5z"
      />
    </svg>
  );
}

/* ─── Variant renderers ──────────────────────────────────────── */

function FooterDisclaimer({ className, selectedBoard }: { className?: string; selectedBoard?: string | null }) {
  const text = selectedBoard
    ? boardSpecificFullDisclaimer(selectedBoard)
    : FULL_DISCLAIMER;

  return (
    <div
      className={`border-t border-[#1A5276]/20 pt-4 ${className ?? ""}`}
      role="contentinfo"
      aria-label="Exam board disclaimer"
    >
      <p className="text-xs leading-relaxed text-gray-400">
        {text}
      </p>
    </div>
  );
}

function ContentDisclaimer({ className, selectedBoard }: { className?: string; selectedBoard?: string | null }) {
  const text = selectedBoard
    ? boardSpecificCompactDisclaimer(selectedBoard)
    : COMPACT_DISCLAIMER;

  return (
    <div
      className={`flex items-start gap-2 rounded-lg border border-gray-200 bg-gray-50 px-3 py-2 ${className ?? ""}`}
      role="note"
      aria-label="Exam board disclaimer"
    >
      <InfoIcon className="mt-0.5 h-4 w-4 shrink-0 text-[#1A5276]" />
      <p className="text-xs leading-relaxed text-gray-600">
        {text}{" "}
        <Link
          href="/legal/terms"
          className="font-medium text-[#1A5276] underline underline-offset-2 hover:text-[#1A5276]/80 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1A5276] focus-visible:ring-offset-1 rounded-sm"
        >
          Full disclaimer
        </Link>
      </p>
    </div>
  );
}

function AiFeedbackDisclaimer({ className, selectedBoard }: { className?: string; selectedBoard?: string | null }) {
  const text = selectedBoard
    ? boardSpecificAiDisclaimer(selectedBoard)
    : AI_DISCLAIMER;

  return (
    <div
      className={`flex items-start gap-2 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 ${className ?? ""}`}
      role="alert"
      aria-label="AI feedback disclaimer"
    >
      <WarningIcon className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
      <p className="text-xs leading-relaxed text-amber-800">
        {text}
      </p>
    </div>
  );
}

function MarketingDisclaimer({ className }: { className?: string }) {
  return (
    <p
      className={`text-xs text-gray-500 ${className ?? ""}`}
      role="note"
      aria-label="Exam board disclaimer"
    >
      {MARKETING_DISCLAIMER}
    </p>
  );
}

/* ─── Main component ─────────────────────────────────────────── */

export function ExamBoardDisclaimer({
  variant = "content",
  className,
  selectedBoard,
}: ExamBoardDisclaimerProps) {
  switch (variant) {
    case "footer":
      return <FooterDisclaimer className={className} selectedBoard={selectedBoard} />;
    case "content":
      return <ContentDisclaimer className={className} selectedBoard={selectedBoard} />;
    case "ai-feedback":
      return <AiFeedbackDisclaimer className={className} selectedBoard={selectedBoard} />;
    case "marketing":
      return <MarketingDisclaimer className={className} />;
  }
}
