/**
 * merchant-of-venice set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s1: { en: `Key Moments`, ar: `لحظات حاسمة` },
  s2: { en: `Lancelot Gobbo`, ar: `لانسلوت جوبو` },
  s3: { en: `Justice vs Mercy`, ar: `العدالة مقابل الرحمة` },
  s4: { en: `Prejudice and Anti-Semitism`, ar: `التعصب واليهودية المضادة` },
  s5: { en: `Love and Friendship`, ar: `الحب والصداقة` },
  s6: { en: `Appearance vs Reality`, ar: `внешний вид مقابل الواقع` },
  s8: { en: `Gender and Disguise`, ar: `جنس وتمويه` },
  s9: { en: `Bassanio and Others`, ar: `باسيو وآخرين` },
  s10: { en: `Elizabethan Attitudes to Jews`, ar: `اتجاهات العصر الإليزابيثي نحو اليهود` },
  s11: {
    en: `Usury and Moneylending`,
    ar: `فوائد مرتفعة وقرض Tiền переведён с использованием неправильного языка (китайский). Я переведу текст на основе заданных правил для кхалиджского арабского:

 الربا والقروض`,
  },
  s12: { en: `Venice as a Setting`, ar: `فيسيه كموقع تجريبي` },
  s13: { en: `Marriage and the Law`, ar: `الزواج والقانون` },
  s14: { en: `Religious Conversion`, ar: `التحويل الديني` },
  s15: { en: `Structure of the Scene`, ar: `estructure التمثيلية` },
  s16: { en: `What Happens`, ar: `ماhtub7 يصير` },
  s17: { en: `Key Techniques`, ar: `TECHNIQUES الرئيسية` },
  s18: {
    en: `The Duke appeals to Shylock for mercy. Shylock refuses, citing the law and his &ldquo;humour.&rdquo;`,
    ar: `الدوكن يسألك شيلوك على رحمه. شيلوك ما يقبل، معتمد على القانون وHumourه.`,
  },
  s19: {
    en: `Shylock&apos;s animal imagery (rats, pigs) dehumanises his own position. The Duke&apos;s bias is clear.`,
    ar: `صور شيلوك الحيوانية (الفئران، الخنازير) تقلل من إنسانيته في موقفه. التحيز للدوق واضح.`,
  },
  s20: { en: `Bassanio&apos;s offer`, ar: `عرض باسانيو` },
  s22: {
    en: `The escalating offers show desperation. Shylock&apos;s refusal proves this is about principle (revenge), not profit.`,
    ar: `العروض المتصاعدة تدل على اليأس. رفض شايلوك يثبت أن هذا عن مبدأ (الثأر)، وليس ربح.`,
  },
  s23: { en: `Portia&apos;s mercy speech`, ar: `خطبة برتشا عن الرحمة` },
  s24: {
    en: `Disguised as Balthazar, Portia delivers the &ldquo;quality of mercy&rdquo; speech.`,
    ar: `Maskanā fī sharīʿat Balthazar, Portia tudkhiru kalam al-kamāl al-raʾfah.`,
  },
  s25: {
    en: `Religious imagery, natural imagery (rain). Rhetorical persuasion. Dramatic irony: the audience knows this is Portia.`,
    ar: `صور رمزية دينية، صور رمزية طبيعية (المطر). إقناع بلاغي. حذلقة درامية: المشاهدون يعرفون إن هذا بورشيا.`,
  },
  s26: {
    en: `Portia seems to rule for Shylock, then reveals the technicality: flesh but no blood, exactly one pound.`,
    ar: `بورتيا تبدو كأنها تحكم لشيلوك، ثمتكشف عن التفاصيل الفنية: لحم لكن بدون دم، بوصة واحدة بالضبط.`,
  },
  s27: {
    en: `Peripeteia (reversal of fortune). Legal wordplay. Portia mirrors Shylock&apos;s own insistence on the letter of the law.`,
    ar: `التحول في الحظ (تبدل الحظوظ). لعب قانوني بالكلمات. بورشيا تعكس إصرار شايلوك على حرفية القانون.`,
  },
  s28: { en: `Shylock&apos;s defeat`, ar: `поражение شايلوك` },
  s30: {
    en: `Ironic reversal: the law Shylock championed now destroys him. Pathos as he loses everything.`,
    ar: `عكس إرهيقي: القانون اللي شايلوك كان يدافع عنه دمره الآن. تعاطف لما يفقد كل شي.`,
  },
  s31: { en: `The &ldquo;mercy&rdquo;`, ar: `الرحمة` },
  s32: {
    en: `Antonio &ldquo;mercifully&rdquo; allows Shylock to keep half his wealth if he converts to Christianity and leaves his estate to Jessica.`,
    ar: `أنتونيو يسمح لشيلوك &ldquo؛بMercifully&rdquo؛ بأن يحتفظ بنصف ثروته إذا تحول إلى المسيحية وترك ميراثه جيسيكا.`,
  },
  s33: {
    en: `Deeply ironic &ldquo;mercy.&rdquo; The forced conversion strips Shylock of his identity. His final line: &ldquo;I am not well.&rdquo;`,
    ar: `م Mercerية حادة. التحول القسري يسلب شايلوك هويته. سطره الأخيرة: "أنا لست بخير.`,
  },
  s34: { en: `Key Arguments About the Trial`, ar: `نقاط principal حول المحاكمة` },
  s35: { en: `Portia is the hero`, ar: `بوريا هي героинь` },
  s36: { en: `Portia is complicit in cruelty`, ar: `بوريا متواطئة في customs الحين Customs` },
  s37: { en: `Shylock is a villain`, ar: `شيلوك شرير` },
  s38: { en: `Shylock is a victim`, ar: `شيلوك ضحية` },
  s39: { en: `Exam-Ready Analysis Points`, ar: `نقاط التحليل للاستعداد للامتحان` },
  s40: { en: `Old Testament`, ar: `العهد القديم` },
  s41: { en: `New Testament`, ar: `الكتاب المقدس الجديد` },
  s42: { en: `Dramatic irony`, ar: `حالة الحيرة الدرامية` },
  s43: { en: `How to Structure a Literature Essay (PEEL)`, ar: `كيفية تنظيم مقال أدبي (PEEL)` },
  s44: {
    en: `Analyse language, structure, form. Use subject terminology`,
    ar: `تحليل اللغة، البنية، الشكل. استخدم مصطلحات الموضوع`,
  },
  s45: {
    en: `Connect to context, audience, wider themes, or the question`,
    ar: `اتصل بالسياق، الجمهور، الموضوعات الأوسع، أو السؤال`,
  },
  s46: { en: `Sample Essay Plans`, ar: `SAMPLE ESSAY PLANS` },
  s47: { en: `Paragraph 1 (Villain):`, ar: `فقرة 1 (الشيطان أو الشرير)` },
  s48: { en: `Paragraph 2 (Victim):`, ar: `فقرة 2 (الضحية)` },
  s49: { en: `Paragraph 3 (Both):`, ar: `فقرة 3 (لكلا الجنسين)` },
  s50: { en: `Paragraph 4 (Context/Writer&apos;s intent):`, ar: `فقرة 4 (السياق/نوايا الكاتب)` },
  s51: {
    en: `Paragraph 1:`,
    ar: `параграф واحد ماكو ничего لترجمة. هل أنت متأكد إنك شافtest)test)test) الطلب صح؟ إذا كان كذا، حاول تدقيق الجمل اللي جيتك أو سوي لي قاعدة بيانات أكبرtestdata testData testData testData testData testData testData testData testData testData testData`,
  },
  s52: {
    en: `Paragraph 2:`,
    ar: `параграф 2 كان مجرد نص إنجليزي ولم يتم تقديم أي جمل أو فقرات محددة للترجمة. يرجى تقديم النص الإنجليزي المحدد الذي تريد ترجمته إلى اللهجة الخليجية العربية.`,
  },
  s53: {
    en: `Paragraph 3:`,
    ar: `параграф 3 غير متعلق بالمطلوب الترجمة من الإنجليزية إلى العربية. يرجى تقديم النص الإنجليزي الذي تريد ترجمته.`,
  },
  s54: {
    en: `Paragraph 4:`,
    ar: `параграф 4 كان فارغا في النص الأنجليزي، لذا لا يوجد نص لترجمته. الرجاء تقديم النص الذي يرغب في ترجمته.`,
  },
  s55: { en: `Top Tips for Grade 7-9`, ar: `نصائح;top tips للحصول على الدرجات من 7 إلى 9` },
  s56: { en: `Use subject terminology precisely`, ar: `استخدم مصطلحات الموضوع بدقة` },
  s57: {
    en: `Metaphor, simile, rhetorical question, dramatic irony, soliloquy, aside, prose vs verse, peripeteia, pathos, motif, juxtaposition, parallel structure.`,
    ar: `метaphore، simile، سؤال رhetorical، حِوار مُدَاراة دراميّة، soliloquy، aside، prosa ضد verse، peripeteia، pathos، motif، juxtaposition، بنية متوازية`,
  },
  s58: { en: `Embed short quotations`, ar: `ادمج استشهادات قصيرة` },
  s59: {
    en: `Use 2-5 word quotations woven into your sentences rather than long block quotes. E.g., &ldquo;Shylock&apos;s plea that Jews have &lsquo;hands, organs, dimensions&rsquo; asserts shared humanity.&rdquo;`,
    ar: `استخدم اقتباسات بـ 2 إلى 5 كلمات داخل جملك بدلاً من كتل طويلة. مثلاً، "ال HANDS ORGANS DIMENSIONS" لشيلوك يؤكد على الإنسانية المشتركة.`,
  },
  s62: { en: `Integrate context naturally`, ar: `أدخل السياق بشكل طبيعي` },
  s63: { en: `Analyse Shakespeare&apos;s methods`, ar: `تحليل أساليب شكسبير` },
  s64: { en: `Focus on what Shakespeare`, ar: `ركز على ما شكسبير` },
  s65: { en: `Track character across the play`, ar: `ات follower لشخصية خلال المسرحية` },
  s66: {
    en: `Show how characters change. Shylock moves from resigned patience to vengeful fury. Portia moves from obedient daughter to courtroom authority. Track the arc, don&apos;t just describe a snapshot.`,
    ar: `أظهر كيف يتغير الشخصيات. شايلوك ينتقل من الصبر المكتوم إلى الغضب الثأري. بورتيا تنتقل من ابنة مطيعة إلى سلطة محكمة. اتبع المنحنى، لا تصف فقط لقطة واحدة.`,
  },
  s67: { en: `The Merchant of Venice`, ar: `Merchant_of_Venice` },
  s68: { en: `Act-by-Act Plot Summary`, ar: `ملخص القصة مشاهدًا مشاهدًا` },
  s69: { en: `Character Profiles`, ar: `Profiles للشخصيات` },
  s70: { en: `Key Quotations with Analysis`, ar: `اقتباسات رئيسية مع تحليل` },
  s72: {
    en: `The Trial Scene &mdash; Detailed Analysis`,
    ar: `الحانوت القانوني &mdash; تحليل مفصل`,
  },
  s73: {
    en: `Essay Planning and Exam Technique`,
    ar: `TECHNIQUE التخطيط وtechnique في الكتابة الإنشائية`,
  },
}
