/**
 * Destinations for the "focus on" recommendations, resolved to routes that
 * actually exist.
 *
 * WHAT BROKE. Every personalised recommendation the engine could produce
 * pointed at a route this application has never served. Verified against
 * `src/app` on 19 September 2026:
 *
 *   /poems/<slug>          there is no /poems tree at all. Poems live at
 *                          /revision/poetry/<cluster>/<slug>, and the cluster
 *                          is not derivable from the slug.
 *   /texts/<slug>          there is no /texts tree either. Set texts live at
 *                          /revision/texts/<slug>.
 *   /revision/quiz/<slug>  /revision/quiz has no dynamic child, so every
 *                          per-quiz URL was a 404.
 *   /reading/comprehension there is no /reading tree. The comprehension
 *                          activity is /games/comprehension-challenge.
 *
 * Four of the five branches in `getFocusRecommendations` were affected, which
 * is to say the whole personalised half of it. The engine returned 200 with a
 * well-formed, correctly prioritised list of places a student cannot go.
 *
 * WHY A MODULE RATHER THAN FOUR CORRECTED STRINGS. A corrected string drifts
 * the next time a route moves, and drifts silently, because nothing downstream
 * of this file ever checks that an href resolves. These functions can only
 * return a route that exists: each one either finds a real destination in a
 * generated register or falls back to a hub page that is asserted to exist by
 * `a-recommendation-never-sends-you-nowhere.test.ts`.
 *
 * Falling back to a hub is a deliberate downgrade. "Practise Ozymandias" that
 * lands on the poetry hub is worse than landing on Ozymandias and better than
 * a 404, and the test tells us which slugs take the downgrade.
 */

import { GUIDE_LOCATIONS } from '@/lib/revision/guide-locations.generated'
import { getSetText } from '@/lib/board/set-texts'
import { canonicalTextSlug } from '@/lib/revision/text-slug-aliases'

/** Hubs. Each is a static route with a page.tsx, asserted by the test. */
export const POETRY_HUB = '/revision/poetry'
export const TEXTS_HUB = '/revision/texts'
export const QUIZ_HUB = '/revision/quiz'
export const GAMES_HUB = '/games'
export const COMPREHENSION = '/games/comprehension-challenge'

/**
 * Where a poem actually lives, or the poetry hub.
 *
 * The slug alone cannot produce the URL, because the anthology cluster is a
 * path segment: Ozymandias is at /revision/poetry/power-and-conflict/ozymandias.
 * GUIDE_LOCATIONS is generated by scanning the route tree, so it cannot claim a
 * page that is not there. `board` picks between clusters when a poem appears in
 * more than one, as War Photographer does.
 */
export function poemHref(slug: string, board?: string | null): string {
  const found = GUIDE_LOCATIONS.get(slug)
  if (!found || found.length === 0) return POETRY_HUB
  return (found.find((g) => g.board === board) ?? found[0]).href
}

/**
 * Where a set text lives, or the set-text hub.
 *
 * /revision/texts/[slug] calls notFound() for a slug it does not recognise, so
 * an unknown slug must not be put into that URL. The alias map is applied first
 * because progress rows may carry the revision-notes spelling.
 */
export function textHref(slug: string): string {
  const canonical = canonicalTextSlug(slug)
  return getSetText(canonical) ? `${TEXTS_HUB}/${canonical}` : TEXTS_HUB
}

/**
 * The quiz hub.
 *
 * There is no per-quiz route and the hub reads no search parameters, so the
 * slug cannot be carried through. Taking the argument anyway keeps the call
 * site honest about what it knows and gives one place to change if a
 * /revision/quiz/[slug] route is ever added.
 */
export function quizHref(_slug?: string | null): string {
  return QUIZ_HUB
}

/**
 * The games hub.
 *
 * The caller used to append `?text=<slug>` here. Nothing under src/app/games
 * reads a search parameter - not the page, not any component in the tree - so
 * the filter never happened and the student got the unfiltered hub. That is not
 * a broken link, so it is not what this change is about, but a parameter no
 * reader consults is the same class of thing: a promise the code does not keep.
 * It is dropped rather than left in place looking load-bearing.
 *
 * Making /games honour ?text= would be a real improvement. It is a feature, not
 * a navigation fix, so it is recorded rather than smuggled in here.
 */
export function gamesHref(): string {
  return GAMES_HUB
}
