/**
 * poetry set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `On this page`, ar: `في هذه الصفحة` },
  s1: { en: `Power and Conflict`, ar: `القوة والنزاع` },
  s2: { en: `Love and Relationships`, ar: `الحب والعلاقات` },
  s3: { en: `How the AQA Poetry Exam Works`, ar: `كيف يعمل امتحان الشعر حسب أQA` },
  s4: {
    en: `AQA&apos;s comparison question typically follows this format:`,
    ar: `سُؤال المقارنة في امتحان أكاديميا (AQA) يأخذ عادة هذا الشكل:`,
  },
  s5: {
    en: `Key Skills — What Markers Look For`,
    ar: `المهارات الأساسية — ماذا يبحث عنه المصححون`,
  },
  s6: { en: `Relating to context (6 marks)`, ar: `في سياق الموضوع (6 نقاط)` },
  s7: { en: `Timing &amp; Exam Strategy`, ar: `استراتيجية الوقت والخطة الامتحانية` },
  s8: { en: `Suggested Time Split (45 mins)`, ar: `وقت مقترح للتقسيم (٤٥ دقيقة)` },
  s9: {
    en: `Write your comparative essay (aim for 3-4 developed paragraphs).`,
    ar: `اكتب مقالتك المقارنة (استهدف كتابة 3-4 فقرات مطورة).`,
  },
  s10: { en: `Key Strategies`, ar: `استراتيجيات رئيسية` },
  s11: { en: `Power and Conflict — All 15 Poems`, ar: `قوة وصراع — جميع الـ15 قصيدة` },
  s12: {
    en: `Recommended Paragraph Structure`,
    ar: `هيك هي الهيكلة الموصى بها لكتابةagraph:

1. ابدأ الجملة الأولى بتقديم فكرة رئيسية أو موضوع الجملة.
2. استخدم الجمل التالية لتوضيح الفكرة الرئيسية وتقديم الدعم والتفصيلات.
3. ضع جملة ختامية تلخص النقاط الرئيسية وتقدم رؤية أو استنتاج.

تذكر دائماً تنظيم`,
  },
  s13: { en: `Comparative paragraphs (3-4)`, ar: `парагرافات مقارنة (3-4)` },
  s14: {
    en: `Analyse methods (analysing language and structure)`,
    ar: `تحليل الطرق (تحليل اللغة والبنية)`,
  },
  s15: { en: `Integrate context (relating to context)`, ar: `íchِّر السياق (ربطًا بالسياق)` },
  s16: { en: `Brief conclusion`, ar: `خاتمة قصيرة` },
  s18: { en: `Similarly, [poet] also...`, ar: `مثلًا، [الشاعر] أيضًا...` },
  s19: { en: `Both poets present...`, ar: `يقدّم كلا الشاعرين...` },
  s20: {
    en: `Like &lsquo;[poem A]&rsquo;, &lsquo;[poem B]&rsquo; also...`,
    ar: `مثل &[poem A],& [القصيدة ب]& также...`,
  },
  s21: { en: `In the same way...`, ar: `على نفس الطريقة...` },
  s23: { en: `In contrast, [poet]...`, ar: `في المقابل، [الشاعر]...` },
  s24: {
    en: `Whereas &lsquo;[poem A]&rsquo;..., &lsquo;[poem B]&rsquo;...`,
    ar: `&[-poem A]-..., &[-poem B]-...`,
  },
  s26: { en: `Unlike &lsquo;[poem A]&rsquo;...`, ar: `عكس &[lsquo;القصيدة أ]&rsquo;...` },
  s27: { en: `On the other hand...`, ar: `من ناحية أخرى...` },
  s28: { en: `Strong Comparison Pairings`, ar: `paring قوية` },
  s29: { en: `My Last Duchess`, ar: `دوقتي الأخيرة` },
  s30: { en: `Bayonet Charge`, ar: `بيونيت شارج` },
  s31: { en: `War Photographer`, ar: `WAR PHOTOGRAPHER` },
  s32: { en: `Storm on the Island`, ar: `عاصفة على الجزيرة` },
  s34: { en: `Checking Out Me History`, ar: `проверка تاريخي` },
  s35: { en: `When We Two Parted`, ar: `когда انفصنا نحناtwor` },
  s36: { en: `Neutral Tones`, ar: `نبرات محايدة` },
  s37: { en: `Love&apos;s Philosophy`, ar: `فلسفة الحب` },
  s38: { en: `Porphyria&apos;s Lover`, ar: `عاشق پورفيريا` },
  s39: { en: `The Farmer&apos;s Bride`, ar: `عروس المزارع` },
  s40: { en: `Walking Away`, ar: `هروب` },
  s41: { en: `Mother, any distance`, ar: `أمي، أي بعد` },
}
