/**
 * EAL Topic - Listening skill route (server-rendered).
 *
 * Source: Cambridge English Qualifications format (A2 Key, B1 Preliminary,
 *   B2 First, C1 Advanced) - gives us the Listening task shape.
 * British Council LearnEnglish methodology - pedagogical model only,
 *   no content copied.
 *
 * NOT BUILT (recorded 19 September 2026, CUI-7). This route renders a
 * placeholder card and nothing else.
 *
 * The header here used to say the content was filled in "in subsequent waves"
 * by `generate_eal_skill_band.py`. That script does not exist anywhere in this
 * repository and there is no EAL generation script in scripts/. The page said
 * the same thing to the reader - "being generated by the local AI wave
 * pipeline, check back in 6-48 hours" - which was a promise about work that
 * nobody was doing, on a page Google was free to index.
 *
 * The copy is now a plain statement of fact with no implied work in progress,
 * and the page is noindex and out of the sitemap until there is something on
 * it. See src/app/sitemap.ts.
 */
import Link from 'next/link'
import { headers } from 'next/headers'
import { notFound } from 'next/navigation'
import { findEALTopic } from '@/lib/eal/curriculum'

export default async function EALListeningPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const topic = findEALTopic(slug)
  if (!topic) notFound()
  const lang = (await headers()).get('x-lang') === 'ar' ? 'ar' : 'en'
  const tr = (s: { en: string; ar?: string } | undefined): string =>
    s ? (lang === 'ar' && s.ar ? s.ar : s.en) : ''

  return (
    <div className="mx-auto max-w-3xl px-6 py-12">
      <p className="font-mono text-[11px] tracking-[0.14em] uppercase text-teal-600 mb-3">
        <Link href={`/eal/${slug}`}>EAL · {tr(topic.title)}</Link>
      </p>
      <h1 className="font-serif text-3xl sm:text-4xl font-bold tracking-tight mb-3">
        {lang === 'ar' ? 'الاستماع' : 'Listening'}
      </h1>
      <p className="text-base text-muted-foreground leading-relaxed mb-6">
        {lang === 'ar'
          ? 'نصوص صوتية مع أسئلة فهم تختبر تدوين الملاحظات، الفكرة العامة، التفاصيل، والاستنتاج.'
          : 'Audio transcripts with comprehension questions that test note-taking, gist, detail, and inference.'}
      </p>

      <div className="rounded-xl border border-amber-400/30 bg-amber-500/[0.04] p-5">
        <p className="font-mono text-[10px] uppercase tracking-wider text-amber-700 mb-1">
          {lang === 'ar' ? 'قريباً' : 'Coming soon'}
        </p>
        <p className="text-sm text-foreground leading-relaxed">
          {lang === 'ar'
            ? 'لم ننشر تمارين الاستماع لهذا الموضوع بعد.'
            : 'We have not published listening exercises for this topic yet.'}
        </p>
      </div>
    </div>
  )
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const topic = findEALTopic(slug)
  // 2026-06 de-index fix: this route previously returned only a title and
  // inherited the /eal section canonical, so Google folded it into /eal and
  // dropped it. Emit a self-referential canonical (mirrors speaking/page.tsx)
  // plus a topic-specific title + description.
  const title = topic ? `${topic.title.en} - Listening practice` : 'EAL Listening practice'
  const description = topic
    ? `Listening comprehension practice on "${topic.title.en}" for EAL learners at ${topic.cefr}, supporting Arabic speakers preparing for GCSE and IGCSE English.`
    : 'Listening comprehension practice for EAL learners preparing for GCSE and IGCSE English.'
  return {
    title,
    description,
    // CUI-7: nothing is published here, so nothing should be inviting search
    // traffic. Removed from the sitemap in the same change.
    robots: { index: false, follow: false },
    alternates: { canonical: `https://theenglishhub.app/eal/${slug}/listening` },
  }
}
