/**
 * EAL Topic - Listening skill route (server-rendered).
 *
 * Source: Cambridge English Qualifications format (A2 Key, B1 Preliminary,
 *   B2 First, C1 Advanced) - gives us the Listening task shape.
 * British Council LearnEnglish methodology - pedagogical model only,
 *   no content copied.
 *
 * The scaffold renders a Coming Soon card. generate_eal_skill_band.py
 * fills the actual reading passages / listening transcripts / speaking
 * prompts / writing tasks in subsequent waves.
 */
import Link from 'next/link'
import { headers } from 'next/headers'
import { notFound } from 'next/navigation'
import { findEALTopic } from '@/lib/eal/curriculum'

export default async function EALListeningPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const topic = findEALTopic(slug)
  if (!topic) notFound()
  const lang = (await headers()).get('x-lang') === 'ar' ? 'ar' : 'en'
  const tr = (s: { en: string; ar?: string } | undefined): string =>
    s ? (lang === 'ar' && s.ar ? s.ar : s.en) : ''

  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      <p className="font-mono text-[11px] tracking-[0.14em] uppercase text-teal-600 mb-3">
        <Link href={`/eal/${slug}`}>EAL · {tr(topic.title)}</Link>
      </p>
      <h1 className="font-serif text-3xl sm:text-4xl font-bold tracking-tight mb-3">
        {lang === 'ar' ? 'الاستماع' : 'Listening'}
      </h1>
      <p className="text-base text-muted-foreground leading-relaxed mb-6">
        {lang === 'ar'
          ? 'نصوص صوتية مع أسئلة فهم تختبر تدوين الملاحظات، الفكرة العامة، التفاصيل، والاستنتاج.'
          : 'Audio transcripts with comprehension questions that test note-taking, gist, detail, and inference.'}
      </p>

      <div className="rounded-xl border border-amber-400/30 bg-amber-500/[0.04] p-5">
        <p className="font-mono text-[10px] uppercase tracking-wider text-amber-700 mb-1">
          {lang === 'ar' ? 'قريباً' : 'Coming soon'}
        </p>
        <p className="text-sm text-foreground leading-relaxed">
          {lang === 'ar'
            ? 'تمارين الاستماع لهذا الموضوع قيد البناء - تولّد بواسطة سلسلة الموجات الذكية المحلية. تحقق خلال 6-48 ساعة.'
            : 'Listening exercises for this topic are being generated by the local AI wave pipeline. Check back in 6-48 hours.'}
        </p>
      </div>
    </main>
  )
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const topic = findEALTopic(slug)
  // 2026-06 de-index fix: this route previously returned only a title and
  // inherited the /eal section canonical, so Google folded it into /eal and
  // dropped it. Emit a self-referential canonical (mirrors speaking/page.tsx)
  // plus a topic-specific title + description.
  const title = topic ? `${topic.title.en} - Listening practice` : 'EAL Listening practice'
  const description = topic
    ? `Listening comprehension practice on "${topic.title.en}" for EAL learners at ${topic.cefr}, supporting Arabic speakers preparing for GCSE and IGCSE English.`
    : 'Listening comprehension practice for EAL learners preparing for GCSE and IGCSE English.'
  return {
    title,
    description,
    alternates: { canonical: `https://theenglishhub.app/eal/${slug}/listening` },
  }
}
