/**
 * dictionary-ai-act.ts — EU AI Act (Reg (EU) 2024/1689) user-facing copy.
 *
 * Curated EN + Khaleeji (Gulf) Arabic for two compliance surfaces:
 *  - `ai_oversight.*`     — the in-product human-review/contest control
 *                           (RequestHumanReviewButton, Art 14 human oversight)
 *  - `ai_marking_notice.*`— the accurate AI-generated-result disclosure shown
 *                           on the marking results page (Art 13/50). This
 *                           REPLACES the generic `ai_label.*` content notice
 *                           on that surface — the old label claimed "Reviewed
 *                           by humans", which is false for B2C AI marking.
 *
 * Wired into the resolver's curated tier (before placeholder/audit
 * supplements) in dictionary.ts so it always wins over junk entries.
 */

export const AI_ACT_DICTIONARY: Record<string, { en: string; ar: string }> = {
  // ─── Art 14 — in-product human oversight (RequestHumanReviewButton) ──
  'ai_oversight.button': { en: 'Request a human review', ar: 'اطلب مراجعة بشرية' },
  'ai_oversight.dialog_title': { en: 'Request a human review', ar: 'اطلب مراجعة بشرية' },
  'ai_oversight.dialog_description': {
    en: 'This grade and feedback were generated by AI. It is a predicted grade, not an official result. If something looks wrong, ask a member of our team to review it — a human will check your work and respond.',
    ar: 'هالدرجة والملاحظات تكوّنت بالذكاء الاصطناعي. هذي درجة تقديرية، مو نتيجة رسمية. إذا فيه شي ما يبيّن صحيح، اطلب من فريقنا يراجعه — بيشيكه شخص بشري ويرد عليك.',
  },
  'ai_oversight.reason_label': {
    en: 'Tell us what looks wrong (optional)',
    ar: 'قل لنا وش اللي ما يبيّن صحيح (اختياري)',
  },
  'ai_oversight.reason_placeholder': {
    en: 'For example: the grade seems too low, or the feedback misses part of my answer. You can leave this blank.',
    ar: 'مثلاً: الدرجة تبيّن واطية وايد، أو الملاحظات فاتها جزء من جوابي. تقدر تتركها فاضية.',
  },
  'ai_oversight.cancel': { en: 'Cancel', ar: 'إلغاء' },
  'ai_oversight.submit': { en: 'Request review', ar: 'اطلب المراجعة' },
  'ai_oversight.submitting': { en: 'Sending…', ar: 'يتم الإرسال…' },
  'ai_oversight.success': {
    en: 'Your request has been sent. A human will review your work.',
    ar: 'انرسل طلبك. بيراجع شغلك شخص بشري.',
  },
  'ai_oversight.success_with_ref': {
    en: 'Request sent. Your reference number is {ref}.',
    ar: 'انرسل الطلب. رقمك المرجعي هو {ref}.',
  },
  'ai_oversight.error': {
    en: 'Could not send your request. Please try again.',
    ar: 'ما قدرنا نرسل طلبك. حاول مرة ثانية.',
  },
  'ai_oversight.default_detail_marking': {
    en: 'Please have a person review this AI-predicted marking grade.',
    ar: 'الرجاء مراجعة هذي الدرجة المقدّرة بالذكاء الاصطناعي من قبل شخص بشري.',
  },
  'ai_oversight.default_detail_essay-feedback': {
    en: 'Please have a person review this AI essay feedback.',
    ar: 'الرجاء مراجعة ملاحظات المقال المكتوبة بالذكاء الاصطناعي من قبل شخص بشري.',
  },
  'ai_oversight.default_detail_cefr': {
    en: 'Please have a person review this AI CEFR assessment.',
    ar: 'الرجاء مراجعة تقييم CEFR المعمول بالذكاء الاصطناعي من قبل شخص بشري.',
  },

  // ─── Art 13/50 — accurate AI marking-result disclosure ──────────────
  // Replaces the generic "Made with AI · Reviewed by humans" content
  // label on the marking results page (no human reviews B2C marks).
  'ai_marking_notice.title': {
    en: 'This result was generated by AI',
    ar: 'هذي النتيجة تكوّنت بالذكاء الاصطناعي',
  },
  'ai_marking_notice.body': {
    en: 'This mark, grade and feedback were produced automatically by an AI system (Anthropic’s Claude model). It has not been checked by a human and may be wrong or inconsistent. The grade is a predicted, indicative grade for practice — it is NOT an official exam result, and for boards other than AQA it is derived from AQA grade boundaries. If your school has given you a teacher-linked account, your teacher can review and change this mark. To have a person re-check this result, use the “Request a human review” button below.',
    ar: 'هالعلامة والدرجة والملاحظات تكوّنت تلقائياً بنظام ذكاء اصطناعي (نموذج Claude من Anthropic). ما شيّكها إنسان وممكن تكون غلط أو غير متّسقة. الدرجة تقديرية وإرشادية للتدريب — هي مو نتيجة امتحان رسمية، وللمجالس غير AQA تنحسب على أساس حدود درجات AQA. إذا مدرستك عطتك حساب مربوط بمعلّم، يقدر معلّمك يراجع ويعدّل هالدرجة. وعشان يعيد شخص بشري فحص هالنتيجة، استخدم زر «اطلب مراجعة بشرية» تحت.',
  },
  'ai_marking_notice.link': {
    en: 'AI transparency & your rights',
    ar: 'شفافية الذكاء الاصطناعي وحقوقك',
  },

  // ─── Smart IP — student "awaiting teacher review" state ─────────────
  // Shown on /marking/results/[id] when a teacher-linked (b2b_class)
  // submission has NOT yet been approved by a teacher. The hard rule:
  // students never see a draft AI mark for teacher-set work — only the
  // teacher-approved feedback, once it exists.
  'marking.results.awaiting_title': {
    en: 'Awaiting teacher review',
    ar: 'بانتظار مراجعة المعلّم',
  },
  'marking.results.awaiting_body': {
    en: 'Your work has been submitted and is waiting for your teacher to review it. Your feedback and mark will appear here once your teacher has checked and approved them. You will not see an automated mark for teacher-set work before then.',
    ar: 'انرسل شغلك وهو بانتظار معلّمك يراجعه. ملاحظاتك ودرجتك بتبيّن هني أول ما يشيّكها معلّمك ويعتمدها. ما بتشوف درجة تلقائية للشغل اللي حدّده المعلّم قبل جذي.',
  },
  'marking.results.awaiting_status': {
    en: 'Status: waiting for teacher approval',
    ar: 'الحالة: بانتظار اعتماد المعلّم',
  },
}
