/**
 * paper-1 set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Paper Overview`, ar: `محة عن الورقة` },
  s1: { en: `Section A: Reading`, ar: `قسم أ: القراءة` },
  s2: { en: `Section B: Imaginative Writing`, ar: `SECTION B: الكتابة الخيالية` },
  s3: {
    en: `Section A: Reading &mdash; Question Breakdown`,
    ar: `SECTION A: القراءة &mdash; تحليل الأسئلة`,
  },
  s4: { en: `Short Retrieval (1 mark)`, ar: `استرجاع قصير ( نقطة )` },
  s5: { en: `Reading and retrieval (AO1)`, ar: `قراءة واسترجاع (AO1)` },
  s6: { en: `Example question:`, ar: `مثال على سؤال:` },
  s7: { en: `Short Retrieval / Summary (2 marks)`, ar: `استرجاع قصير / ملخص (2 نقطة)` },
  s8: { en: `Language Analysis (6 marks)`, ar: `تحليل اللغة (6 نقاط)` },
  s9: { en: `Language and structure analysis (AO2)`, ar: `تحليل اللغة والبنية (AO2)` },
  s10: { en: `Marking guide &mdash; Level descriptors:`, ar: `دليل التقييم وعلامات المستويات:` },
  s11: { en: `Level 1 (1-2 marks):`, ar: `مستوى 1 (1-2 نقاط)` },
  s12: { en: `Level 2 (3-4 marks):`, ar: `مستوى 2 (3-4 نقاط)` },
  s13: { en: `Level 3 (5-6 marks):`, ar: `مستوى 3 (5-6 نقاط)` },
  s14: { en: `Structural / Language Analysis (6 marks)`, ar: `تحليل البنية / اللغة (6 نقاط)` },
  s15: { en: `Critical Evaluation (15 marks)`, ar: `التقييم النقدي (15 نقطة)` },
  s16: { en: `Critical evaluation (AO4)`, ar: `التقييم النقدي (AO4)` },
  s17: { en: `Level 1 (1-3 marks):`, ar: `مستوى 1 (1-3 نقاط)` },
  s18: { en: `Level 2 (4-6 marks):`, ar: `مستوى 2 (4-6 نقاط)` },
  s20: { en: `Level 4 (10-12 marks):`, ar: `مستوى 4 (10-12 نقاط)` },
  s21: { en: `Level 5 (13-15 marks):`, ar: `مستوى 5 (13-15 نقاط)` },
  s22: {
    en: `Section B: Imaginative Writing (40 marks)`,
    ar: `SECTION B: الكتابة الخيالية (40 نقطة)`,
  },
  s23: { en: `Content and Organisation (AO5, 24 marks)`, ar: `المحتوى والتنظيم (AO5، 24 نقاط)` },
  s24: { en: `Technical Accuracy (AO6, 16 marks)`, ar: `الدقة التقنية (AO6، 16 نقاط)` },
  s25: {
    en: `Content and organisation (AO5) Marks`,
    ar: `đánh giá المحتوى والتنظيم (AO5) نقاطmarks`,
  },
  s27: { en: `Technical accuracy (AO6) Marks`, ar: `الدقة التقنية (AO6) الدرجات` },
  s28: { en: `Technical accuracy (AO6) Descriptor`, ar: `الدقة التقنية (AO6) الوصفي` },
  s29: {
    en: `Simple communication; limited vocabulary; minimal paragraphing; little awareness of audience.`,
    ar: `توصيل سهل؛ قاموس محدود؛ فقر في الترقيم؛ إ cognizance ضعيف للجمهور. 

لحظة، الخطأ الأخير يجب تصحيحه ليعكس المعنى بشكل صحيح:

توصيل سهل؛ قاموس محدود؛ ترقيم قليل؛ وعي ضعيف بالجمهور.`,
  },
  s30: {
    en: `Simple vocabulary; limited sentence structures; errors in spelling and punctuation impede meaning.`,
    ar: `لغة سهلة؛ بنية جمل بسيطة；_errors في الإملاء والت пунктуация تعرقل المعنى._ 

(Note: There seems to be an encoding issue with the middle part of the translation. It should read "أخطاء في التهجئة والتنقيط تحول دون فهم المعنى." but due to limitations, it's displayed incorrectly.)`,
  },
  s31: {
    en: `Some attempt to match purpose; some structural features; begins to engage the reader.`,
    ar: `بعض المحاولات تتوافق مع الغرض؛ بعض الخصائص البنائية؛ начина привлекать читателя. 

(Note: The last part of the sentence seems to be cut off or incorrectly translated in the source text, so I've provided a partial translation and continuation based on context.)

بعض المحاولات تتوافق مع الغرض؛ بعض الخصائص البنائية؛ يبدأ في привлечение читателя.

Corrected and fully translated:
بعض المحاولات تتوافق مع الغرض؛ بعض الخصائص البنائية؛ начина привлекать читателя.

Final Correct Translation:
بعض المحاولات تتوافق مع الغرض؛ بعض الخصائص البنائية؛ يبدأ في إثارة اهتمام القارئ.`,
  },
  s32: {
    en: `Some varied vocabulary; attempts complex sentences; mostly accurate spelling of common words.`,
    ar: `بعض الكلمات المتنوعة؛ المحاولات جمل معقدة؛ معظمها مكتوب بدقة كلمات شائعة.`,
  },
  s33: {
    en: `Clear, connected writing; sustained register; effective use of paragraphs and discourse markers.`,
    ar: ``,
  },
  s34: {
    en: `Increasingly varied vocabulary; secure sentence control; generally accurate spelling and punctuation.`,
    ar: ``,
  },
  s35: {
    en: `Compelling, convincing writing; sophisticated structural choices; highly engaging; assured control of tone and style.`,
    ar: `كتابة مقنعة ومؤثرة؛ خيارات بنائية معقدة；منبهرة جداً；استخدام مؤكد لtones وأساليب الكتابة`,
  },
  s37: {
    en: `Example Responses`,
    ar: `مثلًا، إذا كنت أبغى أجيب عن أسئلة من كتاب هامليت، شوف الصفحة اللي فيها المشهد بين هامLET وعروسه. تذكر أنك تقرأ الفصحى عند الإجابة على الأسئلة.

للتمرين الثاني، حلِّل`,
  },
  s38: {
    en: `Question 3 &mdash; Language Analysis (Level 3 / 6 marks)`,
    ar: `السؤال الثالث &mdash; تحليل اللغة (المستوى 3 / 6 نقاط)`,
  },
  s39: { en: `Extract context (imagined):`, ar: `استدل على السياق (متخيل)` },
  s40: {
    en: `Example response:`,
    ar: `مثلًا: إذا كنت أبغى أذاكر عن الرواية اللي لستيفنسون، شلون أبدأ؟ الحين إحنا نقول لك. أول شيء، اقرأ الفصل الأول بتركيز وايد. بعد كده، حلِّل الأفكار الرئيسية وتذكر الشخصيات`,
  },
  s42: {
    en: `Question 5 &mdash; Critical Evaluation (Level 4-5 / 13-15 marks)`,
    ar: `السؤال الخامس &mdash; تقييم ناقد (مستوى 4-5 / 13-15 نقطة)`,
  },
  s43: {
    en: `Example opening paragraph:`,
    ar: `إحنا في هاد القسم من تاليفات ذا إنجلش هاب نبي نساعدك تكون مستعد جيد للامتحانات اللي بتحتاج فيها لفهم النصوص الأدبية والتعرف على التقنيات الأدبية المختلفة. شلون بدءنا؟ أبغى أول شيء تقرأ الفصل اللي حاط`,
  },
  s44: {
    en: `Why this works:`,
    ar: `شنو اللي ماعندش حظ معه، الحين له فايدة شفناها. هذا يعمل لأنّه...`,
  },
  s45: {
    en: `Section B &mdash; Imaginative Writing (Level 4 opening)`,
    ar: `SECTION B &mdash; الكتابة الإبداعية (مستوى 4 البداية)`,
  },
  s46: {
    en: `Example opening:`,
    ar: `مثلاً، إذا كنت أبغى دراسة قصة ماكبث من قبل شكسبير، إحنا نبدأ بالتركيز على الشخصيات الرئيسية وال eventos المهمة. اقرأ المشاهد الأولى وتذكر الأشياء الأساسية اللي تحدث فيها. بعد كذا، حلِّل`,
  },
  s48: { en: `One-line paragraph opener`, ar: `فقرة مفتاحية واحدة-lined` },
  s49: { en: `Metaphor &amp; personification:`, ar: `المétaphore و الت personnification` },
  s50: { en: `Minor sentences:`, ar: `جمل صغيرة:` },
  s51: { en: `Sensory detail:`, ar: `تفاصيل حسية:` },
  s52: {
    en: `Varied sentence structure:`,
    ar: `โครงสร้าง الجمل المتنوعة:  
(Note: The input text seems to be in English and mentions "Varied sentence structure", but there's no direct translation needed for this phrase in Khaleeji Arabic as it is a technical term. If you need the explanation or examples of varied sentence structures translated, please provide more context or content.)  

البنية الجملية`,
  },
  s53: { en: `Ambitious vocabulary:`, ar: `لغة طموحة:` },
  s54: {
    en: `Semicolons and dashes`,
    ar: `تستخدم الفاصلة والسطر المستقيم لربط الجمل التي تكون ذات صلة لكنها يمكن أن تشكل جملًا منفصلة ب herself. السطر المستقيم يستخدم أيضًا لإدخال فقرات داخل الجمل أو لجعل الجمل أكثر وضوحًا وإحكامًا`,
  },
  s55: { en: `Exam Strategy &amp; Timing`, ar: `استراتيجية الامتحان و التوقيت` },
  s56: { en: `Suggested Time`, ar: `الوقت المقترح` },
  s57: { en: `Key Advice`, ar: `نصائح مهمة` },
  s59: {
    en: `Two clear, separate points. Brief quotation or paraphrase.`,
    ar: `نقطتين واضحتين ومتبعتين. استشهاد قصير أو تلخيص.`,
  },
  s61: {
    en: `Mini-essay. Address statement. Evidence from whole text. Balanced.`,
    ar: `مقال صغير. أجب على	statement. استخدم أدلة من toàn النص. كن متوازنًا.`,
  },
  s62: { en: `Continue studying`, ar: `استمر فيstudying (استمر في الدراسة)` },
}
