/**
 * reports set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `School Reports`, ar: `تقرير المدرسة` },
  s1: {
    en: `Generated 4 April 2026 | Academic Year to Date`,
    ar: `.generated بتاريخ 4 أبريل 2026 | السنة الدراسية الحالية`,
  },
  s2: { en: `Executive Summary`, ar: `ملخص تنفيذي` },
  s3: { en: `Year-on-Year Comparison`, ar: `المقارنة سنة بعد سنة` },
  s4: {
    en: `Key metrics compared to previous academic year`,
    ar: `المetricsات الرئيسية مقارنة بالعام الدراسي السابق`,
  },
  s5: { en: `Year Group Comparison`, ar: `مقارنة بين المستويات الصفية` },
  s6: {
    en: `Average progress by year group with student counts`,
    ar: `متوسط التقدم حسب مجموعات السنة مع أعداد الطلاب`,
  },
  s7: { en: `Year Group`, ar: `السنة الدراسيه` },
  s8: { en: `Avg Progress`, ar: `прогرس متوسط` },
  s9: { en: `Progress Bar`, ar: `مقياس التقدم` },
  s11: { en: `English Literature vs English Language`, ar: `اللغة الإنجليزية ضد الأدب الإنجليزي` },
  s12: { en: `Percentage of students active each week`, ar: `نسبة الطلاب النشطين كل أسبوع` },
  s13: {
    en: `Actionable next steps based on current data`,
    ar: `خطوات عملية بناءً على البيانات الحالية`,
  },
  s14: {
    en: `Generate printable, downloadable reports for any class or student`,
    ar: `اGeneratet شني Printable، Downloadable Reports لـ إي كلاس أو طالب الحين`,
  },
  s15: { en: `School Overview`, ar: `نظرة عامة على المدرسة` },
  s16: {
    en: `Full school performance report with all year groups and departments.`,
    ar: `تقرير الأداء المدرسي الكامل مع جميع المستويات والDepartments`,
  },
  s17: {
    en: `Performance breakdown by year group with class comparisons.`,
    ar: `تحليل الأداء حسب مجموعات السن مع مقارنات بين الفصول`,
  },
  s18: { en: `Class Report`, ar: `تقرير الصف` },
  s19: {
    en: `Detailed class report with student table, RAG status, and module analysis.`,
    ar: `تقرير فصل مفصل مع جدول الطالب، حالة الأحمر والأصفر والأخضر، وتحليل الوحدة.`,
  },
  s20: { en: `Student Report`, ar: `تقرير الطالب` },
  s21: {
    en: `Individual student progress report with assessments and recommendations.`,
    ar: `تقرير تقدم الطالب الفردي مع التقييمات والتقديرات والإقتراحات.`,
  },
  s22: {
    en: `Generate all class and student reports at once for the current term.`,
    ar: `أعد جميع تقارير الفصل والتقييمات لل trimester الحالي دفعة واحدة.`,
  },
  s24: { en: `Select Year Group:`, ar: `chọn سنة الدراسة:` },
  s25: { en: `Class Breakdown`, ar: `تقسيم الحصة` },
  s26: {
    en: `No classes found for this year group in the demo data.`,
    ar: `ماعدش كورسات موجودة لفرقة دي في البيانات الترتيبيحة.`,
  },
  s27: { en: `Predicted Grade Distribution`, ar: `التوزيع المتوقع للدرجات` },
  s28: {
    en: `No individual student data available for this year group in the demo.`,
    ar: `لا تتوفر بيانات طالب فردي لهذا العام الدراسي في النسخة التجريبية.`,
  },
  s29: { en: `At-Risk Students`, ar: `الطلاب في خطر` },
  s30: { en: `Last Active`, ar: `الحين نشط في` },
  s31: { en: `Risk Reason`, ar: `سبب المخاطرة` },
  s32: {
    en: `Top Performers`,
    ar: `أفضل الم.performers.translation.error.correction.أدونواعطهماللقبالمستحق.الحين،شوفقائمةالمتفوقينفيموقعethe English Hub.هناكوايدمنافساتلكناحاولإنتك onFocus وابدأفيتح`,
  },
  s33: {
    en: `No student data for this year group in the demo.`,
    ar: `لا يوجد بيانات طلاب لهذا العام الدراسي في النسخة التجريبية.`,
  },
  s34: { en: `Needs Attention`, ar: `يتطلب الاهتمام` },
  s35: { en: `Common Areas of Weakness`, ar: `مناطق ضعف شايرة مشتركه` },
  s36: { en: `Suggested Interventions`, ar: `Suggestions للتدخّلات` },
  s38: { en: `Class Average`, ar: `متوسط الفصل` },
  s39: { en: `School Average`, ar: `متوسط المدرسة` },
  s40: {
    en: `Student Progress -- RAG Status`,
    ar: `حالة تقدم الطالب -- حالة راج (أحمر، أصفر،أخضر)`,
  },
  s41: {
    en: `Red: below 50% | Amber: 50-69% | Green: 70%+`,
    ar: `احمر: أقل من 50٪ | زهري: 50-69٪ | أخضر: 70٪ فما فوق`,
  },
  s42: { en: `Working At`, ar: `العمل في` },
  s43: { en: `Class Average vs School Average`, ar: `متوسط الفصل ضد متوسط المدرسة` },
  s44: { en: `Select Student:`, ar: `اختر الطالب:` },
  s45: { en: `Overall Progress`, ar: `تقدمك الكلي` },
  s46: { en: `Assessment Summary`, ar: `ملخص التقييم` },
  s47: { en: `Working At Grade`, ar: `работать على المستوى المطلوب` },
  s48: { en: `Predicted Grade`, ar: `الدرجة المتوقعة` },
  s49: { en: `Target Grade`, ar: `الدرجة المستهدفة` },
  s50: { en: `Module Progress`, ar: `تقدم المودуль` },
  s51: { en: `No strengths identified yet`, ar: `لم يتم تحديد أي نقاط قوة حتى الآن` },
  s52: { en: `Areas for Development`, ar: `مناطق للتطوير` },
  s53: { en: `No areas of concern identified`, ar: `لا توجد مناطق مقلقة محددة` },
  s54: { en: `Next Steps`, ar: `الخطوات التالية` },
  s55: { en: `Teacher Comments`, ar: `تعليقات المعلم` },
  s56: { en: `For parents/carers:`, ar: `لأولياء الأمور/الحاضنين:` },
  s57: { en: `Teacher Ranking by Student Outcomes`, ar: `تصنيف المعلمين حسب نتائج الطلاب` },
  s58: {
    en: `Ranked by average student progress across all assigned classes`,
    ar: `مرتب حسب تقدم الطالب المتوسط في جميع الفصول المعينة`,
  },
  s60: { en: `Active Classes`, ar: `classes النشطة` },
  s61: { en: `Total Students`, ar: `إجمالي الطلاب` },
  s62: { en: `Avg Student Progress`, ar: `прогресс الطالب المتوسط` },
  s63: { en: `Assignment Completion`, ar: `Completion,assignments` },
  s64: { en: `Classes and Results`, ar: `classes ونتائج` },
  s65: { en: `Student Outcomes Under Their Care`, ar: `نتائج الطلاب تحت رعايتهم` },
  s66: { en: `Comparison with Department Average`, ar: `مقارنة مع متوسط department` },
  s67: { en: `Average Student Progress`, ar: `прогرس الطالب المتوسط` },
  s68: { en: `Assignment Completion Rate`, ar: `معدل إكمال التسليمات` },
  s69: { en: `Professional Development Recommendations`, ar: `توصيات للتطوير المهني` },
}
