'use client'

/**
 * RequestHumanReviewButton - EU AI Act Article 14 (human oversight).
 *
 * AI marking / feedback returns a *predicted* grade (not an official
 * result). Article 14 requires an in-product path for the affected
 * person (often a minor) to ask a human to review that automated
 * output. This component renders that path: an accessible button that
 * opens a small dialog, collects an optional reason, and POSTs to the
 * existing `POST /api/review` endpoint.
 *
 * IMPORTANT - this component does NOT change the /api/review contract.
 * That route requires `essayId` (non-empty string), `reason` (one of a
 * fixed enum) and `detail` (non-empty string, ≤2000 chars). It returns
 * `{ referenceNumber, estimatedResponse }`. We map our UX onto that
 * contract:
 *   - `essayId`  ← `submissionRef` when available, else a clearly
 *                  marked non-PII placeholder (`unknown-<context>`) so
 *                  the oversight request still reaches the human queue
 *                  rather than silently failing. See the follow-up note
 *                  in the implementation report - the proper fix is an
 *                  API change so feedback pages can pass a real id.
 *   - `reason`   ← always the enum value `'other'` (the dialog collects
 *                  free text, not one of the fixed reason codes).
 *   - `detail`   ← the user's typed reason, or a context-derived
 *                  default when they leave it blank (the field is
 *                  optional in our UX but required by the API).
 *
 * All visible strings go through useT() under the `ai_oversight.*`
 * namespace. Those keys are intentionally NOT added to any dictionary
 * here - the orchestrator wires the copy centrally. Until then the
 * resolver returns `[[ai_oversight.x]]`; `oversightText()` below
 * detects that sentinel and substitutes readable English so the
 * control is fully usable in the meantime.
 */

import { useState } from 'react'
import { toast } from 'sonner'
import { ShieldCheck, Loader2 } from 'lucide-react'
import { useT } from '@/lib/i18n/use-t'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'

type ReviewContext = 'marking' | 'essay-feedback' | 'cefr'

interface RequestHumanReviewButtonProps {
  /**
   * Reference to the assessed submission. Mapped to the API's required
   * `essayId`. When omitted (e.g. ephemeral feedback that is not
   * persisted with an id) the request still goes through with a
   * non-PII placeholder so the human-oversight path is never a dead
   * end - see the component header and the implementation report.
   */
  submissionRef?: string
  /** Which AI output this review concerns - drives default copy. */
  context: ReviewContext
  /** Optional pre-filled reason text. */
  defaultReason?: string
}

/**
 * English fallbacks for the `ai_oversight.*` keys. Used only when the
 * dictionary resolver returns the `[[key]]` sentinel (i.e. the
 * orchestrator has not wired the copy yet). This keeps the component
 * shippable without touching any dictionary file.
 */
const FALLBACKS: Record<string, string> = {
  'ai_oversight.button': 'Request a human review',
  'ai_oversight.dialog_title': 'Request a human review',
  'ai_oversight.dialog_description':
    'This grade and feedback were generated by AI. It is a predicted grade, not an official result. If something looks wrong, ask a member of our team to review it - a human will check your work and respond.',
  'ai_oversight.reason_label': 'Tell us what looks wrong (optional)',
  'ai_oversight.reason_placeholder':
    'For example: the grade seems too low, or the feedback misses part of my answer. You can leave this blank.',
  'ai_oversight.cancel': 'Cancel',
  'ai_oversight.submit': 'Request review',
  'ai_oversight.submitting': 'Sending…',
  'ai_oversight.success': 'Your request has been sent. A human will review your work.',
  'ai_oversight.success_with_ref': 'Request sent. Your reference number is {ref}.',
  'ai_oversight.error': 'Could not send your request. Please try again.',
  'ai_oversight.default_detail_marking':
    'Please have a person review this AI-predicted marking grade.',
  'ai_oversight.default_detail_essay-feedback':
    'Please have a person review this AI essay feedback.',
  'ai_oversight.default_detail_cefr': 'Please have a person review this AI CEFR assessment.',
}

export function RequestHumanReviewButton({
  submissionRef,
  context,
  defaultReason = '',
}: RequestHumanReviewButtonProps) {
  const t = useT()
  const [open, setOpen] = useState(false)
  const [reason, setReason] = useState(defaultReason)
  const [submitting, setSubmitting] = useState(false)

  /**
   * Resolve a key, falling back to readable English when the resolver
   * returns the `[[key]]` sentinel (unwired copy). Supports a single
   * `{ref}` placeholder for the success-with-reference string.
   */
  function oversightText(key: string, ref?: string): string {
    const resolved = t(key)
    const isUnwired = resolved === `[[${key}]]`
    const base = isUnwired ? (FALLBACKS[key] ?? key) : resolved
    return ref !== undefined ? base.replace('{ref}', ref) : base
  }

  async function handleSubmit() {
    setSubmitting(true)
    try {
      // Map our UX onto the EXISTING /api/review contract. We do not
      // alter the route's schema (see component header).
      const trimmedReason = reason.trim()
      const detail =
        trimmedReason.length > 0
          ? trimmedReason
          : oversightText(`ai_oversight.default_detail_${context}`)

      const res = await fetch('/api/review', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          // `essayId` is required & non-empty server-side. Use the
          // provided ref, else a clearly marked placeholder so the
          // oversight request is never silently dropped.
          essayId: submissionRef && submissionRef.length > 0 ? submissionRef : `unknown-${context}`,
          reason: 'other',
          context,
          detail: detail.slice(0, 2000),
        }),
      })

      const data: unknown = await res.json().catch(() => null)

      if (!res.ok) {
        const message =
          data && typeof data === 'object' && 'error' in data
            ? String((data as { error: unknown }).error)
            : oversightText('ai_oversight.error')
        toast.error(message)
        return
      }

      const referenceNumber =
        data && typeof data === 'object' && 'referenceNumber' in data
          ? String((data as { referenceNumber: unknown }).referenceNumber)
          : undefined

      if (referenceNumber) {
        toast.success(oversightText('ai_oversight.success_with_ref', referenceNumber))
      } else {
        toast.success(oversightText('ai_oversight.success'))
      }

      setOpen(false)
      setReason(defaultReason)
    } catch {
      toast.error(oversightText('ai_oversight.error'))
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <Button type="button" variant="outline" onClick={() => setOpen(true)} className="gap-1.5">
        <ShieldCheck className="h-4 w-4" aria-hidden />
        {oversightText('ai_oversight.button')}
      </Button>

      <DialogContent>
        <DialogHeader>
          <DialogTitle>{oversightText('ai_oversight.dialog_title')}</DialogTitle>
          <DialogDescription>{oversightText('ai_oversight.dialog_description')}</DialogDescription>
        </DialogHeader>

        <div className="space-y-2">
          <Label htmlFor="ai-oversight-reason">{oversightText('ai_oversight.reason_label')}</Label>
          <Textarea
            id="ai-oversight-reason"
            value={reason}
            onChange={(e) => setReason(e.target.value)}
            placeholder={oversightText('ai_oversight.reason_placeholder')}
            rows={4}
            maxLength={2000}
            disabled={submitting}
          />
        </div>

        <DialogFooter>
          <DialogClose
            render={
              <Button type="button" variant="outline" disabled={submitting}>
                {oversightText('ai_oversight.cancel')}
              </Button>
            }
          />
          <Button type="button" onClick={handleSubmit} disabled={submitting}>
            {submitting ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" aria-hidden />
                {oversightText('ai_oversight.submitting')}
              </>
            ) : (
              oversightText('ai_oversight.submit')
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
