/**
 * paper-1 set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `What You Do`, ar: `ما تعمله` },
  s1: { en: `Suggested Time`, ar: `الوقت المقترح` },
  s2: { en: `Question 1`, ar: `السؤال الأول` },
  s4: { en: `Question 2`, ar: `السؤال الثاني` },
  s5: {
    en: `Summary &mdash; select and organise ideas from one or both passages`,
    ar: ``,
  },
  s6: { en: `Question 3`, ar: `السؤال الثالث` },
  s7: {
    en: `Language analysis &mdash; how the writer uses language to create effects`,
    ar: `تحليل اللغة &mdash; كيف يستخدم الكاتب اللغة لخلق تأثيرات`,
  },
  s8: { en: `How to answer`, ar: `كيف تجيب` },
  s9: { en: `Read the question first`, ar: `اقرأ السؤال أولًا` },
  s10: {
    en: `Identify relevant points`,
    ar: `ا identifi شلونoints وايد مفيدة للاجابة الحين. دوّر في النص وت concentr شوف على التفاصيل اللي ممكن تكون ذات صلة. روح بطيء وأخذ وقتك.`,
  },
  s11: { en: `Organise your points`, ar: `انظم نقاطك` },
  s12: { en: `Write in your own words`, ar: `اكتب بيديتك` },
  s13: { en: `Stay within the word limit`, ar: `ببلاش تتجاوز حدود عدد الكلمات الحين` },
  s14: { en: `Common Mistakes to Avoid`, ar: `أخطاء شائعة لتجنبها` },
  s15: { en: `What Markers Want`, ar: `ما الي markers محتاجين شنو؟` },
  s16: { en: `The KEY Formula`, ar: `الصيغة الرئيسية` },
  s17: { en: `Keyword / Quote`, ar: `كلمة مفتاحية / اقتباس` },
  s18: { en: `Why / Effect`, ar: `لماذا / النتيجة` },
  s19: { en: `Word Choice`, ar: `اختيار الكلمات` },
  s20: {
    en: `Sentence Structure`,
    ar: `โครงสร้างประโยค

It seems there was a misunderstanding as the response provided is in Thai. Let's try again for Khaleeji Arabic:

بنية الجملة`,
  },
  s21: { en: `Tone &amp; Mood`, ar: `تÓN و مOOD` },
  s22: { en: `Sound Devices`, ar: `الأدوات الصوتية` },
  s23: { en: `Contrast &amp; Juxtaposition`, ar: `المقابلة والتقابل` },
  s24: { en: `Skim-read the entire passage`, ar: `انظر في toàn đoạn văn` },
  s25: { en: `Read the questions`, ar: `اقرأ الأسئلة` },
  s26: { en: `Re-read the passage carefully`, ar: `اقرأ الأبيات جيدًا مرة أخرى` },
  s27: { en: `Answer in order`, ar: `أجب بالترتيب` },
  s28: {
    en: `Check mark allocations`,
    ar: `تحقق من تخصيص النقاط(Initialized MSA for formal instruction)`,
  },
  s29: { en: `Continue studying`, ar: `استمر في الدراسة` },
}
