// ─── Spelling Bee - Extra Word Bank ────────────────────────────────────────────
// 200 additional spelling words ranked by SPELLING difficulty (not meaning).
// Difficulty mapping (matches the page.tsx SpellingWord union 1 | 2 | 3):
//   1 = Foundation (easy spelling traps)
//   2 = Crossover  (medium spelling traps + GCSE-essay literary terms)
//   3 = Higher     (hard spelling, silent letters, foreign loanwords)

export interface SpellingWordExtra {
  id: string
  word: string
  partOfSpeech:
    | 'noun'
    | 'verb'
    | 'adjective'
    | 'adverb'
    | 'pronoun'
    | 'preposition'
    | 'conjunction'
    | 'interjection'
  definition: string
  difficulty: 1 | 2 | 3
  hint?: string
}

export const SPELLING_BANK_EXTRA: SpellingWordExtra[] = [
  // ─── Easy (50) - Foundation spelling traps ─────────────────────────────────
  {
    id: 'sb-extra-001',
    word: 'committee',
    partOfSpeech: 'noun',
    definition: 'A group of people chosen to do a particular job',
    difficulty: 1,
    hint: 'Double m, double t, double e',
  },
  {
    id: 'sb-extra-002',
    word: 'separate',
    partOfSpeech: 'verb',
    definition: 'To divide or set apart',
    difficulty: 1,
    hint: 'Remember: there is "a rat" in sep-a-rate',
  },
  {
    id: 'sb-extra-003',
    word: 'beautiful',
    partOfSpeech: 'adjective',
    definition: 'Pleasing the senses or mind',
    difficulty: 1,
    hint: 'Begins with the vowels b-e-a-u',
  },
  {
    id: 'sb-extra-004',
    word: 'necessary',
    partOfSpeech: 'adjective',
    definition: 'Required to be done; essential',
    difficulty: 1,
    hint: 'One c, two s',
  },
  {
    id: 'sb-extra-005',
    word: 'definitely',
    partOfSpeech: 'adverb',
    definition: 'Without doubt or question',
    difficulty: 1,
    hint: 'No "a" - it is defin-ite-ly',
  },
  {
    id: 'sb-extra-006',
    word: 'embarrass',
    partOfSpeech: 'verb',
    definition: 'To make someone feel awkward or ashamed',
    difficulty: 1,
    hint: 'Double r and double s',
  },
  {
    id: 'sb-extra-007',
    word: 'accommodate',
    partOfSpeech: 'verb',
    definition: 'To provide lodging or space for',
    difficulty: 1,
    hint: 'Double c and double m',
  },
  {
    id: 'sb-extra-008',
    word: 'foreign',
    partOfSpeech: 'adjective',
    definition: 'From another country',
    difficulty: 1,
    hint: 'Breaks the i-before-e rule: e-i',
  },
  {
    id: 'sb-extra-009',
    word: 'government',
    partOfSpeech: 'noun',
    definition: 'The system that rules a country',
    difficulty: 1,
    hint: 'Silent n in the middle',
  },
  {
    id: 'sb-extra-010',
    word: 'immediate',
    partOfSpeech: 'adjective',
    definition: 'Happening at once; without delay',
    difficulty: 1,
    hint: 'Double m, then -iate',
  },
  {
    id: 'sb-extra-011',
    word: 'beginning',
    partOfSpeech: 'noun',
    definition: 'The start of something',
    difficulty: 1,
    hint: 'Double n before -ing',
  },
  {
    id: 'sb-extra-012',
    word: 'believe',
    partOfSpeech: 'verb',
    definition: 'To accept as true',
    difficulty: 1,
    hint: 'i before e (no c)',
  },
  {
    id: 'sb-extra-013',
    word: 'receive',
    partOfSpeech: 'verb',
    definition: 'To be given something',
    difficulty: 1,
    hint: 'e before i after c',
  },
  {
    id: 'sb-extra-014',
    word: 'achieve',
    partOfSpeech: 'verb',
    definition: 'To successfully bring about',
    difficulty: 1,
    hint: 'i before e',
  },
  {
    id: 'sb-extra-015',
    word: 'friend',
    partOfSpeech: 'noun',
    definition: 'A person with whom one shares affection',
    difficulty: 1,
    hint: 'i before e in friend',
  },
  {
    id: 'sb-extra-016',
    word: 'business',
    partOfSpeech: 'noun',
    definition: 'A commercial activity or trade',
    difficulty: 1,
    hint: 'Silent i - "busy" + ness',
  },
  {
    id: 'sb-extra-017',
    word: 'because',
    partOfSpeech: 'conjunction',
    definition: 'For the reason that',
    difficulty: 1,
    hint: 'Big Elephants Can Always Understand Small Elephants',
  },
  {
    id: 'sb-extra-018',
    word: 'different',
    partOfSpeech: 'adjective',
    definition: 'Not the same',
    difficulty: 1,
    hint: 'Double f, then -erent',
  },
  {
    id: 'sb-extra-019',
    word: 'February',
    partOfSpeech: 'noun',
    definition: 'The second month of the year',
    difficulty: 1,
    hint: 'Often-silent first r: Feb-RU-ary',
  },
  {
    id: 'sb-extra-020',
    word: 'Wednesday',
    partOfSpeech: 'noun',
    definition: 'The day after Tuesday',
    difficulty: 1,
    hint: 'Silent d: Wed-nes-day',
  },
  {
    id: 'sb-extra-021',
    word: 'tomorrow',
    partOfSpeech: 'noun',
    definition: 'The day after today',
    difficulty: 1,
    hint: 'One m, double r',
  },
  {
    id: 'sb-extra-022',
    word: 'address',
    partOfSpeech: 'noun',
    definition: 'The location where someone lives or works',
    difficulty: 1,
    hint: 'Double d and double s',
  },
  {
    id: 'sb-extra-023',
    word: 'happened',
    partOfSpeech: 'verb',
    definition: 'Took place; occurred',
    difficulty: 1,
    hint: 'Double p, single n',
  },
  {
    id: 'sb-extra-024',
    word: 'occasion',
    partOfSpeech: 'noun',
    definition: 'A particular event or time',
    difficulty: 1,
    hint: 'Double c, single s',
  },
  {
    id: 'sb-extra-025',
    word: 'success',
    partOfSpeech: 'noun',
    definition: 'The achievement of a goal',
    difficulty: 1,
    hint: 'Double c then double s',
  },
  {
    id: 'sb-extra-026',
    word: 'possess',
    partOfSpeech: 'verb',
    definition: 'To have or own',
    difficulty: 1,
    hint: 'Two pairs of double s',
  },
  {
    id: 'sb-extra-027',
    word: 'profession',
    partOfSpeech: 'noun',
    definition: 'A paid occupation requiring training',
    difficulty: 1,
    hint: 'One f, double s',
  },
  {
    id: 'sb-extra-028',
    word: 'professional',
    partOfSpeech: 'adjective',
    definition: 'Relating to a profession',
    difficulty: 1,
    hint: 'Single f, double s',
  },
  {
    id: 'sb-extra-029',
    word: 'recommend',
    partOfSpeech: 'verb',
    definition: 'To suggest as suitable',
    difficulty: 1,
    hint: 'One c, double m',
  },
  {
    // VERIFIED: OED entry "occurrence", Cambridge UK English Dictionary, accessed 2026
    // Replaced duplicate 'tomorrow' (already at sb-extra-021) with another foundation-level trap word.
    id: 'sb-extra-030',
    word: 'occurrence',
    partOfSpeech: 'noun',
    definition: 'An incident or event',
    difficulty: 1,
    hint: 'Double c, double r, ends -ence',
  },
  {
    id: 'sb-extra-031',
    word: 'until',
    partOfSpeech: 'preposition',
    definition: 'Up to the point in time',
    difficulty: 1,
    hint: 'Only one l (unlike "till")',
  },
  {
    id: 'sb-extra-032',
    word: 'really',
    partOfSpeech: 'adverb',
    definition: 'In actual fact; truly',
    difficulty: 1,
    hint: 'Double l: real + ly',
  },
  {
    id: 'sb-extra-033',
    word: 'finally',
    partOfSpeech: 'adverb',
    definition: 'After a long time',
    difficulty: 1,
    hint: 'Double l: final + ly',
  },
  {
    id: 'sb-extra-034',
    word: 'usually',
    partOfSpeech: 'adverb',
    definition: 'In most cases; normally',
    difficulty: 1,
    hint: 'Double l: usual + ly',
  },
  {
    id: 'sb-extra-035',
    word: 'truly',
    partOfSpeech: 'adverb',
    definition: 'In a truthful way',
    difficulty: 1,
    hint: 'Drops the e from "true"',
  },
  {
    id: 'sb-extra-036',
    word: 'argument',
    partOfSpeech: 'noun',
    definition: 'A reasoned exchange of differing views',
    difficulty: 1,
    hint: 'Drops the e from "argue"',
  },
  {
    // VERIFIED: OED entry "judgement", Cambridge UK Dictionary, accessed 2026.
    // GCSE = UK English; Cambridge lists "judgement" as the British spelling
    // ("judgment" is US/legal). Switched to UK form to match the file's style guide.
    id: 'sb-extra-037',
    word: 'judgement',
    partOfSpeech: 'noun',
    definition: 'A decision or opinion formed',
    difficulty: 1,
    hint: 'British -ement; US drops the e (judgment)',
  },
  {
    id: 'sb-extra-038',
    word: 'knowledge',
    partOfSpeech: 'noun',
    definition: 'Information and skills acquired',
    difficulty: 1,
    hint: 'Silent k at the start',
  },
  {
    id: 'sb-extra-039',
    word: 'island',
    partOfSpeech: 'noun',
    definition: 'Land surrounded by water',
    difficulty: 1,
    hint: 'Silent s',
  },
  {
    id: 'sb-extra-040',
    word: 'castle',
    partOfSpeech: 'noun',
    definition: 'A large fortified building',
    difficulty: 1,
    hint: 'Silent t',
  },
  {
    id: 'sb-extra-041',
    word: 'whistle',
    partOfSpeech: 'noun',
    definition: 'A high-pitched sound made through the lips',
    difficulty: 1,
    hint: 'Silent t',
  },
  {
    id: 'sb-extra-042',
    word: 'rhyme',
    partOfSpeech: 'noun',
    definition: 'Correspondence of sound between word endings',
    difficulty: 1,
    hint: 'Silent h after r',
  },
  {
    id: 'sb-extra-043',
    word: 'honest',
    partOfSpeech: 'adjective',
    definition: 'Truthful and sincere',
    difficulty: 1,
    hint: 'Silent h at the start',
  },
  {
    id: 'sb-extra-044',
    word: 'hour',
    partOfSpeech: 'noun',
    definition: 'A period of sixty minutes',
    difficulty: 1,
    hint: 'Silent h',
  },
  {
    id: 'sb-extra-045',
    word: 'wrist',
    partOfSpeech: 'noun',
    definition: 'The joint between the hand and forearm',
    difficulty: 1,
    hint: 'Silent w',
  },
  {
    id: 'sb-extra-046',
    word: 'wrong',
    partOfSpeech: 'adjective',
    definition: 'Not correct or true',
    difficulty: 1,
    hint: 'Silent w',
  },
  {
    id: 'sb-extra-047',
    word: 'science',
    partOfSpeech: 'noun',
    definition: 'The systematic study of the natural world',
    difficulty: 1,
    hint: 'sc- start, then -ience',
  },
  {
    id: 'sb-extra-048',
    word: 'piece',
    partOfSpeech: 'noun',
    definition: 'A portion of something',
    difficulty: 1,
    hint: 'i before e - a "pie"-ce',
  },
  {
    id: 'sb-extra-049',
    word: 'people',
    partOfSpeech: 'noun',
    definition: 'Human beings in general',
    difficulty: 1,
    hint: 'peo-ple - silent o',
  },
  {
    id: 'sb-extra-050',
    word: 'queue',
    partOfSpeech: 'noun',
    definition: 'A line of people waiting',
    difficulty: 1,
    hint: 'Four silent letters after q',
  },

  // ─── Medium (70) - Crossover spelling traps ────────────────────────────────
  {
    id: 'sb-extra-051',
    word: 'rhythm',
    partOfSpeech: 'noun',
    definition: 'A regular repeated pattern of sound',
    difficulty: 2,
    hint: 'No vowels except y',
  },
  {
    id: 'sb-extra-052',
    word: 'conscience',
    partOfSpeech: 'noun',
    definition: 'An inner sense of right and wrong',
    difficulty: 2,
    hint: 'science with a "con-" - silent c',
  },
  {
    id: 'sb-extra-053',
    word: 'occurred',
    partOfSpeech: 'verb',
    definition: 'Happened; took place',
    difficulty: 2,
    hint: 'Double c and double r',
  },
  {
    id: 'sb-extra-054',
    word: 'pursuing',
    partOfSpeech: 'verb',
    definition: 'Following or chasing',
    difficulty: 2,
    hint: 'One r - pur-su-ing',
  },
  {
    id: 'sb-extra-055',
    word: 'privilege',
    partOfSpeech: 'noun',
    definition: 'A special right or advantage',
    difficulty: 2,
    hint: 'No d - priv-i-lege',
  },
  {
    // VERIFIED: OED entry "embarrassment", accessed 2026.
    // Replaced duplicate 'recommend' (already at sb-extra-029) with a fresh medium-tier trap.
    id: 'sb-extra-056',
    word: 'embarrassment',
    partOfSpeech: 'noun',
    definition: 'A feeling of self-conscious shame or awkwardness',
    difficulty: 2,
    hint: 'Double r, double s, ends -ment',
  },
  {
    id: 'sb-extra-057',
    word: 'schedule',
    partOfSpeech: 'noun',
    definition: 'A planned timetable',
    difficulty: 2,
    hint: 'Silent c after s - sch-',
  },
  {
    id: 'sb-extra-058',
    word: 'sergeant',
    partOfSpeech: 'noun',
    definition: 'A non-commissioned military officer',
    difficulty: 2,
    hint: 'ser-GEANT - sounds like "sar"',
  },
  {
    id: 'sb-extra-059',
    word: 'vacuum',
    partOfSpeech: 'noun',
    definition: 'A space entirely devoid of matter',
    difficulty: 2,
    hint: 'Two u in a row',
  },
  {
    id: 'sb-extra-060',
    word: 'weird',
    partOfSpeech: 'adjective',
    definition: 'Strange or unusual',
    difficulty: 2,
    hint: 'Breaks i-before-e: e-i',
  },
  {
    id: 'sb-extra-061',
    word: 'maintenance',
    partOfSpeech: 'noun',
    definition: 'The process of keeping in good condition',
    difficulty: 2,
    hint: 'main-TEN-ance, not "main-TAIN-ance"',
  },
  {
    id: 'sb-extra-062',
    word: 'questionnaire',
    partOfSpeech: 'noun',
    definition: 'A set of printed questions for a survey',
    difficulty: 2,
    hint: 'Double n, ends in -aire',
  },
  {
    id: 'sb-extra-063',
    word: 'restaurant',
    partOfSpeech: 'noun',
    definition: 'A place where meals are served',
    difficulty: 2,
    hint: 'Silent middle: rest-AU-rant',
  },
  {
    id: 'sb-extra-064',
    word: 'parallel',
    partOfSpeech: 'adjective',
    definition: 'Side by side and never meeting',
    difficulty: 2,
    hint: 'Double l in the middle, single l at end',
  },
  {
    id: 'sb-extra-065',
    word: 'parliament',
    partOfSpeech: 'noun',
    definition: 'A legislative assembly of a country',
    difficulty: 2,
    hint: 'Silent i - par-LIA-ment',
  },
  {
    id: 'sb-extra-066',
    word: 'colleague',
    partOfSpeech: 'noun',
    definition: 'A person you work with',
    difficulty: 2,
    hint: 'Double l, ends -eague',
  },
  {
    id: 'sb-extra-067',
    word: 'cemetery',
    partOfSpeech: 'noun',
    definition: 'A burial ground',
    difficulty: 2,
    hint: 'Three e, no a',
  },
  {
    id: 'sb-extra-068',
    word: 'mischievous',
    partOfSpeech: 'adjective',
    definition: 'Playfully naughty',
    difficulty: 2,
    hint: 'No "i" before -ous: mis-chie-vous',
  },
  {
    id: 'sb-extra-069',
    word: 'bureaucracy',
    partOfSpeech: 'noun',
    definition: 'A system of government by officials',
    difficulty: 2,
    hint: 'French-style -eau spelling',
  },
  {
    id: 'sb-extra-070',
    word: 'colonel',
    partOfSpeech: 'noun',
    definition: 'A senior army officer',
    difficulty: 2,
    hint: 'Pronounced "kernel" but spelled with l',
  },
  {
    id: 'sb-extra-071',
    word: 'lieutenant',
    partOfSpeech: 'noun',
    definition: 'A junior commissioned officer',
    difficulty: 2,
    hint: 'Begins lieu- (like "in lieu of")',
  },
  {
    id: 'sb-extra-072',
    word: 'manoeuvre',
    partOfSpeech: 'noun',
    definition: 'A planned movement or operation',
    difficulty: 2,
    hint: 'British: -oeuvre; US: maneuver',
  },
  {
    id: 'sb-extra-073',
    word: 'apparent',
    partOfSpeech: 'adjective',
    definition: 'Clearly visible or understood',
    difficulty: 2,
    hint: 'Double p, one r',
  },
  {
    id: 'sb-extra-074',
    word: 'apparently',
    partOfSpeech: 'adverb',
    definition: 'As far as one knows',
    difficulty: 2,
    hint: 'Double p, single r',
  },
  {
    id: 'sb-extra-075',
    word: 'opportunity',
    partOfSpeech: 'noun',
    definition: 'A favourable chance for progress',
    difficulty: 2,
    hint: 'Double p, single t',
  },
  {
    id: 'sb-extra-076',
    word: 'exaggerate',
    partOfSpeech: 'verb',
    definition: 'To represent as larger than it is',
    difficulty: 2,
    hint: 'Double g, then -erate',
  },
  {
    id: 'sb-extra-077',
    word: 'harass',
    partOfSpeech: 'verb',
    definition: 'To pester or persistently trouble',
    difficulty: 2,
    hint: 'One r, double s',
  },
  {
    id: 'sb-extra-078',
    word: 'guarantee',
    partOfSpeech: 'noun',
    definition: 'A formal promise or assurance',
    difficulty: 2,
    hint: 'gu- start, double e end',
  },
  {
    id: 'sb-extra-079',
    word: 'guard',
    partOfSpeech: 'noun',
    definition: 'A person who watches or protects',
    difficulty: 2,
    hint: 'gu- silent u',
  },
  {
    id: 'sb-extra-080',
    word: 'mortgage',
    partOfSpeech: 'noun',
    definition: 'A loan to buy property',
    difficulty: 2,
    hint: 'Silent t',
  },
  {
    id: 'sb-extra-081',
    word: 'tongue',
    partOfSpeech: 'noun',
    definition: 'The fleshy organ in the mouth',
    difficulty: 2,
    hint: 'Ends -gue',
  },
  {
    id: 'sb-extra-082',
    word: 'fatigue',
    partOfSpeech: 'noun',
    definition: 'Extreme tiredness',
    difficulty: 2,
    hint: 'Ends -gue, silent ue',
  },
  {
    id: 'sb-extra-083',
    word: 'league',
    partOfSpeech: 'noun',
    definition: 'A group of teams or nations',
    difficulty: 2,
    hint: 'Ends -gue',
  },
  {
    id: 'sb-extra-084',
    word: 'plague',
    partOfSpeech: 'noun',
    definition: 'A contagious disease causing many deaths',
    difficulty: 2,
    hint: 'Ends -gue',
  },
  {
    id: 'sb-extra-085',
    word: 'aisle',
    partOfSpeech: 'noun',
    definition: 'A passage between rows of seats',
    difficulty: 2,
    hint: 'Silent s',
  },
  {
    id: 'sb-extra-086',
    word: 'gauge',
    partOfSpeech: 'noun',
    definition: 'An instrument for measuring',
    difficulty: 2,
    hint: 'Unusual au spelling - gauge, not "guage"',
  },
  {
    id: 'sb-extra-087',
    word: 'leisure',
    partOfSpeech: 'noun',
    definition: 'Free time for relaxation',
    difficulty: 2,
    hint: 'Breaks i-before-e: e-i',
  },
  {
    id: 'sb-extra-088',
    word: 'seize',
    partOfSpeech: 'verb',
    definition: 'To take hold of suddenly',
    difficulty: 2,
    hint: 'Breaks i-before-e: e-i',
  },
  {
    id: 'sb-extra-089',
    word: 'protein',
    partOfSpeech: 'noun',
    definition: 'A nutrient made of amino acids',
    difficulty: 2,
    hint: 'Breaks i-before-e: e-i',
  },
  {
    id: 'sb-extra-090',
    word: 'caffeine',
    partOfSpeech: 'noun',
    definition: 'A stimulant found in coffee and tea',
    difficulty: 2,
    hint: 'Breaks i-before-e: e-i',
  },
  {
    id: 'sb-extra-091',
    word: 'neighbour',
    partOfSpeech: 'noun',
    definition: 'A person living next door',
    difficulty: 2,
    hint: 'British -our; US neighbor',
  },
  {
    id: 'sb-extra-092',
    word: 'colour',
    partOfSpeech: 'noun',
    definition: 'A property of light such as red or blue',
    difficulty: 2,
    hint: 'British -our; US color',
  },
  {
    id: 'sb-extra-093',
    word: 'favourite',
    partOfSpeech: 'adjective',
    definition: 'Preferred above all others',
    difficulty: 2,
    hint: 'British -our; US favorite',
  },
  {
    id: 'sb-extra-094',
    word: 'centre',
    partOfSpeech: 'noun',
    definition: 'The middle point of something',
    difficulty: 2,
    hint: 'British -re; US center',
  },
  {
    id: 'sb-extra-095',
    word: 'theatre',
    partOfSpeech: 'noun',
    definition: 'A building for plays and performances',
    difficulty: 2,
    hint: 'British -re; US theater',
  },
  {
    id: 'sb-extra-096',
    word: 'metre',
    partOfSpeech: 'noun',
    definition: 'The basic SI unit of length',
    difficulty: 2,
    hint: 'British -re; US meter',
  },
  {
    id: 'sb-extra-097',
    word: 'practise',
    partOfSpeech: 'verb',
    definition: 'To do repeatedly to gain skill',
    difficulty: 2,
    hint: 'Verb with -ise; noun is practice with -ice',
  },
  {
    id: 'sb-extra-098',
    word: 'licence',
    partOfSpeech: 'noun',
    definition: 'A permit from an authority',
    difficulty: 2,
    hint: 'British noun -ence; verb is license -ense',
  },
  {
    // VERIFIED: OED entry "cancel, v.", Cambridge UK Dictionary, accessed 2026.
    // Hint corrected - the US single-l form is 'canceled' (not 'cancelled').
    id: 'sb-extra-099',
    word: 'cancelled',
    partOfSpeech: 'verb',
    definition: 'Called off or annulled',
    difficulty: 2,
    hint: 'British double l (cancelled); US single l (canceled)',
  },
  {
    id: 'sb-extra-100',
    word: 'travelled',
    partOfSpeech: 'verb',
    definition: 'Went from place to place',
    difficulty: 2,
    hint: 'British double l; US single l',
  },
  {
    id: 'sb-extra-101',
    word: 'jewellery',
    partOfSpeech: 'noun',
    definition: 'Decorative items worn for adornment',
    difficulty: 2,
    hint: 'British double l; US jewelry',
  },
  {
    id: 'sb-extra-102',
    word: 'analyse',
    partOfSpeech: 'verb',
    definition: 'To examine in detail',
    difficulty: 2,
    hint: 'British -yse; US analyze',
  },
  {
    id: 'sb-extra-103',
    word: 'organise',
    partOfSpeech: 'verb',
    definition: 'To arrange in a systematic way',
    difficulty: 2,
    hint: 'British -ise; US organize',
  },
  {
    id: 'sb-extra-104',
    word: 'recognise',
    partOfSpeech: 'verb',
    definition: 'To identify as already known',
    difficulty: 2,
    hint: 'British -ise; US recognize',
  },
  {
    id: 'sb-extra-105',
    word: 'sceptical',
    partOfSpeech: 'adjective',
    definition: 'Inclined to question or doubt',
    difficulty: 2,
    hint: 'British sc-; US skeptical',
  },
  {
    id: 'sb-extra-106',
    word: 'aluminium',
    partOfSpeech: 'noun',
    definition: 'A light silvery metal',
    difficulty: 2,
    hint: 'British -inium; US aluminum',
  },
  {
    id: 'sb-extra-107',
    word: 'discipline',
    partOfSpeech: 'noun',
    definition: 'Training to follow rules',
    difficulty: 2,
    hint: 'sc- in the middle',
  },
  {
    id: 'sb-extra-108',
    word: 'fascinate',
    partOfSpeech: 'verb',
    definition: 'To attract strongly',
    difficulty: 2,
    hint: 'Silent c - fas-CIN-ate',
  },
  {
    id: 'sb-extra-109',
    word: 'muscle',
    partOfSpeech: 'noun',
    definition: 'Body tissue that produces movement',
    difficulty: 2,
    hint: 'Silent c - mus-cle',
  },
  {
    id: 'sb-extra-110',
    word: 'descend',
    partOfSpeech: 'verb',
    definition: 'To move downwards',
    difficulty: 2,
    hint: 'sc- in the middle',
  },
  {
    id: 'sb-extra-111',
    word: 'ascend',
    partOfSpeech: 'verb',
    definition: 'To move upwards',
    difficulty: 2,
    hint: 'sc- in the middle',
  },
  {
    id: 'sb-extra-112',
    word: 'crescendo',
    partOfSpeech: 'noun',
    definition: 'A gradual increase in loudness',
    difficulty: 2,
    hint: 'Italian sc- pronounced "sh"',
  },
  {
    id: 'sb-extra-113',
    word: 'cappuccino',
    partOfSpeech: 'noun',
    definition: 'A coffee with steamed milk foam',
    difficulty: 2,
    hint: 'Double p, double c',
  },
  {
    id: 'sb-extra-114',
    word: 'spaghetti',
    partOfSpeech: 'noun',
    definition: 'Long thin strings of pasta',
    difficulty: 2,
    hint: 'Italian gh, double t',
  },
  {
    id: 'sb-extra-115',
    word: 'broccoli',
    partOfSpeech: 'noun',
    definition: 'A green vegetable with edible flower buds',
    difficulty: 2,
    hint: 'Double c, single l',
  },
  {
    id: 'sb-extra-116',
    word: 'desperate',
    partOfSpeech: 'adjective',
    definition: 'Feeling hopeless or reckless',
    difficulty: 2,
    hint: 'des-PER-ate, not "des-PAR-ate"',
  },
  {
    id: 'sb-extra-117',
    word: 'familiar',
    partOfSpeech: 'adjective',
    definition: 'Well known from long association',
    difficulty: 2,
    hint: 'fam-IL-iar, single l',
  },
  {
    id: 'sb-extra-118',
    word: 'forty',
    partOfSpeech: 'noun',
    definition: 'The number 40',
    difficulty: 2,
    hint: 'No u - unlike "four"',
  },
  {
    id: 'sb-extra-119',
    word: 'ninth',
    partOfSpeech: 'adjective',
    definition: 'Coming after the eighth',
    difficulty: 2,
    hint: 'Drops the e from "nine"',
  },
  {
    // VERIFIED: OED entry "thorough", Cambridge UK English Dictionary, accessed 2026.
    // Replaced duplicate 'truly' (already at sb-extra-035) with a fresh medium trap.
    id: 'sb-extra-120',
    word: 'thorough',
    partOfSpeech: 'adjective',
    definition: 'Complete with regard to every detail',
    difficulty: 2,
    hint: 'Silent ough; not the same as "through"',
  },

  // ─── Hard (50) - Higher spelling traps ─────────────────────────────────────
  {
    id: 'sb-extra-121',
    word: 'acquiesce',
    partOfSpeech: 'verb',
    definition: 'To accept reluctantly without protest',
    difficulty: 3,
    hint: 'cq cluster, ends -esce',
  },
  {
    id: 'sb-extra-122',
    word: 'bourgeoisie',
    partOfSpeech: 'noun',
    definition: 'The middle class',
    difficulty: 3,
    hint: 'French -geoisie ending',
  },
  {
    id: 'sb-extra-123',
    word: 'conscientious',
    partOfSpeech: 'adjective',
    definition: 'Careful and thorough in duty',
    difficulty: 3,
    hint: 'sci- in the middle, ends -tious',
  },
  {
    id: 'sb-extra-124',
    word: "hors d'oeuvre",
    partOfSpeech: 'noun',
    definition: 'A small savoury dish served before a meal',
    difficulty: 3,
    hint: 'French apostrophe; silent h',
  },
  {
    id: 'sb-extra-125',
    word: 'inoculate',
    partOfSpeech: 'verb',
    definition: 'To vaccinate against disease',
    difficulty: 3,
    hint: 'Single n and single c',
  },
  {
    id: 'sb-extra-126',
    word: 'liaison',
    partOfSpeech: 'noun',
    definition: 'A close working relationship',
    difficulty: 3,
    hint: 'Two i: li-AI-son',
  },
  {
    id: 'sb-extra-127',
    word: 'millennium',
    partOfSpeech: 'noun',
    definition: 'A period of one thousand years',
    difficulty: 3,
    hint: 'Double l and double n',
  },
  {
    id: 'sb-extra-128',
    word: 'pneumonia',
    partOfSpeech: 'noun',
    definition: 'Lung inflammation caused by infection',
    difficulty: 3,
    hint: 'Silent p at the start',
  },
  {
    id: 'sb-extra-129',
    word: 'surveillance',
    partOfSpeech: 'noun',
    definition: 'Close observation of a person or place',
    difficulty: 3,
    hint: 'sur-VEILL-ance, double l',
  },
  {
    id: 'sb-extra-130',
    word: 'supersede',
    partOfSpeech: 'verb',
    definition: 'To take the place of something older',
    difficulty: 3,
    hint: 'Ends -sede (only word that does)',
  },
  {
    id: 'sb-extra-131',
    word: 'pharaoh',
    partOfSpeech: 'noun',
    definition: 'A ruler of ancient Egypt',
    difficulty: 3,
    hint: 'ph- start; -aoh end (rare order)',
  },
  {
    id: 'sb-extra-132',
    word: 'silhouette',
    partOfSpeech: 'noun',
    definition: 'A dark outline against a light background',
    difficulty: 3,
    hint: 'Silent h, double t',
  },
  {
    id: 'sb-extra-133',
    word: 'connoisseur',
    partOfSpeech: 'noun',
    definition: 'An expert judge in matters of taste',
    difficulty: 3,
    hint: 'Double n, double s, French -eur',
  },
  {
    id: 'sb-extra-134',
    word: 'rendezvous',
    partOfSpeech: 'noun',
    definition: 'A meeting at an agreed time and place',
    difficulty: 3,
    hint: 'French - silent z and final s',
  },
  {
    id: 'sb-extra-135',
    word: 'chauffeur',
    partOfSpeech: 'noun',
    definition: 'A person employed to drive a car',
    difficulty: 3,
    hint: 'French - ch- as "sh", -eur ending',
  },
  {
    id: 'sb-extra-136',
    word: 'entrepreneur',
    partOfSpeech: 'noun',
    definition: 'A person who starts a business',
    difficulty: 3,
    hint: 'French - -preneur ending',
  },
  {
    id: 'sb-extra-137',
    word: 'reservoir',
    partOfSpeech: 'noun',
    definition: 'A large natural or artificial lake',
    difficulty: 3,
    hint: 'French -voir ending',
  },
  {
    id: 'sb-extra-138',
    word: 'camouflage',
    partOfSpeech: 'noun',
    definition: 'Disguise blending with surroundings',
    difficulty: 3,
    hint: 'French -ouflage',
  },
  {
    // VERIFIED: OED entry "reconnaissance", accessed 2026.
    // Replaced duplicate 'questionnaire' (already at sb-extra-062) with a higher-tier French loanword.
    id: 'sb-extra-139',
    word: 'reconnaissance',
    partOfSpeech: 'noun',
    definition: 'Preliminary military or scientific surveying of an area',
    difficulty: 3,
    hint: 'Double n, double s, French -ssance',
  },
  {
    id: 'sb-extra-140',
    word: 'bouillon',
    partOfSpeech: 'noun',
    definition: 'A clear savoury broth',
    difficulty: 3,
    hint: 'French - ill pronounced "y"',
  },
  {
    id: 'sb-extra-141',
    word: 'mnemonic',
    partOfSpeech: 'noun',
    definition: 'A device aiding memory',
    difficulty: 3,
    hint: 'Silent m at the start',
  },
  {
    id: 'sb-extra-142',
    word: 'psyche',
    partOfSpeech: 'noun',
    definition: 'The human soul, mind, or spirit',
    difficulty: 3,
    hint: 'Silent p; ends -che',
  },
  {
    id: 'sb-extra-143',
    word: 'pseudonym',
    partOfSpeech: 'noun',
    definition: 'A fictitious name used by an author',
    difficulty: 3,
    hint: 'Silent p at the start',
  },
  {
    id: 'sb-extra-144',
    word: 'gnocchi',
    partOfSpeech: 'noun',
    definition: 'Small Italian potato dumplings',
    difficulty: 3,
    hint: 'Silent g; cch pronounced "k"',
  },
  {
    id: 'sb-extra-145',
    word: 'hierarchy',
    partOfSpeech: 'noun',
    definition: 'A ranked system of organisation',
    difficulty: 3,
    hint: 'hi-er-ar-chy - i before e',
  },
  {
    id: 'sb-extra-146',
    word: 'haemorrhage',
    partOfSpeech: 'noun',
    definition: 'Heavy and uncontrolled bleeding',
    difficulty: 3,
    hint: 'British ae-; double r and -rrh-',
  },
  {
    id: 'sb-extra-147',
    word: 'diarrhoea',
    partOfSpeech: 'noun',
    definition: 'A condition of frequent loose stools',
    difficulty: 3,
    hint: 'Double r, -rrhoea ending (British)',
  },
  {
    id: 'sb-extra-148',
    word: 'archaeology',
    partOfSpeech: 'noun',
    definition: 'The study of human history through remains',
    difficulty: 3,
    hint: 'British -ae-; US archeology',
  },
  {
    id: 'sb-extra-149',
    word: 'paediatrician',
    partOfSpeech: 'noun',
    definition: 'A doctor for children',
    difficulty: 3,
    hint: 'British -ae-; US pediatrician',
  },
  {
    id: 'sb-extra-150',
    word: 'manoeuvrability',
    partOfSpeech: 'noun',
    definition: 'The ability to be moved or steered easily',
    difficulty: 3,
    hint: 'British -oeuv-; US maneuverability',
  },
  {
    id: 'sb-extra-151',
    word: 'idiosyncrasy',
    partOfSpeech: 'noun',
    definition: 'A distinctive personal habit',
    difficulty: 3,
    hint: 'Ends -sy, not "-cy"',
  },
  {
    id: 'sb-extra-152',
    word: 'onomatopoeia',
    partOfSpeech: 'noun',
    definition: 'A word that imitates a sound',
    difficulty: 3,
    hint: 'Greek -poeia ending',
  },
  {
    id: 'sb-extra-153',
    word: 'pharmaceutical',
    partOfSpeech: 'adjective',
    definition: 'Relating to medicinal drugs',
    difficulty: 3,
    hint: '-ceutical (eu before t)',
  },
  {
    id: 'sb-extra-154',
    word: 'apocryphal',
    partOfSpeech: 'adjective',
    definition: 'Of doubtful authenticity',
    difficulty: 3,
    hint: 'y in middle, ph- sound',
  },
  {
    id: 'sb-extra-155',
    word: 'diphtheria',
    partOfSpeech: 'noun',
    definition: 'A serious bacterial infection of the throat',
    difficulty: 3,
    hint: 'phth- cluster',
  },
  {
    id: 'sb-extra-156',
    word: 'isthmus',
    partOfSpeech: 'noun',
    definition: 'A narrow strip of land joining two larger areas',
    difficulty: 3,
    hint: 'sthm cluster',
  },
  {
    id: 'sb-extra-157',
    word: 'rendezvoused',
    partOfSpeech: 'verb',
    definition: 'Met at a prearranged place',
    difficulty: 3,
    hint: 'Add -d to French rendezvous',
  },
  {
    id: 'sb-extra-158',
    word: 'fluorescent',
    partOfSpeech: 'adjective',
    definition: 'Emitting light when stimulated',
    difficulty: 3,
    hint: 'flu-OR-escent - uo together',
  },
  {
    // VERIFIED: OED entry "haemorrhagic", Cambridge UK Dictionary, accessed 2026.
    // GCSE = UK English; OED gives 'haemorrhagic' as the British headword
    // (US drops the leading 'a'). Switched from the US spelling.
    id: 'sb-extra-159',
    word: 'haemorrhagic',
    partOfSpeech: 'adjective',
    definition: 'Causing or relating to bleeding',
    difficulty: 3,
    hint: 'British ae-; double r and -rrhagic; US hemorrhagic',
  },
  {
    id: 'sb-extra-160',
    word: 'subpoena',
    partOfSpeech: 'noun',
    definition: 'A legal order to attend court',
    difficulty: 3,
    hint: 'Silent b; oe together',
  },
  {
    id: 'sb-extra-161',
    word: 'phlegm',
    partOfSpeech: 'noun',
    definition: 'Thick mucus in the throat',
    difficulty: 3,
    hint: 'Silent g at the end',
  },
  {
    id: 'sb-extra-162',
    word: 'czar',
    partOfSpeech: 'noun',
    definition: 'An emperor of Russia before 1917',
    difficulty: 3,
    hint: 'Begins cz- (sometimes spelled tsar)',
  },
  {
    id: 'sb-extra-163',
    word: 'syzygy',
    partOfSpeech: 'noun',
    definition: 'An alignment of three celestial bodies',
    difficulty: 3,
    hint: 'Three y, no other vowels',
  },
  {
    id: 'sb-extra-164',
    word: 'sacrilegious',
    partOfSpeech: 'adjective',
    definition: 'Showing disrespect for sacred things',
    difficulty: 3,
    hint: 'sacri- not "sacre-"; not from "religious"',
  },
  {
    id: 'sb-extra-165',
    word: 'minuscule',
    partOfSpeech: 'adjective',
    definition: 'Extremely small',
    difficulty: 3,
    hint: 'min-US-cule, not "mini-scule"',
  },
  {
    id: 'sb-extra-166',
    word: 'misspell',
    partOfSpeech: 'verb',
    definition: 'To spell incorrectly',
    difficulty: 3,
    hint: 'Double s where mis + spell meet',
  },
  {
    id: 'sb-extra-167',
    word: 'unnecessary',
    partOfSpeech: 'adjective',
    definition: 'Not needed',
    difficulty: 3,
    hint: 'Double n; one c, two s',
  },
  {
    id: 'sb-extra-168',
    word: 'beleaguered',
    partOfSpeech: 'adjective',
    definition: 'In a very difficult situation',
    difficulty: 3,
    hint: '-leagu- in the middle',
  },
  {
    id: 'sb-extra-169',
    word: 'rambunctious',
    partOfSpeech: 'adjective',
    definition: 'Boisterous and noisy',
    difficulty: 3,
    hint: 'Ends -nctious',
  },
  {
    id: 'sb-extra-170',
    word: 'paraphernalia',
    partOfSpeech: 'noun',
    definition: 'Miscellaneous articles or equipment',
    difficulty: 3,
    hint: 'Five syllables; -phernalia',
  },

  // ─── GCSE-essay-relevant (30) - literary terms ─────────────────────────────
  {
    id: 'sb-extra-171',
    word: 'foreshadowing',
    partOfSpeech: 'noun',
    definition: 'A hint of what will happen later in a story',
    difficulty: 2,
    hint: 'fore + shadow + ing',
  },
  {
    id: 'sb-extra-172',
    word: 'juxtaposition',
    partOfSpeech: 'noun',
    definition: 'Placing two things side by side for contrast',
    difficulty: 3,
    hint: 'jux-ta-po-sition; tricky -xta- cluster',
  },
  {
    id: 'sb-extra-173',
    word: 'allegory',
    partOfSpeech: 'noun',
    definition: 'A story whose details symbolise deeper meanings',
    difficulty: 2,
    hint: 'Double l, single g',
  },
  {
    id: 'sb-extra-174',
    word: 'paradox',
    partOfSpeech: 'noun',
    definition: 'A self-contradictory statement that may be true',
    difficulty: 2,
    hint: 'para- + -dox',
  },
  {
    id: 'sb-extra-175',
    word: 'soliloquy',
    partOfSpeech: 'noun',
    definition: "A speech revealing a character's inner thoughts",
    difficulty: 3,
    hint: 'sol-i-LO-quy; ends -quy',
  },
  {
    id: 'sb-extra-176',
    word: 'oxymoron',
    partOfSpeech: 'noun',
    definition: 'A figure of speech combining contradictory terms',
    difficulty: 2,
    hint: 'oxy + moron',
  },
  {
    id: 'sb-extra-177',
    word: 'anachronism',
    partOfSpeech: 'noun',
    definition: 'Something out of its proper time period',
    difficulty: 3,
    hint: 'an-ACH-ron-ism; silent ch as "k"',
  },
  {
    id: 'sb-extra-178',
    word: 'denouement',
    partOfSpeech: 'noun',
    definition: 'The final resolution of a plot',
    difficulty: 3,
    hint: 'French - silent t at end',
  },
  {
    id: 'sb-extra-179',
    word: 'eponymous',
    partOfSpeech: 'adjective',
    definition: 'Giving the name to a work or place',
    difficulty: 3,
    hint: 'ep-ON-ymous; one n',
  },
  {
    id: 'sb-extra-180',
    word: 'hyperbole',
    partOfSpeech: 'noun',
    definition: 'Exaggeration not meant to be taken literally',
    difficulty: 2,
    hint: 'Pronounced hy-PER-bo-lee',
  },
  {
    id: 'sb-extra-181',
    word: 'metaphor',
    partOfSpeech: 'noun',
    definition: 'A direct comparison between two unlike things',
    difficulty: 2,
    hint: 'meta + phor',
  },
  {
    id: 'sb-extra-182',
    word: 'simile',
    partOfSpeech: 'noun',
    definition: 'A comparison using "like" or "as"',
    difficulty: 1,
    hint: 'sim-i-le, three syllables',
  },
  {
    id: 'sb-extra-183',
    word: 'personification',
    partOfSpeech: 'noun',
    definition: 'Giving human qualities to non-human things',
    difficulty: 2,
    hint: 'person + ification',
  },
  {
    id: 'sb-extra-184',
    word: 'alliteration',
    partOfSpeech: 'noun',
    definition: 'Repetition of initial consonant sounds',
    difficulty: 2,
    hint: 'Double l, single t',
  },
  {
    id: 'sb-extra-185',
    word: 'assonance',
    partOfSpeech: 'noun',
    definition: 'Repetition of vowel sounds in nearby words',
    difficulty: 2,
    hint: 'Double s, single n',
  },
  {
    id: 'sb-extra-186',
    word: 'sibilance',
    partOfSpeech: 'noun',
    definition: 'Repetition of soft "s" or "sh" sounds',
    difficulty: 2,
    hint: 'sib-i-lance',
  },
  {
    id: 'sb-extra-187',
    word: 'enjambment',
    partOfSpeech: 'noun',
    definition: 'A line of poetry running on without a pause',
    difficulty: 3,
    hint: 'French -mb- cluster',
  },
  {
    id: 'sb-extra-188',
    word: 'caesura',
    partOfSpeech: 'noun',
    definition: 'A pause near the middle of a line of verse',
    difficulty: 3,
    hint: 'cae- (Latin ae)',
  },
  {
    id: 'sb-extra-189',
    word: 'protagonist',
    partOfSpeech: 'noun',
    definition: 'The main character in a story',
    difficulty: 2,
    hint: 'pro-TAG-on-ist',
  },
  {
    id: 'sb-extra-190',
    word: 'antagonist',
    partOfSpeech: 'noun',
    definition: 'The character opposing the protagonist',
    difficulty: 2,
    hint: 'an-TAG-on-ist',
  },
  {
    id: 'sb-extra-191',
    word: 'catharsis',
    partOfSpeech: 'noun',
    definition: 'The release of strong emotions through art',
    difficulty: 3,
    hint: 'ca-THAR-sis; th cluster',
  },
  {
    id: 'sb-extra-192',
    word: 'pathos',
    partOfSpeech: 'noun',
    definition: 'A quality evoking pity or sadness',
    difficulty: 2,
    hint: 'pa-thos, single th',
  },
  {
    // VERIFIED: OED entry "bathos, n.", accessed 2026.
    // Hint corrected - original was self-referential and made no sense.
    // The real trap is confusing 'bathos' (anticlimax) with 'pathos' (pity).
    id: 'sb-extra-193',
    word: 'bathos',
    partOfSpeech: 'noun',
    definition: 'An anticlimax from elevated to trivial',
    difficulty: 3,
    hint: 'b- not p-: easy to confuse with "pathos"',
  },
  {
    id: 'sb-extra-194',
    word: 'verisimilitude',
    partOfSpeech: 'noun',
    definition: 'The appearance of being real',
    difficulty: 3,
    hint: 'veri-simili-tude; six syllables',
  },
  {
    id: 'sb-extra-195',
    word: 'didactic',
    partOfSpeech: 'adjective',
    definition: 'Intended to teach a moral lesson',
    difficulty: 2,
    hint: 'di-DAC-tic',
  },
  {
    id: 'sb-extra-196',
    word: 'polemic',
    partOfSpeech: 'noun',
    definition: 'A strong verbal or written attack',
    difficulty: 2,
    hint: 'po-LEM-ic',
  },
  {
    id: 'sb-extra-197',
    word: 'colloquialism',
    partOfSpeech: 'noun',
    definition: 'An informal word or phrase used in conversation',
    difficulty: 3,
    hint: 'col-LO-qui-alism; -loqui- like soliloquy',
  },
  {
    id: 'sb-extra-198',
    word: 'euphemism',
    partOfSpeech: 'noun',
    definition: 'A mild word substituted for a harsh one',
    difficulty: 2,
    hint: 'eu-PHE-mism',
  },
  {
    id: 'sb-extra-199',
    word: 'epiphany',
    partOfSpeech: 'noun',
    definition: 'A sudden moment of insight',
    difficulty: 2,
    hint: 'ep-IPH-any; ph not f',
  },
  {
    id: 'sb-extra-200',
    word: 'zeitgeist',
    partOfSpeech: 'noun',
    definition: 'The defining mood or spirit of a period',
    difficulty: 3,
    hint: 'German loanword; ei pronounced "eye"',
  },
]
