/**
 * songs-of-ourselves-v1 set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Set-text notice`, ar: `تنبيه النص المحدد` },
  s1: { en: `Songs of Ourselves`, ar: `أغاني أنفسنا` },
  s2: { en: `The Thought-Fox`, ar: `الذئب-الفكر` },
  s3: { en: `Hawk Roosting`, ar: `هوك روستינג` },
  s4: { en: `Verified Vol&nbsp;1 Part&nbsp;4 poems:`, ar: `` },
  s5: { en: `The City Planners`, ar: `المخططون للمدينة` },
  s6: { en: `Funeral Blues`, ar: `موسيقى العزاء` },
  s7: { en: `He Never Expected Much`, ar: `لم يتوقع الكثير قط` },
  s8: {
    en: `On Finding a Small Fly Crushed in a Book`,
    ar: `عند العثور على حشرة صغيرة مسحوقة في كتاب`,
  },
  s9: { en: `Rights notice:`, ar: `حقوق التأليف والنشر:` },
  s11: { en: `Songs of Ourselves &mdash; Volume 1`, ar: `أناشيد أنفسنا &mdash; الجزء الأول` },
  s12: {
    en: `Cambridge International Poetry Anthology`,
    ar: `Anthologie الشعرية الدولية من جامعة كامبريدج`,
  },
  s13: { en: `Songs of Ourselves Volume 1`, ar: `أناشيد أنفسنا الجزء الأول` },
  s15: { en: `What you need to know`, ar: `شي ما تحتاج تعرف عليه` },
  s16: { en: `Form &amp; Structure`, ar: `شكل وStructure` },
  s17: { en: `Detailed Analysis`, ar: `تحليل مفصل` },
  s18: { en: `Integrated Comparison Technique`, ar: `TECHNIQUE المتكاملة للمقارنة` },
  s19: { en: `Structuring your response`, ar: `اstructuring رديך` },
  s20: { en: `What to compare`, ar: `شنو أبغى أشوف بالمقارنة؟` },
  s21: { en: `Useful comparative connectives`, ar: `ربطات مقارنة مفيدة` },
}
