/**
 * jekyll-and-hyde set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Paper 2: Exploring Effects and Impact`, ar: `ورقية 2: استكشاف التأثيرات والتأثير` },
  s1: { en: `Assessment Objectives`, ar: `أهداف التقييم` },
  s2: { en: `Reading and response:`, ar: `قراءة ورد فعل:` },
  s3: { en: `Language, form and structure:`, ar: `لغة، شكل وStructure` },
  s4: { en: `Contextual understanding:`, ar: `الفهم السياقي` },
  s5: { en: `Written accuracy:`, ar: `دقة الكتابة:` },
  s6: {
    en: `Chapters 1&ndash;2: The Door and the Search`,
    ar: `الفصلان الأول والثاني: الباب والبحث`,
  },
  s7: {
    en: `Chapters 3&ndash;4: Jekyll&rsquo;s Dinner Party and the Carew Murder`,
    ar: `الفصلين الثالث والرابع: حفلة جيكل وجريمة مقتل كيرو`,
  },
  s8: { en: `Chapters 5&ndash;7: Jekyll&rsquo;s Withdrawal`, ar: `الفصول 5 إلى 7: انسحاب جايلك` },
  s9: { en: `Chapter 8: The Last Night`, ar: `الفصل الثامن: الليلة الأخيرة` },
  s10: {
    en: `Chapters 9&ndash;10: The Revelations`,
    ar: `الفصول 9 و 10: الكشوفات وال Révelations`,
  },
  s11: { en: `Dr Henry Jekyll`, ar: `دكتور هنري جيكيل` },
  s12: { en: `Key character arc`, ar: `arc شخصية رئيسية` },
  s13: { en: `Mr Edward Hyde`, ar: `mr إدوارد هايد` },
  s14: { en: `Mr Gabriel Utterson`, ar: `mr جابرييل أتثرسن` },
  s15: { en: `Dr Hastie Lanyon`, ar: `دكتور هاستي لانيون` },
  s17: { en: `Victorian Respectability`, ar: `الحترامية في العصر الفيكتوري` },
  s18: { en: `Darwin and Evolution`, ar: `داروين والتطور` },
  s19: { en: `On the Origin of Species`, ar: `على أصل الأنواع` },
  s20: { en: `The Descent of Man`, ar: `هبوط الإنسان` },
  s21: { en: `Freud and the Unconscious Mind`, ar: `فرويد والذهن غير الواعي` },
  s22: { en: `Victorian London`, ar: `لندن في عهد فيكتوريا` },
  s23: { en: `Science and Religion`, ar: `العلم والدين` },
  s24: { en: `Robert Louis Stevenson`, ar: `روبرت لويس ستيفنسون` },
  s25: { en: `Introduction (3&ndash;4 sentences)`, ar: `مقدمة (ثلاثة إلى أربع جمل)` },
  s26: {
    en: `Paragraph 1: How the theme/character is introduced`,
    ar: `كيف ي Introduced the موضوع/الشخصية`,
  },
  s27: {
    en: `Paragraph 2: Development through the middle chapters`,
    ar: `تطور خلال الفصول الوسطى`,
  },
  s28: {
    en: `Paragraph 3: The revelations (Chapters 9&ndash;10)`,
    ar: `الDisclosureات (الفصول 9 إلى 10)`,
  },
  s30: { en: `OCR Exam Technique Tips`, ar: `نصائح تقنية للاختبارات الخاصة بـ OCR` },
  s31: { en: `No extract:`, ar: `لا يوجد نص لترجمته` },
  s32: { en: `Time management:`, ar: `إدارة الوقت:` },
  s33: {
    en: `The Strange Case of Dr Jekyll and Mr Hyde`,
    ar: `حالة الدكتور جايلك و Mister هайд الغريبة`,
  },
}
