/**
 * complaints set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: {
    en: `Complaints Procedure`,
    ar: `процEDURE الشكاوى

Note: The word "Procedure" is kept in Latin as it's a technical term and there isn't an exact equivalent that needs to be translated into Khaleeji Arabic while maintaining its formal tone. However, the context suggests adding "الشكاوى" which means complaints in`,
  },
  s1: { en: `The English Hub`, ar: `The English Hub` },
  s2: { en: `Using the In-Platform Form`, ar: `استخدام الشكل داخل المنصة` },
  s3: { en: `Help &gt; Make a Complaint`, ar: `مساعدة &gt; شكوِّع` },
  s4: {
    en: `Your name (or you can complain anonymously)`,
    ar: `اسمك (أو يمكنك الشكوى بأمانة دون ذكر اسم)`,
  },
  s6: {
    en: `What happened — describe the problem in your own words`,
    ar: `شنو حصل — شوف المشكلة بدقيقة ووصفها بأOwn Words`,
  },
  s7: { en: `When it happened`, ar: `متى ما حصلت` },
  s8: {
    en: `Any evidence (screenshots, emails, reference numbers)`,
    ar: `أي أدلة (Screenshots، رسائل إلكترونية، أرقام مرجعية)`,
  },
  s9: { en: `Safeguarding Concerns`, ar: `Concernات الأمنة للطفل` },
  s10: {
    en: `Assessment and assignment to the appropriate team`,
    ar: `التقييم والتعيين في الفريق المناسب`,
  },
  s11: { en: `We may contact you for more information`, ar: `نستطيع التواصل معك لمعلومات إضافية` },
  s12: { en: `Stage 1: Initial Response`, ar: `الرد الأولي` },
  s14: { en: `Stage 3: Final Response`, ar: `الرد النهائي للمرحلة الثالثة` },
  s15: { en: `Trading Standards`, ar: `المواصفات التجارية` },
  s16: {
    en: `Citizens Advice Consumer Service: 0808 223 1133`,
    ar: `خدمة المستهلك لـ Citizens Advice: 0808 223 1133`,
  },
  s17: { en: `Plain language:`, ar: `لغة سهلة` },
  s18: { en: `No pressure:`, ar: `لا ضغط:` },
  s19: { en: `Parent/guardian involvement:`, ar: `مشاركة الوالد/ة:` },
  s20: { en: `Anonymous option:`, ar: `tùy الخيار` },
  s21: {
    en: `Immediate fix`,
    ar: `الحل immediate شلونه؟ ابغى أدور عليه وايد سرعة الحين. سكّر كل شي ببلاش لحظة.`,
  },
  s23: { en: `System update`, ar: `تحديث النظام` },
}
