import { SET_TEXTS, type SetText, type TextCategory } from '@/lib/board/set-texts'

// ─── Deterministic revision-notes template ─────────────────────────────────
// This module is the NON-AI path of /api/toolkit/generate-notes. It runs
// whenever the model is unavailable, errors, times out, refuses the request
// (OFF_TOPIC) or no API key is configured.
//
// TWO HONESTY DEFECTS WERE FIXED HERE (2026-09-17):
//
//   1. PROVENANCE. The template output was footed "Generated by The English
//      Hub AI Toolkit", and the only honest signal - the "Template-Based"
//      badge in the UI - was `print:hidden`. The PDF a 14-16 year old
//      downloads and revises from therefore claimed AI authorship that did
//      not exist. Provenance now travels INSIDE the notes body, is applied
//      from one place for both the AI and the template path, and so survives
//      printing, saving to My Materials and copy-paste.
//
//   2. FABRICATION. For any topic not in SET_TEXTS - and the revision-builder
//      offers 32 such topics, 12 of them under "Language Topics" - the
//      template asserted an author ("the writer"), four invented themes
//      (Power, Responsibility, Social Class, Morality), a category and a
//      section of character analysis. A learner revising "Creative Writing"
//      was told, in a printable document, that Power is a central theme of
//      it and that "the writer" explores it through characterisation. The
//      same invented theme list was served for the 40 set texts that carry
//      no `keyThemes` in our index. Nothing is invented now: if we do not
//      hold verified content for a topic, the notes say so.
// ──────────────────────────────────────────────────────────────────────────

export type NotesSource = 'ai' | 'template'

/**
 * Human-readable text-type labels.
 *
 * The previous inline mapping had three branches and fell through to
 * 'Poetry' for everything else, so each of the 20 prose and non-fiction set
 * texts in the index was printed to a learner as "Poetry". Every category in
 * the union is now named explicitly, so adding a category is a type error
 * rather than a silent mislabel.
 */
export const CATEGORY_LABELS: Record<TextCategory, string> = {
  shakespeare: 'Shakespeare play',
  '19th-century': '19th-century novel',
  modern: 'Modern text',
  'poetry-anthology': 'Poetry anthology',
  'non-fiction': 'Non-fiction',
  prose: 'Prose',
}

/**
 * The provenance block carried inside the notes body.
 *
 * Applied by the route to BOTH branches, so no code path can ship notes
 * whose printed footer disagrees with how they were actually produced.
 */
export function notesProvenanceFooter(source: NotesSource): string {
  if (source === 'ai') {
    return `---

*How these notes were produced: written for you by an AI model (Anthropic's Claude) from The English Hub's revision prompt. AI can get things wrong, so check every quotation and claim against your copy of the text, your class notes and your exam board's specification. See theenglishhub.app/legal/ai-governance.*`
  }
  return `---

*How these notes were produced: assembled by The English Hub from a fixed revision template. They are NOT AI-generated and they are not personalised analysis. Use them alongside your class notes, your teacher's feedback and past paper practice.*`
}

function gradeAdviceFor(targetGrade: number): string {
  if (targetGrade >= 7) {
    return "At Grade 7+, examiners expect you to analyse the writer's methods with sophistication, embed quotations fluently, and consider alternative interpretations. Use critical terminology precisely."
  }
  if (targetGrade >= 5) {
    return 'At Grade 5-6, aim to explain clearly how the writer uses language and structure. Support every point with a relevant quotation and explain its effect on the reader.'
  }
  return 'At Grade 4, focus on making clear points supported by quotations. Identify techniques and explain their basic effect. Structure your response with clear paragraphs.'
}

function weakAreaSection(weakAreas: string[]): string {
  if (weakAreas.length === 0) return ''
  return `\n\n## Focus Areas for Improvement\n\nBased on your performance data, prioritise these areas:\n\n${weakAreas
    .map(
      (w) =>
        `- **${w}** -- Revisit your notes and practise answering questions specifically on this topic.`,
    )
    .join('\n')}`
}

const EXAM_TECHNIQUE_BODY = `### Model Paragraph Structure (PEEA)
1. **Point** -- State your argument clearly
2. **Evidence** -- Embed a short, relevant quotation
3. **Explanation** -- Analyse the language/technique used
4. **Alternative/Context** -- Consider a different interpretation or link to context

### Timing
- Read the question carefully and underline key words
- Plan for 3-5 minutes before writing
- Aim for 3-4 developed paragraphs in a 30-mark response
- Leave 2 minutes to proofread`

function formGuidance(category: TextCategory): string {
  switch (category) {
    case 'shakespeare':
      return '- Consider the use of **blank verse** vs **prose** and what a switch between them suggests about a character.\n- Look at **soliloquies** and **asides** for what they reveal about motivation.'
    case '19th-century':
      return '- Consider the **narrative voice** -- is it first or third person? Reliable or unreliable?\n- Look at **chapter structure**, and at **serialisation** if your edition notes that the text first appeared in instalments.'
    case 'poetry-anthology':
      return '- Consider the **form** (sonnet, dramatic monologue, free verse) and what that choice does.\n- Look at **stanza shape**, **line length**, **rhyme** and **rhythm**, and at any point where the poem breaks its own pattern.'
    case 'non-fiction':
      return '- Consider the **form** (speech, essay, article, letter, diary) and the audience it was written for.\n- Look at how the **argument** is built, and at how it positions the reader.'
    case 'modern':
    case 'prose':
      return '- Consider how the **form** (play, novel, short story) shapes what the audience or reader is shown, and when.\n- Look at stage directions, dialogue or narrative perspective, depending on the form.'
  }
}

/** Themes we can evidence, or an honest statement that we cannot. */
function themesSection(text: SetText): string {
  const themes = text.keyThemes ?? []
  if (themes.length === 0) {
    return `## Key Themes

The English Hub does not yet hold a verified theme list for "${text.title}", so none is printed here. Revising from themes we cannot evidence would risk sending you into the exam with the wrong ones. Take the themes from your exam board's specification and your class notes, then apply the method below to each of them.`
  }
  return `## Key Themes

These are the themes The English Hub records for "${text.title}" in its set-text index. They are a starting point, not a complete list, and the quotations and the analysis have to be yours:

${themes
  .map(
    (t, i) =>
      `### ${i + 1}. ${t}\n\n- Find two short quotations you could use to write about **${t}**.\n- Note where in the text ${t} is strongest, and where it is challenged.\n- Practise linking ${t} to the context in which ${text.author} was writing.\n`,
  )
  .join('\n')}`
}

/**
 * Notes for a topic that is NOT one of our set texts.
 *
 * The revision-builder's "Language Topics", "Creative Writing" and "Exam
 * Technique" option groups are skills, not texts: they have no author, no
 * themes and no characters. This path therefore asserts nothing about any
 * text - it gives exam technique, which is our own guidance, and says
 * plainly that we hold no topic-specific content.
 */
function skillsTopicNotes(
  topic: string,
  board: string,
  targetGrade: number,
  weakAreas: string[],
): string {
  return `# Revision Notes: ${topic}

**Board:** ${board.toUpperCase()}
**Target:** Grade ${targetGrade}

---

## About these notes

The English Hub does not hold verified subject content for "${topic}", so these notes cover **general exam technique only**. They give you no themes, characters, authors or quotations for this topic, because we would have to invent them, and invented literary "facts" lose marks. For content specific to "${topic}", use your class notes, your exam board's specification and your teacher.

---

## Exam Technique

${gradeAdviceFor(targetGrade)}

${EXAM_TECHNIQUE_BODY}${weakAreaSection(weakAreas)}

---

## Quick-Fire Revision Checklist

- [ ] Can you say what the examiner is asking for in this type of question?
- [ ] Have you read the mark scheme for it in your own words?
- [ ] Can you write a PEEA paragraph on it under timed conditions?
- [ ] Have you practised at least one past paper question on this topic?
- [ ] Have you asked your teacher what to prioritise here?`
}

/** Notes for one of our set texts, built only from what the index holds. */
function setTextNotes(
  text: SetText,
  board: string,
  targetGrade: number,
  weakAreas: string[],
): string {
  return `# Revision Notes: ${text.title}

**Author:** ${text.author}
**Type:** ${CATEGORY_LABELS[text.category]}
**Board:** ${board.toUpperCase()}
**Target:** Grade ${targetGrade}

---

${themesSection(text)}

---

## Characters & Relationships

Work through the characters in "${text.title}" as you meet them in your own copy and your class notes:

- How are they introduced, and how do they develop?
- What methods does ${text.author} use to present them (dialogue, description, actions)?
- How do they relate to the themes you are revising?
- What is the significance of their name, role, or position?

---

## Writer's Methods

### Language
- Identify key **imagery** (metaphors, similes, personification)
- Look for **semantic fields** that reinforce a theme
- Note changes in **tone** and what they suggest

### Structure
- How does ${text.author} organise the narrative or argument?
- Are there shifts in perspective, time, or focus?
- How do the opening and the ending connect?

### Form
${formGuidance(text.category)}

---

## Exam Technique

${gradeAdviceFor(targetGrade)}

${EXAM_TECHNIQUE_BODY}${weakAreaSection(weakAreas)}

---

## Quick-Fire Revision Checklist

- [ ] Can you name three themes you have evidence for, and a quotation for each?
- [ ] Can you explain the significance of the title?
- [ ] Do you know the historical/social context and how it shapes meaning?
- [ ] Can you compare two characters and their functions in the text?
- [ ] Can you write a PEEA paragraph under timed conditions?
- [ ] Have you practised at least one past paper question on this text?`
}

/**
 * Build the deterministic notes body. The provenance footer is NOT appended
 * here: the route appends it once, for whichever path actually produced the
 * text, so the two can never disagree.
 */
export function generateTemplateNotes(
  topic: string,
  board: string,
  targetGrade: number,
  weakAreas: string[],
): string {
  const text = SET_TEXTS.find(
    (t) => t.title.toLowerCase() === topic.toLowerCase() || t.slug === topic,
  )
  return text
    ? setTextNotes(text, board, targetGrade, weakAreas)
    : skillsTopicNotes(topic, board, targetGrade, weakAreas)
}
