/**
 * to-kill-a-mockingbird set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Harper Lee, 1960`, ar: `هاربر لي، 1960` },
  s2: { en: `Jim Crow Laws and Segregation`, ar: `قوانين جيم كراو والتفريق العنصري` },
  s3: {
    en: `The Scottsboro Boys Trial`,
    ar: `TRIAL أعضاء فريق THE ENGLISH HUB التعليمي ، اقرأوا عن تجربة المحاكمة الشهيرة لصبيان سكوتزبورو. استعدوا للأسئلة المتعلقة بهذا الموضوع في الامتحانات GCSE و IGCSE.`,
  },
  s4: { en: `Civil Rights Era Publication (1960)`, ar: `` },
  s5: { en: `Harper Lee&apos;s Biography`, ar: `سيرة هاربر لي` },
  s6: { en: `To Kill a Mockingbird`, ar: `To Kill a Mockingbird` },
  s7: { en: `Go Set a Watchman`, ar: `Go Set a Watchman` },
  s8: { en: `The Bildungsroman Tradition`, ar: `الرواية التعليمية تقليد` },
  s9: { en: `Wilhelm Meister`, ar: `` },
  s11: { en: `Tom Robinson`, ar: `توم روبنسون` },
  s12: { en: `Boo Radley`, ar: `بو رادلي` },
  s13: { en: `The Mad Dog (Tim Johnson)`, ar: `الكلب المجنون (تيم جونسون)` },
  s14: { en: `Boo&apos;s Gifts in the Tree-Knothole`, ar: `هدايا بو في فتحة شجرة` },
  s15: { en: `Atticus&apos;s Glasses`, ar: `نظارات أتكاس` },
  s17: { en: `The Radley House`, ar: `البيتRadleyHOUSE` },
  s18: { en: `Mayella&apos;s Geraniums`, ar: `جرانيم ميلداiała` },
  s19: { en: `GCSE-Style Questions`, ar: `أسئلة من نوع(gcse)` },
  s20: { en: `Exam Tips for To Kill a Mockingbird`, ar: `نصائح للامتحانات لكتاب موت طائر الشوزن` },
  s21: { en: `Always link to context.`, ar: `always راجع السياقLinkId:1` },
  s22: { en: `Use Lee&apos;s methods.`, ar: `استخدم طرق لى.` },
  s23: { en: `Refer to authorial intention.`, ar: `.intentية الكاتب` },
  s24: { en: `Connect themes.`, ar: `اقترن بالمواضيع.` },
  s25: { en: `Use precise terminology.`, ar: `استخدم لغة دقيقة.` },
  s26: {
    en: `Address the whole novel.`,
    ar: `ا.address الكتاب كله.بلا فرق بين أجزاءه، اقرأ الرواية كلها.`,
  },
  s27: { en: `Quote precisely.`, ar: `اقتبس بدقة.` },
  s28: { en: `Plot Summary`, ar: `ملخص القصة` },
  s29: { en: `Character Profiles`, ar: `Profiles للشخصيات` },
  s30: {
    en: `The first-person narrator and protagonist, almost six at the novel`,
    ar: `الراوي والبطل الأول شخصية تقترب من السادسة في الرواية`,
  },
  s31: { en: `The Finch family`, ar: `عائلة فنش` },
  s32: {
    en: `The drunken, illiterate, racist patriarch of the Ewells, Maycomb`,
    ar: `الوالد الأبشي drunk والجاهل والعنصرية لعائلة إيويلز، مايكومب`,
  },
  s33: { en: `The Finches`, ar: `الفينتشز` },
  s34: { en: `The children`, ar: `الأطفال` },
  s35: {
    en: `The Sheriff of Maycomb County, an honest lawman caught between duty and decency. He gives Atticus the rifle to shoot the rabid dog, recognising Atticus`,
    ar: `شريف مقاطعة مايكومب، رجل شرطة أمين بين واجبه وأدبه. يعطي أتكاوس البندقية ليقتل الكلب المسعور، مدركاً أن أتكاوس`,
  },
  s36: { en: `Key Themes`, ar: `ال THEMES الرئيسيين` },
  s37: { en: `Racial Injustice`, ar: `عدالة عنصرية` },
  s39: {
    en: `The novel is a Bildungsroman tracking Scout and Jem`,
    ar: `الرواية هي رواية نمو تتتبع سكوت وجد`,
  },
  s40: { en: `Moral Courage`, ar: `شجاعة أخلاقية` },
  s41: {
    en: `Lee redefines courage through Atticus and Mrs Dubose. Real courage, Atticus says, is`,
    ar: `لي ردينف كوراج من خلال أتكاوس و ميس دابوس. الكوراج الحقيقي، كما يقول أتكاوس، هو`,
  },
  s42: {
    en: `The ethical core of the novel, articulated in Atticus`,
    ar: `الแก่นสารทางจริยธรรมของนวนิยายที่ถูกอธิบายโดยแอตติกัส

Translation corrected to fit Khaleeji Arabic:

جوهر القيم الأخلاقية في الرواية التي عبر عنها أتكاس`,
  },
  s45: {
    en: `Lee contrasts formal schooling with genuine learning. Scout`,
    ar: `لي CONTRAST BETWEEN التعليم الرسمي والتعلم الحقيقي. سكوت`,
  },
  s47: { en: `Key Quotations with Analysis`, ar: `اقتباسات رئيسية مع تحليل` },
  s48: { en: `Key Symbols and Motifs`, ar: `` },
  s49: {
    en: `Exam-Style Questions with Planning Notes`,
    ar: `أسئلة من نوع الاختبار مع ملاحظات التخطيط`,
  },
  s50: { en: `Further Practice Questions`, ar: `أسئلة ممارسة إضافية` },
}
