/**
 * twentieth-century set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Twentieth Century`, ar: `قرن العشرين` },
  s1: { en: `An Inspector Calls`, ar: `مفتش يCallCheck` },
  s2: { en: `Lord of the Flies`, ar: `` },
  s3: { en: `Animal Farm`, ar: `مزرعة الحيوانات` },
  s4: { en: `Blood Brothers`, ar: `دماء الأخوة` },
  s5: { en: `World War I (1914-1918)`, ar: `حرب العالم الأولى (1914-1918)` },
  s6: { en: `World War II (1939-1945)`, ar: `الحرب العالمية الثانية (1939-1945)` },
  s7: { en: `Margaret Thatcher&apos;s`, ar: `مارغريت تاتشر` },
  s8: { en: `George Orwell`, ar: `جورج أورويل` },
  s9: { en: `Beveridge Report (1942)`, ar: `` },
  s10: { en: `Margaret Thatcher`, ar: `مارغريت ثاتشر` },
  s11: { en: `William Golding`, ar: `ويليام جولدنج` },
  s12: { en: `Lord of the Flies (1954)`, ar: `` },
  s13: { en: `Cold War allegory`, ar: `مétaphore للحرب الباردة` },
  s15: { en: `Key Timeline`, ar: `خط الزمن الرئيسي` },
  s16: { en: `World War I & World War II`, ar: `الحرب العالمية الأولى والحرب العالمية الثانية` },
  s17: { en: `The Changing Class System`, ar: `النظام الطبقي المتغير` },
  s18: { en: `Socialism vs Capitalism`, ar: `الاشتراكية مقابل الرأسمالية` },
  s19: { en: `The Welfare State`, ar: `الدولة التأمينية` },
  s21: { en: `How to Link Context to Your Texts`, ar: `كيف تربط السياق بنصوصك` },
}
