// Do not go gentle into that good night, by Dylan Thomas (1951). Out of UK
// copyright: Thomas died on 9 November 1953, so the poem entered the UK public
// domain on 1 January 2024. It is still in copyright in the United States,
// which is why Project Gutenberg cannot carry it; the site works to UK law.
//
// NOT GENERATED BY A FETCHER. The text is the one the exam prints: the Pearson
// Edexcel International GCSE English Anthology, Issue 8 (February 2026), page
// 69 (page 75 of the PDF Pearson publishes free). It was extracted from that
// PDF with pdftotext on 26 September 2026, not typed, and the extraction
// refused to write unless it found the villanelle's exact form: 19 lines in
// stanzas of 3, 3, 3, 3, 3 and 4, with each refrain four times. The margin line
// numbers (5, 10, 15) are the anthology's and are dropped here.

import type { TextData } from '@/components/study/InteractiveTextViewer'

export const doNotGoGentleIntoThatGoodNightText: TextData = {
  title: 'Do not go gentle into that good night',
  author: 'Dylan Thomas',
  type: 'poem',
  sections: [
    {
      id: 'poem',
      title: 'Do not go gentle into that good night',
      content:
        '<p>Do not go gentle into that good night,<br />\nOld age should burn and rave at close of day;<br />\nRage, rage against the dying of the light.</p>\n\n<p>Though wise men at their end know dark is right,<br />\nBecause their words had forked no lightning they<br />\nDo not go gentle into that good night.</p>\n\n<p>Good men, the last wave by, crying how bright<br />\nTheir frail deeds might have danced in a green bay,<br />\nRage, rage against the dying of the light.</p>\n\n<p>Wild men who caught and sang the sun in flight,<br />\nAnd learn, too late, they grieved it on its way,<br />\nDo not go gentle into that good night.</p>\n\n<p>Grave men, near death, who see with blinding sight<br />\nBlind eyes could blaze like meteors and be gay,<br />\nRage, rage against the dying of the light.</p>\n\n<p>And you, my father, there on the sad height,<br />\nCurse, bless, me now with your fierce tears, I pray.<br />\nDo not go gentle into that good night.<br />\nRage, rage against the dying of the light.</p>',
    },
  ],
}
