// AUTO-GENERATED by scripts/fetch-public-domain-poem.mjs - do not edit by hand.
//
// La Belle Dame sans Merci, by John Keats (1819). Out of UK copyright.
//
// The text is a byte copy of a published edition, not typed and not reproduced
// from memory. Taken from Life of John Keats: His Life and Poetry, His Friends, Critics and After-Fame, Project Gutenberg #36356, by
// anchoring on the poem's own first and last line - this edition does not
// always head a poem with its name. Gutenberg branding and licence text are
// stripped per their terms; the underlying work is out of copyright.
//
// Re-run the generator to refresh. It refuses to write if either anchor line
// has moved or if the extraction is not exactly 59 lines.

import type { TextData } from '@/components/study/InteractiveTextViewer'

export const laBelleDameSansMerciText: TextData = {
  title: 'La Belle Dame sans Merci',
  author: 'John Keats',
  // 'poem', not 'novella'. The viewer prints this word under the title and
  // uses it to choose between "scenes", "chapters" and "stanzas", so six poems
  // shipped telling a student that The Tyger is a novella with one chapter.
  type: 'poem',
  sections: [
    {
      id: 'poem',
      title: 'La Belle Dame sans Merci',
      content:
        "<p>O what can ail thee, knight-at-arms<br />\nAlone and palely loitering?<br />\nThe sedge is withered from the lake,<br />\nAnd no birds sing!</p>\n\n<p>O what can ail thee, knight-at-arms<br />\nSo haggard and so woe-begone?<br />\nThe squirrel's granary is full,<br />\nAnd the harvest's done.</p>\n\n<p>I see a lily on thy brow,<br />\nWith anguish moist and fever dew;<br />\nAnd on thy cheek a fading rose<br />\nFast withereth too--</p>\n\n<p>I met a lady in the meads<br />\nFull beautiful, a faery's child;<br />\nHer hair was long, her foot was light,<br />\nAnd her eyes were wild--</p>\n\n<p>I made a garland for her head,<br />\nAnd bracelets too, and fragrant zone;<br />\nShe looked at me as she did love,<br />\nAnd made sweet moan--</p>\n\n<p>I set her on my pacing steed,<br />\nAnd nothing else saw all day long;<br />\nFor sideways would she lean, and sing<br />\nA faery's song--</p>\n\n<p>She found me roots of relish sweet,<br />\nAnd honey wild, and manna dew;<br />\nAnd sure in language strange she said,<br />\nI love thee true--</p>\n\n<p>She took me to her elfin grot,<br />\nAnd there she gazed and sighed full sore,<br />\nAnd there I shut her wild, wild eyes<br />\nWith kisses four.</p>\n\n<p>And there she lulled me asleep,<br />\nAnd there I dreamed, ah woe betide,<br />\nThe latest dream I ever dreamed<br />\nOn the cold hill side.</p>\n\n<p>I saw pale kings, and princes too,<br />\nPale warriors, death-pale were they all;<br />\nWho cried--'La Belle Dame sans Merci<br />\nHath thee in thrall.'</p>\n\n<p>I saw their starv'd lips in the gloam<br />\nWith horrid warning gaped wide,<br />\nAnd I awoke, and found me here<br />\nOn the cold hill side.</p>\n\n<p>And this is why I sojourn here<br />\nAlone and palely loitering,<br />\nThough the sedge is withered from the lake,<br />\nAnd no birds sing.</p>",
    },
  ],
}
