// AUTO-GENERATED by scripts/fetch-public-domain-poem.mjs - do not edit by hand.
//
// Remember, by Christina Rossetti (1862). Out of UK copyright.
//
// The text is a byte copy of a published edition, not typed and not reproduced
// from memory. Taken from Poems, Project Gutenberg #19188, by
// anchoring on the poem's own first and last line - this edition does not
// always head a poem with its name. Gutenberg branding and licence text are
// stripped per their terms; the underlying work is out of copyright.
//
// Re-run the generator to refresh. It refuses to write if either anchor line
// has moved or if the extraction is not exactly 14 lines.

import type { TextData } from '@/components/study/InteractiveTextViewer'

export const rememberText: TextData = {
  title: 'Remember',
  author: 'Christina Rossetti',
  type: 'poem',
  sections: [
    {
      id: 'poem',
      title: 'Remember',
      content:
        '<p>Remember me when I am gone away,<br />\nGone far away into the silent land;<br />\nWhen you can no more hold me by the hand,<br />\nNor I half turn to go yet turning stay.<br />\nRemember me when no more, day by day,<br />\nYou tell me of our future that you planned:<br />\nOnly remember me; you understand<br />\nIt will be late to counsel then or pray.<br />\nYet if you should forget me for a while<br />\nAnd afterwards remember, do not grieve:<br />\nFor if the darkness and corruption leave<br />\nA vestige of the thoughts that once I had,<br />\nBetter by far you should forget and smile<br />\nThan that you should remember and be sad.</p>',
    },
  ],
}
