// AUTO-GENERATED by scripts/fetch-public-domain-poem.mjs - do not edit by hand.
//
// The Tyger, by William Blake (1794). Out of UK copyright.
//
// The text is a byte copy of a published edition, not typed and not reproduced
// from memory. Taken from Poems of William Blake, Project Gutenberg #574, by
// anchoring on the poem's own first and last line - this edition does not
// always head a poem with its name. Gutenberg branding and licence text are
// stripped per their terms; the underlying work is out of copyright.
//
// Re-run the generator to refresh. It refuses to write if either anchor line
// has moved or if the extraction is not exactly 29 lines.

import type { TextData } from '@/components/study/InteractiveTextViewer'

export const theTygerText: TextData = {
  title: 'The Tyger',
  author: 'William Blake',
  type: 'poem',
  sections: [
    {
      id: 'poem',
      title: 'The Tyger',
      content:
        '<p>Tyger, tyger, burning bright<br />\nIn the forests of the night,<br />\nWhat immortal hand or eye<br />\nCould frame thy fearful symmetry?</p>\n\n<p>In what distant deeps or skies<br />\nBurnt the fire of thine eyes?<br />\nOn what wings dare he aspire?<br />\nWhat the hand dare seize the fire?</p>\n\n<p>And what shoulder and what art<br />\nCould twist the sinews of thy heart?<br />\nAnd, when thy heart began to beat,<br />\nWhat dread hand and what dread feet?</p>\n\n<p>What the hammer?  what the chain?<br />\nIn what furnace was thy brain?<br />\nWhat the anvil? what dread grasp<br />\nDare its deadly terrors clasp?</p>\n\n<p>When the stars threw down their spears,<br />\nAnd watered heaven with their tears,<br />\nDid he smile his work to see?<br />\nDid he who made the lamb make thee?</p>\n\n<p>Tyger, tyger, burning bright<br />\nIn the forests of the night,<br />\nWhat immortal hand or eye<br />\nDare frame thy fearful symmetry?</p>',
    },
  ],
}
