/**
 * ai-feedback-head-to-head - bilingual content module.
 * First generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * REWRITTEN BY HAND, 10 October 2026, when the Edexcel and OCR cards were
 * re-marked to the boards' real schemes. Several of the machine translations
 * mixed scripts ("thêm", "Kontekst", "clidriver" and "evaluated" sat inside the
 * Arabic), and the one for "Add a reader-effect sentence" said something else
 * entirely: you read these sentences and imagine yourself in the story. Seven
 * of the page's labels had no Arabic at all. Every entry is now Modern Standard
 * Arabic, with AO codes, board names and specification codes kept in Latin.
 * Do not regenerate this file with the script above; it would put the garbling
 * back.
 *
 * The page finds each string by its exact English, so an edit to a _tr()
 * literal on the page needs the same edit to the matching English here, or the
 * Arabic page quietly falls back to English.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: {
    en: `The essay (identical across all three marks)`,
    ar: `المقال (النص نفسه في التصحيحات الثلاثة)`,
  },
  s1: { en: `Level 5 · 27/34`, ar: `المستوى 5 · 27 من 34` },
  s2: { en: `AO1 - Read, understand, respond`, ar: `AO1 - القراءة والفهم والاستجابة` },
  s3: { en: `To push from Level 5 to Level 6`, ar: `للانتقال من المستوى 5 إلى المستوى 6` },
  s4: { en: `AO2 - Language, form, structure`, ar: `AO2 - اللغة والشكل والبنية` },
  s5: { en: `To reach Level 6:`, ar: `للوصول إلى المستوى 6:` },
  s6: { en: `AO3 - Context`, ar: `AO3 - السياق` },
  s7: { en: `Contextual factors`, ar: `العوامل السياقية` },
  s8: { en: `AO4 - Accuracy · 3/4`, ar: `AO4 - الدقة اللغوية · 3 من 4` },
  s9: { en: `Technical accuracy`, ar: `الدقة اللغوية` },
  s10: { en: `Next moves for AQA:`, ar: `الخطوات التالية لامتحان AQA:` },
  s11: {
    en: `Upgrade three informal phrases to academic register.`,
    ar: `حوّل ثلاث عبارات غير رسمية إلى أسلوب أكاديمي.`,
  },
  s12: { en: `Level 3 · 11/20`, ar: `المستوى 3 · 11 من 20` },
  s13: { en: `AO2 and AO4 are not assessed here`, ar: `لا يُقيَّم AO2 ولا AO4 هنا` },
  s14: { en: `How Pearson sets this question`, ar: `كيف تضع Pearson هذا السؤال` },
  s15: { en: `To move into Level 5`, ar: `للانتقال إلى المستوى 5` },
  s16: { en: `Next moves for Edexcel:`, ar: `الخطوات التالية لامتحان Edexcel:` },
  s17: {
    en: `Add relevant context to every paragraph.`,
    ar: `أضف سياقًا ذا صلة إلى كل فقرة.`,
  },
  s18: {
    en: `Tie each context point to a quotation.`,
    ar: `اربط كل نقطة عن السياق باقتباس.`,
  },
  s19: {
    en: `Save close analysis for part (a).`,
    ar: `احتفظ بالتحليل اللغوي المفصّل للجزء (a).`,
  },
  s20: { en: `Level 4 · 25/40`, ar: `المستوى 4 · 25 من 40` },
  s21: { en: `To push higher:`, ar: `لرفع الدرجة:` },
  s22: { en: `Next moves for OCR:`, ar: `الخطوات التالية لامتحان OCR:` },
  s23: {
    en: `Analyse form and audience effect.`,
    ar: `حلّل الشكل المسرحي وأثره في الجمهور.`,
  },
  s24: { en: `Add one point of period context.`, ar: `أضف نقطة واحدة عن سياق العصر.` },
  s25: { en: `Re-cast the conclusion`, ar: `أعد صياغة الخاتمة` },
  s26: { en: `What the three marks show`, ar: `ماذا تكشف التصحيحات الثلاثة` },
  s27: { en: `Dimension`, ar: `المعيار` },
  s28: { en: `Edexcel 1ET0/01`, ar: `Edexcel 1ET0/01` },
  s29: { en: `Level and mark on this answer`, ar: `المستوى والدرجة في هذه الإجابة` },
  s30: { en: `Context (AO3)`, ar: `السياق (AO3)` },
  s31: { en: `6 of 34 marks`, ar: `6 من 34 درجة` },
  s32: { en: `5 of 20 marks · required`, ar: `5 من 20 درجة · مطلوب` },
  s33: { en: `8 of 40 marks`, ar: `8 من 40 درجة` },
  s34: { en: `Language analysis (AO2)`, ar: `تحليل اللغة (AO2)` },
  s35: { en: `12 of 34 marks`, ar: `12 من 34 درجة` },
  s36: { en: `Not assessed in part (b)`, ar: `لا يُقيَّم في الجزء (b)` },
  s37: { en: `14 of 40 marks`, ar: `14 من 40 درجة` },
  s38: { en: `Top improvement`, ar: `أهم تحسين` },
  s39: { en: `Add form + structure`, ar: `أضف الشكل والبنية` },
  s40: { en: `Add relevant context`, ar: `أضف سياقًا ذا صلة` },
  s41: { en: `Form and audience effect`, ar: `الشكل وأثره في الجمهور` },
  s42: { en: `Mistake to avoid`, ar: `خطأ يجب تجنبه` },
  s43: { en: `Bolting context on at the end`, ar: `إلحاق السياق في النهاية بدل دمجه` },
  s44: {
    en: `Using only one or two moments`,
    ar: `الاقتصار على موقف أو موقفين من المسرحية`,
  },
  s45: { en: `In short`, ar: `باختصار` },
}
