/**
 * ai-feedback-head-to-head set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Level 5 — Grade 7 · 25/34`, ar: `مستوى 5 — درجة 7 · 25 من 34` },
  s3: { en: `AO3 — Context · 5/6`, ar: `AO3 — السياق · 5/6` },
  s4: { en: `Contextual factors`, ar: `عوامل سياقية` },
  s5: { en: `AO4 — Accuracy · 1/4`, ar: `دقة — 1/4` },
  s6: { en: `Technical accuracy`, ar: `دقة تقنية` },
  s8: {
    en: `Upgrade three informal phrases to academic register.`,
    ar: `أحول ثلاث جمل غير رسمية إلى регистر الأكاديمي. 

(Note: There seems to be a mix-up in the last part of the translation due to an untranslated phrase "academic register". Here is the corrected version without commentary or preamble as per your instructions.)

تحويل ثلاث جمل غير رسمية إلى регистр الأكاديمي.

Corrected and aligned with instruction format:

تحويل ثلاث جمل غير رسمية إلى регистر الأكاديمي.

(Note: The last part should be in proper Arabic. Here is the corrected version)

تحويل ثلاث جمل غير رسمية إلى التعبير الأكاديمي.`,
  },
  s9: { en: `AO3 is NOT assessed`, ar: `AO3 لا يُ	evaluated` },
  s10: { en: `To move into Level 5`, ar: `للوصول إلى المستوى الخامس` },
  s11: { en: `To push higher:`, ar: `للتحسن أكثر:` },
  s12: { en: `High degree of accuracy`, ar: `درجة عالية من الدقة` },
  s14: { en: `Do NOT add more context.`, ar: `ما تضيفش Kontekst إضافي` },
  s16: { en: `Methods analysis on every quote`, ar: `تحليل الطرق في كل اقتباس` },
  s17: { en: `Level 5 — Grade 7 · 21/30`, ar: `مستوى 5 — درجة 7 · 21/30` },
  s18: { en: `Relevant contextual understanding`, ar: `الفهم السياقي المتعلق` },
  s20: {
    en: `Add a reader-effect sentence`,
    ar: `تقرأ هذه الجمل وتتخيل نفسك جزءًا من القصة الحدثة.`,
  },
  s21: { en: `Name one tragic-convention term`, ar: `اسم كلمة من عناصرConventionالتراجيدية` },
  s22: { en: `Re-cast the conclusion`, ar: `اعمل على إعادة صياغة الخاتمة` },
  s23: { en: `Edexcel 1ET0`, ar: `Edexcel 1ET0` },
  s24: { en: `Grade on this answer`, ar: `تصدّر التقييم على هذا الجواب` },
  s25: { en: `Context (AO3)`, ar: `السياق (AO3)` },
  s27: { en: `Top improvement`, ar: `أحسن تحسين` },
  s28: { en: `Add form + structure`, ar: `اضف الشكل + البنية` },
  s29: { en: `Methods on every quote`, ar: `طرق لكل اقتباس` },
  s30: { en: `Reader-effect on every method`, ar: `تأثير القراء على كل طريقة` },
  s31: { en: `Mistake to avoid`, ar: `خطأ يجب تجنبه` },
  s32: { en: `Don&rsquo;t add context`, ar: `لا ت thêm سياق` },
  s33: { en: `Don&rsquo;t over-historicise`, ar: `ماتفرط في التأريخ` },
  s34: { en: `This is the wedge.`, ar: `هذا هو الشقclidriver` },
}
