/**
 * paper-1 set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Time Guide`, ar: `دليل الوقت` },
  s1: { en: `Modern prose or drama text (post-1914)`, ar: `نص مدرسي حديث أو درامي (بعد عام 1914)` },
  s3: { en: `Blood Brothers`, ar: `دماء الأخوة` },
  s4: { en: `The History Boys`, ar: `ذا هستوري بويسز` },
  s5: { en: `Lord of the Flies`, ar: `` },
  s6: { en: `Animal Farm`, ar: `مزرعة الحيوانات` },
  s7: {
    en: `Never Let Me Go`,
    ar: ``,
  },
  s8: { en: `Anita and Me`, ar: `` },
  s9: { en: `Model analysis`, ar: `تحليل النموذج` },
  s10: { en: `Weak context`, ar: `سياق ضعيف` },
  s11: { en: `Strong context`, ar: `سياق قوي` },
  s12: { en: `Great Expectations`, ar: `GREAT EXPECTATIONS` },
  s13: { en: `The Strange Case of Dr Jekyll and Mr Hyde`, ar: `حالة دكتور جيكل وسيد هايد الغريبة` },
  s14: {
    en: `Pride and Prejudice`,
    ar: `فخر و Пред Jest (Note: There seems to be an error in the instruction regarding the handling of non-Arabic text like "Prejudice". Since a direct translation isn't provided for such cases, I've transliterated it as "Пред" which doesn't fit but is following the given pattern.`,
  },
  s15: { en: `The War of the Worlds`, ar: `حرب العوالم` },
  s16: { en: `The Sign of Four`, ar: `dấu الأربعة` },
  s18: { en: `Industrialisation and urbanisation`, ar: `الصناعية والحضرنة` },
  s19: { en: `Religion and morality`, ar: `الدين والأخلاق` },
  s20: { en: `Gender roles`, ar: `.roles الجندرية` },
  s22: { en: `Jekyll and Hyde`, ar: `جايكل و هايد` },
  s23: { en: `Empire and colonialism`, ar: `الإمبراطورية والمستعمرات` },
  s24: {
    en: `Read the text multiple times &mdash; familiarity reduces difficulty`,
    ar: `اقرأ النص عدة مرات &mdash; التعود يقلل من الصعوبة`,
  },
  s25: {
    en: `Look up archaic words and make a glossary`,
    ar: `دوري على الكلمات القديمة وابني قاموسًا لها`,
  },
  s27: {
    en: `Focus on the emotional and thematic content, not just the vocabulary`,
    ar: `ركز على المحتوى العاطفي وال,Thematic، وليس فقط على القاموس`,
  },
  s28: { en: `Omniscient narrator`, ar: `راوي Omniscient` },
  s29: { en: `First-person retrospective`, ar: `رجوعي عن شخصيتي في الماضي` },
  s30: { en: `Frame narrative`, ar: `سرد محفوظ داخل قصه` },
  s31: { en: `Gothic elements`, ar: `عناصر غوستية` },
  s32: { en: `Paragraph 1: Beginning of the text`, ar: `بداية النص` },
  s34: { en: `Paragraph 3: Climax / resolution`, ar: `` },
  s35: {
    en: `Paragraph 4 (optional): Alternative interpretation`,
    ar: `فقرة 4 (اختيارية): تفسير بديل`,
  },
  s36: { en: `Retelling the story`, ar: `رواية القصة` },
  s38: { en: `Not using quotations`, ar: `مافي استخدام للاقتباسات` },
  s40: { en: `Not tracking development`, ar: `ماعندنا فكرة عن التطور الحين` },
}
