/**
 * privacy-qatar-supplement set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Qatar Privacy Notice Supplement`, ar: `إعلان الخصوصية الإضافي لقطر` },
  s1: { en: `The English Hub`, ar: `The English Hub` },
  s2: { en: `Upskill Energy Limited`, ar: `Upskill Energy Limited` },
  s3: {
    en: `Consent (PDPPL Article 4)`,
    ar: `الموافقة (المادة 4 من قانون حماية البيانات الشخصية)`,
  },
  s5: { en: `Contractual necessity`, ar: `ضرورة عقدية` },
  s6: { en: `Legal obligation`, ar: `الالتزام القانوني` },
  s7: { en: `By jurisdiction`, ar: `بموجب الاختصاص` },
  s8: { en: `European Union (Frankfurt, Germany).`, ar: `الاتحاد الأوروبي (فرانكفورت، ألمانيا)` },
  s9: { en: `United States.`, ar: `الولايات المتحدة` },
  s10: { en: `Global edge.`, ar: `حافة العالم` },
  s11: { en: `United Kingdom.`, ar: `المملكة المتحدة` },
  s12: { en: `Transfers to the European Union`, ar: `تحويلات إلى الاتحاد الأوروبي` },
  s13: { en: `Transfers to the United Kingdom`, ar: `تحويلات إلى المملكة المتحدة` },
  s14: { en: `Transfers to the United States.`, ar: `تحويلات إلى الولايات المتحدة الأمريكية.` },
  s15: {
    en: `Cloudflare global edge.`,
    ar: `.cloudflare global edge. 

*(Note: The term 'Cloudflare' is a brand name and should remain in English as per instructions.)*`,
  },
  s16: {
    en: `Right of access (PDPPL Article 13)`,
    ar: `حق الوصول (المادة 13 من قانون حماية البيانات الشخصية)`,
  },
  s17: { en: `Right to correction`, ar: `حق التصحيح` },
  s18: { en: `Right to deletion`, ar: `حق الحذف` },
  s19: { en: `Right to withdraw consent`, ar: `حق الانسحاب من الموافقة` },
  s20: { en: `Right to object`, ar: `حق الرفض` },
  s21: { en: `Right to lodge a complaint`, ar: `حق تقديم شكوى` },
}
