/**
 * othello set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s1: { en: `Key Moments`, ar: `لحظات حاسمة` },
  s2: { en: `Venice and Cyprus`, ar: `فيينس وقبرص` },
  s3: { en: `Moors in Elizabethan England`, ar: `الموريون في إنجلترا الإليزابيثية` },
  s4: { en: `Military Honour and Service`, ar: `чеونر و خدمة` },
  s5: {
    en: `Women&apos;s Roles in Elizabethan/Jacobean Society`,
    ar: `أدوار النساء في المجتمع الإليزابيثي/الجاكوبيني`,
  },
  s6: { en: `Essay Structure: PEEL Paragraphs`, ar: `Структура مقالة: فقرات PEEL` },
  s7: {
    en: `Make a clear argument that directly answers the question.`,
    ar: `اكتب جوابًا واضحًا يجيب عن السؤال مباشرة.`,
  },
  s8: {
    en: `Analyse language, structure, or form. What does the quotation suggest? How does it work?`,
    ar: `analysي اللُّغة، الهِيكل، أو الشكْل. مَاذا يُقترح من خلال الاقتباس؟ كيف يعمل؟`,
  },
  s9: {
    en: `Link to context, the wider text, another interpretation, or the writer&apos;s purpose.`,
    ar: `Linck ila al-mawḍūʿ al-ʾaḥdathi, al-matn al-aʿamm, taṣwir baʿithi, aw nafsiyyat al-kātib.`,
  },
  s10: { en: `Sample Essay Plans`, ar: `SAMPLE ESSAY PLANS` },
  s11: { en: `Iago as the origin:`, ar: `إيغورو الأصل:` },
  s12: { en: `Othello&apos;s transformation:`, ar: `تحول عتيلو:` },
  s13: { en: `The handkerchief:`, ar: `khănفة` },
  s14: { en: `Jealousy as self-destruction:`, ar: `الغيرة كهدم ذاتي:` },
  s15: { en: `Racist language from others:`, ar: `لغة عنصرية من الآخرين:` },
  s16: { en: `Othello&apos;s dignity vs prejudice:`, ar: `عزة أوديسو ضد العنصرية:` },
  s17: { en: `Internalised racism:`, ar: `العنصرية المنطبقة داخلياً:` },
  s18: { en: `Shakespeare&apos;s purpose:`, ar: `غرض شكسبير:` },
  s19: { en: `Soliloquies and dramatic irony:`, ar: `مونولوجات وحميعية درامية:` },
  s20: { en: `Manipulation techniques:`, ar: `تقنيات التلاعب:` },
  s21: { en: `Motiveless malignity:`, ar: `مotiveless malignity:` },
  s22: { en: `Final silence:`, ar: `صمت نهائي:` },
  s23: { en: `Desdemona&apos;s agency and its limits:`, ar: `Agency ديسدمونا وحدودها` },
  s24: { en: `Emilia&apos;s defiance:`, ar: `تحدي إميليا:` },
  s25: { en: `Bianca as mirror:`, ar: `Bianca كأيقونة عاكسة:` },
  s26: { en: `Male control and violence:`, ar: `CONTROL الرجل والعنف:` },
  s27: { en: `Top Exam Tips`, ar: `نصائح=top للامتحانات` },
  s28: {
    en: `Always use &ldquo;Shakespeare presents...&rdquo;`,
    ar: `استخدم دائمًا &ldquo;شيكسبير ي presente...&rdquo;

(Note: There seems to be a typo in "presents" which is not in Arabic. The correct translation should be "يشكspbir ي present..." but since it's an instruction and "presente" doesn't fit, I kept the English word as it was likely intended for clarity.) 

For accuracy, let's correct that:

استخدم دائمًا &ldquo;شيكسبير ي present...&rdquo;`,
  },
  s29: { en: `Embed short quotations`, ar: `ادمج استشهادات قصيرة` },
  s30: { en: `Link language to meaning`, ar: `اربط اللغة مع المعنى` },
  s32: { en: `Track changes across the play`, ar: `راقب التغييرات عبر مجريات المسرحية` },
  s34: { en: `Question 1`, ar: `السؤال الأول` },
  s35: { en: `Question 2`, ar: `سؤال 2` },
  s36: { en: `Question 3`, ar: `السؤال الثالث` },
  s37: { en: `Question 4`, ar: `السؤال الرابع` },
  s38: { en: `Act-by-Act Plot Summary`, ar: `ملخص القصة مشاهدًا مشاهد` },
  s39: { en: `Character Profiles`, ar: `ملفات الشخصيات` },
  s40: { en: `Major Themes`, ar: `ال THEMES الرئيسيين` },
  s41: { en: `Key Quotations with Analysis`, ar: `اقتباسات رئيسية مع تحليل` },
  s42: { en: `Historical and Social Context`, ar: `السياق التاريخي والاجتماعي` },
  s43: { en: `Essay Planning`, ar: `hoạch التعبير الكتابي` },
  s44: { en: `Practice Questions`, ar: `أسئلة ممارسة` },
  s45: { en: `Write your essay response here...`, ar: `اكتب ردود فعلך هنا...` },
}
