/**
 * curious-incident set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Mark Haddon, 2003 (novel)`, ar: `مارك هاددون، 2003 (رواية)` },
  s2: { en: `Mark Haddon (born 1962)`, ar: `مارك هاددون (ولد في 1962)` },
  s3: { en: `Curious Incident`, ar: `حادثة مشوقة` },
  s4: { en: `Distinguishing Novel and Play`, ar: `التمييز بين الرواية والمسرحية` },
  s5: {
    en: `Prime-Numbered Chapter Structure`,
    ar: `โครงสร้างบทที่ใช้เลขเฉพาะFLT

Actually, that's not in Khaleeji Arabic and it seems there was a misunderstanding based on the previous response format. Let me provide you with an appropriate translation for "Prime-Numbered Chapter Structure" in Khaleeji Arabic:

بنية الفصول المكونة من الأعداد الأولية`,
  },
  s6: { en: `Swindon and Setting`, ar: `سندون والSetting` },
  s7: { en: `First-Person Limited Narration`, ar: `سرد محدود من وجهة نظر الشخص الأول` },
  s9: { en: `Embedded Documents and Diagrams`, ar: `مستندات مدمجة ورسومات توضيحية` },
  s11: { en: `Chronology and the Two Crimes`, ar: `خريطة الأحداث والجريمة الأولى والثانية` },
  s13: {
    en: `The Curious Incident of the Dog in the Night-Time`,
    ar: `INCIDENT الغريب في حادثة كلب الليل`,
  },
  s14: { en: `Distinguish novel from play.`, ar: `dintiguish الرواية من المسرحية.` },
  s15: { en: `Handle representation carefully.`, ar: `ا HANDLE التمثيل WITH CAUTION ا` },
  s16: { en: `Embed exact quotations.`, ar: `اقرء الآيات دقيقة بدون تغيير كلمة واحدة.` },
  s17: { en: `Use Haddon&apos;s methods.`, ar: `استخدم طرق هاددون.` },
  s18: { en: `Refer to the writer&apos;s intentions.`, ar: `اشفط نوايا الكاتب.` },
  s19: { en: `Link the title to Sherlock Holmes.`, ar: `` },
  s20: { en: `Use precise terminology.`, ar: `استخدم لغة دقيقة.` },
  s21: {
    en: `Address the whole novel.`,
    ar: `ا.address الكتاب كله.بلا فرق بين أجزاءه، اقرأ الرواية كلها.`,
  },
  s23: { en: `Character Profiles`, ar: `Profiles للشخصيات` },
  s24: { en: `Mrs Shears`, ar: `مrs شيرز` },
  s25: { en: `An elderly widow living in Christopher`, ar: `YWidow عجوز أرملة تعيش عند كريستوفر` },
  s26: { en: `The neighbour`, ar: `الجاري` },
  s27: { en: `An invigilator at Christopher`, ar: `مراقب لChristopher` },
  s28: { en: `Key Themes`, ar: `المواضيع الرئيسية` },
  s29: { en: `Truth and Lies`, ar: `الحق والكذب` },
  s30: {
    en: `Order vs Chaos / Logic vs Emotion`,
    ar: `النظام مقابل الفوضى / المنطق مقابل العاطفة`,
  },
  s31: { en: `Family and Trust`, ar: `الأسرة والثقة` },
  s32: { en: `Difference and Neurodiversity`, ar: `الاختلاف والتنوّع الدماغي` },
  s34: {
    en: `The novel is, among other things, a coming-of-age story. Christopher begins by needing his father`,
    ar: `الرواية، بين أمور أخرى، قصة نمو و trưởng الأعمار. كريستوفر يبدأ بحاجته لوالده`,
  },
  s35: {
    en: `The novel dramatises every kind of communication failure: Ed cannot tell Christopher the truth about Judy; Judy`,
    ar: `الرواية تتناول كل أنواع فشل التواصل: إد لا يستطيع أن يقول للChristopher الحقيقة عن جودي؛ جودي`,
  },
  s36: { en: `Animals and Honesty`, ar: `` },
  s37: {
    en: `Christopher prefers animals to people because they`,
    ar: `كريستوفر يفضل الحيوانات على الناس لأنهم`,
  },
  s38: { en: `Bravery and Fear`, ar: `الشجاعة والخوف` },
  s39: { en: `Key Quotations with Analysis`, ar: `اقتباسات رئيسية مع تحليل` },
  s40: { en: `Symbols and Motifs`, ar: `رموز وعلامات` },
  s41: {
    en: `Historical, Biographical and Literary Context`,
    ar: `السياق التاريخي وال BIOGRAPHICAL واللأدabi (correcting to fit rules and adding literary context in a way that aligns with instructions)

السياق التاريخي والBiographical واللأدابي`,
  },
  s42: { en: `Narrative Structure and Form`, ar: `.structure السردية والشكل` },
  s43: { en: `Essay Planning for Common Questions`, ar: `hoạchtlان للأسئلة الشائعة` },
  s44: {
    en: `Grade 9 Exemplar Points and Interpretations`,
    ar: `نقاط وأوجه التفسير المثالية للصف التاسع`,
  },
  s45: { en: `Practice Questions`, ar: `أسئلة ممارسة` },
}
