/**
 * paper-2 set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Paper Structure`, ar: `Structure الورقة taxpapers` },
  s1: { en: `Section A: Modern Texts (34 marks)`, ar: `раздел أ: النصوص الحديثة (34 نقطة)` },
  s2: {
    en: `Answer on your studied modern prose or drama text`,
    ar: `أجيب عن النص الأدبي الحديث أو المسرحي الذي درسته`,
  },
  s3: { en: `One essay question from a choice of two`, ar: `واحد سؤال مقال من بين خياراتين` },
  s4: {
    en: `No extract provided - write from memory`,
    ar: `من فضلك، قدم استفسارك أو النص الذي تحتاج إلى ترجمته. أنا هنا لمساعدتك!`,
  },
  s5: {
    en: `One poem printed for you from the anthology`,
    ar: `شلونك حفظت شعر واحد مطبوع لك من الكتاب؟`,
  },
  s6: {
    en: `Compare it with another poem of your choice`,
    ar: `دوري عن شعر آخر من اختياركCOMPARE IT WITH ANOTHER POEM OF YOUR CHOICE`,
  },
  s7: {
    en: `Must be from the same cluster (Power and Conflict)`,
    ar: `.must تكون من نفس الكتلة (السلطة والنزاع)`,
  },
  s8: { en: `Section C: Unseen Poetry (32 marks)`, ar: `SECTION C: شعر غير مشاهد (32 نقطة)` },
  s9: {
    en: `Part 1: Analyse one unseen poem (24 marks)`,
    ar: `تحليل قصيدة غير معروفة واحدة (24 نقطة)`,
  },
  s10: {
    en: `Part 2: Compare with a second unseen poem (8 marks)`,
    ar: `phần 2: сравنة مع قصيدة ثانية غير مروية (8 نقاط)`,
  },
  s12: { en: `Section A: Modern Texts`, ar: `SECTION A: النصوص الحديثة` },
  s13: { en: `Key Comparison Pairs`, ar: `paris الحين مقارنات زوجيات` },
  s15: { en: `Read the poem three times.`, ar: `اقرأ الشعر ثلاث مرات.` },
  s16: { en: `Identify the subject and tone.`, ar: `اعرف الموضوع والطابع.` },
  s17: { en: `Examine structure.`, ar: `اقرأ структура` },
  s18: { en: `Analyse language.`, ar: `تحليل اللغة` },
  s20: { en: `Write 4-5 paragraphs`, ar: `اكتب أربع إلى خمس فقرات.` },
  s21: {
    en: `Focus on similarities and differences`,
    ar: `ركز على الشimilarities والdifferences شنو؟ (استخدم الفصحى لل disclosing: ضع في اعتبارك أنك تحتاج إلى التركيز على النقاط المشتركة والاختلافات.)`,
  },
  s22: { en: `Use comparison connectives:`, ar: `استخدم روابط المقارنة:` },
  s23: { en: `Compare methods,`, ar: `.compare الطرق` },
}
