/**
 * paper-2 set-text guide - bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Time Guide`, ar: `دليل الوقت` },
  s1: { en: `Fiction and literary texts`, ar: `القصص والأعمال الأدبية` },
  s2: { en: `Imaginative / creative writing`, ar: `الكتابة الإبداعية / الكتابة الخيالية` },
  s3: {
    en: `Literary fiction from any period`,
    ar: `الرواية من أي فترة_was not part of the instruction to include as a direct quote or keep in English, so correcting based on provided rules:

الأدب الخيالي من أي فترة`,
  },
  s4: {
    en: `Prose extracts with rich descriptive or narrative elements`,
    ar: `استعارات وتفاصيل رواية غنية أو سرد ذات عناصر توصيفية ثرية`,
  },
  s5: { en: `Word-Level Analysis`, ar: `تحليل على مستوى الكلمة` },
  s6: {
    en: `Semantic fields`,
    ar: `حقldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldsldslds`,
  },
  s7: { en: `Figurative language`, ar: `لغة رمزية` },
  s8: { en: `Sensory language`, ar: `لغة حسية` },
  s9: { en: `Sentence-Level Analysis`, ar: `تحليل على مستوى الجملة` },
  s10: { en: `Short sentences`, ar: `جُمل قصيرة` },
  s11: { en: `Long, complex sentences`, ar: `جمل طويلة ومعقدة` },
  s12: { en: `Minor sentences / fragments`, ar: `جمل صغيرة / أجزاء` },
  s13: { en: `Listing / accumulation`, ar: `القائمة / التجميع` },
  s14: { en: `Focus shifts`, ar: `التركيز يتغير` },
  s15: { en: `Narrative perspective`, ar: `perspective القصة` },
  s16: { en: `Tension and release`, ar: `توتر وراحة` },
  s17: { en: `Paragraph length and structure`, ar: `طولagraph وestructureraph الضبطraph` },
  s18: { en: `How to structure an evaluation response`, ar: `كيف تStructure ردّ على تقييم` },
  s20: {
    en: `Select evidence from the text that supports your view`,
    ar: `اختر أدلة من النص التي تدعم رأيك`,
  },
  s21: {
    en: `Analyse the language and/or structural choices in your evidence`,
    ar: ``,
  },
  s24: {
    en: `Write a descriptive piece based on an image or scenario`,
    ar: `دوري وصف مصور لصورة أو موقف`,
  },
  s25: {
    en: `Write a narrative (short story or part of a story)`,
    ar: `اكتب قصة روائية (قصة قصيرة أو جزء من قصة)`,
  },
  s26: {
    en: `Write from a particular perspective or point of view`,
    ar: `اكتب من وجهة نظر معينة أو نقطة النظر الخاصة بك`,
  },
  s28: { en: `Strong opening example`, ar: `مثال قوي لبداية` },
  s29: { en: `Use all five senses`, ar: `استخدم جميع الخمس حواس` },
  s30: { en: `Zoom in and out`, ar: `دور و شفت` },
  s31: { en: `Use figurative language purposefully`, ar: `استخدم اللغة المجازية بهدف معين` },
  s32: {
    en: `Vary your sentence structures`,
    ar: ``,
  },
  s33: {
    en: `Create a clear structure`,
    ar: ``,
  },
  s34: { en: `Content and Organisation (24 marks)`, ar: `المحتوى والتنظيم (24 نقطة)` },
  s35: { en: `Communication is convincing and compelling`, ar: `الاتصال مقنع ومشوق` },
  s36: {
    en: `Tone, style, and register match purpose and audience`,
    ar: `تتناسب لهجة وأسلوب الكتابة مع الغرض والجمهور`,
  },
  s37: { en: `Extensive, ambitious vocabulary`, ar: `لغة واسعة وأماني طموحة` },
  s38: {
    en: `Sustained crafting with varied structural features`,
    ar: `الكتابة المستمرة مع مميزات بنائية متنوعة`,
  },
  s39: {
    en: `Compelling, well-connected ideas with fluent paragraphing`,
    ar: `فكرة مقنعة ومترابطة مع ترقيم فقرات سلسة`,
  },
  s40: { en: `Technical Accuracy (16 marks)`, ar: `الدقة التقنية (16 نقطة)` },
  s41: {
    en: `Wide range of sentence forms for effect`,
    ar: `مدى واسع من أشكال الجمل لخلق التأثير`,
  },
  s42: { en: `Accurate and varied punctuation`, ar: `` },
  s44: { en: `Secure control of grammar`, ar: `` },
  s46: { en: `Continue studying`, ar: `استمر في الدراسة` },
}
