/**
 * pigeon-english set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Stephen Kelman, 2011`, ar: `ستيفن كيلمان، 2011` },
  s2: { en: `Pigeon English`, ar: `لغة الحمام` },
  s3: { en: `The Damilola Taylor Case (2000)`, ar: `قضية داميلولا تايلور (2000)` },
  s5: { en: `Booker Shortlist 2011`, ar: `قائمة Booker القصيرة لعام 2011` },
  s6: { en: `Curious Incident`, ar: `حادثة مشوقة` },
  s7: { en: `Stephen Kelman: Background`, ar: `ستيفن كيلمان: الخلفية` },
  s8: { en: `The London Council Estate`, ar: `المنزل councillي في لندن` },
  s9: { en: `First-Person Child Narrator`, ar: `راوي طفل في شخصية أول شخصة` },
  s10: { en: `Circular Structure`, ar: `estructة دائرية` },
  s11: {
    en: `Episodic Pacing`,
    ar: `تَقْدِيمُ الأحداثِ حلقاتًaaSAR_annotation_no_change_needed_for_this_term_AsAR`,
  },
  s12: { en: `Final Tonal Shift`, ar: `التحول الصوتي النهائي` },
  s13: { en: `Exam Tips for Pigeon English`, ar: `نصائح للامتحان في كتاب pigeon english` },
  s14: { en: `Always link to Damilola Taylor.`, ar: `دائماً اربط مع داميلولا تايلور.` },
  s15: { en: `Use Kelman&apos;s methods.`, ar: `استخدم طرق كيلمان` },
  s16: { en: `Refer to Kelman&apos;s intentions.`, ar: `انظر إلى نوايا كيلمان.` },
  s17: { en: `Verify quotations.`, ar: `تاكد من الاقتباسات.` },
  s18: { en: `Use precise terminology.`, ar: `استخدم لغة دقيقة.` },
  s19: { en: `Address the whole novel.`, ar: `ا.address الكتاب كله.بلا فصل في فصل.` },
  s21: { en: `Character Profiles`, ar: `Profiles الشخصيات` },
  s22: { en: `Harri and Lydia`, ar: `هاري و ليديا` },
  s23: {
    en: `Still in Ghana, waiting to be brought over once the family in London has earned and saved enough. Their absence is the emotional centre of Harri`,
    ar: `ما زلت في غانا، بانتظار ما يكفيهم من المال والادخار حتى العائلة في لندن تستطيع تأمين نقلهم. غيابهم هو المركز العاطفي في حياة هاري`,
  },
  s24: { en: `Auntie Sonia`, ar: `أختي سونيا` },
  s25: { en: `Key Themes`, ar: `المواضيع الرئيسية` },
  s26: { en: `Childhood vs Violence`, ar: `childhood ضد العنف` },
  s27: {
    en: `The central tension of the novel. Harri narrates with a child`,
    ar: `التناقض الرئيسي في الرواية. هاري يروي القصة كطفل`,
  },
  s28: { en: `Migration &amp; Belonging`, ar: `الهجرة والانتماء` },
  s29: {
    en: `Harri is in the middle of becoming English. He absorbs slang, copies fashion, befriends Dean and crushes on Poppy — but he also says`,
    ar: `هاري في وسط إنه يصير إنجليزي. هو يستوعب السلاش، يقلد الموضة، يصبح صديق دين ويشوف بوبпи لكنه أيضاً يقول`,
  },
  s30: { en: `Faith &amp; Hope`, ar: `الإيمان والأمل` },
  s31: { en: `Friendship &amp; Group Dynamics`, ar: `صداقة وديناميكيات المجموعة` },
  s32: {
    en: `Storytelling &amp; Voice`,
    ar: `رواية القصص وال_voice_ (أترك كلمة voice كما هي في الإنجليزية)`,
  },
  s33: { en: `Key Quotations with Analysis`, ar: `اقتباسات رئيسية مع تحليل` },
  s34: { en: `Symbols and Motifs`, ar: `رموز وعلامات` },
  s35: { en: `Historical and Social Context`, ar: `السياق التاريخي والاجتماعي` },
  s36: { en: `Structure and Voice`, ar: `الهيئة والصوت` },
  s37: { en: `Essay Planning for Common Questions`, ar: `hoạchtlة المقال لأسئلة م-common` },
  s38: {
    en: `Grade 9 Exemplar Points and Interpretations`,
    ar: `نقاط وأInterpretations للنموذج لطلاب الصف التاسع`,
  },
  s39: { en: `Practice Questions`, ar: `أسئلة للتمرين` },
}
