/**
 * funeral-blues set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Funeral Blues`, ar: `موسيقى العزاء` },
  s1: { en: `Version note:`, ar: `ملاحظة الإصدار:` },
  s2: { en: `Another Time`, ar: `وقت آخر` },
  s3: { en: `Twelve Songs IX`, ar: `اثني عشر أغنية التاسعة` },
  s4: { en: `The Ascent of F6`, ar: `صعود ف6` },
  s5: { en: `UK rights notice`, ar: `حقوق المملكة المتحدة` },
  s6: { en: `At a glance`, ar: `في نظرة سريعة` },
  s7: { en: `First publication:`, ar: `النشرة الأولى:` },
  s8: { en: `Form & structure:`, ar: `الشكل والبنية:` },
  s10: { en: `Notes for study`, ar: `ملاحظات للدراسة` },
  s11: { en: `The City Planners`, ar: `المخططون للمدينة` },
  s12: { en: `Anthem for Doomed Youth`, ar: `نشيد الشباب الضائع` },
  s13: { en: `Full study guide in production`, ar: `دليل الدراسة الكامل قيد الإنتاج` },
  s14: { en: `Source attribution`, ar: `الإسناد[source]` },
  s15: {
    en: `Cambridge IGCSE 0475 Songs of Ourselves Vol 1 Part 4`,
    ar: `Cambridge IGCSE 0475 أغنيات أنفسنا الجزء الأول Часть 4`,
  },
  s16: {
    en: `Study guide stub for`,
    ar: `دليلstudyingstub для الدراسة.stubчрежден для изучения.CreatedBy The English Hub لـ The English HubCreated الحين لإبنك أو بنتك لمساعدتهم في استذكار موادهم الدراسية.AQASTUDYGUIDEEdexcelSTUDYGUIDEOCRSTUD`,
  },
}
