/**
 * paper-1 set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Time Guide`, ar: `دليل الوقت` },
  s1: { en: `Non-fiction / literary non-fiction`, ar: `القصص الواقعية / السيرة litteraria` },
  s2: { en: `Writing to present information and ideas`, ar: `كتابة عرض المعلومات والأفكار` },
  s3: {
    en: `Newspaper and magazine articles (broadsheet and tabloid)`,
    ar: `المقالات في الجرائد وال مجلات (الصُحف الرسمية والصحافة الشعبية)`,
  },
  s4: { en: `Travel writing, diaries, and journals`, ar: `كتابة السفر، اليوميات، والدفاتر` },
  s5: {
    en: `Autobiography and biography extracts`,
    ar: `م/licenses_and_disclosures>tracts من الكتابات الذاتية وال BIOGRAPHY`,
  },
  s6: { en: `Letters (personal and formal)`, ar: `الرسائل (شخصية ورسمية)` },
  s7: { en: `Speeches and essays`, ar: `الخطب والرسائل الكتابية` },
  s8: { en: `Reviews and blogs`, ar: `` },
  s9: { en: `Reportage and investigative journalism`, ar: `` },
  s10: {
    en: `Literary non-fiction from the 19th, 20th, or 21st century`,
    ar: `النقد litterary من القرن التاسع عشر، العشرين، أو الحادي والعشرين`,
  },
  s11: { en: `Read the questions first`, ar: `اقرأ الأسئلة أولًا` },
  s12: { en: `Annotate as you read`, ar: `دوّر واعنّن enquanto تقرأ` },
  s14: { en: `Track the writer&rsquo;s argument`, ar: `اتبع حجة الكاتب` },
  s15: { en: `Note shifts in tone or focus`, ar: `لاحظ التحولات في لهجة أو تركيز_EDEFAULTmaktb` },
  s16: { en: `An article for a newspaper or magazine`, ar: `مقال لصحيفة أو مجلة` },
  s17: { en: `Formal Letter`, ar: `carta رسمية` },
  s18: {
    en: `Your address (top right), their address (left), date`,
    ar: `عنوانك (يمين أعلى)، عنوانهم (يسار)，تاريخ`,
  },
  s19: { en: `Formal register throughout`, ar: `الRegister formal خلال toàn bộtextContent` },
  s20: { en: `Clear paragraphs with logical progression`, ar: `` },
  s21: { en: `Engaging headline`, ar: `عنوان جذاب` },
  s22: { en: `Optional subheading or strapline`, ar: `عنوان اختياري أو شريط أسفلي` },
  s23: {
    en: `Opening hook to grab attention`,
    ar: `Latchi ma tshofuh fee elmaktaba wa anta feeh, shno biladna kayn adab welshan wi'? افتح ما تشوفه في المكتبة وانت فية، شنو بلادنا كين أدب وشنع وايد؟`,
  },
  s24: { en: `Short paragraphs with clear topic sentences`, ar: `فقرات قصيرة مع جمل موضوع واضحة` },
  s26: {
    en: `Address the audience directly (&ldquo;Ladies and gentlemen&rdquo;)`,
    ar: `يا سيداتي وسادتي`,
  },
  s27: {
    en: `Rhetorical devices: tricolon, anaphora, rhetorical questions`,
    ar: `أدوات رhetorique: tricolon، anaphora، أسئلة رhetorique`,
  },
  s28: { en: `Emotive language and personal anecdotes`, ar: `لغة عاطفية وقصص شخصية` },
  s29: {
    en: `Strong, memorable conclusion with a call to action`,
    ar: `خاتمة قوية وذكية مع دعوة إلى التحركactionDate: 2023-11-16 15:49:08 UTC`,
  },
  s30: {
    en: `Varied sentence lengths for impact when spoken aloud`,
    ar: `أطوال جمل متنوعة للتأثير عندSpeaking aloud`,
  },
  s32: {
    en: `Balanced opinions (both positive and negative points)`,
    ar: `آراء متوازنة (نقاط إيجابية وسلبية)`,
  },
  s33: {
    en: `Descriptive language to bring the experience alive`,
    ar: `لغة وصفية لتجسيد التجربة حيًا`,
  },
  s34: { en: `Possible star rating or summary verdict`, ar: `تقييم محتمل أو حكم نهائي` },
  s35: { en: `Rhetorical question`, ar: `سؤال رhetorical` },
  s36: { en: `Tricolon (rule of three)`, ar: `` },
  s37: {
    en: `Three parallel words, phrases, or clauses`,
    ar: `ثلاث كلمات، جمل صغيرة، أو شرائح متوازية`,
  },
  s38: {
    en: `Repetition of a word or phrase at the start of successive clauses`,
    ar: `تكرار كلمة أو جملة في بداية نصوص متتابعة`,
  },
  s39: { en: `Direct address`, ar: `المراعاة المباشرة` },
  s41: { en: `Statistics / evidence`, ar: `الإحصائيات / الأدلة` },
  s42: { en: `Using data to support an argument`, ar: `استخدام البيانات لدعم الحجة` },
  s43: {
    en: `Acknowledging the opposing view before dismissing it`,
    ar: `اعتراف بالرأي المضاد قبل رفضه`,
  },
  s44: { en: `Emotive language`, ar: `لغة عاطفية` },
  s45: {
    en: `Words chosen to provoke an emotional response`,
    ar: `كلمات اختيرت لتأجيج رد فعل عاطفي`,
  },
  s47: { en: `Use ambitious vocabulary`, ar: `استخدم مفردات طموحة` },
  s48: { en: `Punctuate accurately`, ar: `دوروِر بدقة` },
  s49: {
    en: `Paragraph effectively`,
    ar: ``,
  },
  s50: { en: `Suggested Time`, ar: `الوقت المقترح` },
  s51: { en: `Reading the texts and annotating`, ar: `اقرأ النصوص و.annotate عليها` },
  s52: { en: `Section A: Reading questions`, ar: `قسم أ: أسئلة القراءة` },
  s53: { en: `Section B: Shorter writing task`, ar: `القسم ب: مهمة الكتابة القصيرة` },
  s54: { en: `Section B: Longer writing task`, ar: `SECTION B: مهمة الكتابة الأطول` },
  s55: { en: `Feature-spotting without analysis`, ar: `الملاحظة دون تحليل` },
  s56: { en: `Retelling the text`, ar: `رواية النص` },
  s58: { en: `Writing one-sided arguments`, ar: `كتابة حجج جانبية` },
  s59: { en: `Poor time management`, ar: `إدارة وقت سيئة` },
  s60: { en: `Weak openings and endings`, ar: `فتحات ضعيفة وختامات` },
  s61: { en: `Continue studying`, ar: `استمر فيstudying (استمر في الدراسة)` },
}
