/**
 * paper-2 set-text guide — bilingual content module (Khaleeji AR).
 * Auto-generated by D:\AI-Agent-Server\agents\english-hub-co\scripts\translate_set_text_guide.py
 * using local Ollama (qwen2.5:14b primary, gemma4:26b fallback).
 *
 * Conventions: Khaleeji-leaning, no Levantine, English quotations
 * preserved verbatim, character + author + brand + AO codes in Latin.
 * Binary M/F gender policy.
 */

export type Bi = { en: string; ar: string }

export const STRINGS: Record<string, Bi> = {
  s0: { en: `Extended Tier`, ar: `المستوى الممدود` },
  s1: { en: `Suggested Time`, ar: `الوقت المقترح` },
  s2: {
    en: `Directed Writing &mdash; write in a specified format using ideas from a passage and your own ideas`,
    ar: `كتابة موجهة — اكتب بناءً على صيغة محددة باستخدام أفكار من نص وافكارك الخاصة`,
  },
  s3: {
    en: `Composition &mdash; choose one from a selection of narrative OR descriptive titles`,
    ar: `الكتابة الإبداعية &mdash; اختار واحدة من مجموعة من عناوين القصة أو الوصف`,
  },
  s4: { en: `Formal Letter`, ar: `carta رسمية` },
  s5: { en: `Format requirements:`, ar: `متطلبات الشكل:` },
  s6: { en: `Informal Letter`, ar: `carta غير رسمية` },
  s7: { en: `Newspaper / Magazine Article`, ar: `مقال في الصحيفة / المجلة` },
  s8: { en: `Journal / Diary Entry`, ar: `` },
  s9: { en: `Reading (Content)`, ar: `قراءة (المحتوى)` },
  s10: { en: `Writing (Language)`, ar: `الكتابة (لغة)` },
  s11: { en: `Narrative Writing`, ar: `كتابة القصة` },
  s12: {
    en: `Story Structure`,
    ar: `โครงสร้างเรื่องราว

Oops! It seems there was a misunderstanding in translating "Story Structure" into Khaleeji Arabic based on your instructions. Here is the correct translation:

هيكلي القصة`,
  },
  s13: { en: `Opening / Exposition`, ar: `فتح / تمهيد` },
  s14: { en: `Rising Action`, ar: `` },
  s15: { en: `Falling Action`, ar: `الentialAction نحو النهاية` },
  s16: { en: `Top Tips for Narrative`, ar: `أبرز النصائح للقصة الحكائية` },
  s18: { en: `Limit your characters`, ar: `حدّد شخصيتكCharCode:1` },
  s19: { en: `Focus on a single event`, ar: `ركز على حدث واحد` },
  s20: { en: `Show, don&rsquo;t tell`, ar: `أشعر، لا تخبر` },
  s21: { en: `Use dialogue sparingly`, ar: `` },
  s22: { en: `End with impact`, ar: `TERMINATE بالتأثير` },
  s23: { en: `Descriptive Writing`, ar: `الكتابة الوصفية` },
  s24: { en: `The Five Senses Framework`, ar: `إطار الخمس حواس` },
  s25: { en: `Colours, shapes, light, movement`, ar: `الألوان، الأشكال، النور، الحركة` },
  s26: { en: `Volume, rhythm, silence, echoes`, ar: `الحجم، النغم، الصمت، الإصداء` },
  s27: { en: `Texture, temperature, pressure`, ar: `الملمس، الحرارة، الضغط` },
  s28: { en: `Aromas, odours, fragrances`, ar: `روائح، عطور، روائح زكيه` },
  s30: { en: `Top Tips for Descriptive`, ar: `أكبر نصائح للوصف` },
  s31: { en: `Zoom in and out`, ar: `دور للقريب والبعيد` },
  s32: { en: `Use varied sentence structures`, ar: `استخدم بنية الجمل المختلفة` },
  s33: { en: `Choose precise vocabulary`, ar: `اختر لغة دقيقة` },
  s34: {
    en: `Create atmosphere`,
    ar: `ا_create_atmosphere_ (Use instructional verb form: اقرأ النصوص بصوت عالٍ لخلق جو مميز)`,
  },
  s35: { en: `Avoid telling a story`, ar: `تجنب حكي قصة` },
  s36: { en: `Outstanding (35&ndash;40 marks)`, ar: `ممتاز (من 35 إلى 40 نقطة)` },
  s37: {
    en: `Content &amp; Structure`,
    ar: `المحتوى وestructure (تركز على الكلمة الإنجليزية "Structure" لأنها مصطلح تكنولوجي أو أدبي يجب الحفاظ عليه باللغة الأصلية)`,
  },
  s39: { en: `Very Good (29&ndash;34 marks)`, ar: `جيد جدًا (29 إلى 34 نقطة)` },
  s40: { en: `Good (22&ndash;28 marks)`, ar: `جيد (من 22 إلى 28 نقطة)` },
  s41: { en: `Adequate (15&ndash;21 marks)`, ar: `مناسب (15 إلى 21 نقطة)` },
  s42: { en: `Limited (8&ndash;14 marks)`, ar: `محدود (8 إلى 14 نقطة)` },
  s43: { en: `Poor (1&ndash;7 marks)`, ar: `عديب (من 1 إلى 7 نقاط)` },
  s44: { en: `Continue studying`, ar: `استمر في الدراسة` },
}
